- src/core/AnimatedNode.js
This workaround allows for counting already initialized easily (need for tests) and fix issue of changing immutable object's field `initialized` while detaching ("object has been frozen" exception) in AnimatedNode
> Fix freezing initalized value in AnimatedNode

- Example/App.js
- Example/package.json
- Example/startAPI/index.js
- Example/yarn.lock
- README.md
- android/src/main/java/com/swmansion/reanimated/nodes/Node.java
- ios/Nodes/REAAlwaysNode.h
- ios/Nodes/REAAlwaysNode.m
- ios/Nodes/REANode.m
- package.json
- src/Animated.test.js
- src/__mocks__/ReanimatedModule.js
- src/animations/DecayAnimation.js
- src/animations/SpringAnimation.js
- src/animations/TimingAnimation.js
- src/animations/backwardsCompatibleAnimWrapper.js
- src/animations/spring.js
- src/animations/timing.js
- src/core/AnimatedNode.js
- src/core/AnimatedValue.js
- src/core/__mocks__/AnimatedProps.js
- src/derived/__mocks__/evaluateOnce.js
- src/derived/evaluateOnce.js
- src/utils.js
- yarn.lock
Handle start Api like in RN core
- Add `always` node - `final` node (like `props`) which evaluate its children
- Add start and stop function which attach and detach node as a child of value we wish to "override" with animation
- Change way of evaluating node in topological order by final nodes
- Add setValue and evaluateOnce
> Add start/stop api

- Example/android/app/build.gradle
> bump compileSdkVersion in Example

- README.md
- src/derived/ceil.js
- src/derived/floor.js
- src/derived/index.js
I found an use case where I needed an equivalent `Math.floor` operation, so I thought about creating a new derived node that performs that operation using the existing nodes.
Let me know what you think and if you want me to tweak something :)
Cheers!
> Creating 2 new derived nodes: floor and ceil

- package.json
Missing in the node_modules folder
> Added podspec to npm files

- android/src/main/java/com/swmansion/reanimated/nodes/Node.java
related to @simontreny suggestion on https://github.com/kmagiera/react-native-reanimated/commit/438bb676b26811addf7b27404997913b078728d2#commitcomment-30000958
> Move initializing the set of visited node outside eval loop on Android

- src/base.js
- src/core/AnimatedConcat.js
> Add missing files related to concat node

- Example/App.js
- Example/code/index.js
- README.md
- src/Animated.js
- src/core/AnimatedCode.js
Logic of evaluation was strictly connected with views but it should not be like because some logic could be abstracted from views
Add `Animated.Code` which behaves like view, but indeed is not related to any layout.
> Animated code

- src/core/AnimatedNode.js
- src/createAnimatedComponent.js
+ Patch createAnimatedComponent using Set with dodgy instances from https://github.com/kitten/react-native-reanimated/commit/ebd0e94aabce6783fdaaf1c1b8817bb1d0d5bc1d (😍)
> Patch createAnimatedComponent using Set with dodgy instances from

- src/Animated.js
This is useful for things like: https://github.com/kmagiera/react-native-screens/issues/26
> Export createAnimatedComponent

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
- ios/REANodesManager.m
https://github.com/kmagiera/react-native-reanimated/issues/112
on iOS it's not allowed to invoke callback with NULL, so I wrapped it into NULL-object
> Make detaching null-safety

- ios/REANodesManager.m
> Add missing semicolon

- README.md
Probably not super important because these functions are symmetric with `Math.cos` and `Math.sin` but I thought maybe some people might find it useful.
> 📚Add unit to cos() and sin()

- react-native-reanimated.d.ts
Issue related: https://github.com/kmagiera/react-native-reanimated/issues/138
> Add backward compatible API typings

- android/build.gradle
This commit fix error "Could not resolve all artifacts for configuration ':react-native-reanimated:classpath'". I just up grade version and add google repo
> fix build on android

- README.md
Put the `runTimer` array in a `block`
> [README] Fix Clock example

- src/createAnimatedComponent.js
https://github.com/facebook/react-native/pull/21415
https://github.com/facebook/react-native/issues/21342
> Renamed ViewStyleProps to DeprecatedViewStyleProps.

- README.md
I see it was written here before but it calls for clarifying a bit
> Clarify that color node accepts only integer values

- react-native-reanimated.d.ts
> Expose createAnimatedComponent definition

- android/build.gradle
update to support gradle >=4.10
> update to support gradle >=4.10

- src/ReanimatedModule.web.js
Prevents crashing when referenced in libs like react-navigation.
> [web] Added shim for web

- ios/RNReanimated.xcodeproj/project.pbxproj
- ios/RNReanimated.xcodeproj/xcshareddata/xcschemes/RNReanimated-tvOS.xcscheme
hi! I've simply added a new target for tvos, since i'm developing an apple tv app and i needed some reanimated views there.
> TVos support

- react-native-reanimated.d.ts
concat#1 can be useful to convert a numerical animated value to a string.
> Add typing for concat#0 concat#1

- .travis.yml
Probably broke due to a travis change.
> Fix android CI setup

- react-native-reanimated.d.ts
🎉Finally, we can type View transformations 😍
> fix(🐛): Add TS support for animated transforms

- react-native-reanimated.d.ts
This fixes typescript error `Cannot find name 'TransformStyle'.`.
> :bug: (react-native-reanimated.d.ts) fix TransformsStyle

- android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java
This allow using the constant directly with `TurboReactPackage`.
> Make `ReanimatedModule.NAME` public

- src/createAnimatedComponent.js
Refactors the create animated component removing the deprecated componentWillMount lifecycle and moving the attachProps to the constructor.
> Remove deprecated componentWillMount

- android/build.gradle
> FIX javaCompileProvider

- src/derived/floor.js
> [iOS] Fix floor() implementation

- RNReanimated.podspec
> Add tvos podspec support

- docs/pages/11.baseNodes/proc.md
> Fix typo in proc docs page

- react-native-reanimated.d.ts
- src/Animated.js
> Feat: Allow for automatic exports of functions

- Example/ios/Podfile.lock
- android/src/main/java/com/swmansion/reanimated/NodesManager.java
- android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java
- ios/REAModule.m
- ios/REANodesManager.h
- ios/REANodesManager.m
- src/core/AnimatedValue.js
There is no need to create new nodes just to change the value of ValueNode.
> Use in AnimatedValue.setValue react method instead of evaluateOnce.

- react-native-reanimated.d.ts
Currently top-level functions as exported as `any` this PR fixes that.
> Fix TypeScript exports 🏷

- src/core/AnimatedCode.js
```jsx
const Breaking = () => {
const [state, setState] = useState(false);
/* ... */
return (
/* ... */
<Animated.Code exec={block([ /* ... */, state ? node1 : node2 ])}>
/* ... */
)
}
props are changing but nodes in `AnimatedCode` are not reattaching, because I bound all logics with `didMount` and `willUnmount`. 
Therefore, I simply forced calling unmounting and mounting of nodes on each props' change. Also, I made it PureComponent since shallow equal is enough for our case,
> Make AnimatedCode sensible for props changing

- mock.js
This mock can be useful to test Reanimated functions written in pure JS and can be used for libraries that use Reanimated. 
For instance, redash provides its own mock, another libraries might build another one. That way we could all leverage the same mock.
> Feat: Provide basic mock

- Example/colors/index.js
- src/derived/color.js
- use `concat` to make color work as documented 
- seems `color` is still broken due to a variety of unrelated factors
- fix transform style error in example
> [web] Add color support 🎨

- src/core/AnimatedParam.js
- src/core/AnimatedStartClock.js
This gets the `Expample/test/index` test somewhat working on web. This functionality just matches what is already implemented natively.
> [web] Add missing animated param methods

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
Not sure if this is right fix for the problem, but cant see any problem with app after applying this.
Solves #559
> Fix for crashing on Android [#559]

- Example/App.js
- Example/babel.config.js
- Example/package.json
- Example/yarn.lock
Reanimated Bottom Sheet is probably one of the most complex things built with reanimated and probably can be used while verifying bugs not observable in more primitive examples.
> Add bottom sheet example

- mock.js
> Remove type adnotations from mocks.js

- android/src/main/cpp/AndroidErrorHandler.cpp
- android/src/main/cpp/AndroidScheduler.cpp
- android/src/main/cpp/JNIRegistry.cpp
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/headers/AndroidErrorHandler.h
- android/src/main/cpp/headers/AndroidScheduler.h
- android/src/main/cpp/headers/JNIRegistry.h
This code reduces number of JNI searches to one per specific class and one per certain method
> Turbo version jni registry

- react-native-reanimated.d.ts
Move Nullable type to Reanimated namespace.
See #599
> Hide Nullable from global scope

- .github/workflows/main.yml
Please add access token in secrets
> Add publishing docs with gh-pages

- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/---feature-request.md
- .github/ISSUE_TEMPLATE/-question.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
We'll need to add a few labels:
- 🐞 Bug
- 💡 Feature request
- 🤔 To verify
> Add issue and PR templates

- src/reanimated2/InstallFunctions.js
> hermes eval global fix, spread temp workaround

- .github/workflows/main.yml
> Fix config of docs deployment action

- docs/docs/about.md
- docs/docs/api/cancelAnimation.md
- docs/docs/api/delay.md
- docs/docs/api/useAnimatedGestureHandler.md
- docs/docs/api/useAnimatedScrollHandler.md
- docs/docs/api/useAnimatedStyle.md
- docs/docs/api/useDerivedValue.md
- docs/docs/api/useSharedValue.md
- docs/docs/api/withSpring.md
- docs/docs/api/withTiming.md
- docs/docs/installation.md
- docs/docs/migration.md
- docs/docs/worklets.md
- docs/src/pages/index.js
Fixes some typos and confusion in the new docs.
> Fix typos & setup code in Reanimated 2 docs

- docs/src/css/custom.css
- docs/src/pages/index.js
Fixes button alignment in hero
> Fixes button alignment in hero

- src/Animated.test.js
- src/core/Core.test.js
- src/reanimated2/__mocks__/NativeReanimated.js
Adds mocks for Reanimated 2 `ReanimatedModule.js`
> Add mocks for Reanimated 2

- docs/docs/installation.md
Closes: https://github.com/software-mansion/react-native-reanimated/issues/841
> Add note about renaming.

- mock.js
Fixes #869
Updated mocks for **.timing**, **.decay** and **.spring**
> Update mocks for animation nodes

- docs/docusaurus.config.js
- docs/package.json
- docs/yarn.lock
…trackingId
Add google analytics support to docusaurus documentation
Adds Google Analytics plugin in `docusaurus.config.js`
> Add google analytics to docs

- docs/docs/about.md
> Typo fixes

- docs/versioned_docs/version-2.0.0-alpha/api/withSpring.md
> Make sure we list velocity in withSpring config

- Example/babel.config.js
- Example/index.js
- Example/src/App.js
- Example/src/ChatHeadsExample.js
- Example/src/DragAndSnapExample.js
- Example/src/LightboxExample.js
- Example/src/LiquidSwipe/Weave.js
- Example/src/ScrollEventExample.js
- Example/src/ScrollableViewExample.js
- Example/src/SwipeableListExample.js
- babel.config.js
- mock.js
- src/reanimated2/Colors.js
- src/reanimated2/Easing.js
- src/reanimated2/Hooks.js
- src/reanimated2/NativeReanimated.js
- src/reanimated2/UpdateProps.js
- src/reanimated2/WorkletEventHandler.js
- src/reanimated2/animations.js
- src/reanimated2/core.js
This change provides consistency in the future as in some of the previous PRs we spotted unrelated changes coming directly from prettier activity. This PR does not contain any logic change, bug fix, new feature etc. whatsoever.
For any requests considering further files/directories refactoring in that manner, please comment below.
> @karol/prettier

- Example/package.json
- Example/yarn.lock
> Remove patch-package

- react-native-reanimated.d.ts
@jakub-gonet @terrysahaidak  thks for your support on this!
> Simplify proc type signature

- docs/src/pages/index.js
Changed links in the docs to make alpha version docs easier to view.
Most of it is formatting changes, `index.js` wasn't formatted.
> Change links in docs to use next/ version

- docs/versioned_docs/version-1.x.x/animations/springUtils.md
- docs/versioned_docs/version-1.x.x/declarative.md
> Fix dead links in docs

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/Tools/Mapper.cpp
- Common/cpp/headers/NativeModules/NativeReanimatedModule.h
- Common/cpp/headers/SpecTools/ErrorHandler.h
- Common/cpp/headers/Tools/Mapper.h
- android/src/main/cpp/AndroidErrorHandler.cpp
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/headers/AndroidErrorHandler.h
- android/src/main/java/com/swmansion/reanimated/AndroidErrorHandler.java
- ios/native/IOSErrorHandler.h
- ios/native/IOSErrorHandler.mm
- ios/native/NativeProxy.mm
- src/reanimated2/animations.js
Provides a mechanism of handling errors more gracefully and in some cases prevents crashes. 
Modified Error handler code, added `try ... catch ...` clauses and injected error handler into `NativeReanimatedModule`. Also refactored calling exception throw on Android in java with `fbjni`. 
Sample code which is better handled after those changes:
`const sv = useSharedValue(3)`
` const style = useAnimatedStyle(() => {`
`sv = 33; // here`
`console.log('invalid ' + sv) // and here`
`return {`
`width: withTiming(someOtherSV.value, config),`
`};`
`});`
> @karol/error handler

- package.json
- yarn.lock
Readds pre-commit hooks for linting and formatting which were mistakenly removed when releasing v2 version
> Add precommit hooks

- docs/docs/installation.md
Update diff links after the playground upgrade.
> Update diff links in docs.

- .github/ISSUE_TEMPLATE/---bug-report-v2.md
- .github/ISSUE_TEMPLATE/---feature-request-v2.md
- .github/ISSUE_TEMPLATE/-question-v2.md
Added templates to add `Reanimated2` labels automatically
> Add issue templates for Reanimated v2

- package.json
Previous version didn't work right when no changes to native code were made
> Fix release-it native changes check

- package.json
> Missing semicolon

- Example/index-template.js
- Example/index.js
- Example/src/AnimatedStyleUpdateExample.js
Cleanup `index.js`, `index-template.js` and `AnimatedStyleUpdateExample.js`
> cleanup index and example screen

- docs/versioned_docs/version-1.x.x/config.md
- docs/versioned_sidebars/version-1.x.x-sidebars.json
> Add config docs page

- Example/scripts/generateIndex.js
- Example/src/App.js
- Example/src/ChatHeadsExample.js
- Example/test/SimpleTest.js
- Example/test/TestApp.js
- prettier.config.js
- src/reanimated2/Easing.js
- src/reanimated2/Hooks.js
- src/reanimated2/animations.js
- src/reanimated2/core.js
- src/reanimated2/interpolation.js
This PR has been created to make code more consistent, and better looking.
To achieve what's changed following paths have been taken under consideration when running `prettier` and `eslint`:
- `src/reanimated2/*.js`
- `Example/test/*.js`
- `Example/src/*.js`
- `Example/scripts/*.js`
All prettier changes are automatically generated.
Two files have been changed in order to deal with eslint errors
- `ChatHeadsExample.js`
- `SimpleTest.js`
Also prettier config has been changed(always use parenthesis - `()`) to improve code consistency. Example:
Before:
```
const f = a => () {
// ...
}
```
Now:
```
const f = (a) => () {
// ...
}
```
> Fix prettier/eslin

- docs/src/pages/index.js
> Remove emoji from landing page

- docs/docs/api/useAnimatedScrollHandler.md
- docs/docs/api/useAnimatedStyle.md
- docs/docs/api/useSharedValue.md
- docs/docs/api/withSpring.md
Those highlights were shifted by one line down.
> Fix code highlights

- src/createAnimatedComponent.js
> Fix initial value for props

- Example/src/App.js
Just checked liquid swipe example with the latest alpha.5 build and seems to be working great.
Seems like it's because of this PR: https://github.com/react-native-community/react-native-masked-view/pull/52 which is released as `0.1.10`
- Remove notice about liquid swipe is iOS only
> Liquid swipe works on android now too

- src/reanimated2/Hooks.js
Updated the gesture handler's triggering logic in useAnimatedGestureHandler hook in v2.
Fixes #835
- Along with the mentioned issue, it should also resolve a group of similar issues that aren't posted.
- Tested it with @terrysahaidak 's reanimated-gallery, and some custom test cases (for TapGestureHandler).
- This is a conservative implementation (it also checks for the event.oldState, which might not completely necessary)
-  I could do a small refactor maybe to use less comparisons (waiting for reviewer's opinions)
Edit: tagged the wrong person :-/
> Updated useAnimatedGestureHandler implementation (#835)

- android/src/main/java/com/swmansion/reanimated/nodes/TransformNode.java
```jsx
<Animated.View
style={{
color: 'green',
transform: [
{rotateY: '30deg'},
Platform.OS === 'web'
? {translateZ: 100}
: {translate: [0, 0, 100]},
],
}}
/>
```
> Support translate array syntax, enables translateZ

- .travis.yml
- package.json
- yarn.lock
> Add TS check to CI

- docs/versioned_docs/version-1.x.x/nodes/color.md
- docs/versioned_docs/version-1.x.x/nodes/interpolate.md
Fix broken links to interpolate colors doc
> Fix broken links in docs

- .travis.yml
We didn't check the TS test file when checking types in CI.
> Check test file in CI TS check

- react-native-reanimated-tests.tsx
The context type was changed in #1066 and tests weren't updated.
> Update context type in TS tests

- react-native-reanimated.d.ts
This PR adds `dependencies` prop to the `Animated.Code` component prop type which was introduced in 212f80d587c9f719768797792a146fe957e289ce.
- Added `dependencies` prop to `<Animated.Code />` component type.
> [v1] Add `dependency` prop to `Animated.Code` type

- Example/ios/ReanimatedExample/AppDelegate.mm
- docs/docs/installation.md
Fixes app compile error introduced in #1142.
> Fix iOS Reanimated imports in the Example and docs

- Example/test-suite/TestModules.js
- Example/test-suite/tests/AnimatedRef.js
- Example/test-suite/tests/Colors.js
- Example/test/TestApp.js
- Example/test/scrollToTest.js
Added test for `scrollTo`
Added test-suite for `processColor`
Did a little clean up in the `test-suite`.
> Improve tests

- package.json
> Bump Reanimated version

- Example/ios/Podfile.lock
- Example/package.json
- Example/src/ScrollableViewExample.js
- Example/yarn.lock
- make liquid swipe example work
- Fix scroll imitation example
> Android fixes

- android/src/main/java/com/swmansion/reanimated/NativeMethodsHelper.java
> Fix measure function on Android.

- Example/test/AnimatedReactionTest.js
- docs/docs/api/useAnimatedReaction.md
- docs/docs/api/useAnimatedRef.md
- docs/sidebars.js
Update docs for `useAnimatedReaction`
> useAnimatedReaction docs

- src/reanimated2/__snapshots__/plugin.test.js.snap
- src/reanimated2/plugin.test.js
Groundwork for addressing things like https://github.com/software-mansion/react-native-reanimated/issues/823
I wanted to make changes to the babel plugin, but I couldn't see any focused tests for the plugin itself. From the looks of thing we're relying on the test app here.
Since I don't want to break things, here are some fairly basic tests to cover the babel plugin.
If there already are tests that cover this feel free to close this out and point me in the right direction :)
- Add Jest spec for babel plugin transformation
> Add unit tests for the babel plugin

- android/build.gradle
> Fix building on Linux

- docs/docs/troubleshooting.md
- docs/sidebars.js
Added troubleshooting page to docs in order to create a list of common problems with Reanimated.
Suggested by @terrysahaidak in [this comment](https://github.com/software-mansion/react-native-reanimated/issues/1090#issuecomment-670948991)
> Add troubleshooting section to docs

- docs/docs/troubleshooting.md
Updated Troubleshooting.md docs, the braces/brackets were just messed up
> Fix URL in Troubleshooting.md

- Common/cpp/SharedItems/ShareableValue.cpp
The pr fixes some bugs introduced in #1236. 
We should only adapt the cache when object has already been converted.
We can't adapt caches when value is a  worklet because it's jest a function after conversion so we don't know if it's host function or not. Also fixed problem with jsThis creation which was caused by removing get method from frozenObject.
> Fix caching

- docs/docs/installation.md
Mentioned that Expo supports Reanimated 2
> Update installation docs

- package.json
> Bump Reanimated version.

- src/core/AnimatedCode.js
Fixes #1252.
When not using dependencies in the `<Code />` component it defaulted to empty array which prevented updates when the component was refreshed.
This could be observed by using `Animated.call()` calling function which made `<Code />` rerender.
> [v1] Fix rerenders of `<Code />` component

- docs/docs/troubleshooting.md
- docs/docs/web-support.md
- docs/sidebars.js
Add web support note to the docs
> Add web support note to the docs

- plugin.js
> fix: react-native compilation issues with node 10.x.x

- package.json
- yarn.lock
> Update fbjs dependency

- Example/src/MeasureExample.js
- Example/test-suite/tests/Colors.js
This PR fixes measure example and color test suite after `runOnJS` change.
> Fix measure example and colors test

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
- src/reanimated2/Hooks.js
Adds deps to useAnimatedReaction hook.
Fixes #1317 
- Add optional dependency list to useAnimatedReaction hook
> Add deps to useAnimatedReaction

- docs/docs/about.md
- docs/docs/api/useAnimatedGestureHandler.md
- docs/docs/api/useAnimatedReaction.md
- docs/docs/api/useAnimatedScrollHandler.md
- docs/docs/api/useAnimatedStyle.md
- docs/docs/api/useDerivedValue.md
- docs/docs/api/useSharedValue.md
- docs/sidebars.js
Update docs:
- add content regarding hooks' dependencies (fixes https://github.com/software-mansion/react-native-reanimated/issues/1303 and https://github.com/software-mansion/react-native-reanimated/issues/1014)
- fix link in `about` section (fixes https://github.com/software-mansion/react-native-reanimated/issues/1349)
- add section about `useAnimatedProps` (fixes https://github.com/software-mansion/react-native-reanimated/issues/895)
> Update docs(link in about, hooks' dependencies, useAnimatedProps)

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
Update types for `withDelay`, `withRepeat` and `withSequence`
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1353
> Update animations' types

- src/reanimated2/Colors.js
- src/reanimated2/UpdateProps.js
- src/reanimated2/index.js
Add color interpolation, taken from https://github.com/wcandillon/react-native-redash/blob/master/src/Colors.ts
> Add color interpolation

- .github/PULL_REQUEST_TEMPLATE.md
Added checklist and test section to the PR template.
> Adjust PR template

- Example/package.json
- Example/yarn.lock
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
- src/reanimated2/core.js
> Animation lag android

- src/reanimated2/Colors.js
Move `getMatchers` call after type checks.
> Colors efficiency improvement

- Example/src/App.js
- ios/native/NativeProxy.mm
- ios/native/REAIOSScheduler.mm
I forgot to pass NativeReaniamtedModule to the scheduler on iOS.
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1374
-->
```JS
import React, {useEffect} from 'react';
import {View} from 'react-native';
export const Playground = () => {
const opacity = useSharedValue(0);
opacity.value = 1;
}, [opacity]);
return {
opacity: opacity.value,
};
});
return (
<View style={{justifyContent: 'center', alignItems: 'center', flex: 1}}>
<Animated.Text style={style}>Hello</Animated.Text>
</View>
);
};
```
> Fix Scheduler

- RNReanimated.podspec
- ios/native/UIResponder+Reanimated.mm
Fix call invoker for iOS for RN 0.62.x
> Fix call invoker for rn 62

- docs/docs/api/useAnimatedProps.md
Fixes #1396.
Fix `useAnimatedProps` example so people can copy-paste and see the result.
> Fix example for `useAnimatedProps()`

- docs/versioned_docs/version-2.0.0-alpha.8/installation.md
> Fix link to previous ios installation in docs

- docs/docs/animations.md
- docs/docs/shared-values.md
- docs/versioned_docs/version-2.0.0-alpha.7/animations.md
- docs/versioned_docs/version-2.0.0-alpha.7/shared-values.md
- docs/versioned_docs/version-2.0.0-alpha.8/animations.md
- docs/versioned_docs/version-2.0.0-alpha.8/shared-values.md
> Fix docs typo

- plugin.js
- src/reanimated2/__snapshots__/plugin.test.js.snap
- src/reanimated2/plugin.test.js
This PR adds the first iteration of Reanimated 2 jest tests and improves plugin readability a bit.
- Added more jest tests for the plugin
- Minor plugin readability improvements
- Extracted adding `_closure` in the worklet body to function.
> Add tests and cosmetic improvements for plugin

- docs/docs/api/nativeMethods/measure.md
Update of documentation. I added information about possible exceptions in measure() function. It is related with issue: https://github.com/software-mansion/react-native-reanimated/issues/1390
in file `docs/docs/api/nativeMethods/measure.md`
> Update of docs - added info about exception in measure()

- Common/cpp/Registries/EventHandlerRegistry.cpp
- Common/cpp/headers/Registries/EventHandlerRegistry.h
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1394
Why there won't be any deadlocks anymore? Because we don't schedule anything in locked sections of the code.
Add Mutex to the `EventHandlerRegistry::isAnyHandlerWaitingForEvent` method as it can be called from different threads.
Copy handlers registered for an event before processing and wrap only that part in the lock. 
<details>
<summary>
Repro
</summary>
```Js
scrollTo,
useAnimatedGestureHandler,
useAnimatedScrollHandler,
import { View } from 'react-native';
import { PanGestureHandler } from 'react-native-gesture-handler';
export default function Repro() {
const aref = useAnimatedRef();
const handler = …
```
> Fix scrollTo freezing

- docs/docs/api/runonJS.md
- docs/sidebars.js
> Add run on js docs note

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
> [v1] Update interpolate `outputRange` type to allow strings

- Common/cpp/Tools/RuntimeDecorator.cpp
- Example/ios/Podfile.lock
- Example/src/SwipeableListExample.js
- package.json
- src/createAnimatedComponent.js
- src/reanimated2/Hooks.js
- src/reanimated2/core.js
- src/reanimated2/js-reanimated/JSReanimated.js
- src/reanimated2/js-reanimated/index.js
- src/reanimated2/platform-specific/RNRenderer.js
Update version to alpha 9 + some bug fixes
> Update version to alpha 9

- .github/workflows/issue-validator.yml
the name of issue validator action should be `Validate issues`, not `Check versions`
> Fix action's name

- .github/workflows/issue-validator.yml
Add icons for the issue labels' names for the issue validator.
> Fix validator labels(add icons)

- Example/ios/Podfile.lock
- package.json
> Bump version to alpha 9.1

- src/reanimated2/NativeReanimated.native.js
fix the problem with unknown reference to `_updatePropsJS`
> Fix unknown reference to _updatePropsJS

- android/src/main/cpp/NativeProxy.cpp
Until now we've been using `jni::autobox` when processing new props' values to be updated in java for numbers and booleans, but it wouldn't work for booleans since `autobox` uses `JLong::valueOf` like [here](https://github.com/facebookincubator/fbjni/blob/e109650ca03e3db54ab973c14d10f176b6436c48/cxx/fbjni/detail/Boxed.h#L73). Getting rid of the `autobox` call solves this problem.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1414
In `NativeProxy.cpp` replace `autobox` call with passing boolean per se.
<details>
```
import {
SafeAreaView,
View,
FlatList,
StyleSheet,
Text,
StatusBar,
Button
} from 'react-native';
// import { …
```
> Fix bool props on Android

- docs/docs/api/useAnimatedProps.md
> Fix typo in docs

- Example/ios/Podfile.lock
- package.json
> Bump version to rc.0

- package.json
> Bump version to rc.1

- Example/package.json
- Example/yarn.lock
Bump version of navigation dependency. It's related with issue in navigation [#8951](https://github.com/react-navigation/react-navigation/issues/8951)
> Bump version of navigation in Example app

- mock.js
Extends mock for unit tests
Added missed functions mocks
- Added mock for useValue hook
- Added mock for interpolateColors
> [v1] Add missing mocks

- docs/docs/api/useAnimatedProps.md
> Mention props config in the useAnimatedProps

- Example/reanimated1/App.js
- Example/src/App.js
- Example/src/WebApp.js
- Example/test/TestApp.js
I replaced usage of YellowBox by LogBox in Example because YellowBox is deprecated and they log warning in every refresh of application.
> YellowBox -> LogBox in Example

- react-native-reanimated.d.ts
- src/reanimated2/animations.js
For animations defined outside this file like in redash.
> Export defineAnimation()

- react-native-reanimated.d.ts
- tsconfig.json
> Add return type to useAnimatedReaction

- src/reanimated2/Hooks.js
We have to check if someone added a new dependency.
> Check the lengths when comparing deps.

- Example/test/TestApp.js
- Example/test/UpdatePropsTest.js
- docs/docs/api/useAnimatedProps.md
- plugin.js
- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
- src/ConfigHelper.js
- src/createAnimatedComponent.js
- src/reanimated2/Hooks.js
- src/reanimated2/PropAdapters.js
- src/reanimated2/UpdateProps.js
- src/reanimated2/core.js
- src/reanimated2/index.js
The goal is to handle a situation when props are set differently directly underneath, on the basic components than on a higher layer of components. Let's say we have a library that exports component A. Inside of this component, we render some other components like View, Text, etc. Now we may want to name some of the props differently for some reason. Then, when we want to update animated props it will not work unless we convert them into the proper names/formats.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1398 - in b28038d
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1593 - in 99c1aa0
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1360
These changes allow users to add their custom adapters for only one use …
> Use adapters for animated props

- src/reanimated2/mock.js
Removed old function names from a mock file.
Inspired: https://github.com/software-mansion/react-native-reanimated/pull/1598
Thanks, @mym0404
> Update of mocs

- package.json
> bump version to rc.2

- docs/docs/api/nativeMethods/measure.md
- docs/docs/api/nativeMethods/scrollTo.md
Add docs for native functions - `scrollTo` and `measure`.
> Add docs for native functions

- Example/test-suite/tests/AttachComponent.js
- Example/test/AdaptersTest.js
- Example/test/TestApp.js
- src/reanimated2/PropAdapters.js
Improves testing by adding adapters test and a fix to attach component test on android.
Also, there was one little bug in the SVG adapter(double `translateX`).
> Improve testing

- android/build.gradle
This was necessary to fix https://github.com/software-mansion/react-native-gesture-handler/issues/494
Update Android Tools gradle version
Following https://reactnative.dev/docs/navigation with a new project fails (at least with the Typescript template)
> Update Android Tools gradle version

- src/reanimated2/core.js
Handle a situation when someone forgets to add a babel plugin by throwing a corresponding error.
> Handle lack of babel plugin

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
Fix jsi::Error handling
Fixes #1629
> Fix jsi::Error handling

- android/build.gradle
Fix Gradle tasks Executions order.
> Fix gradle task execution order.

- package.json
> Bump version to rc.3

- ios/native/NativeMethods.mm
Fixes #1701 
- Reverted 95e76c593af3ce790582bb327953807c04771472
https://user-images.githubusercontent.com/4061838/107160873-38df4080-6999-11eb-8795-12990861c3e7.mp4
https://user-images.githubusercontent.com/4061838/107160879-40064e80-6999-11eb-9d34-12d60d639691.mp4
https://gist.github.com/gorhom/06e4c7f429ee1f6ab2d9a1c27dc9aa60
> fix: scrollTo freezes UI, reverted 95e76c5

- Common/cpp/SharedItems/ShareableValue.cpp
> Add missing switch case

- Common/cpp/headers/SharedItems/ValueWrapper.h
- Example/ios/Podfile.lock
the virtual destructor was missing from valueWrapper what resulted in undefined behavior when some of the classes that extend ValueWrapper was destroyed.
Add virtual destructor to ValueWrapper class.
> Fix full reload

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/headers/SharedItems/SharedParent.h
It removes from SharableValue duplicated type of shared value.
> Remove duplicated value types

- docs/docs/worklets.md
Use runOnJS in callback example
> [docs]Use runOnJS in callback example

- src/reanimated2/Hooks.js
- src/reanimated2/core.js
Added possibility to use Reanimated2 without added plugin when someone uses only Reanimated1 API.
> Move plugin check

- src/reanimated2/Easing.js
- src/reanimated2/interpolation.js
Automatically use interpolateNode nad EasingNode when users still use old naming (interpolate, Easing) in V1 code.
```JS
import React from "react";
import { SectionList, StatusBar, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import Animated, { Easing } from 'react-native-reanimated';
let opacity = new Animated.Value(0);
const animate = easing => {
opacity.setValue(0);
Animated.timing(opacity, {
toValue: 1,
duration: 1200,
easing
}).start();
};
const size = opacity.interpolate({
inputRange: [0, 1],
outputRange: [0, 80]
});
const animatedStyles = [
styles.box,
{
opacity,
width: size,
height: size
}
];
return (
<StatusBar hidden={true} />
<Text style={styles.title}>
Press rows below to preview the Easing!
</Text>
<View …
```
> Migrate automatically

- package.json
> Bump to 2.0.0

- .github/ISSUE_TEMPLATE/bug-report-v2.md
- .github/ISSUE_TEMPLATE/bug-report.md
Added correct label for Reanimated 2 template and slightly adjusted templates.
> Update issue templates

- package.json
Update Reanimated version to 2.0.1
> Update to 2.0.1

- src/reanimated2/Bezier.ts
- src/reanimated2/Colors.ts
- src/reanimated2/Easing.ts
- src/reanimated2/globals.d.ts
Add some types to Easing, Colors, Bezier.
> Type Easings and Colors

- Example/ios/Podfile.lock
- package.json
Update reanimated version to 2.1.0
> Bump to 2.1.0

- docs/docs/animations.md
- docs/docs/shared-values.md
- docs/versioned_docs/version-2.0.0-rc.2/animations.md
- docs/versioned_docs/version-2.0.0-rc.2/shared-values.md
- docs/versioned_docs/version-2.0.0/animations.md
- docs/versioned_docs/version-2.0.0/shared-values.md
Just a couple of minor things on the docs
> Docs fixes (broken link + typo)

- src/reanimated2/js-reanimated/JSReanimated.ts
Fixes prettier issue introduced in #1891.
¯\\_(ツ)_/¯
> Fix indent

- docs/docs/installation.md
- docs/versioned_docs/version-2.0.0/installation.md
> Adjust iOS installation docs

- docs/docs/testing.md
After migration to TS, we forgot to update the path to the Jest setup file in documentation.
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1916
> Update path to Jest setup file

- docs/docs/about.md
- docs/versioned_docs/version-2.0.0-rc.2/about.md
- docs/versioned_docs/version-2.0.0/about.md
Just documentation update inspired https://github.com/software-mansion/react-native-reanimated/issues/1918
> Added info about supported versions of react-native

- docs/docs/web-support.md
- docs/versioned_docs/version-2.0.0-rc.2/web-support.md
- docs/versioned_docs/version-2.0.0/web-support.md
Added information about webpack configuration.
> Added information about webpack configuration

- docs/docs/testing.md
- docs/versioned_docs/version-2.0.0/testing.md
Inspired by [this](https://github.com/software-mansion/react-native-reanimated/issues/1821#issuecomment-825320970) comment.
> Mention babel plugin in testing doc

- docs/versioned_docs/version-2.0.0/api/runonJS.md
> Fix typo in runOnJS docs

- README.md
> Update README with new branded header image

- ios/native/NativeMethods.mm
> Fix vector init

- android/build.gradle
In .sh we have:
```sh
for for_hermes in "True" "False"
```
and 
```java
FOR_HERMES = System.getenv("FOR_HERMES") ? true : false;
```
always returned true.
> Fix FOR_HERMES init

- Example/src/App.tsx
> Add missing semicolumn

- src/reanimated2/layoutReanimation/defaultAnimationsBuilder.ts
> Fix Bounce Animations

- Example/ios/Podfile.lock
- ios/LayoutReanimation/REAViewTraverser.m
> Fix LayoutAnimations on iOS

- package.json
I want to check CI with `eslint` check
> Test eslint with CI

- src/reanimated2/Hooks.ts
This fixes issue with the manual tests app.
> Added missing nullcheck

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReactBatchObserver.java
Remove unused immport from Java - not exists in RN63
> Remove unused immport from Java - not exists in RN63

- src/reanimated2/layoutReanimation/defaultAnimations/Slide.ts
In default animations was a problem when the component has a margin.
Before:
After:
> Fix problem with margin in default animations

- Example/ios/Podfile.lock
- package.json
> Bump version

- docs/docs/layout_animations.md
- docs/versioned_docs/version-2.3.0-alpha.1/layout_animations.md
Just link to video about layout animations
> Link to youtube

- src/reanimated2/globals.d.ts
- src/reanimated2/layoutReanimation/AnimatedRoot.tsx
- src/reanimated2/layoutReanimation/animationBuilder/BaseAnimationBuilder.ts
- src/reanimated2/layoutReanimation/animationBuilder/BaseBounceAnimationBuilder.ts
There was a problem with compiling typescript during the building release package. I tested it and now works properly.
> Fix tsc build

- react-native-reanimated.d.ts
- src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts
- src/reanimated2/layoutReanimation/animationBuilder/commonTypes.ts
This pr fixes some typescript errors connected with Keyframes.
> Fixed Keyframe typescript errors

- Example/src/LayoutReanimation/DefaultAnimations.tsx
- Example/src/LayoutReanimation/KeyframeAnimation.tsx
- docs/docs/api/LayoutAnimations/CustomAnimations.md
- docs/docs/api/LayoutAnimations/EntryAnimations.md
- docs/docs/api/LayoutAnimations/ExitAnimations.md
- docs/docs/api/LayoutAnimations/KeyframeAnimations.md
- docs/docs/api/LayoutAnimations/LayoutTransitions.md
- package.json
- react-native-reanimated.d.ts
- src/reanimated2/animations.ts
- src/reanimated2/layoutReanimation/AnimatedRoot.tsx
- src/reanimated2/layoutReanimation/animationBuilder/BaseAnimationBuilder.ts
- src/reanimated2/layoutReanimation/animationBuilder/BaseBounceAnimationBuilder.ts
- src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts
- src/reanimated2/layoutReanimation/animationBuilder/LayoutAnimationBuilder.ts
- src/reanimated2/layoutReanimation/animationBuilder/commonTypes.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Bounce.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Fade.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Flip.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Lightspeed.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Pinwheel.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Roll.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Rotate.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Slide.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Stretch.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Zoom.ts
- yarn.lock
In layout animations often many properties are animated at the same time, so there is a need to have a callback that will trigger after all properties finish their animation. This pr adds to LayoutAnimation object optional property `callback` where user can pass a function that will trigger when layout animation ends.
- Added `callback` propterty to LayoutAnimation
- Added `withCallback` modifier to predefined animation, keyframes, and layout transitions
- Updated docs
- Bumped eslint version to latest
> Callback for layout animation

- Example/ios/Podfile.lock
- createNPMPackage.sh
- package.json
> Bump version to 2.3.0-alpha.2

- docs/docs/layout_animations.md
- docs/versioned_docs/version-2.3.0-alpha.1/layout_animations.md
> Fix typo in dosc

- src/reanimated2/layoutReanimation/animationBuilder/LayoutAnimationBuilder.ts
Added missing optional to the callback in animation builder - this broke building script.
> Added missing optional to the callback in animation builder

- android-npm/build.gradle
> Fix gradle for rn65

- docs/docs/api/LayoutAnimations/CustomAnimations.md
- docs/docs/api/LayoutAnimations/EntryAnimations.md
Fixed typos in:
* CustomAnimations.md: dimations -> dimentions
* EntryAnimations.md: particulr -> particular
My first open-source contribution! A classical way to start I guess :)
> Fixed Layout Animations docs typos

- src/reanimated2/hook/useAnimatedGestureHandler.ts
Remove dependency to gesture-handler
> Remove dependency to gesture-handler

- android-npm/build.gradle
Added support for Gradle flavor. Solution based on https://stackoverflow.com/a/34679933/7276742
Fixes
- https://github.com/software-mansion/react-native-reanimated/issues/2245
- https://github.com/software-mansion/react-native-reanimated/issues/2292
> Support for gradle flavors

- docs/docs/tutorials/LayoutAnimations/_fullCode.md
- docs/docs/tutorials/LayoutAnimations/animated_list.mdx
- docs/versioned_docs/version-2.3.0-alpha.3/tutorials/LayoutAnimations/_fullCode.md
- docs/versioned_docs/version-2.3.0-alpha.3/tutorials/LayoutAnimations/animated_list.mdx
Updated code snippet in layout animations tutorial
> Code snippet change in layout animations tutorial

- Example/index.js
- Example/test/WithNavigation.tsx
- android/src/main/java/com/swmansion/reanimated/Scheduler.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedUIManager.java
- ios/LayoutReanimation/REAAnimationsManager.h
- ios/LayoutReanimation/REAAnimationsManager.m
- ios/LayoutReanimation/REAUIManager.h
- ios/LayoutReanimation/REAUIManager.mm
- ios/native/NativeProxy.mm
- ios/native/REAIOSScheduler.mm
- package.json
- src/createAnimatedComponent.js
- src/reanimated2/animation/decay.ts
- src/reanimated2/hook/index.ts
- src/reanimated2/hook/utils.ts
- src/reanimated2/layoutReanimation/LayoutAnimationRepository.tsx
- yarn.lock
PR contains many fixes for Layout Animations on both platforms - Android and iOS
Authors: @Szymon20000 @piaskowyk
> Layout Animation fixes for rnscreens 

- .github/workflows/docs-check.yml
- docs/docs/api/animations/withDecay.md
- docs/docs/api/animations/withDelay.md
- docs/docs/api/animations/withRepeat.md
- docs/docs/api/animations/withSequence.md
- docs/docs/api/animations/withSpring.md
- docs/docs/api/animations/withTiming.md
- docs/docs/api/hooks/useSharedValue.md
- docs/docs/api/nativeMethods/measure.md
- docs/docs/api/nativeMethods/scrollTo.md
- docs/docs/fundamentals/animations.md
- docs/docs/fundamentals/shared-values.md
- docs/versioned_docs/version-2.3.0-alpha.3/api/animations/withDecay.md
- docs/versioned_docs/version-2.3.0-alpha.3/api/animations/withDelay.md
- docs/versioned_docs/version-2.3.0-alpha.3/api/animations/withSequence.md
- docs/versioned_docs/version-2.3.0-alpha.3/api/animations/withSpring.md
- docs/versioned_docs/version-2.3.0-alpha.3/api/animations/withTiming.md
- docs/versioned_docs/version-2.3.0-alpha.3/api/hooks/useSharedValue.md
- docs/versioned_docs/version-2.3.0-alpha.3/api/miscellaneous/interpolate.md
- docs/versioned_docs/version-2.3.0-alpha.3/api/nativeMethods/measure.md
- docs/versioned_docs/version-2.3.0-alpha.3/api/nativeMethods/scrollTo.md
- docs/versioned_docs/version-2.3.0-alpha.3/fundamentals/animations.md
- docs/versioned_docs/version-2.3.0-alpha.3/fundamentals/shared-values.md
- docs/versioned_sidebars/version-2.3.0-alpha.3-sidebars.json
Fixed docs wrong links and added GitHub action for docs test build to prevent such situations in the future.
> Fixed docs

- createNPMPackage.sh
Restore initial state of `/android/rnVersionPatch/backup`
> Update the build script

- src/reanimated2/core.ts
We changed url to installation instructions in docs
> Update url to installation instructions

- Example/test/ModalInNavigationNativeStack.tsx
- Example/test/TestApp.js
New test case with native-stack.
> Added test case with native-stack

- README.md
Replace the outdated `installation` doc link in `README.md` with new one.
> doc: Update `installation` link in `README.md`

- src/reanimated2/layoutReanimation/defaultAnimations/Default.ts
Fix native stack modal example
> Fix default layout transition

- src/reanimated2/layoutReanimation/LayoutAnimationRepository.tsx
I merge entering animation with layout animation. I want to make smooth appearing if a component started layout animation during entering animation. 
https://user-images.githubusercontent.com/36106620/134588531-19af5a25-6d89-4ca3-930d-8323ced85b57.mov
> Simultaneous entering&layout

- docs/docs/api/LayoutAnimations/LayoutTransitions.md
- docs/versioned_docs/version-2.3.0-beta.1/api/LayoutAnimations/LayoutTransitions.md
Changed size of videos in docs
> Resized docs videos

- Example/android/app/build.gradle
- Example/android/build.gradle
- Example/android/gradle.properties
- Example/ios/Podfile
- Example/ios/Podfile.lock
- Example/ios/ReanimatedExample.xcodeproj/project.pbxproj
- Example/package.json
- Example/yarn.lock
- RNReanimated.podspec
- android/CMakeLists.txt
- android/build.gradle
- createNPMPackage.sh
- ios/native/REAInitializer.mm
- package.json
- yarn.lock
Added support for `react-native@0.66`. I temporarily removed binary for RN62 from the package, but in the future, I will add an option to build reanimated from sources.
> Support for RN66

- Example/ios/Podfile.lock
- package.json
- src/reanimated2/layoutReanimation/defaultAnimations/Lightspeed.ts
- src/reanimated2/utils.ts
Update package.json before release 🚀
> Release 2.3.0-beta.2

- src/createAnimatedComponent.tsx
Added missing null check for viewDescriptors
> Revert nullcheck

- src/reanimated2/layoutReanimation/defaultAnimations/Slide.ts
SlideInUp behaves the same as SlideInDown
Changed initial value for originY to slide in up, opposite as in SlideInDown
> slide in up wrong init value fix

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
I added a check to dismiss the layout animation if the catalyst instance was destroyed. It sometimes throws null pointer exceptions during a fast refresh.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2481
Inspired by https://github.com/software-mansion/react-native-reanimated/pull/2559
> Dismiss layout animation if catalyst instance was destroyed

- src/reanimated2/animation/styleAnimation.ts
> Fix TS generate

- Example/ios/Podfile.lock
- RNReanimated.podspec
> Remove unused dependency - React-RCTVibration (#2596)

- RNReanimated.podspec
I added the possibility to detect `react-native` version in monorepo and added some comments to a better understanding of flow.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2585
> Detect react-native version

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
Animations of disappearing for native stack elements are more complicated, so we decided to disable this type of animation at this moment. It's just a temporary solution. We will come back to this after a stable release.
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/2460 https://github.com/software-mansion/react-native-reanimated/issues/2501
Autors: @piaskowyk @WoLewicki 
<details>
<summary>example 1</summary>
```js
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import {Button, Text, View} from 'react-native';
const Stack = createNativeStackNavigator();
function HomeScreen({navigation}) {
return (
<View style={{flex: 1, alignItems: 'center', …
```
> Disable disapearing animation for native stack

- Example/ios/Podfile.lock
- Example/ios/ReanimatedExample.xcodeproj/project.pbxproj
- Example/package.json
- Example/yarn.lock
- createNPMPackage.sh
- package.json
- src/createAnimatedComponent.tsx
- src/reanimated2/layoutReanimation/LayoutAnimationRepository.ts
- yarn.lock
> Release 2.3.0-beta.4 🎉

- react-native-reanimated.d.ts
> Remove unnecessary TypeScript interface

- docs/versioned_docs/version-2.3.0/api/LayoutAnimations/CustomAnimations.md
This PR adds missing code in the 2.3.0 docs about custom layout animations.
> docs: add missing code

- docs/docs/api/LayoutAnimations/CustomAnimations.md
The code snippet inside the documentation was incorrect.
> Fix code snippet inside the documentation 

- Example/ios/Podfile.lock
- package.json
Update reanimated version in package.json
> Release 2.3.1

- mock.js
> ADD interpolateColors to jest mock 

- docs/docs/api/miscellaneous/interpolate.md
"Identity" is spelled with two "Y":
- Corrected the typo
> Fixed mispelled extrapolation variable

- Example/src/App.tsx
- Example/src/ReactionsCounterExample.tsx
> Reactions counter example

- docs/versioned_docs/version-2.0.0/api/miscellaneous/interpolate.md
- docs/versioned_docs/version-2.1.0/api/miscellaneous/interpolate.md
- docs/versioned_docs/version-2.2.0/api/miscellaneous/interpolate.md
- docs/versioned_docs/version-2.3.0/api/miscellaneous/interpolate.md
> Fix typos in docs

- react-native-reanimated.d.ts
- src/reanimated2/Colors.ts
- src/reanimated2/hook/utils.ts
The color cache was mutable only from the JS side. I decided to remove the cache and instead of this I created a new faster function with a better cache mechanism without previous limitations.
Performance comparation between `interpolateColor` and `interpolateSharableColor`:
```
old 2894ms - new 1741ms // 39.8% faster
old 2720ms - new 1697ms // 37.6% faster
old 2739ms - new 1650ms // 39.7% faster
old 2738ms - new 1781ms // 34.9% faster
old 2727ms - new 1662ms // 39.0% faster
```
Performance test code:
```js
const interpolateConfig = useInterpolateConfig([0, 350], ['#ff0000', '#00ff00']);
const v1 = interpolateSharableColor(randomWidth.value, interpolateConfig);
const iterations = 10000;
const t1_start = Date.now();
for(let i = 0; i < iterations; i++) {
const v = …
```
> Fix immutable color cache

- android-npm/build.gradle
This was causing a build crash for me
Use + for string concatenation in Groovy
None
> Fix bad string concatenation in build.gradle

- .github/workflows/build-npm-package.yml
- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
- createNPMPackage.sh
- package.json
- yarn.lock
Update react-native version and build script to build new releases with CI.
Result: https://github.com/software-mansion/react-native-reanimated/actions/runs/1786462605
> Update building script

- .github/workflows/static-root-checks.yml
- Example/ios/Podfile.lock
- package.json
- src/reanimated2/NativeMethods.ts
- src/reanimated2/NativeReanimated/NativeReanimated.ts
- src/reanimated2/animation/commonTypes.ts
- src/reanimated2/animation/decay.ts
- src/reanimated2/animation/delay.ts
- src/reanimated2/animation/index.ts
- src/reanimated2/animation/repeat.ts
- src/reanimated2/animation/sequence.ts
- src/reanimated2/animation/spring.ts
- src/reanimated2/animation/styleAnimation.ts
- src/reanimated2/animation/timing.ts
- src/reanimated2/animation/util.ts
- src/reanimated2/commonTypes.ts
- src/reanimated2/core.ts
- src/reanimated2/hook/commonTypes.ts
- src/reanimated2/hook/useAnimatedRef.ts
- src/reanimated2/hook/useAnimatedStyle.ts
- src/reanimated2/hook/utils.ts
- src/reanimated2/index.ts
- src/reanimated2/js-reanimated/JSReanimated.ts
- src/reanimated2/js-reanimated/Mapper.ts
- src/reanimated2/js-reanimated/MapperRegistry.ts
- src/reanimated2/js-reanimated/commonTypes.ts
- src/reanimated2/layoutReanimation/defaultTransitions/EntryExitTransition.ts
- src/reanimated2/utils.ts
- yarn.lock
> Release 2.4.0

- android/build.gradle
These changes reduce package size compiled on CI x3 time.
> Fix package size on CI

- src/reanimated2/Colors.ts
- src/reanimated2/index.ts
- src/reanimated2/interpolateColor.ts
During tests before release, I noticed another circular dependency, so I create a new module `interpolateColor.ts` to break a cycle.
> Resolved another circular dependencies

- react-native-reanimated.d.ts
Fixes 
* #2971
Updated TS types definition in [react-native-reanimated.d.ts](https://github.com/software-mansion/react-native-reanimated/blob/main/react-native-reanimated.d.ts)
No such error
```js
withTiming,
Easing,
export function TestScreen() {
const randomWidth = useSharedValue(10);
const config = {
duration: 500,
easing: Easing.bezier(0.5, 0.01, 0, 1),
};
return {
width: withTiming(randomWidth.value, config),
};
});
return (
<View
style={{
flex: 1,
alignItems: 'center',
justifyContent: 'center',
flexDirection: 'column',
}}>
<Animated.View
style={[{ width: 100, height: 80, backgroundColor: …
```
> Fix 2971: TS error with Easing.bezier

- docs/docs/fundamentals/events.md
- docs/versioned_docs/version-2.0.0/events.md
- docs/versioned_docs/version-2.1.0/events.md
- docs/versioned_docs/version-2.2.0/events.md
- docs/versioned_docs/version-2.3.0/fundamentals/events.md
Added the link of available gesture handlers
Document change
> Add link to events.md

- README.md
> corrected grammatical errors

- src/reanimated1/core/AnimatedFunction.js
- src/reanimated1/derived/interpolate.js
- src/reanimated2/Colors.ts
- src/reanimated2/animation/styleAnimation.ts
- src/reanimated2/animation/timing.ts
- src/reanimated2/animation/util.ts
- src/reanimated2/component/FlatList.tsx
- src/reanimated2/hook/utils.ts
- src/reanimated2/interpolation.ts
- src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts
- src/reanimated2/layoutReanimation/defaultTransitions/CurvedTransition.ts
- src/reanimated2/layoutReanimation/defaultTransitions/FadingTransition.ts
- src/reanimated2/layoutReanimation/defaultTransitions/JumpingTransition.ts
- src/reanimated2/layoutReanimation/defaultTransitions/LinearTransition.ts
- src/reanimated2/layoutReanimation/defaultTransitions/SequencedTransition.ts
The CI failed, so I fixed eslint errors and ran prettier.
> Fix eslint errors

- package.json
I do it often 😄 So I want to make it faster.
> Added simple cleanup command

- react-native-reanimated.d.ts
Fixes regression introduced in #2947.
> Use `P extends object` in AnimateProps generic type

- android/src/main/java/com/swmansion/reanimated/ReanimatedJSIModulePackage.java
- src/reanimated2/core.ts
- src/reanimated2/mock.ts
https://github.com/software-mansion/react-native-reanimated/runs/5294182050?check_suite_focus=true
https://github.com/software-mansion/react-native-reanimated/runs/5294181942?check_suite_focus=true
I run java prettier and fix type conflict for `global.performance`.
> Fix failing CI

- Example/ios/Podfile.lock
- android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java
- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensorListener.java
- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensorType.java
- package.json
Update package.json before release
package build: https://github.com/software-mansion/react-native-reanimated/actions/runs/2014759605
> Release 2.5.0

- src/reanimated2/interpolateColor.ts
- Minor typo fix on a variable name
> fix: typo in variable

- react-native-reanimated.d.ts
- withSequence, withRepeat, withDelay, withTiming, withSpring, interpolateColor and interpolateColors returns data in the format that's received, most use AnimatableValue (e.g. string, number or number[]). The typing on the other hand always assumes the returned type will be a number, this will stop builds on projects with `strict` enabled and trigger false typing errors.
- Includes Fixes for #2968 
- Updated method with generics that identifies the type used and adjust the type returned to match that
Example code to reproduce issue:
```typescript
withTiming,
withSequence,
interpolateColor,
export default function Component() {
const animatedColor = …
```
> Fix output data type not matching input data

- plugin.js
Add the missing findIndex method to the babel plugin for it to work in worklets.
Added findIndex to the babel plugin
> Add findIndex to babel plugin

- src/reanimated2/jestUtils.ts
Fixes `Property 'toHaveAnimatedStyle' does not exist on type 'JestMatchers<ReactTestInstance>'.ts(2339)` error.
- Added a declaration for `toHaveAnimatedStyle` function in `jest` namespace;
I added the declaration in `jestUtils.ts` file as per [this](https://stackoverflow.com/a/59725365/9272042) recommendation. Not sure, maybe we can declare it in better place - let me know if you think so 🙂 
Also I suppressed `eslint` error. Not sure, maybe it would be better to ignore it at `eslintrc` file 🤷‍♂️ 
Try to rename existing `.js` tests in `.tsx` and see the error.
```tsx
import { render, fireEvent } from '@testing-library/react-native';
import { renderHook } from '@testing-library/react-hooks'; …
```
> Add declaration for toHaveAnimatedStyle to use custom matcher in TS files

- src/reanimated2/js-reanimated/index.ts
> Fix typo in warning message

- Example/ios/Podfile.lock
- package.json
Release 2.7.0
Build: https://github.com/software-mansion/react-native-reanimated/actions/runs/2149552919
> Release 2.7.0

- docs/docs/api/hooks/useAnimatedSensor.md
- docs/sidebars.js
- docs/versioned_docs/version-2.5.x/api/hooks/useAnimatedSensor.md
- docs/versioned_sidebars/version-2.5.x-sidebars.json
I will add documentation for the `useAnimatedSensor` hook.
> Docs [3] useAnimatedSensor

- jest.config.js
Fixes jest tests failures when using node 18.
> Fix jest tests

- createNPMPackage.sh
- package.json
Reanimated v3 no longer required the building of binaries so we can simplify the script.
> Update npm building script

- .github/workflows/android-build.yml
- FabricExample/patches/react-native-gesture-handler+2.4.2.patch
- FabricExample/patches/react-native-safe-area-context+4.2.5.patch
- FabricExample/patches/react-native-screens+3.13.1.patch
- android/build.gradle
> Build FabricExample only for arm64-v8a

- docs/docs/api/animations/withDecay.md
- react-native-reanimated.d.ts
- src/reanimated2/animation/decay.ts
I added a new parameter to `withDecay` animation:
https://user-images.githubusercontent.com/36106620/168560831-0ccb4092-50a1-491c-8f75-65b0cb0155d8.mov
https://user-images.githubusercontent.com/36106620/168560869-a277860d-b2ec-42c6-8841-3ed89785fede.mov
```js
withDecay({
clamp: [10, 100],
velocity: 200,
rubberBandEffect: true, // <-- flag
rubberBandFactor: 0.6, // <-- optional config
});
```
<details>
<summary>Example code</summary>
```js
import Animated, { useSharedValue, withDecay, useAnimatedStyle } from 'react-native-reanimated';
import { StyleSheet, Button, View } from 'react-native';
export default function ScrollViewExample() {
const position = useSharedValue(0.000001);
return {
transform: [{
translateX: …
```
> withDecay - add rubber band effect

- android/CMakeLists.txt
- android/build.gradle
Adds wildcards in CMakeLists.txt so we no longer need to list every single *.cpp file.
> Add wildcards in CMakeLists.txt

- docs/docs/api/LayoutAnimations/KeyframeAnimations.md
- docs/versioned_docs/version-2.3.x/api/LayoutAnimations/KeyframeAnimations.md
- docs/versioned_docs/version-2.5.x/api/LayoutAnimations/KeyframeAnimations.md
Fixing issues in code examples of KeyframeAnimations docs 
- Made changes to main docs file and two versioned docs files
> Add bracket to KeyframeAnimations docs

- docs/docs/fundamentals/installation.md
- docs/versioned_docs/version-2.5.x/fundamentals/installation.md
Fixed a typo in the installation docs
Fixed a typo in the installation docs
n/a
> Fixed typo.

- .github/workflows/build-release-npm-package-rea2.yml
- .github/workflows/build-release-npm-package-rea3.yml
- .github/workflows/build-release-npm-package.yml
I added to CI release package build script possibility to building Reanimated 2 because there was only possible to build Reanimated 3.
> Update CI release build

- android/CMakeLists.txt
Port of https://github.com/software-mansion/react-native-reanimated/pull/3315 to Reanimated v2 branch
> Improve linking common shared libraries for Hermes & JSC in CMakeLists.txt #3315

- android/build.gradle
Without this option Android builds with new architecture are broken:
```
Execution failed for task ':app:mergeReleaseNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
> 2 files found with path 'lib/arm64-v8a/libfolly_runtime.so' from inputs:
- /builds/--/mobile-v2/node_modules/react-native-reanimated/android/build/intermediates/library_jni/release/jni/arm64-v8a/libfolly_runtime.so
- /root/.gradle/caches/transforms-3/555a304f50e4429505632401978f848e/transformed/jetified-react-native-0.69.0-release/jni/arm64-v8a/libfolly_runtime.so
If you are using jniLibs and CMake IMPORTED targets, see
https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```
- Add exclude for `libfolly_runtime.so` …
> Add native lib exclude on Android

- Example/android/app/build.gradle
- Example/android/build.gradle
- Example/ios/Podfile
- Example/package.json
- Example/yarn.lock
Update react-native version to `0.69` in the Example app. These changes are necessary for the `Reanimated2` branch.
> Update react-native version to `0.69` in Example app

- react-native-reanimated.d.ts
- src/reanimated2/js-reanimated/JSReanimated.ts
I added the missing implementation native function for the web and I added the missing types declaration in the `d.ts` file.
> useAnimatedKeyboard mock for web

- .github/workflows/docs-check.yml
- docs/docusaurus.config.js
- docs/package.json
- docs/yarn.lock
This PR updates Docusaurus to the newest available version.
> chore: bump docusaurus version

- docs/docs/fundamentals/shared-values.md
- docs/versioned_docs/version-2.0.x/shared-values.md
- docs/versioned_docs/version-2.1.x/shared-values.md
- docs/versioned_docs/version-2.2.x/shared-values.md
- docs/versioned_docs/version-2.3.x/fundamentals/shared-values.md
- docs/versioned_docs/version-2.5.x/fundamentals/shared-values.md
Fixes #3424.
- Fixed spring animation example in shared values fundamentals in docs
> Fix spring animation example in shared values fundamentals in docs

- docs/docusaurus.config.js
This PR eliminates the following warning when running Docusaurus:
```
[WARNING] Docusaurus config validation warning. Field "url": the url is not supposed to contain a sub-path like '/react-native-reanimated/', please use the baseUrl field for sub-paths
```
by removing `/react-native-reanimated/` from `url` field in `docusaurus.config.js`.
> URL for your website. This can also be considered the top-level hostname. For example, `https://facebook.github.io` is the URL of https://facebook.github.io/metro/, and `https://docusaurus.io` is the URL for https://docusaurus.io/ This field is related to the [`baseUrl`](https://docusaurus.io/docs/api/docusaurus-config#baseUrl) field.
https://docusaurus.io/docs/api/docusaurus-config#url
> Base URL for your site. Can be considered as the path after the …
> Fix URL in Docusaurus config

- docs/package.json
- docs/yarn.lock
This PR bumps Docusaurus from `2.0.0.rc-1` to `2.0.1`.
> Bump Docusaurus to 2.0.1

- mock.js
Added missed FlatList component in mocks file
> fix: missed FlatList component in mocks

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/workflows/close-when-stale.yml
- .github/workflows/needs-more-info.yml
- .github/workflows/needs-repro.yml
- .github/workflows/platforms.yml
The goal of this PR is to unify labels throughout Software Mansion React Native Open Source projects.
This PR also simplifies cache in actions and updates the` bug-report.yml` issue template
> chore: fix github actions bot and unify labels

- .github/ISSUE_TEMPLATE/bug-report.yml
Just a typo
Fixed the typo
--
--
> chore: typo in issue template

- Common/cpp/SharedItems/ShareableValue.cpp
This PR improves the user experience of error handling in worklets on iOS.
Previously, when `JSError` was thrown in `useAnimatedStyle`, the only error message was `Javascript worklet error`. 😢 
After the changes, the original error message along with stack trace is available. 🥳  
|:-:|:-:|
| <img width="505" alt="Zrzut ekranu 2022-08-26 o 11 32 17" src="https://user-images.githubusercontent.com/20516055/186878341-99c721dc-8fac-4eda-a47a-69ee71d3bd2f.png"> | <img width="505" alt="Zrzut ekranu 2022-08-26 o 11 57 31" src="https://user-images.githubusercontent.com/20516055/186879362-78b6d22e-8a6c-4529-b0cc-9f5a4bd0f858.png"> |
- Show original error message when `useAnimatedStyle` worklet throws
1. Replace `Example/src/App.tsx` with the following example:
```tsx
import React …
```
> Show original error message when `useAnimatedStyle` throws error

- Common/cpp/Fabric/FabricUtils.cpp
- Common/cpp/NativeModules/NativeReanimatedModuleSpec.h
- Common/cpp/Tools/JSIStoreValueUser.cpp
- Common/cpp/Tools/ReanimatedHiddenHeaders.h
- RNReanimated.podspec
- android/CMakeLists.txt
- android/build.gradle
- android/src/main/java/com/swmansion/reanimated/keyboardObserver/ReanimatedKeyboardEventListener.java
- ios/native/REAInitializer.h
- ios/native/REAInitializer.mm
- ios/native/UIResponder+Reanimated.mm
This PR renames and deduplicates variables in build scripts.
The motivation behind this PR is that in CMakeLists.txt we set `REACT_NATIVE_TARGET_VERSION` and `RNVERSION` which should always be identical. Also, both variables are used in C++ sources.
`RNReanimated.podspec`
* `reactVersion` &rarr; `reactNativeVersion`
* `reactJson` &rarr; `reactNativePackageJson`
* `rnVersion` &rarr; `reactNativeMinorVersion` (as integer)
* `'-DRNVERSION=' + rnVersion` &rarr; `'-DREACT_NATIVE_MINOR_VERSION=' + reactNativeMinorVersion.to_s`
* `reactVersion.match(/^0.62/)` &rarr; `reactNativeMinorVersion == 62`
`build.gradle`, `CMakeLists.txt`
* `RNVERSION` &rarr; `REACT_NATIVE_MINOR_VERSION`
* `REACT_NATIVE_TARGET_VERSION` &rarr; `REACT_NATIVE_MINOR_VERSION`
* `rnMinorVersion` &rarr; …
> Unify variables related to React Native version

- FabricExample/App.tsx
- FabricExample/src/OverlappingBoxesExample.tsx
This PR adds reproduction of #3584 to FabricExample app.
https://user-images.githubusercontent.com/20516055/191202214-b472a89c-e7a6-426e-90cf-a9d8b22b61d4.mov
> Add overlapping boxes example

- src/index.web.ts
Fixes #3623
Export reanimated1 API from index.web.ts
> Fix missing Reanimated 1 API on web (#3623)

- docs/docs/guide/debugging.mdx
This PR does exactly what's in the title.
> Rename "Debugging worklets" section

- package.json
Add missing file reanimated_utils.rb to npm package
> Add reanimated_utils.rb to package

- .github/workflows/validate-java.yml
We want to trigger CI with java validation on changes in build.gradle file also.
> Trigger Validate Java CI on changes in build.gradle file

- package.json
This PR adds file `scripts/reanimated_utils.rb` to `files` list in `package.json` which was added in Reanimated2 branch but is still missing on main branch.
> Add missing `scripts/reanimated_utils.rb` in package.json

- package.json
- src/reanimated2/hook/useScrollViewOffset.ts
Fixes #3703.
This require cycle was not detected in `src/` directory so I've added `lib/` directory to checked paths as well.
> Fix require cycle in `useScrollViewOffset`

- Example/README.md
> Update README.md for Example app

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
> Release 3.0.0-rc.4

- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/yarn.lock
- package.json
- yarn.lock
Update react-native version to 0.70.5 after issue in react-native release https://github.com/facebook/react-native/issues/35210
> Update react-native version to 0.70.5

- .github/workflows/build-on-windows.yml
CI to test build app with Reanimated on Windows operation system.
> CI - Build Reanimated on Windows

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
Release 3.0.0-rc.5
React Native version tester result: https://github.com/piaskowyk/reanimated-rn-version-tester/actions/runs/3440289033
> Release 3.0.0-rc.5

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
> Release 3.0.0-rc.6

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- FabricExample/yarn.lock
- TVOSExample/ios/Podfile.lock
- package.json
> Release 3.0.0-rc.8

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
- ios/LayoutReanimation/REAAnimationsManager.m
Reverts software-mansion/react-native-reanimated#3866
> Revert "Get rid of sharedViews"

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
Release 3.0.0-rc.9
Package build: https://github.com/software-mansion/react-native-reanimated/actions/runs/3757527250
> Release 3.0.0-rc.9

- Common/cpp/Tools/ReanimatedVersion.cpp
- Common/cpp/Tools/ReanimatedVersion.h
- android/src/main/cpp/NativeProxy.cpp
- ios/REAModule.mm
- ios/native/REAInitializer.mm
This PR eliminates code duplication introduced in #3810.
Just run Example and FabricExample apps on Android and iOS.
> Move `REANIMATED_VERSION` definition to ReanimatedVersion.h

- src/reanimated2/layoutReanimation/animationBuilder/commonTypes.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Bounce.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Lightspeed.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Roll.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Slide.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Zoom.ts
Fixes https://github.com/software-mansion/react-native-reanimated/issues/3689
Run `DefaultAnimations` example, change device orientation, run for example `SlideInLeft` animation.
> Support device orientation change in default layout animations

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
This PR fixes a crash on Fabric in `ensureYogaChildrenAlighment`.
Original crash:
After moving `shadowTreeCloner.updateYogaChildren();` to the scope with the lock:
After 619a6a02479669d3e85793d27d13bb1ffa27aa4c I was no longer able to reproduce the crash.
1. Change number of circles in BokehExample to 500
2. Launch FabricExample
3. Reload the app a few times with an interval of 2 seconds
> Keep `NewestShadowNodesRegistry` lock for longer

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
Just update of package.json before release.
Package build: https://github.com/software-mansion/react-native-reanimated/actions/runs/3883993156
> Release 3.0.0-rc.10

- Example/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
`package.json` update before release
> Release 2.14.1

- Common/cpp/SharedItems/Shareables.h
Just a rename.
Just check if it compiles.
> Rename `dataAccessLock_` to `dataAccessMutex_`

- src/reanimated2/platform-specific/checkVersion.ts
This PR provides a better error message in cases like #3943.
> Raise error when `cppVersion` is undefined

- Example/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- createNPMPackage.sh
- package.json
This PR bumps version in package.json as well as updates Podfile.locks in Example and TVOSExample.
> Release 2.14.2

- src/reanimated2/js-reanimated/JSReanimated.ts
Applied requested changes to #3955 after late code review. 
- Removed unnecessary if condition inside callback.
- Fixed unit conversion bug
- Chrome on the android device.
> Fix small bugs in useAnimatedSensor for web

- Example/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
This PR bumps version in package.json as well as updates Podfile.locks in Example and TVOSExample.
> Release 2.14.3

- src/reanimated2/hook/useAnimatedStyle.ts
Reverts software-mansion/react-native-reanimated#3950
> Revert "Optimize previous style calculation in `styleUpdater`"

- FabricExample/App.tsx
- FabricExample/src/ArticleProgressExample.tsx
- docs/docs/api/hooks/useScrollViewOffset.md
- src/reanimated2/hook/useScrollViewOffset.ts
This PR applies code review suggestions from #3438.
Build Example app and check if Article progress example works.
> Various `useScrollViewOffset` improvements

- docs/docs/fundamentals/animations.md
- docs/versioned_docs/version-2.0.x/animations.md
- docs/versioned_docs/version-2.1.x/animations.md
- docs/versioned_docs/version-2.2.x/animations.md
- docs/versioned_docs/version-2.3.x/fundamentals/animations.md
- docs/versioned_docs/version-2.5.x/fundamentals/animations.md
small spelling mistake correction in docs
Not applicable, since change is in docs
> small spell correction

- FabricExample/App.tsx
Before:
https://user-images.githubusercontent.com/20516055/216360767-1fb30308-d7d7-40cc-8c08-434d6c94e2a6.mov
After:
https://user-images.githubusercontent.com/20516055/216360979-dfb6e9cd-9a12-48fe-91db-31ff5f29ab15.mov
Launch FabricExample on Android and iOS.
> Fix blank spots in examples list in FabricExample

- Common/cpp/Tools/JsiUtils.h
This PR fixes formatting after changes in #4027.
Check if CI is green.
> Format JsiUtils.h

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/NativeModules/NativeReanimatedModule.h
- Common/cpp/Tools/PlatformDepMethodsHolder.h
- src/reanimated2/globals.d.ts
Follow-up to #4020.
Check if Conditional demo from FabricExample works.
> Use consistent argument names and types in `_removeShadowNodeFromRegistry`

- Common/cpp/Tools/JsiUtils.cpp
- Common/cpp/Tools/JsiUtils.h
- android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/java/com/swmansion/reanimated/Utils.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/NativeMethodsHolder.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/Snapshot.java
- android/src/paper/java/com/swmansion/reanimated/NativeProxy.java
- ios/LayoutReanimation/REAAnimationsManager.m
- ios/LayoutReanimation/REAScreensHelper.h
- ios/LayoutReanimation/REAScreensHelper.m
- ios/LayoutReanimation/REASharedTransitionManager.m
- ios/LayoutReanimation/REASnapshot.m
- ios/native/NativeProxy.mm
- src/reanimated2/layoutReanimation/sharedTransitions/index.ts
This PR provides support for shared transition in modal screens and support for transform animations.
previous version: https://github.com/software-mansion/react-native-reanimated/pull/3994
> [Shared Element Transition] Added shared transition support for modal screens

- package.json
For correctness of npm build. Follow up to #4067.
> Amend package.json for 'plugin/' instead of 'plugin.js'

- Example/src/App.tsx
After navigation upgrade we need to add gesture handler RootView manually.
> Add gesture handler RootView to Example app

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
Not every ViewManager can be ViewGroupManager, so I added additional check to prevent app crashes.
> Fix ViewGroupManager cast

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
- src/reanimated2/platform-specific/checkVersion.ts
Release 3.0.0 🎉
Package build: https://github.com/software-mansion/react-native-reanimated/actions/runs/4283227194
> Release 3.0.0 🎉

- src/createAnimatedComponent.tsx
- src/reanimated2/layoutReanimation/animationsManager.ts
Added missing null checks in release of Reanimated 3.0.0
Fixes #4153
> Added missing null checks

- .github/workflows/static-example-apps-checks.yml
- FabricExample/react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
> Fix TypeScript tests after .d.ts cleanup

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
- src/reanimated2/platform-specific/checkVersion.ts
> Release 3.0.1

- react-native-reanimated.d.ts
* Add missing `InterfaceOrientation`
* Restore missing`EasingFunction`
* Remove `Animated.Extrapolate` from .d.ts
> Fix .d.ts again

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
- src/reanimated2/platform-specific/checkVersion.ts
Package build: https://github.com/software-mansion/react-native-reanimated/actions/runs/4357058927
> Release 3.0.2

- docs/docs/api/hooks/useAnimatedProps.md
> Fix a typo

- Example/.eslintrc.js
- Example/package.json
- Example/src/AnimatedScrollExample.tsx
- Example/src/ColorInterpolationExample.tsx
- Example/src/CubesExample.tsx
- Example/src/LayoutReanimation/WaterfallGridExample.tsx
- Example/src/LightboxExample.tsx
- Example/src/MeasureExample.tsx
- Example/src/ReactionsCounterExample.tsx
- Example/src/ScrollToExample.tsx
- Example/src/WebSpecific/LightBoxExample.tsx
- Example/yarn.lock
> Properly setup ESLint and fix lint errors in Example app

- ios/native/NativeMethods.mm
- ios/native/NativeProxy.mm
- ios/native/REAIOSErrorHandler.mm
- ios/native/REAIOSLogger.mm
- ios/native/REAIOSScheduler.mm
- ios/native/REAInitializer.mm
- ios/native/REAMessageThread.mm
Run `yarn format:ios`.
Check if Example and FabricExample builds successfully on iOS.
> Add missing end namespace comments

- .github/workflows/build-on-windows.yml
- .github/workflows/close-when-stale.yml
- .github/workflows/docs-check.yml
- .github/workflows/main.yml
- .github/workflows/needs-more-info.yml
- .github/workflows/needs-repro.yml
- .github/workflows/platforms.yml
- .github/workflows/static-example-apps-checks.yml
- .github/workflows/static-root-checks.yml
- .github/workflows/validate-cpp.yml
- .github/workflows/validate-java.yml
- .github/workflows/validate-plugin.yml
This PR performs the following bumps:
* `actions/checkout@v3`
* `actions/cache@v3`
* `actions/setup-java@v3`
* `actions/setup-python@v4`
Just see if the CI is green.
> Bump actions to latest versions

- Example/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
> Release 2.15.0

- .github/workflows/build-npm-package-action.yml
> Remove size check CI on Reanimated2

- FabricExample/App.tsx
- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/patches/react-native-box2d+0.2.5.patch
- FabricExample/src/BillardExample.tsx
- FabricExample/src/BilliardExample.tsx
- FabricExample/yarn.lock
This PR adds billards game demo in FabricExample.
https://twitter.com/tomekzaw_/status/1638919959081254912
🎱
> Billiard example

- package.json
- yarn.lock
Fixes [#132](https://github.com/release-it/release-it/blob/main/docs/dry-runs.md) from Dependabot
It wasn't used anyway.
> [Dependabot] Fix critical #132

- .github/workflows/android-build.yml
- .github/workflows/build-monorepo.yml
- .github/workflows/build-on-windows.yml
- .github/workflows/build-v8.yml
- .github/workflows/docs-check.yml
- .github/workflows/ios-build.yml
- .github/workflows/static-example-apps-checks.yml
- .github/workflows/static-root-checks.yml
- .github/workflows/tvos-build.yml
- .github/workflows/validate-cpp.yml
- .github/workflows/validate-ios.yml
- .github/workflows/validate-java.yml
- .github/workflows/validate-plugin.yml
Added `merge_group` event to workflows that are running for pull requests to prevent merging outdated code.
> Add merge_group event to github workflows

- Example/ios/Podfile.lock
- FabricExample/ios/.xcode.env
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- TVOSExample/yarn.lock
- package.json
- src/reanimated2/platform-specific/jsVersion.ts
Update of package.json before release of 3.1.0 🐎
> Release 3.1.0 🐎

- Example/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
> Release 2.17.0

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
> Simple code cleanup - remove unused function parameter

- src/reanimated2/commonTypes.ts
- src/reanimated2/hook/commonTypes.ts
- src/reanimated2/hook/useAnimatedGestureHandler.ts
- src/reanimated2/hook/useAnimatedScrollHandler.ts
- src/reanimated2/hook/utils.ts
> Rename Context type and explain typing code bits

- .github/workflows/build-npm-package-action.yml
> Publish on npm only when flag is enabled

- src/reanimated2/animation/spring.ts
<table>
<tr><td>BEFORE</td><td>AFTER</td></tr>
<tr><td>
https://github.com/software-mansion/react-native-reanimated/assets/56199675/1ab3bab9-b6cc-4524-a9a4-dd5fc3d2583b
</td><td>
https://github.com/software-mansion/react-native-reanimated/assets/56199675/d838c02a-217f-4d87-b1fa-22cd733ca413
</td></tr>
</table>
Run "Chat Heads" example
> Fix spring bug

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
- src/reanimated2/platform-specific/jsVersion.ts
Update of package.json and lock files.
> Release 3.2.0 🐎

- src/reanimated2/component/ScrollView.tsx
> Add React import

- docs/docs/api/SharedElementTransitions.md
- docs/src/pages/index.js
Fix sharedElementTransitions link in the documentation
> docs: fix example link

- ios/RCTEventDispatcher+Reanimated.h
- ios/RCTEventDispatcher+Reanimated.m
This PR fixes a typo introduced by me in #4576.
> Fix typo in `reanimated_sendEvent`

- src/reanimated2/js-reanimated/JSReanimated.ts
> Remove duplicate import

- android/build.gradle
This allows changing the ndk version used to build this.
Tested by using a different ndk version in an app.
> Allow setting ndk path/version

- src/reanimated2/animation/util.ts
> Provide correct types to prevent implicit casting boolean to integer

- android/src/fabric/java/com/swmansion/reanimated/ReaCompatibility.java
- android/src/paper/java/com/swmansion/reanimated/ReaCompatibility.java
This PR renames `nodeManager` to `nodesManager` to match the name of the class.
> Fix typo in `nodesManager`

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
I am going to rewrite a comment that had typo
I am not going to test it at all 😝
> Fix typo in comment

- ios/native/NativeProxy.mm
> Fix React-Fabric imports with `USE_FRAMEWORKS=static`

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
- android/src/reactNativeVersionPatch/nativeHierarchyManager/latest/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
This PR fixes some Java warnings related to Layout Animations / Shared Element Transitions.
> Fix some Java warnings

- ios/LayoutReanimation/REASharedTransitionManager.m
- ios/LayoutReanimation/REASwizzledUIManager.mm
- ios/REAUtils.h
- ios/REAUtils.m
This PR combines the swizzling methods in the codebase. Before, we had two `swizzleMethod` functions that had the exact same implementation.
Open example with SET
> Unify `swizzleMethod`

- src/reanimated2/animation/spring.ts
- src/reanimated2/animation/springUtils.ts
Fixed a couple of typos in withSpring internal code
It's not part of the public API so it should be cool, right?
> Fix typos in withSpring internal code

- android/src/main/cpp/NativeProxy.h
> Rename `rt` to `rnRuntime`

- Common/cpp/Tools/Scheduler.cpp
- Common/cpp/Tools/Scheduler.h
- Common/cpp/Tools/ThreadSafeQueue.h
- android/src/main/cpp/AndroidScheduler.cpp
- android/src/main/cpp/AndroidScheduler.h
- android/src/main/java/com/swmansion/reanimated/Scheduler.java
- ios/native/REAIOSScheduler.mm
This PR introduces a few minor improvements in `Scheduler` class before a great refactor. Feel free to review commits one-by-one.
1. BokehExample + <kbd>r</kbd>
2. runOnUI / runOnJS example
> Minor improvements in Scheduler

- android/build.gradle
not a big PR but noticing that some of the string literals are just the variable on top so i'm DRYing up the string literals.
build.gradle should still run correctly
> DRY up build.gradle variables

- app/src/examples/AnimatedTabBarExample.tsx
- app/src/examples/ExtrapolationExample.tsx
- app/src/examples/MatrixTransform.tsx
- app/src/examples/SharedElementTransitions/RestoreState.tsx
This PR fixes some regression in our examples introduced in https://github.com/software-mansion/react-native-reanimated/pull/4672 PR.
|Before|After|
|---|---|
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/a711194f-d699-4445-9d54-c7e80e373a9e" /> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/9a81ff19-d5cd-45f5-9f32-a12b3e6446f4" /> |
|Before|After|
|---|---|
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/948a6b28-370b-4da1-a0d7-9bb757026f9f" /> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/64bd05fa-1549-41f7-bffb-7a22d530cb66" /> |
|Before|After|
|---|---|
| <video …
> Fix examples

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
- src/reanimated2/platform-specific/jsVersion.ts
Release 3.4.0 <img src="https://cdn3.emoji.gg/emojis/2747_PartyParrot.gif" height="24px" alt="PartyParrot" />
Package build: ✅ https://github.com/software-mansion/react-native-reanimated/actions/runs/5656199880
RN version tester: ✅ (0.64 - 0.72) https://github.com/piaskowyk/reanimated-rn-version-tester/actions/runs/5653190770
> Release 3.4.0 🐎

- ios/native/NativeProxy.mm
This PR removes two redundant folly `#include`s.
CI check is sufficient
> Remove unused folly headers

- src/reanimated2/animation/transformationMatrix/matrixUtils.tsx
- src/reanimated2/animation/util.ts
According to this react-native issue [LINK](https://github.com/facebook/react-native/issues/31704) there is no support for Logical OR and AND assignment `||=` `&&=`, unless you use `@babel/plugin-proposal-logical-assignment-operators`. To simplify setup of our library we should remove all logical assignments (especially that according to [this issue](https://github.com/software-mansion/react-native-reanimated/issues/4825) adding babel plugins doesn't help). Closes #4825.
I've tested [this app](https://github.com/CavanWagg/react-native-reanimated-error) on Android and IOS. On IOS always everything works, however android app crashes without this fix, exactly as described in the issue.
> Fix "Unexpected token "=" error"

- android/CMakeLists.txt
- android/build.gradle
This PR removes legacy stuff from build.gradle which is no longer needed for Reanimated 3.
Co-authored-by: Krzysztof Piaskowy <krzysztof.piaskowy@swmansion.com>
> Remove Reanimated 2 logic from build.gradle

- .husky/pre-commit
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. to pre-commit
Add `yarn find-unused-code:js` to pre-commit.
Commit changes and see that nothing explodes :boom:
> Add `yarn find-unused-code:js` to pre-commit

- app/src/examples/LayoutAnimations/DefaultAnimations.tsx
- app/src/examples/index.ts
This PR does two things:
1. Moves empty example at top of the main list, so it is easier to access while we test new things
2. Adds `userSelect: none;` to DefaultLayoutAnimations example, because sometimes it blocks exiting animation
Tested on example app
> Move empty example at top and add `userSelect: none;`

- docs/src/theme/Navbar/MobileSidebar/Layout/index.js
> Fix landing docs crash on mobile

- src/reanimated2/PlatformChecker.ts
This pull request introduces support for react-native-windows! 🎉 However, please note that it does not include native support. Instead, it enables the web implementation of Reanimated for the Windows platform.
Kudos to [@hsjoberg](https://github.com/hsjoberg) because his PR [#4669](https://github.com/software-mansion/react-native-reanimated/pull/4669) was an inspiration for this one! 🙌
```
npx react-native init reanimatedWindows --version "latest"
cd reanimatedWindows
npx react-native-windows-init --overwrite
yarn add react-native-reanimated
npx react-native run-windows
```
> Add basic JS implementation support for react-native-windows 🎉

- src/reanimated2/js-reanimated/index.ts
Since react-native-web 19 `textShadow` props are not animating properly. This PR aims to fix that problem.
Fixes #4903 
Tested on repo from [this issue](https://github.com/software-mansion/react-native-reanimated/issues/4903) on different react-native-web versions
> Fix text shadow not animating

- .github/FUNDING.yml
We want to show the funding button we recently enabled on the organisation for all our repositories.
> Create FUNDING.yml to enable sponsor button

- src/reanimated2/UpdateProps.ts
- src/reanimated2/helperTypes.ts
- src/reanimated2/hook/Hooks.ts
- src/reanimated2/hook/useAnimatedStyle.ts
- src/reanimated2/js-reanimated/index.ts
This PR changes behavior of `useAnimatedProps` so that props get updated properly on web.
Fixes #4909
Tested on [example from issue](https://github.com/apatozi/issue-reanimated-useanimatedprops-web).
> Fix `useAnimatedProps` on web

- app/src/examples/LogExample.tsx
```diff
-Test failed, expected "42", "got 43"
+Test failed, expected "42", got "43"
```
> Fix error message in LogExample

- Common/cpp/SharedItems/Shareables.cpp
- Common/cpp/SharedItems/Shareables.h
This PR moves implementation of shareables from `.h` to `.cpp` file in order to fix `dynamic_cast` across shared library boundaries on Android when using Reanimated with other third-party libraries, e.g. VisionCamera.
* `Shareable` &ndash; already had empty virtual destructor
* `RetainingShareable` &ndash; moved implementation of `getJSValue` to .cpp
* `ShareableJSRef` &ndash; added empty virtual destructor
* `ShareableArray` &ndash; moved implementation of `toJSValue` to .cpp
* `ShareableObject` &ndash; moved implementation of `toJSValue` to .cpp
* `ShareableHostObject` &ndash; moved implementation of `toJSValue` to .cpp
* `ShareableHostFunction` &ndash; moved implementation of `toJSValue` to .cpp
* `ShareableWorklet` &ndash; moved implementation of `toJSValue` to .cpp
* …
> Fix dynamic_cast (RTTI) by adding key function to shareables

- src/animationBuilder.tsx
I've forgot that empty array is evaluated as true, so I have to fix the condition.
> Warning fix

- Common/cpp/Fabric/FabricUtils.cpp
- Common/cpp/Fabric/FabricUtils.h
- Common/cpp/NativeModules/NativeReanimatedModule.cpp
Removed unnecessary code in FabricUtils and added two checks for RN >= 0.72
Check if CI passes, no logical changes
> Cleaned up FabricUtils

- src/createAnimatedComponent.tsx
Don't warn against overwriting styles in case of layout animation, since most of use cases are valid
Tested with entering, layout and exiting animations
> Don't warn against overwriting styles in case of layout animation

- apple/REAModule.mm
This PR add support for Reduce Motion setting on macOS platform  by checking `accessibilityDisplayShouldReduceMotion` property from `NSWorkspace`.
Tested with `Reduced Motion` example.
> Add reduce motion on macOS

- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensorListener.java
This PR fixes the accelerometer type used in the listener on android.
Check `useAnimatedSensor - accelerometer` example
> Fix accelerometer on android

- app/src/examples/SetNativePropsExample.tsx
- docs/docs/advanced/dispatchCommand.mdx
- docs/docs/advanced/setNativeProps.mdx
- docs/src/examples/SetNativeProps.jsx
- docs/src/theme/DocSidebarItems/index.js
This PR documents the new  `setNativeProps` function added in https://github.com/software-mansion/react-native-reanimated/pull/4595
https://github.com/software-mansion/react-native-reanimated/assets/39658211/32ab57fa-37a5-4e3e-abfb-2afdf1a99157
```sh
cd docs
yarn
yarn start
```
> Add `setNativeProps` docs

- src/reanimated2/NativeMethods.ts
fixes https://github.com/software-mansion/react-native-reanimated/issues/5061
> fix ReferenceError: Property '_IS_FABRIC' doesn't exist

- docs/docs/advanced/createWorkletRuntime.mdx
- docs/docs/threading/createWorkletRuntime.mdx
- docs/docs/threading/runOnJS.mdx
- docs/docs/threading/runOnUI.mdx
- docs/src/theme/DocSidebarItems/index.js
This PR adds documentation for `createWorkletRuntime` function added in #4944.
> Add `createWorkletRuntime` docs

- app/src/examples/ChatHeadsExample.tsx
- docs/docs/utilities/clamp.mdx
- docs/docs/utilities/getRelativeCoords.mdx
- docs/docs/utilities/interpolateColor.mdx
- docs/src/examples/Clamp.jsx
- src/reanimated2/interpolation.ts
This PR adds documentation for `clamp` utility function added in https://github.com/software-mansion/react-native-reanimated/issues/4960
https://github.com/software-mansion/react-native-reanimated/assets/39658211/fbc009f1-e12c-4944-bcd4-0ac1048ea36a
> Add `clamp` docs

- docs/docs/core/useSharedValue.mdx
Added note about handling objects in shared values
Thanks to @cdehaan for pointing this out! 🎖️ 
Supersedes https://github.com/software-mansion/react-native-reanimated/pull/5037
> Document storing objects in shared values

- src/reanimated2/hook/index.ts
- src/reanimated2/hook/useAnimatedGestureHandler.ts
- src/reanimated2/hook/useAnimatedProps.ts
- src/reanimated2/hook/useAnimatedScrollHandler.ts
- src/reanimated2/hook/useEvent.ts
- src/reanimated2/hook/useHandler.ts
- src/reanimated2/hook/useScrollViewOffset.ts
- src/reanimated2/hook/useWorkletCallback.ts
- src/reanimated2/hook/utils.ts
_This PR is made only to split #5056 to separate PRs for review comfort._
Hooks were cramped together for a long time. Let's allow them to be in separate files. This PR only does the split.
> Properly type event hooks [0/9]

- src/reanimated2/hook/useAnimatedStyle.ts
Something weird happened with GitHub's automerge and `Files changed` in that PR is weird & some changes disappeared.
Reverts software-mansion/react-native-reanimated#5079
> Revert "Properly type event hooks [2/9]"

- Common/cpp/ReanimatedRuntime/WorkletRuntime.cpp
- Common/cpp/ReanimatedRuntime/WorkletRuntimeDecorator.cpp
This PR fixes the following error when building Reanimated for iOS:
🟢
> Fix "'folly/logging/LogCategory.h' file not found"

- app/src/examples/LayoutAnimations/AnimatedList.tsx
While doing tests on this example I've found it really frustrating that input doesn't have default value, so I've decided to add it.
Tested on Participant List example.
> Add default initial value to Participant List example

- .github/workflows/build-next-example.yml
- NextExample/.gitignore
- NextExample/cypress.config.ts
- NextExample/cypress/e2e/simpleAnimationTest.cy.ts
- NextExample/package.json
- NextExample/pages/index.js
- NextExample/pages/test.js
- NextExample/yarn.lock
This PR adds e2e tests for web. Tests are implemented with cypress.
Check if the test passes, then change the target width in `test.js` and check that the test doesn't pass. Execute `yarn build` to build `NextExample` and then run `yarn e2e:headless` to start tests.
> Add e2e tests in NextExample

- package.json
This PR removes old unused code from package.json
> Small cleanup of package.json

- docs/docs/utilities/interpolate.mdx
docs: Added import for `Extrapolation` in interpolate
> fix: extrapolation import

- src/reanimated2/PlatformChecker.ts
While working on refactor of `animationsManager.ts` file typescript threw error that I cannot assign `{}` to `boolean`. Even though refreshing window helped, we decided to keep this cast.
Checked that `reducedMotion` hook works.
> Add boolean cast into `reducedMotion`

- .eslintrc.js
- src/reanimated2/layoutReanimation/defaultTransitions/EntryExitTransition.ts
Enforce always using braces after if
```diff
- if(condition)
-    return true
+ if(condition){
+    return true
+ }
```
> Add eslint rule 'curly'

- package.json
> Remove plugin's .map file in package

- src/reanimated2/SetNativeProps.ts
- src/reanimated2/platformFunctions/dispatchCommand.ts
- src/reanimated2/platformFunctions/dispatchCommand.web.ts
- src/reanimated2/platformFunctions/measure.ts
- src/reanimated2/platformFunctions/scrollTo.ts
- src/reanimated2/platformFunctions/setGestureState.ts
This PR changes the `platformFunctions` (and `setNativeProps`) code to make it more readable.
> Refactor `platformFunctions`

- Common/cpp/SharedItems/Shareables.h
- Common/cpp/Tools/CollectionUtils.h
> Add `const` keyword in a few places

- app/src/examples/ArticleProgressExample.tsx
This PR fixes ArticleProgressExample again. In current code, `textRef.current` is passed as a copy so it never changes and thus the example doesn't work. I've also decided to simplify the code and name intermediate results of mathematical formulas used to calculate the width of the progress bar.
cc @jfedak whom I've complained to that the example doesn't work on macOS
cc @tjzel who never believed in `clamp`
> Fix ArticleProgressExample again

- docs/README.md
- docs/docs/fundamentals/handling-gestures.mdx
- docs/versioned_docs/version-2.x/api/hooks/useAnimatedGestureHandler.md
- docs/versioned_docs/version-2.x/fundamentals/architecture.md
- docs/versioned_docs/version-2.x/fundamentals/events.md
- docs/versioned_docs/version-2.x/guide/debugging.mdx
- docs/versioned_sidebars/version-2.x-sidebars.json
- src/createAnimatedComponent/createAnimatedComponent.tsx
Make CI status great again.
url validator
> Fix broken links

- docs/src/components/InteractivePlayground/useAnimatedSensorPlayground/threejs/MathUtils.js
- docs/src/components/InteractivePlayground/useAnimatedSensorPlayground/threejs/Matrix4.js
- docs/src/components/InteractivePlayground/useAnimatedSensorPlayground/threejs/Quaternion.js
- docs/src/components/InteractivePlayground/useAnimatedSensorPlayground/threejs/Vector3.js
When implementing useAnimatedSensor docs and it's interactive playground I've left some dead links copied over from Three.js source. This PR removes all the links from three.js related codebase.
```
cd docs
yarn start
```
& 
CI
> Fix "validate urls in source code" CI

- app/src/examples/JSPropsExample.tsx
- app/src/examples/index.ts
This PR adds the example from https://github.com/software-mansion/react-native-reanimated/pull/5009 to the example app.
https://github.com/software-mansion/react-native-reanimated/assets/20516055/18353069-27c8-4a58-9ab0-19bbda16863e
> Add JSProps example

- docs/docs/fundamentals/glossary.mdx
> Fix double `Animated.ScrollView` in docs

- src/reanimated2/component/FlatList.tsx
> Remove `console.log`

- src/reanimated2/layoutReanimation/web/animationsManager.ts
- src/reanimated2/layoutReanimation/web/componentUtils.ts
- src/reanimated2/layoutReanimation/web/config.ts
This PR changes where we set component visibility at the beginning on entering animation. Moving it to `onanimationstart` prevents flickering. 
Tested on example app and provided repro:
<details>
<summary> Repro code </summary>
```jsx
import { StyleSheet, View, Text } from 'react-native';
FadeIn,
FadeInLeft,
FadeInRight,
FadeInUp,
FadeInDown,
FadeOut,
FadeOutLeft,
FadeOutRight,
FadeOutUp,
FadeOutDown,
const DELAY = 500;
const fadeAnimation = [
{
enteringName: 'FadeIn',
enteringAnimation: FadeIn,
exitingName: 'FadeOut',
exitingAnimation: FadeOut,
},
{
enteringName: 'FadeInLeft',
enteringAnimation: FadeInLeft,
exitingName: 'FadeOutLeft',
exitingAnimation: FadeOutLeft,
},
{
enteringName: 'FadeInRight', …
```
> Fix `entering` in web LA

- app/src/examples/index.ts
> Change example name to Habits

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- MacOSExample/macos/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
- src/reanimated2/platform-specific/jsVersion.ts
Release 3.6.0
Package build: https://github.com/software-mansion/react-native-reanimated/actions/runs/6982688924
> Release 3.6.0

- apple/keyboardObserver/REAKeyboardEventObserver.h
This PR removes the last include guard in our codebase.
> Remove include guard in REAKeyboardEventObserver.h

- Common/cpp/ReanimatedRuntime/ReanimatedHermesRuntime.h
> Fix "Use of undeclared identifier 'debugger'"

- .github/ISSUE_TEMPLATE/bug-report.yml
> Add build types to issue template

- docs/docs/utilities/interpolate.mdx
Fix a function in the sample code
> fix: correct typo in `interpolate.mdx`

- docs/docs/fundamentals/getting-started.mdx
Fix a minor grammatical error: "could be [...] ran" is incorrect. At minimum it should be "could be [...] run".
N/A
> [doc] Minor grammar fix

- app/src/examples/IPodExample.tsx
- app/src/examples/LayoutAnimations/DefaultAnimations.tsx
- app/src/examples/LayoutAnimations/NestedNativeStacksWithLayout.tsx
- app/src/examples/LiquidSwipe/LiquidSwipe.tsx
- app/src/examples/LiquidSwipe/Weave.tsx
- app/src/examples/LogExample.tsx
- app/src/examples/PinExample.tsx
- app/src/examples/SharedElementTransitions/Card.tsx
- app/src/examples/SharedElementTransitions/FlatList.tsx
- app/src/examples/SharedElementTransitions/ImageStack.tsx
- app/src/examples/SharedElementTransitions/Modals.tsx
- app/src/examples/SharedElementTransitions/Profiles.tsx
- app/src/examples/SharedElementTransitions/TransitionRestart.tsx
- app/src/examples/SharedStyleExample.tsx
This PR fixes most of the TS and ESLint errors in Examples.
> Fix TS and ESLint in Examples

- src/createAnimatedComponent/createAnimatedComponent.tsx
- src/reanimated2/layoutReanimation/web/componentUtils.ts
- src/reanimated2/layoutReanimation/web/config.ts
- src/reanimated2/layoutReanimation/web/domUtils.ts
Current animation cleanup mechanism has many flaws. The biggest problem is that it may cause bugs such as disappearing components, or even removing predefined animations from DOM. 
This PR introduces new approach to cleaning animations, which should solve problems mentioned above.
Tested on the code below (uncomment transform to see bugs)
<details>
<summary> Test code </summary>
```jsx
import { StyleSheet, View, Text, Pressable } from 'react-native';
FadeIn,
FadeInLeft,
FadeInRight,
FadeInUp,
FadeInDown,
FadeOut,
FadeOutLeft,
FadeOutRight,
FadeOutUp,
FadeOutDown,
RollOutLeft,
Keyframe,
const DELAY = 500;
const fadeAnimation = [
{
enteringName: 'FadeIn',
enteringAnimation: FadeIn,
exitingName: 'FadeOut', …
```
> Fix animation cleanup

- src/reanimated2/layoutReanimation/web/componentUtils.ts
#5444 introduced one trick to calculate header height. After further investigation it turned out, that we also have to use the same technique for `left` property from the snapshot. Below you can find two short videos which show the difference.
https://github.com/software-mansion/react-native-reanimated/assets/63123542/4f2ad34c-b5ab-41de-a0bb-4b1692cdd664
https://github.com/software-mansion/react-native-reanimated/assets/63123542/d237ee0c-57ea-4b5d-958a-633674bdd1f9
Tested on example app and code below
<details>
<summary> Test code </summary>
```jsx
import { StyleSheet, View, Text, Pressable } from 'react-native';
import Animated, { FadeIn, FadeOut } from 'react-native-reanimated';
const DELAY = 500;
const fadeAnimation = [
{
enteringName: 'FadeIn', …
```
> [Web LA] Update `left` from snapshot.

- .github/ISSUE_TEMPLATE/bug-report.yml
> Update versions in issue template

- docs/docs/layout-animations/layout-transitions.mdx
Layout transition docs had empty brackets, which are removed in this PR
> Layout-transition docs - Empty brackets removed

- src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts
- src/reanimated2/layoutReanimation/defaultTransitions/EntryExitTransition.ts
I'm not sure what exactly caused the types breaking but better narrowing fixes it.
CI
> Fix TypeScript nightly

- Common/cpp/ReanimatedRuntime/WorkletRuntime.cpp
- Common/cpp/ReanimatedRuntime/WorkletRuntime.h
- app/src/examples/AnimatedStyleUpdateExample.tsx
- src/reanimated2/index.ts
- src/reanimated2/initializers.ts
- src/reanimated2/js-reanimated/JSReanimated.ts
- src/reanimated2/mutables.ts
- src/reanimated2/threads.ts
This PR fixes some small issues from https://github.com/software-mansion/react-native-reanimated/pull/4300
> [Fix TS] Introduce executeOnUIRuntimeSync and use it to replace Sync Data Holder

- src/reanimated2/mutables.ts
Adding it as an answer to feedback from #5117. Fixes #5117.
🪨
> Add suggestions to errors for accessing mutable's `value`

- .github/ISSUE_TEMPLATE/bug-report.yml
Remove label "needs review" from bug report template
No tests.
> Remove label "needs review" from bug report template

- src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts
> Fix TS nightly CI

- app/src/examples/JSPropsExample.tsx
| --- | --- |
| ![Screenshot 2024-01-12 at 12 23 42](https://github.com/software-mansion/react-native-reanimated/assets/36106620/e052c02e-5604-482c-b6b0-4337c66617ab) | ![Screenshot 2024-01-12 at 12 24 46](https://github.com/software-mansion/react-native-reanimated/assets/36106620/9c59531e-55de-4323-a030-967a3f361b02) |
> Fix JSProp example on Web

- Common/cpp/LayoutAnimations/LayoutAnimationsManager.cpp
- Common/cpp/LayoutAnimations/LayoutAnimationsManager.h
- Common/cpp/NativeModules/NativeReanimatedModuleSpec.cpp
- Common/cpp/NativeModules/NativeReanimatedModuleSpec.h
- Common/cpp/Registries/EventHandlerRegistry.cpp
- Common/cpp/Registries/EventHandlerRegistry.h
- Common/cpp/SharedItems/Shareables.h
- android/src/main/cpp/TurboModule.cpp
- android/src/main/cpp/TurboModule.h
The aim of this PR is to replace passing shared pointer by value with reference passing. In addition I marked some fields as `const`.
See the CI
> Pass shared_ptr by reference

- docs/src/components/Hero/Horse/index.tsx
- docs/src/components/Hero/Horse/styles.module.css
Our hook gets produces buggy behaviour on each page refresh, so I've replaced it with css media-query.
The reduced motion warning works correcrtly.
> Fix horse with reduced motion

- app/src/examples/PlanetsExample.tsx
- app/src/examples/index.ts
This PR adds an example with animated planets.
https://github.com/software-mansion/react-native-reanimated/assets/20516055/24dd3bfc-c78b-435a-958e-d2408361965f
> Add planets example

- app/src/examples/ArticleProgressExample.tsx
Just some minor improvements in article progress example.
https://github.com/software-mansion/react-native-reanimated/assets/20516055/421d6572-6267-461a-89c2-bf05deb9a280
> Improve article progress example

- app/src/examples/BokehExample.tsx
Just some minor improvements in bokeh example.
https://github.com/software-mansion/react-native-reanimated/assets/20516055/cbf0b8b0-4529-4d24-b81b-0f8b5dd744b2
> Improve bokeh example

- app/src/examples/AmountExample.tsx
- app/src/examples/index.ts
This PR adds amount example with animated text input content.
https://github.com/software-mansion/react-native-reanimated/assets/20516055/260f3c11-c3ad-41f6-a5a0-13b0cd00706c
> Add amount example

- src/reanimated2/mock.ts
Add `SlideOutDown` to jest mocks.
> Add SlideOutDown to jest mock

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- MacOSExample/macos/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
- src/reanimated2/platform-specific/jsVersion.ts
> Release 3.7.0 🐎

- docs/docs/fundamentals/glossary.mdx
> docs: add `withClamp` animation modifier to docs glossary

- app/src/examples/LettersExample.tsx
Currently, in development the animation in Letters gets interrupted near its end and stays like this, which doesn't look right. This doesn't happen in production builds however - it seems to be related to `setInterval` repetition time parameter - making it longer makes the behavior uniform in both development and production.
💌
> [Example] Fix interrupted animation of Letters in development

- docs/docs/guides/compatibility.mdx
This PR adds version 3.7.0 to the compatibility table in the docs.
> Update compatibility table

- docs/src/components/Animations/AnimationsSection/index.tsx
- docs/src/components/Animations/AnimationsSection/styles.module.css
- docs/src/components/Hero/StartScreen/index.tsx
- docs/src/components/Hero/StartScreen/styles.module.css
- docs/src/components/HomepageButton/styles.module.css
https://github.com/software-mansion/react-native-reanimated/assets/39658211/dfb8c1f0-6734-4e40-8e91-47cee5876d94
https://github.com/software-mansion/react-native-reanimated/assets/39658211/727c0160-3847-479d-9a68-bf5d37763a3c
> docs: fix too big button hitbox on landing

- docs/src/theme/Admonition/index.js
- docs/src/theme/Admonition/styles.module.css
- docs/src/theme/MDXComponents/DetailsStyling.tsx
- docs/src/theme/MDXComponents/styles.module.css
- docs/src/theme/PaginatorNavLink/index.js
https://github.com/software-mansion/react-native-reanimated/assets/39658211/f8b0f22d-18b9-4a3b-83a7-8ab241248712
https://github.com/software-mansion/react-native-reanimated/assets/39658211/803432f3-7ecc-43fe-870c-1365e030cedc
> docs: various small fixes

- app/src/examples/WithoutBabelPluginExample.tsx
- src/reanimated2/commonTypes.ts
- src/reanimated2/hook/useAnimatedStyle.ts
- src/reanimated2/index.ts
- src/reanimated2/runtimes.ts
- src/reanimated2/shareables.ts
- src/reanimated2/threads.ts
- src/reanimated2/valueUnpacker.ts
To avoid confusion with `_WORKLET`.
🤯
> Rename `isWorklet` to `isWorkletFunction`

- package.json
This PR removes old commands from package.json
> Remove unused commands from `package.json`

- src/reanimated2/animation/delay.ts
- src/reanimated2/animation/repeat.ts
- src/reanimated2/animation/sequence.ts
Reverts software-mansion/react-native-reanimated#5647
> Revert "Fix higher-order animations re-render behaviour"

- apple/keyboardObserver/REAKeyboardEventObserver.mm
This PR optimizes curve parameters for the keyboard position estimation. The curve parameters were calculated using an optimization script that aimed to minimize approximation errors. The script consists of four stages:
- Analyzing the video to compute the keyboard frame during animations
- Calculating the average keyboard height during the animation
- Initial stage of curve approximation with a step of 0.1
- Additional stage of curve approximation with a step of 0.01
Best factors for opening animation: 
- a1: 1
- a2: 4.62
- b1: 2.44
- b2: 9.82
- c1: 0.22
- c2: 2.09
- error: 0.0165
- visualisation: https://www.desmos.com/calculator/ufy5rbucpd
Best factors for closing animation: 
- a1: 1
- a2: 5.65
- b1: 2.74
- b2: 8.38
- c1: 0.93
- c2: 3.29
- error: 0.0268
- visualisation: …
> [useAnimatedKeyboard][iOS] Improve curve parameters

- package.json
> Remove legacy scripts from package.json

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- MacOSExample/macos/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
- src/reanimated2/platform-specific/jsVersion.ts
> Release 3.8.0

- docs/docs/guides/compatibility.mdx
> Add 3.8.0 to compatibility table

- android/src/reactNativeVersionPatch/RuntimeExecutor/73/com/swmansion/reanimated/NativeProxy.java
- android/src/reactNativeVersionPatch/RuntimeExecutor/latest/com/swmansion/reanimated/NativeProxy.java
- src/createAnimatedComponent/createAnimatedComponent.tsx
Fix some stuff in @WoLewicki's PR #5734.
> Fixes for Reanimated with Bridgeless

- src/reanimated2/animation/util.ts
Include easing factories in easing warning
> Include factory in easing warning

- .github/workflows/build-v8-nightly.yml
- .github/workflows/helper/configureV8.js
Fixed `.github/workflows/helper/configureV8.js`. 
Changed data for replacing in android files.
> fixing configureV8.js

- app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/TestRunner.ts
- app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/stringFormatUtils.ts
- app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/types.ts
Improve test styling - adapt jest look and mark nested "describe" with appropriate indentation.
> Style test logs

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- MacOSExample/macos/MacOSExample.xcodeproj/project.pbxproj
- MacOSExample/macos/Podfile.lock
- TVOSExample/ios/Podfile.lock
- cspell.json
- package.json
- src/reanimated2/platform-specific/jsVersion.ts
Release 3.9.0 🎉
Package build: https://github.com/software-mansion/react-native-reanimated/actions/runs/8846918580
> Release 3.9.0

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- MacOSExample/macos/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
- src/reanimated2/platform-specific/jsVersion.ts
> Release 3.10.0

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
- src/reanimated2/platform-specific/jsVersion.ts
> Release 3.11.0

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
- app/src/examples/EmptyExample6.tsx
This PR fixes issues with shared transition not running when elements of a flat list get rerendered.
> Fix snapshot flatlist rerender issue

- app/src/examples/ComposedHandlerInternalMergingExample.tsx
Randomly found out that my "interpolateColor at home" in one of `composedEventHandler` examples from example app doesn't really work on Web. Thus the change.
Check out Composed Handler Internal Merging Example from example app on any platform.
:shipit:
> Use proper `interpolateColor` in composedHandler example

- Example/ios/Podfile.lock
- FabricExample/ios/Podfile.lock
- MacOSExample/macos/Podfile.lock
- TVOSExample/ios/Podfile.lock
- docs/docs/guides/compatibility.mdx
- package.json
- src/reanimated2/platform-specific/jsVersion.ts
> Release 3.12.0

- .github/workflows/static-example-apps-checks.yml
- apps/web-example/index.js
- apps/web-example/tsconfig.json
This PR resolves the issue of hot reload not working after modifying the example code in a common app or the source code of Reanimated.
- open web-example
- modify an example in common-app and see if hot-reload happened
- modify a source code of reanimated and see if hot-reload happened
> Fix hot-reload in web-example

- apps/macos-example/babel.config.js
- apps/macos-example/index.js
- apps/macos-example/macos/MacOSExample-macOS/Assets.xcassets/AppIcon.appiconset/Contents.json
- apps/macos-example/macos/MacOSExample-macOS/Assets.xcassets/Contents.json
- apps/next-example/tsconfig.json
- apps/web-example/index.js
- packages/react-native-reanimated/Common/cpp/LayoutAnimations/LayoutAnimationsManager.cpp
- packages/react-native-reanimated/Common/cpp/LayoutAnimations/LayoutAnimationsManager.h
- packages/react-native-reanimated/Common/cpp/LayoutAnimations/LayoutAnimationsProxy.cpp
- packages/react-native-reanimated/Common/cpp/LayoutAnimations/LayoutAnimationsProxy.h
- packages/react-native-reanimated/Common/cpp/LayoutAnimations/LayoutAnimationsUtils.cpp
- packages/react-native-reanimated/Common/cpp/LayoutAnimations/LayoutAnimationsUtils.h
- packages/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.cpp
- packages/react-native-reanimated/Common/cpp/NativeModules/NativeReanimatedModule.h
- packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
I have just ran `yarn format` and this is an effect 🤷‍♂️
> Run formatter

- .github/workflows/validate-cpp.yml
- packages/react-native-reanimated/Common/cpp/LayoutAnimations/LayoutAnimationsProxy.h
This PR aims to fix the C++ linter on CI after transition to the monorepo.
> Fix C++ linter on CI

- packages/docs-reanimated/package.json
- packages/docs-reanimated/src/examples/LayoutTransitions.tsx
- packages/docs-reanimated/yarn.lock
New reanimated versions has fixes for layout transitions -> this PR is needed for [Layout Transitions](https://github.com/software-mansion/react-native-reanimated/pull/6144) to work!
> docs: Bump react-native-reanimated@nightly

- .github/workflows/close-when-stale.yml
20 days for close when stale is way too long. 
👍
> Make `close when stale` time 14 days

- apps/common-app/src/examples/LayoutAnimations/KeyframeAnimation.tsx
We replaced `Keyframe Animation` with refreshed example.
Before:
https://github.com/software-mansion/react-native-reanimated/assets/59940332/0c2b752d-5108-4005-adf7-f5e9fab513b6
After:
https://github.com/software-mansion/react-native-reanimated/assets/59940332/805fc753-e994-4a53-8f9b-229e0690562a
> [LA] Replace Keyframe example

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/paper-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/docs-reanimated/docs/guides/compatibility.mdx
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
> Release 3.13.0

- packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ScreensHelper.java
- packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/TabNavigatorObserver.java
Fixes https://github.com/software-mansion/react-native-reanimated/issues/6210
This pull request adds an instance check before invoking a method via reflection.
> [SET] instance check before invoking a method via reflection

- apps/common-app/src/App.tsx
- apps/common-app/src/examples/GetViewPropExample.tsx
- apps/common-app/src/examples/LayoutAnimations/LayoutTransitionExample.tsx
- apps/common-app/src/examples/LayoutAnimations/NestedNativeStacksWithLayout.tsx
- apps/common-app/src/examples/LogExample.tsx
- apps/common-app/src/examples/OldMeasureExample.tsx
- apps/common-app/src/examples/RefExample.tsx
- apps/common-app/src/examples/SetNativePropsExample.tsx
- apps/common-app/src/examples/ShareablesExample.tsx
- apps/common-app/src/examples/SharedElementTransitions/ImageStack.tsx
- apps/common-app/src/examples/WorkletFactoryCrashExample.tsx
- apps/common-app/src/examples/WorkletRuntimeExample.tsx
When introducing monorepo we unified all the eslint rules across the project.
That's why we the eslint rules got more restrictive and we had to fix all the existing problems.
Run `yarn lint` inside apps/common-app
> Fix eslint rules inside apps/common-app

- packages/docs-reanimated/docs/fundamentals/glossary.mdx
> docs: update Reanimated Babel plugin README link in glossary.mdx

- .github/workflows/build-on-windows-nightly.yml
- .github/workflows/build-v8-nightly.yml
- .github/workflows/check-react-native-nightly.yml
- .github/workflows/check-static-framework-nightly.yml
> Use git protocol in CI

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/paper-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/docs-reanimated/docs/guides/compatibility.mdx
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
> Release 3.14.0

- packages/react-native-reanimated/package.json
Reanimated `package.json` metadata tweaks based on the React Native Directory checks. The following changes have been made:
* update [`repository` field](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository) to reflect the monorepo structure correctly
* update the `homepage` field to point to the accutial homepage, not the GitHub repository README
N/A
> chore: Reanimated package.json metadata tweaks

- packages/react-native-reanimated/src/component/ReducedMotionConfig.tsx
Just update url to page in docs
> Fix link to docs

- apps/common-app/src/examples/RuntimeTests/ReJest/RuntimeTestsRunner.tsx
> fix: tests not included by default

- .husky/pre-commit
> fix: Plugin precommit script

- packages/docs-reanimated/docs/utilities/interpolate.mdx
In interpolate, the input value  can come from outside of the provided input range and it will be extrapolated.
> docs: update interpolate value argument description

- apps/common-app/package.json
- apps/fabric-example/ios/Podfile.lock
- apps/fabric-example/package.json
- apps/macos-example/package.json
- apps/paper-example/ios/Podfile.lock
- apps/paper-example/package.json
- apps/tvos-example/ios/Podfile.lock
- yarn.lock
RN Screens 0.34.0 fixes some noticeable fabric issues.
👍
> Bump RNScreens to 3.34.0

- apps/common-app/src/examples/LiquidSwipe/LiquidButton.tsx
- apps/common-app/src/examples/LiquidSwipe/LiquidSwipe.tsx
With dedication to @bartlomiejbloniarz 🚀
> chore: Rename LiquidSwipe Button

- packages/docs-reanimated/docs/layout-animations/layout-transitions.mdx
Fixes `CurvedTransiton` typo in docs.
> docs: CurvedTransition typo

- package.json
- yarn.lock
> chore: Remove codegen resolution

- packages/react-native-reanimated/package.json
- yarn.lock
We are using a very old version 🤯
> chore: Bump react-native-builder-bob

- packages/react-native-reanimated/src/UpdateProps.ts
- packages/react-native-reanimated/src/screenTransition/styleUpdater.ts
> chore(TypeScript): Add ViewDescriptorsWrapper type to fix types

- packages/react-native-reanimated/src/UpdateProps.ts
I didn't merge main to #6481 and now I pay the price.
> chore: Hotfix formatting

- packages/docs-reanimated/src/examples/MeasureBasic.tsx
The box in InteractiveExample was disappearing form time to time. Usage of animatedProps fixed that issues.
Before:
https://github.com/user-attachments/assets/1cef8cda-0d8e-44f6-a377-ee5a3889ff6a
After:
https://github.com/user-attachments/assets/204e9a25-fd6f-4440-9c5d-52e11fe44cc9
> docs: Fix `measure` InteracitveExample

- packages/docs-reanimated/docs/shared-element-transitions/overview.mdx
- packages/docs-reanimated/src/examples/SharedElementTransition.tsx
We've rewrite [Shared Element Transition](https://docs.swmansion.com/react-native-reanimated/docs/shared-element-transitions/overview/) page.
https://github.com/user-attachments/assets/f414a67c-f067-4c65-bdbd-918155458374
> docs: Rewrite Shared Element Transition page

- apps/common-app/src/examples/RuntimeTests/ReJest/TestRunner/UpdatesContainer.ts
- apps/common-app/src/examples/StrictDOMExample.tsx
- packages/react-native-reanimated/src/animationBuilder.tsx
- packages/react-native-reanimated/src/createAnimatedComponent/PropsFilter.tsx
> chore: Fix TypeScript issues for `react-native@0.76`

- packages/docs-reanimated/docs/reanimated-babel-plugin/about.md
- packages/docs-reanimated/src/components/Testimonials/TestimonialList/index.tsx
- packages/docs-reanimated/versioned_docs/version-1.x/examples.md
- packages/docs-reanimated/versioned_docs/version-2.x/fundamentals/animations.md
- packages/docs-reanimated/versioned_docs/version-2.x/guide/testing.md
- packages/react-native-reanimated/scripts/validate-urls.js
Fix broken links in documentation
See CI test
> Fix broken links in documentation

- .github/workflows/reanimated-compatibility-check-nightly.yml
It shows in `checks` on GitHub then.
🚀
> feat: Allow to fire compatibility check action with label

- .github/workflows/reanimated-compatibility-check-nightly.yml
Turns out it works as a conjunction... also fixing expression syntax.
> fix: Remove path from Compatibility Action

- .husky/pre-commit
- .husky/pre-push
Since I accidentally pushed c4bb3a5 let's add some more protection maybe...
> feat: Add main branch protection scripts

- packages/react-native-reanimated/scripts/validate-android.sh
- packages/react-native-reanimated/scripts/validate-apple.sh
- packages/react-native-reanimated/scripts/validate-common.sh
🚀
Also fixing unescaped double quotes.
Adding @jfedak as reviewer because GitHub suggested him 🤷
> chore: Ignore comments in validation scripts

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/paper-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
This PR changes the version of reanimated to 3.17.0.
> Bump reanimated version to 3.17.0

- package.json
Sometimes when I want to make another app for testing (i.e. on older RN version) it's problematic.
🚀
> refactor: Specify each example app workspace

- packages/react-native-reanimated/scripts/validate-android.sh
- packages/react-native-reanimated/scripts/validate-apple.sh
- packages/react-native-reanimated/scripts/validate-common.sh
Relevant code hasn't arrived yet but we will be prepared.
`yarn lint`
> chore(Worklets): Add worklets validation to scripts

- apps/common-app/src/examples/SharedElementTransitions/LayoutAnimation.tsx
- apps/fabric-example/metro.config.js
- apps/paper-example/metro.config.js
- apps/tvos-example/metro.config.js
- packages/react-native-reanimated/metro-config/index.d.ts
- packages/react-native-reanimated/metro-config/index.js
- packages/react-native-reanimated/metro-config/tsconfig.json
Since
- https://github.com/facebook/react-native/pull/46602
got merged we can apply the fixes. Helps on CI.
🚀
> chore: Use updated MetroConfig type

- apps/common-app/src/App.tsx
> fix(example): Reloading to crashing screen

- .github/workflows/reanimated-typescript-compatibility-test-nightly.yml
> chore: Remove reference for 0.72 tests on CI

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/paper-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
> release: 3.17.0-rc.0

- packages/react-native-reanimated/package.json
Added by accident during monorepo migration.
> chore: remove extraneous packageManager field

- .github/workflows/reanimated-android-validation.yml
- packages/react-native-reanimated/android/CMakeLists.txt
- packages/react-native-reanimated/android/src/main/cpp/worklets/CMakeLists.txt
- packages/react-native-worklets/android/CMakeLists.txt
- packages/react-native-worklets/android/src/main/cpp/worklets/CMakeLists.txt
This PR adds missing `cmake-format` dependency installation step in the workflow file.
> Fix Android validation CI

- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h
- packages/react-native-reanimated/Common/cpp/reanimated/RuntimeDecorators/RNRuntimeDecorator.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/RuntimeDecorators/RNRuntimeDecorator.h
- packages/react-native-reanimated/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.cpp
- packages/react-native-reanimated/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.h
- packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
- packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
- packages/react-native-reanimated/android/src/main/cpp/worklets/android/WorkletsModule.cpp
- packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm
- packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.h
- packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm
- packages/react-native-reanimated/apple/worklets/apple/WorkletsModule.mm
Reanimated no longer creates UI Worklet Runtime. Now it's created by Worklets and Reanimated only borrows it.
See that apps are working and zooming 👍
> refactor(Worklets): move UIWorkletRuntime

- apps/common-app/src/apps/css/examples/animations/screens/testExamples/Playground.tsx
- packages/react-native-reanimated/Common/cpp/reanimated/CSS/registry/StaticPropsRegistry.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/CSS/registry/StaticPropsRegistry.h
Fix crash caused by enabling freeze (from `react-freeze`) in `react-native-screens` when CSS transitions are used on the freezed screen.
|-|-|
| <video src="https://github.com/user-attachments/assets/7d584fb8-3bae-4274-bacd-de5eb6543df5" /> | <video src="https://github.com/user-attachments/assets/4908bcd4-dab9-4352-967a-aaca3e0146df" /> |
Copy and paste the following code to the playground example in the example app:
<details>
<summary>Source code</summary>
```tsx
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { useLayoutEffect, useReducer, useRef } from 'react';
import { Keyboard, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from …
```
> fix: CSS transitions crash when react-freeze is used

- apps/common-app/src/App.tsx
- apps/common-app/src/apps/css/examples/animations/routes.ts
- apps/common-app/src/apps/css/navigation/Navigator.tsx
- apps/common-app/src/apps/css/navigation/utils.ts
- apps/common-app/src/components/navigation/BackButton.tsx
- apps/web-example/tsconfig.json
- packages/react-native-reanimated/src/css/platform/web/utils.ts
This PR:
- fixes hot reload on web,
- improves navigation (uses proper screen title, better back button name (adds space between words)),
- fixes web url to navigation state mapping (proper page is displayed on refresh or when navigating to a screen via url change)
> fix: Hot reload in web-example, improve navigation

- apps/common-app/src/apps/reanimated/examples/RuntimeTests/tests/props/boxShadow.test.tsx
Quick fix -> This file belongs in a new location, though the app could be built
🪨
> fix: Move boxShadow runtime test file from old directory 

- packages/docs-reanimated/docs/guides/building-for-android-on-windows.md
- packages/docs-reanimated/versioned_docs/version-3.x/guides/building-for-android-on-windows.md
> docs: Expand Building for Android on Windows

- packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedMountHook.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ShadowTreeCloner.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
- packages/react-native-reanimated/android/CMakeLists.txt
- packages/react-native-reanimated/android/build.gradle
- packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
- packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java
This PR adds `REANIMATED_PROFILING` build config field which enables systraces in Java and C++ code as well as few instances of systraces to most relevant methods.
> Enable systraces by default in example app

- .github/workflows/reanimated-clang-tidy-lint-nightly.yml
- .github/workflows/reanimated-clang-tidy-lint.yml
- packages/react-native-reanimated/.clang-tidy
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/scripts/clang-tidy-lint.sh
We'll improve our code gradually with this.
> feat: enable clang-tidy

- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.h
- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsUtils.cpp
This PR cherry-picks #6934 with cpp changes that add support for 0.78.0-rc.3 (worked also with rc5).
Build the example app
> cherry-pick: Add 0.78.0-rc.3 support

- apps/common-app/src/apps/reanimated/examples/index.ts
We've improved our code a lot since we needed to disable some examples. Now, the time has come, and we can enable some of them again.
> Enable fabric examles

- packages/react-native-reanimated/src/createAnimatedComponent/commonTypes.ts
- packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
cherry-pick: https://github.com/software-mansion/react-native-reanimated/pull/6885
> cherry-pick: Fix resolving ref to SVG components on Web #6885

- packages/react-native-reanimated/src/createAnimatedComponent/commonTypes.ts
- packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
- packages/react-native-reanimated/src/platform-specific/findHostInstance.ts
cherry-pick: https://github.com/software-mansion/react-native-reanimated/pull/7054
> cherry-pick: Handle component internal animated ref #7054

- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h
- packages/react-native-reanimated/Common/cpp/worklets/Tools/SingleInstanceChecker.h
- packages/react-native-reanimated/android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
- packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
- packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
- packages/react-native-reanimated/android/src/main/cpp/worklets/android/WorkletsModule.cpp
- packages/react-native-reanimated/android/src/main/cpp/worklets/android/WorkletsModule.h
- packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java
- packages/react-native-reanimated/android/src/main/java/com/swmansion/worklets/WorkletsModule.java
- packages/react-native-reanimated/android/src/paper/java/com/swmansion/reanimated/NativeProxy.java
- packages/react-native-reanimated/apple/worklets/apple/WorkletsModule.mm
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/core.ts
- packages/react-native-reanimated/src/hook/useAnimatedKeyboard.ts
- yarn.lock
Picking:
- #6850
- #6900
- #6732
> chore: cherry-pick for 3.17.0

- apps/fabric-example/android/app/build.gradle
- apps/fabric-example/android/gradle.properties
- packages/react-native-reanimated/android/build.gradle
- packages/react-native-worklets/android/build.gradle
> Cleanup build.gradle

- packages/react-native-reanimated/android/build.gradle
- packages/react-native-worklets/android/build.gradle
This PR removes unused imports in build.gradle files as well as sorts the remaining lines.
Check if CI is green.
> Remove unused and sort imports in build.gradle

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/paper-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
Release of Reanimated 3.17.1
Tested on clean bare/expo projects with RN 0.77 / React 18 and RN 0.78 / React 19
> release: 3.17.1

- packages/react-native-reanimated/apple/reanimated/apple/REAReducedMotion.h
- packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.h
- packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm
This PR moves the definition of `getIsReducedMotion` function from `NativeProxy.h` to a separate new file `REAReducedMotion.h`.
> Move reduced motion enabled check function to a separate file on iOS

- apps/common-app/src/apps/reanimated/examples/SwipeableListExample.tsx
This example was not working at all on web. Replacing the old gesture handler API with the new one fixes the issue.
https://github.com/user-attachments/assets/32b58b1e-cac7-4c9d-8c90-807a8d11647c
Open the example in the example app and see that it works.
> fix: Swipeable list example not working on web

- .gitignore
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h
- packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.h
> chore: remove unused valueUnpackerCode members

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/package.json
- packages/react-native-worklets/package.json
- yarn.lock
> feat(worklets): release 0.1.0

- packages/react-native-worklets/src/errors.ts
- packages/react-native-worklets/src/index.ts
- packages/react-native-worklets/src/privateGlobals.d.ts
- packages/react-native-worklets/src/shareables.ts
- packages/react-native-worklets/src/valueUnpacker.ts
- packages/react-native-worklets/src/workletFunction.ts
- packages/react-native-worklets/src/workletTypes.ts
🚀 
CI green, there's no runtime change.
> chore: fix WorkletFunction and ValueUnpacker types

- .github/workflows/npm-reanimated-package-build.yml
- .github/workflows/npm-worklets-package-build.yml
> fix: nightly release CI

- .github/workflows/npm-reanimated-package-build.yml
- .github/workflows/npm-reanimated-publish-nightly.yml
- .github/workflows/npm-worklets-package-build.yml
- .github/workflows/npm-worklets-publish-nightly.yml
- README.md
> chore: use Worklets NPM token

- .github/workflows/V8-reanimated-build-check-nightly.yml
- .github/workflows/reanimated-common-validation.yml
- .github/workflows/reanimated-compatibility-check-nightly.yml
- .github/workflows/reanimated-typescript-compatibility-test-nightly.yml
- apps/macos-example/App.tsx
- packages/react-native-reanimated/src/processBoxShadow.ts
- yarn.lock
> chore(Reanimated3): fix CI

- apps/fabric-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
Release of Reanimated 4.0.0-beta.3
Note: It works well with RN 0.77. Proper support for RN 0.78 will be added in `beta.4`.
Tested our example apps and a package in clean bare/expo projects
> release: 4.0.0-beta.3

- .github/workflows/V8-reanimated-build-check-nightly.yml
- README.md
Restore once V8 is supported again.
👍
> chore: disable V8 workflow

- .github/workflows/reanimated-compatibility-check-nightly.yml
- .github/workflows/reanimated-typescript-compatibility-test-nightly.yml
> chore: fix compatibility CI

- apps/fabric-example/ios/Podfile
- apps/macos-example/macos/Podfile
- apps/tvos-example/ios/Podfile
- packages/react-native-reanimated/RNReanimated.podspec
- packages/react-native-reanimated/scripts/reanimated_utils.rb
> fix: new architecture assertion on iOS

- .github/workflows/npm-reanimated-package-build.yml
- .github/workflows/npm-reanimated-publish-nightly.yml
Now we would release Reanimated3 nightlies under `reanimated3-nightly` tag.
9a8f84c29fbb0c4a4467d3ab6a0a0d96c7ea0ca8 did a `--dry-run` for testing.
> feat: release Reanimated3 nightlies

- apps/macos-example/macos/Podfile
> chore: fix macos podfile

- .yarn/patches/react-native-builder-bob-npm-0.33.1-383d9e23a5.patch
- packages/react-native-reanimated/package.json
- packages/react-native-worklets/package.json
- yarn.lock
Fixes #6665. Read the issue for more context.
`react-native-builder-bob` applies `@babel/preset-react` on the emitted code, effectively ignoring our TSConfig setting of `jsx: 'react-native'`. `jsx: 'react-native'` is beneficial for library consumers because it allows for greater manipulation of emitted JSX.
https://www.typescriptlang.org/tsconfig/#jsx
Also bringing back `jsxRuntime: 'automatic'` for the same reasons.
https://babeljs.io/docs/babel-plugin-transform-react-jsx#react-automatic-runtime
<details>
<summary>
See the diff to understand resulting changes
</summary>
```diff
diff --color -ru package-old/lib/module/component/FlatList.js package-new/lib/module/component/FlatList.js
--- package-old/lib/module/component/FlatList.js	1985-10-26 09:15:00
+++ …
```
> chore: patch bob to preserve jsx

- packages/docs-reanimated/package.json
- packages/docs-reanimated/yarn.lock
Tested, works
https://github.com/user-attachments/assets/243295fc-8ab0-441b-8f4b-15e4542e81ae
> docs: update reanimated nightly version && install react-native-worklets

- packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
> cherry-pick: fix: Impossibility to remove layout transitions

- packages/react-native-reanimated/__typetests__/common/miscTest.tsx
- packages/react-native-reanimated/src/Easing.ts
- packages/react-native-reanimated/src/commonTypes.ts
- packages/react-native-reanimated/src/layoutReanimation/animationBuilder/ComplexAnimationBuilder.ts
- packages/react-native-reanimated/src/layoutReanimation/animationBuilder/Keyframe.ts
- packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/CurvedTransition.ts
> Cherry pick #6958

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/paper-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
Release of Reanimated 3.17.2. Cherry-picks can be found here #7207 
Tested in our example app (Fabric, Paper, tvOS - every on iOS and Android, and MacOS) and in Clean App (RN and RN web), both prod and debug.
> release: 3.17.2

- packages/docs-reanimated/docs/guides/compatibility.mdx
- packages/docs-reanimated/versioned_docs/version-3.x/guides/compatibility.mdx
> docs: Add 3.17.2 to compatibility table

- packages/react-native-reanimated/src/Colors.ts
I've added processing of array and color-related props so every item would be processed.
Use code provided with an issue #7282
> (cherry-pick) feat: Add processing for array color related props 

- apps/common-app/src/examples/SharedElementTransitions/Profiles.tsx
- apps/common-app/src/examples/index.ts
Fix `RCTStatusBarManager` issue on profiles example : 
https://github.com/user-attachments/assets/39cf23af-03da-41be-a7ff-5949d5e531cf
> Fix profiles example

- apps/common-app/src/examples/SharedElementTransitions/Profiles.tsx
Fix `RCTStatusBarManager` issue on profiles example :
https://github.com/user-attachments/assets/39cf23af-03da-41be-a7ff-5949d5e531cf
> [cherry-pick] Fix profiles example (#7359)

- packages/react-native-reanimated/src/createAnimatedComponent/PropsFilter.tsx
This PR changes the `PropsFilter` behavior for animated styles.
Before these changes, initial styles of all animated style objects were merged into a single initial style object. After the first render, the same initial style object was returned for each animated style, so e.g. when we had multiple animated styles, the same initial style object was added to the style array multiple times.
Even though the previous implementation worked on Fabric, I decided to change it for consistency with implementation in reanimated `3.x.x`. The new implementation, that returns a correct initial style corresponding to the animated style object, feels better (in terms of logic) as gives more expected results (each animated style is given its own initial style properties, not combined props from all …
> fix: Return proper initial styles in PropsFilter for animated style objects

- apps/common-app/src/examples/TransformOriginExample.tsx
- apps/common-app/src/examples/index.ts
- packages/react-native-reanimated/src/createAnimatedComponent/InlinePropManager.ts
- packages/react-native-reanimated/src/hook/useAnimatedStyle.ts
- packages/react-native-reanimated/src/screenTransition/styleUpdater.ts
- packages/react-native-reanimated/src/updateProps/index.ts
- packages/react-native-reanimated/src/updateProps/processTransformOrigin.ts
- packages/react-native-reanimated/src/updateProps/updateProps.ts
> cherry-pick: Support for all transform origin values

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/paper-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- apps/web-example/package.json
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
- yarn.lock
Included fixes:
- #7376
- #7395
- #7394
- #7400
|| Fabric (iOS) | Fabric (Android) | Paper (iOS) | Paper (Android) | Web | MacOS | TVOS (iOS) | TVOS (android) |
| Builds           | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | 
| Runs             | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
> Release 3.17.4

- .github/ISSUE_TEMPLATE/bug-report.yml
- spelling fixes,
- proper architecture (change the sentence that says that Paper is the default architecture)
- allow selection multiple options for the `device` and the `build type`
> chore: Improve bug report template

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/paper-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
Included fixes:
- #7404
- #7422
I focused on the examples most related to the applied changes. I didn't test all examples in the example app as there are very little changes in this release that shouldn't affect most of the logic.
|| Fabric (iOS) | Fabric (Android) | Paper (iOS) | Paper (Android) | Web | MacOS | TVOS (iOS) | TVOS (android) |
| Builds           | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | 
| Runs             | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
> Release 3.17.5

- packages/docs-reanimated/docs/guides/compatibility.mdx
- packages/docs-reanimated/versioned_docs/version-3.x/guides/compatibility.mdx
- packages/docs-reanimated/yarn.lock
This PR just adds `3.17.5` to compatibility tables in docs.
> docs: Update reanimated version in compatibility tables in docs

- packages/react-native-reanimated/RNReanimated.podspec
> Rename `sv` to `sss` in RNReanimated.podspec

- apps/common-app/src/apps/reanimated/examples/ShareablesExample.tsx
- packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.cpp
- packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.h
- packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxySpec.cpp
- packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxySpec.h
- packages/react-native-worklets/Common/cpp/worklets/SharedItems/Shareables.cpp
- packages/react-native-worklets/Common/cpp/worklets/SharedItems/Shareables.h
- packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntimeDecorator.cpp
- packages/react-native-worklets/src/WorkletsModule/JSWorklets.ts
- packages/react-native-worklets/src/WorkletsModule/NativeWorklets.ts
- packages/react-native-worklets/src/WorkletsModule/workletsModuleProxy.ts
- packages/react-native-worklets/src/privateGlobals.d.ts
- packages/react-native-worklets/src/shareables.ts
This PR adds few new functions : 
- `makeShareableNumber`
- `makeShareableBoolean`
- `makeShareableBigInt`
and is part of a series of PRs that aim to refactor the `makeSharableClone` function -> https://github.com/software-mansion/react-native-reanimated/pull/7481
`Shareables` example
<video src="https://github.com/user-attachments/assets/9affdcf7-beae-416f-a7da-01fa7c48423b" />
> refactor(Worklets)(makeShareableClone): add makeShareableNumber, makeShareableBoolean, makeShareableBigInt

- apps/common-app/src/apps/reanimated/examples/ShareablesExample.tsx
- packages/react-native-worklets/src/WorkletsModule/NativeWorklets.ts
This Pr adds two new variables to `NativeWorklets` class:
- `#shareableTrue`
- `#shareableFalse`
this will reduce the number of `makeShareableBoolean` calls
`Shareables` example
> refactor(Worklets): add shareableTrue and shareableFalse

- packages/react-native-reanimated/Common/cpp/reanimated/CSS/progress/AnimationProgressProvider.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/CSS/progress/AnimationProgressProvider.h
- packages/react-native-reanimated/Common/cpp/reanimated/CSS/registry/CSSAnimationsRegistry.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
- packages/react-native-reanimated/src/css/managers/CSSTransitionsManager.web.ts
This PR fixes remaining CSS issues I noticed while testing example apps
> fix: Remaining CSS issues fixes

- packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedShadowNode.cpp
- packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedViewStateData.cpp
- packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedViewStateData.h
- packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/managers/CSSAnimationsManager.cpp
- packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/managers/CSSAnimationsManager.h
- packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/managers/CSSTransitionManager.h
- packages/react-native-reanimated/src/css/managers/new/CSSAnimationsManager.ts
Base implementation of the CPP `CSSAnimationsManager` class. Will be fully implemented in the next PR, similarly as I did with the transitions manager.
> feat: Base implementation of the native CSSAnimationsManager

- packages/react-native-reanimated/__tests__/Animation.test.tsx
- packages/react-native-reanimated/__tests__/InterpolateColor.test.tsx
- packages/react-native-reanimated/__tests__/SharedValue.test.tsx
- packages/react-native-reanimated/__tests__/__snapshots__/Animation.test.tsx.snap
- packages/react-native-reanimated/__tests__/__snapshots__/InterpolateColor.test.tsx.snap
- packages/react-native-reanimated/__tests__/__snapshots__/SharedValue.test.tsx.snap
- packages/react-native-reanimated/__tests__/__snapshots__/animatedProps.test.tsx.snap
- packages/react-native-reanimated/__tests__/__snapshots__/hooks.useAnimatedStyle.test.tsx.snap
- packages/react-native-reanimated/__tests__/__snapshots__/hooks.useSharedValue.test.tsx.snap
- packages/react-native-reanimated/__tests__/__snapshots__/inlineStyles.test.tsx.snap
- packages/react-native-reanimated/__tests__/__snapshots__/jestUtils.test.tsx.snap
- packages/react-native-reanimated/__tests__/__snapshots__/props.test.tsx.snap
- packages/react-native-reanimated/__tests__/animatedProps.test.tsx
- packages/react-native-reanimated/__tests__/hooks.useAnimatedStyle.test.tsx
- packages/react-native-reanimated/__tests__/hooks.useSharedValue.test.tsx
- packages/react-native-reanimated/__tests__/inlineStyles.test.tsx
- packages/react-native-reanimated/__tests__/jestUtils.test.tsx
- packages/react-native-reanimated/__tests__/props.test.tsx
- packages/react-native-reanimated/__tests__/spring.test.tsx
- packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
- packages/react-native-reanimated/src/hook/commonTypes.ts
- packages/react-native-reanimated/src/hook/useAnimatedStyle.ts
- packages/react-native-reanimated/src/mutables.ts
> chore(Reanimated3): cherry-pick #7372

- packages/docs-reanimated/docs/guides/troubleshooting.mdx
- packages/docs-reanimated/versioned_docs/version-3.x/guides/troubleshooting.mdx
> docs: mention tvOS and visionOS support in Troubleshooting

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/paper-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
Includes:
- https://github.com/software-mansion/react-native-reanimated/pull/7372
- https://github.com/software-mansion/react-native-reanimated/pull/7398
- https://github.com/software-mansion/react-native-reanimated/pull/7428
- https://github.com/software-mansion/react-native-reanimated/pull/7515
- #7546
- #7545
- #7506
- #7600 
|| Fabric (iOS) | Fabric (Android) | Paper (iOS) | Paper (Android) | Web | MacOS | TVOS (iOS) | TVOS (android) |
| Builds           | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | 
| Runs             | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
> Release 3.18.0

- packages/react-native-reanimated/src/hook/useAnimatedRef.ts
This PR removes duplicate code between the web and the native implementation of the `useAnimatedRef` hook as asked in https://github.com/software-mansion/react-native-reanimated/pull/7612#discussion_r2124188984
Copy-paste the following code snippet and see how it works.
<details>
<summary>Code snippet</summary>
```tsx
import { Button, ScrollView, StyleSheet, Text, View } from 'react-native';
import type Animated from 'react-native-reanimated';
import {
useAnimatedReaction,
const [shouldRender, setShouldRender] = useState(false);
const scrollRef = useAnimatedRef<Animated.ScrollView>();
const scrollOffset = useScrollViewOffset(scrollRef); …
```
> chore: Remove duplicate code from useAnimatedRef implementation

- packages/react-native-worklets/package.json
> chore(Worklets): add plugin build step to build script

- packages/react-native-worklets/package.json
- packages/react-native-worklets/src/WorkletsModule/NativeWorklets.ts
- packages/react-native-worklets/src/shareables.ts
- packages/react-native-worklets/src/specs/NativeWorkletsModule.ts
- packages/react-native-worklets/src/workletTypes.ts
- yarn.lock
Turns out `ts-prune` wasn't installed properly in Worklets' workspace and it didn't work. I fixed all errors it found.
🚀
> chore(Worklets): enable ts-prune

- scripts/patches/experimental-bundling.patch
- scripts/toggle-experimental-bundling.sh
QoL script that allows the toggle experimental bundling in repo programmatically.
🚀
> feat(Worklets): add script to toggle experimental bundling

- packages/react-native-worklets/Common/cpp/worklets/Tools/WorkletsSystraceSection.h
Adding a header that defines `WorkletsSystraceSection` for profiling. The file is a copy of `ReanimatedSystraceSection.h`.
🚀
> feat(Worklets): add systrace section for profiling

- packages/react-native-reanimated/RNReanimated.podspec
- packages/react-native-worklets/RNWorklets.podspec
> (cherry-pick) fix: bump to C++20

- packages/react-native-reanimated/src/hook/useScrollViewOffset.ts
> (cherry-pick) fix: Crash in useScrollViewOffset if animatedRef is not initialized

- apps/common-app/src/examples/ModalExitingExample.tsx
- apps/common-app/src/examples/index.ts
- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsUtils.h
> (cherry-pick) Don't run exiting animations on modal removal

- packages/react-native-reanimated/src/hook/useAnimatedRef.ts
> fix: Prevent uninitialized ScrollView warning from showing up on unmount

- eslint.config.mjs
- packages/react-native-reanimated/__tests__/bezier.test.ts
- packages/react-native-reanimated/src/layoutReanimation/web/createAnimation.ts
- packages/react-native-reanimated/src/mock.ts
- packages/react-native-reanimated/src/privateGlobals.d.ts
- packages/react-native-reanimated/src/publicGlobals.ts
- packages/react-native-reanimated/src/updateProps/updateProps.ts
- packages/react-native-worklets/src/WorkletsModule/JSWorklets.ts
- packages/react-native-worklets/src/WorkletsModule/NativeWorklets.ts
- packages/react-native-worklets/src/WorkletsModule/workletsModuleProxy.ts
- packages/react-native-worklets/src/initializers.ts
- packages/react-native-worklets/src/privateGlobals.d.ts
> chore: cleanup after eslint bump

- packages/react-native-worklets/scripts/export-value-unpacker.js
Less volatile in case some extra statements are generated, it happened to me after I ran `yarn dedupe`.
🚀
> chore(Worklets): smarter value unpacker export script

- packages/react-native-reanimated/src/updateProps/updateProps.ts
This PR adds missing handling of `box-shadow` prop 
Before : 
<video src="https://github.com/user-attachments/assets/625abd2b-cf5e-477d-87e6-4914fcda7a55" />
After :
<video src="https://github.com/user-attachments/assets/9ca117bd-1e6f-46b5-9af9-aa6f2d2ad97a" />
<details>
<summary>Empty Example - Code snippet</summary>
```js
import { StyleSheet, Text, View } from 'react-native';
AnimatableValue,
withSpring,
import { DefaultStyle } from 'react-native-reanimated/lib/typescript/hook/commonTypes';
const boxShadowActiveSV = useSharedValue({
blurRadius: 7,
color: 'blue',
offsetX: 20,
offsetY: 20,
spreadDistance: 10,
});
const …
```
> fix: add missing handling of `box-shadow` prop

- packages/docs-worklets/docusaurus.config.js
This PR adds support for `Algolia` docs search, which is needed to be able to use the search engine in `docusarus`.
> feat(docs-worklets): Setup `Algolia` for worklets docs

- apps/common-app/src/apps/reanimated/examples/CircularSliderExample.tsx
> Rename `JSPropsExample` to `CircularSliderExample`

- apps/common-app/src/examples/LayoutAnimations/ReparentingExample.tsx
- apps/common-app/src/examples/index.ts
- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.h
> (cherry-pick) Fix reparenting

- apps/common-app/src/examples/LayoutAnimations/MoveWithExiting.tsx
- apps/common-app/src/examples/index.ts
- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
> (cherry-pick) Fix zombie view when parent is moved

- packages/docs-reanimated/docs/guides/troubleshooting.mdx
- packages/docs-reanimated/versioned_docs/version-3.x/guides/troubleshooting.mdx
- packages/docs-worklets/docs/reanimated-babel-plugin/about.md
- packages/docs-worklets/src/components/DeprecatedBanner/styles.module.css
> fix: update incorrect links in reanimated docs

- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
> (cherry-pick) [Fabric LA] Mark deleted nodes as DELETED 

- apps/common-app/src/examples/LayoutAnimations/DurationZero.tsx
- apps/common-app/src/examples/index.ts
- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.h
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h
> (cherry-pick) [Fabric LA] Add progress batching

- packages/docs-reanimated/docs/guides/migration-from-3.x.md
http://localhost:3000/react-native-reanimated/docs/next/guides/migration-from-3.x
> Expand Migrating from Reanimated 3.x to 4.x

- packages/react-native-worklets/plugin/index.js
- packages/react-native-worklets/plugin/src/class.ts
- packages/react-native-worklets/plugin/src/closure.ts
- packages/react-native-worklets/plugin/src/generate.ts
- packages/react-native-worklets/plugin/src/workletFactory.ts
Previously only named import were preserved to be used in worklets in Bundle Mode.
🚀
> fix(Worklets): default imports in Bundle Mode

- packages/react-native-reanimated/src/animation/util.ts
> (cherry-pick) fix: precision errors in color interpolation keeping the animation to run forever

- apps/common-app/src/apps/reanimated/examples/ChatHeadsExample.tsx
- apps/common-app/src/apps/reanimated/examples/DragAndSnapExample.tsx
- apps/common-app/src/apps/reanimated/examples/ExtrapolationExample.tsx
- apps/common-app/src/apps/reanimated/examples/IPodExample.tsx
- apps/common-app/src/apps/reanimated/examples/LightBoxExample.tsx
- apps/common-app/src/apps/reanimated/examples/OldMeasureExample.tsx
- apps/common-app/src/apps/reanimated/examples/ScrollableViewExample.tsx
- apps/common-app/src/apps/reanimated/examples/WorkletExample.tsx
This PR migrates all usages of `useAnimatedGestureHandler` in the example app to the new RNGH API.
> Migrate all usages of `useAnimatedGestureHandler` in example app

- packages/react-native-reanimated/src/hook/useAnimatedStyle.ts
This PR fixes hot-reload regression introduced in #7539
> Revert `useAnimatedStyle` changes

- apps/fabric-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
Release of the Reanimated 4.0.0 🎉 
Package download link: https://github.com/software-mansion/react-native-reanimated/actions/runs/16471538836
> release: Reanimated 4.0.0

- packages/docs-reanimated/docusaurus.config.js
- packages/docs-reanimated/src/components/Hero/StartScreen/index.tsx
> chore: bump default Reanimated in docs

- apps/fabric-example/ios/Podfile.lock
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
- packages/react-native-worklets/Common/cpp/worklets/Public/AsyncQueue.h
- packages/react-native-worklets/Common/cpp/worklets/Tools/AsyncQueueImpl.cpp
- packages/react-native-worklets/Common/cpp/worklets/Tools/AsyncQueueImpl.h
- packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntime.h
Implementing requested APIs for libraries like `react-native-vision-camera` https://github.com/software-mansion/react-native-reanimated/discussions/7831.
Future PRs will tackle `createWorkletRuntime` and the rest of the necessary changes.
CI & WorkletRuntime Example
> feat(Worklets): make AsyncQueue virtual and public

- packages/react-native-worklets/src/initializers.ts
Fixes #7897.
Nothing to test really.
> fix(Worklets): _$$_IMPORT_ALL identifier clash in some web setups

- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
> chore(Reanimated): bump version in monorepo

- packages/docs-reanimated/docs/guides/compatibility.mdx
@patrycjakalinska noticed that something is off so I fixed it.
> docs: Update compatibility table

- packages/react-native-reanimated/android/build.gradle
- packages/react-native-reanimated/scripts/reanimated_utils.rb
- packages/react-native-worklets/android/build.gradle
- packages/react-native-worklets/scripts/worklets_utils.rb
Reanimated v4 requires React Native 0.78 or newer.
> Bump minimal React Native version in assertions

- packages/react-native-worklets/package.json
- packages/react-native-worklets/src/utils/jsVersion.ts
[Worklets - 0.4.1](https://github.com/software-mansion/react-native-reanimated/releases/tag/worklets-0.4.1)
> release(Worklets): 0.4.1

- .yarn/patches/react-native-screens-npm-4.10.0-a9c3a4e55e.patch
- apps/fabric-example/android/gradle.properties
- packages/react-native-reanimated/android/build.gradle
- packages/react-native-worklets/android/build.gradle
- yarn.lock
> (cherry-pick) Fix Gradle Configuration Cache

- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
Suggested by @MatiPl01 in https://github.com/software-mansion/react-native-reanimated/pull/7979#discussion_r2248226413, promised by @tomekzaw in https://github.com/software-mansion/react-native-reanimated/pull/7979#discussion_r2250492348.
> Add "[Reanimated]" prefix in error messages for fast path on Android

- packages/react-native-reanimated/android/build.gradle
- packages/react-native-reanimated/scripts/reanimated_utils.rb
- packages/react-native-worklets/android/build.gradle
- packages/react-native-worklets/scripts/worklets_utils.rb
> (cherry-pick) Bump minimal React Native version in assertions

- packages/react-native-reanimated/android/build.gradle
- packages/react-native-worklets/android/build.gradle
🍒: https://github.com/software-mansion/react-native-reanimated/pull/7977
> cherry-pick(3.19): Update Java compatibility

- packages/react-native-reanimated/src/layoutReanimation/web/animationParser.ts
- packages/react-native-reanimated/src/layoutReanimation/web/createAnimation.ts
> (cherry-pick) fix: Keyframe LA easing not working properly on web

- packages/react-native-reanimated/src/layoutReanimation/web/componentUtils.ts
> (cherry-pick) [Web LA] fix: Call callback in scheduleAnimationCleanup if not called already

- packages/react-native-reanimated/src/layoutReanimation/web/componentUtils.ts
> (cherry-pick) [Web LA] Fix resetting scroll positions in exiting animations

- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
> (cherry-pick) Add "[Reanimated]" prefix in error messages for fast path on Android 

- apps/common-app/src/apps/reanimated/examples/RuntimeTests/tests/animations/withSequence/numbers.test.tsx
Fix `withSequence` runtime tests
Runtime `animations` tests
> fix: `withSequence` runtime tests

- packages/react-native-worklets/apple/worklets/apple/AnimationFrameQueue.mm
This PR fixes the conditional statements that caused us to always limit the frame rate to 60 FPS, even when it would be possible to switch to 120 FPS.
https://github.com/user-attachments/assets/0f1d657f-d1fd-40ed-909a-707d624079e4
> Fix ProMotion

- apps/common-app/src/apps/reanimated/examples/FpsExample.tsx
- apps/common-app/src/apps/reanimated/examples/index.ts
This PR add FPS example.
| real iPhone | iPhone simulator | Android real device | Android emulator |
|:-:|:-:|:-:|:-:|
| <img width="200" src="https://github.com/user-attachments/assets/092eab3c-3b96-46fe-8dda-9b6d0f64584d" /> | <img width="200" src="https://github.com/user-attachments/assets/6a2b91c3-8d4c-4e0b-a569-2a7aa965620f" /> | <img width="200" src="https://github.com/user-attachments/assets/8ef5f899-ab72-4bd3-897f-1a4bca7fa35e" /> | <img width="200" src="https://github.com/user-attachments/assets/df1d2a5c-34a6-4ec3-bf0a-1d6631cd9712" /> |
> Add FPS example

- packages/react-native-worklets/apple/worklets/apple/AnimationFrameQueue.mm
> (cherry-pick) Fix ProMotion

- packages/react-native-reanimated/src/layoutReanimation/web/config.ts
- packages/react-native-reanimated/src/layoutReanimation/web/createAnimation.ts
> (cherry-pick) fix: Invalid web LA keyframe processing when from/to offset is used

- packages/docs-reanimated/docs/guides/migration-from-3.x.md
> Update migration docs about `@gorhom/bottom-sheet`

- packages/docs-reanimated/src/components/InteractivePlayground/useSpringPlayground/index.tsx
Typo in the playground generated config.
Open the documentation, and read the presented code with the configuration.
https://docs.swmansion.com/react-native-reanimated/docs/animations/withSpring/
> Fix typo in the property name

- .github/workflows/reanimated-typescript-compatibility-test-nightly.yml
- packages/react-native-reanimated/package.json
This PR fixes nightly RN version compatibility build
> fix: nightly RN version compatibility build

- packages/docs-reanimated/docs/guides/feature-flags.md
- packages/docs-worklets/docs/guides/feature-flags.md
- packages/docs-worklets/yarn.lock
> docs: change default value in static feature flags sections

- packages/react-native-worklets/apple/worklets/apple/AnimationFrameQueue.mm
This PR fixes the conditional statements that caused us to always limit the frame rate to 60 FPS, even when it would be possible to switch to 120 FPS.
> cherry-pick(Worklets): Fix ProMotion #8020

- packages/react-native-reanimated/compatibility.json
- packages/react-native-reanimated/scripts/validate-worklets-version.js
This PR updates version compatibility checking between reanimated and worklets.
> chore: update version compatibility checking between reanimated and worklets

- packages/react-native-worklets/RNWorklets.podspec
This PR fixes `RNWorklets.podspec` typo
> cherry-pick(Worklets): podspec typo

- packages/react-native-reanimated/src/createAnimatedComponent/AnimatedComponent.tsx
> (cherry-pick) fix: Reduce Motions + animation callbacks

- packages/docs-worklets/docs/fundamentals/getting-started.mdx
- packages/docs-worklets/docs/worklets-babel-plugin/_category_.json
- packages/docs-worklets/docs/worklets-babel-plugin/about.md
- packages/docs-worklets/docs/worklets-babel-plugin/options.md
This PR updates `getting-started` docs page
> feat(Worklets): update `getting-started` docs page

- apps/common-app/src/apps/reanimated/examples/AboutExample.tsx
- apps/common-app/src/apps/reanimated/examples/AnimatableRefExample.tsx
- apps/common-app/src/apps/reanimated/examples/PendulumExample.tsx
- apps/common-app/src/apps/reanimated/examples/PerfomanceMonitorExample.tsx
- apps/common-app/src/apps/reanimated/examples/RuntimeTests/ReJest/matchers/rawMatchers.ts
- apps/common-app/src/apps/reanimated/examples/RuntimeTests/tests/advancedAPI/useFrameCallback.test.tsx
- apps/common-app/src/apps/reanimated/examples/RuntimeTests/tests/core/useSharedValue/animationsCompilerApi.test.tsx
- apps/common-app/src/apps/reanimated/examples/RuntimeTests/tests/core/useSharedValue/assigningObjects.test.tsx
- apps/common-app/src/apps/reanimated/examples/RuntimeTests/tests/props/boxShadow.test.tsx
> chore: prerelease example app fixes

- packages/react-native-reanimated/Common/cpp/reanimated/CSS/configs/interpolators/base/view.h
Just a change from the black to the transparent box shadow default color value
> fix: Default boxShadow color value

- packages/react-native-worklets/scripts/worklets_utils.rb
TVOS build without it just fine but it doesn't seem to hurt.
Build TVOS
> chore(Worklets): add missing tvos detection

- .husky/pre-commit
add `yarn install` command to lint docs step
> chore: add `yarn install` command to lint docs step

- packages/docs-worklets/src/css/overrides.css
- packages/docs-worklets/src/pages/index.tsx
> fix(docs-worklets): Remove duplicated page title

- packages/docs-worklets/src/components/HomepageAboutSection/index.tsx
- packages/docs-worklets/src/components/HomepageAboutSection/styles.module.css
- packages/docs-worklets/src/components/HomepageUseCasesSection/UseCase/styles.module.css
> feat(Worklets): Add a promotional video about `worklets` to docs

- apps/fabric-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-worklets/package.json
- packages/react-native-worklets/src/utils/jsVersion.ts
Build artifact CI https://github.com/software-mansion/react-native-reanimated/actions/runs/17584244284
> release(Worklets): 0.5.1

- packages/react-native-reanimated/src/index.ts
- packages/react-native-reanimated/src/initializers.ts
> (cherry-pick) fix: Initialize logger before all other things 

- apps/common-app/src/apps/reanimated/examples/DynamicColorIOSExample.tsx
- packages/react-native-reanimated/src/common/processors/colors.ts
There were a need to add type guards to our internal examples on other platforms.
> fix: DynamicColorIOS bug

- apps/fabric-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/compatibility.json
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
Artifact CI https://github.com/software-mansion/react-native-reanimated/actions/runs/17983078811
> release(Reanimated): 4.1.2

- packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
Cherry-pick of the https://github.com/software-mansion/react-native-reanimated/pull/8208
> (cherry-pick) [Web LA] Ensure callbacks are called when ReducedMotion is on

- packages/react-native-reanimated/android/CMakeLists.txt
- packages/react-native-worklets/android/CMakeLists.txt
Cherry-pick of https://github.com/software-mansion/react-native-reanimated/pull/8089
> (cherry-pick): Fix missing `ReactAndroid_VERSION_MINOR` CMake variable used before find_package

- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.h
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
- packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h
- packages/react-native-reanimated/Common/cpp/reanimated/Tools/PlatformDepMethodsHolder.h
- packages/react-native-reanimated/android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
- packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
- packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
> (cherry-pick) [LA] Add check if view is mounted on Android  (#8083)

- packages/react-native-reanimated/src/ViewDescriptorsSet.ts
- packages/react-native-reanimated/src/createAnimatedComponent/AnimatedComponent.tsx
> (cherry-pick) fix: Animated styles not registered after unfreeze

- apps/fabric-example/ios/Podfile.lock
- apps/macos-example/macos/Podfile.lock
- apps/paper-example/ios/Podfile.lock
- apps/tvos-example/ios/Podfile.lock
- packages/react-native-reanimated/package.json
- packages/react-native-reanimated/src/ViewDescriptorsSet.ts
- packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
- packages/react-native-reanimated/src/platform-specific/jsVersion.ts
Release of reanimated `3.19.2` :tada:
Cherry-pick thread: #8261
|| Fabric (iOS) | Fabric (Android) | Paper (iOS) | Paper (Android) | Web | TVOS (iOS) | TVOS (Android) | Next |
| Builds           | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
| Works            | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |
> release: Reanimated 3.19.2
