software-mansion/react-native-reanimated

android/src/main/cpp/NativeProxy.cpp
ios/native/NativeMethods.mm

I've noticed that there are some unnecessary reallocations during returning result from Android's measure function. Without any memory reservation, push_back may cause several reallocations and copy of the data.
None

Fixed minor Android measure function small performance issue

---

ios/RCTEventDispatcher+Reanimated.h
ios/RCTEventDispatcher+Reanimated.m

This PR adds `static __weak REAModule *reaModule;` variable which stores the result of `[[self bridge] moduleForName:@"ReanimatedModule"]` so we can call it only once during initialization instead of on each event.
When `REAModule` is deallocated, all `__weak` pointers are automatically replaced with `nil` so it doesn't leak any resources as well as works fine after a reload.

Memoize ReanimatedModule in `sendEvent`

---

app/src/examples/ArticleProgressExample.tsx
app/src/examples/IPodExample.tsx
app/src/examples/ScrollEventExample.tsx
app/src/examples/ScrollViewExample.tsx
app/src/examples/ScrollViewOffsetExample.tsx
app/src/examples/WorkletExample.tsx
docs/docs/api/hooks/useAnimatedScrollHandler.md
docs/docs/api/hooks/useScrollViewOffset.md
docs/docs/api/miscellaneous/interpolate.md
src/reanimated2/component/ScrollView.tsx

The inspiration for this changes are two issues:
- https://github.com/software-mansion/react-native-reanimated/issues/4585#issuecomment-1595921845
- https://github.com/software-mansion/react-native-reanimated/pull/4416/commits/4137d1a7d4ddba180c54582c2e1036a285c0ba3e
Users expect continuous scroll events. But the default value of [scrollEventThrottle](https://reactnative.dev/docs/scrollview#scrolleventthrottle-ios) is 0, which results in the scroll event being sent only once each time the view is scrolled. Which is easy to forget about it and in effect, it seems like a Reanimated issue. I know that this is a change of default ScrollView behavior but I believe that it would be less confusing for the users.

Set default scrollEventThrottle

---

src/reanimated2/hook/useAnimatedStyle.ts
src/reanimated2/hook/utils.ts

Currently, TypeScript guards against returning an object which contains `null` from `useAnimatedStyle`:
However, if we ignore this error, we will get the following runtime error:
This PR adds missing null checks to avoid runtime error in this scenario.
Co-authored-by: @kmagiera
<details>
<summary>App.tsx</summary>
```tsx
import {StyleSheet, View} from 'react-native';
import Animated, {useAnimatedStyle} from 'react-native-reanimated';
return {
width: 100,
height: 100,
backgroundColor: 'red',
display: null,
};
});
return (
<Animated.View style={animatedStyle} />
</View>
);
}
const styles = StyleSheet.create({
container: {
flex: 1,
alignItems: …
```

Add missing null checks

---

src/createAnimatedComponent.tsx
src/reanimated2/Colors.ts
src/reanimated2/PlatformChecker.ts
src/reanimated2/animation/decay.ts
src/reanimated2/hook/useAnimatedStyle.ts

This PR replaces direct platform checks such as `Platform.OS === 'android'` or `process.env.JEST_WORKER_ID` with functions from `PlatformChecker.ts` (or captured constants when used inside worklets).

Unify platform checks

---

src/reanimated2/UpdateProps.ts

This PR fixes a regression introduced in #4503.
If there was more than one view descriptor, `queueMicrotask(this.flush)` would never be called.
ChessboardExample.tsx

Fix update props flush for multiple view descriptors

---

src/reanimated2/js-reanimated/index.ts
src/reanimated2/threads.ts

This PR is amending some changes from #4276 where we exchanged `setImmediates` for `queueMicrotask` for `_scheduneOnJS`.
`queueMicrotask` does not take any arguments, only a callback and the change of behaviour stemming from this was not considered in `runOnJS` implementation. This PR fixes this and also makes `runOnJS` actually call `_scheduleOnJS` on web, making it asynchronous and consistent with general behavior of `runOnJS` - before it was unreachable code on web since it would simply return the provided function that was called synchronously.
Run WebExample and see that now `runOnJS` is working properly. I used the following snippet:
```TypeScript
function foo() {
console.log('hello');
}
function foz(str: string) {
console.log(str);
}
runOnJS(foo)();
runOnJS(foz)('bye');
function …
```

Fix runOnJS on Web and make it asynchronous

---

android/src/main/java/com/swmansion/reanimated/NodesManager.java
android/src/main/java/com/swmansion/reanimated/nativeProxy/EventHandlerMock.java
android/src/main/java/com/swmansion/reanimated/nativeProxy/NoopEventHandler.java

The goal of this PR was to remove unused variables form `private void handleEvent(Event event)`:
```diff
private void handleEvent(Event event) {
-  // If the event has a different name in native, convert it to it's JS name.
-  String eventName = mCustomEventNamesResolver.resolveCustomEventName(event.getEventName());
-  int viewTag = event.getViewTag();
if (mCustomEventHandler != null) {
event.dispatch(mCustomEventHandler);
}
}
```
But then I realized that we can avoid some unnecessary null-checks for mCustomEventHandler. The mCustomEventHandler could be a null value before initialization by void registerEventHandler(RCTEventEmitter handler) method.

Remove unnecessary null-checks for mCustomEventNamesResolver

---

android/src/main/cpp/NativeProxy.cpp
ios/REAModule.mm
ios/native/NativeProxy.mm

This PR aims to rename `module` variable which holds an instance of `NativeReanimatedModule` because `module` is a keyword since C++20. From now on, we will use the following naming convention:
* `std::shared_ptr<NativeReanimatedModule> nativeReanimatedModule`
* `std::weak_ptr<NativeReanimatedModule> weakNativeReanimatedModule`
* `REAModule* reaModule` (iOS)

Unify naming of `NativeReanimatedModule` and `REAModule` instances

---

Common/cpp/NativeModules/NativeReanimatedModule.cpp
Common/cpp/NativeModules/NativeReanimatedModule.h

This PR moves the inline implementation of `scheduleOnJS` from C++ lambda body to a separate method of `NativeReanimatedModule` so that it can be re-used for different purposes 😉 
WorkletExample.tsx &rarr; runOnUI + runOnJS demo

Move `scheduleOnJS` to a separate method

---

RNReanimated.podspec

In https://github.com/software-mansion/react-native-reanimated/pull/4504 we introduced dependency for `React-hermes` in iOS. But this dependency is available since rn@0.70 - more details here: https://github.com/facebook/react-native/commit/b3040ec6244da6ea274654abfd84516de4f5bf52
https://github.com/piaskowyk/reanimated-rn-version-tester/actions/runs/5360486792/jobs/9725423101
https://github.com/piaskowyk/reanimated-rn-version-tester/actions/runs/5364839077

Fix backward compatibility with react-native <= 0.69

---

ios/LayoutReanimation/REAAnimationsManager.h
ios/LayoutReanimation/REAAnimationsManager.m
ios/native/NativeProxy.mm

This PR just removes unused parameter `depth` from _startAnimationForTag on iOS.

Remove unused parameter from _startAnimationForTag method

---

android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java

This PR removes unused `viewTag` parameter from `updateLayout` on Android.

Remove unused parameter from updateLayout [Android]

---

src/reanimated2/hook/useAnimatedReaction.ts

In https://github.com/software-mansion/react-native-reanimated/pull/4466 I've replaced `useSharedValue` with `useRef` to avoid cloning saved objects on every update. This worked really well unless, as it turned out, there was a re-render in between the updates, in which case the saved value would reset back to null.
I think it's because the ref object that was captured in the closure of the worklet responsible for updating was actually a cloned object instead of the real ref, so each update would be applied to the cloned one. This PR reverts `useRef` change and instead passes `true` for `oneWayReadsOnly`, simply preventing the cloning as it was originally done in https://github.com/software-mansion/react-native-reanimated/pull/4466.
Fixes …

Replace `useRef` with `useSharedValue` in `useAnimatedReaction` to preserve value between renders

---

.github/workflows/build-monorepo.yml
ios/LayoutReanimation/REASnapshot.m

Current main CI is broken because of:
```
/Users/runner/work/react-native-reanimated/react-native-reanimated/monorepo/RootApp/node_modules/react-native-reanimated/ios/LayoutReanimation/REASnapshot.m:87:38: use of undeclared identifier 'RCTView'
_values[@"borderRadius"] = @(((RCTView *)view).borderRadius);
```
This PR try to resolve this issue by adding `RCTView.h` import. What is strange the problem exists only in monorepo.
See CI status

Fix monorepo-CI

---

Common/cpp/NativeModules/NativeReanimatedModule.cpp
Common/cpp/NativeModules/NativeReanimatedModule.h
Common/cpp/Registries/EventHandlerRegistry.cpp
Common/cpp/Registries/EventHandlerRegistry.h
android/src/main/cpp/NativeProxy.cpp
android/src/main/cpp/NativeProxy.h
android/src/main/java/com/swmansion/reanimated/nativeProxy/EventHandler.java
ios/REANodesManager.h
ios/REANodesManager.mm
ios/native/NativeProxy.mm
src/reanimated2/WorkletEventHandler.ts

The current event mechanism allows us to register for an event only when we know the react tag of the event emitter. This PR adds the possibility to register on events just by event name without knowing the emitter react tag. It'll be helpful for shared transition progress feature: https://github.com/software-mansion/react-native-reanimated/pull/4421
I tested it on iOS/Android & Paper/Fabric
<details>
```js
import { ParamListBase } from '@react-navigation/native';
import {
createNativeStackNavigator,
NativeStackScreenProps,
} from '@react-navigation/native-stack';
import Animated, { useEvent } from 'react-native-reanimated';
const Stack = createNativeStackNavigator();
function Screen1({ …
```

Register for events by name

---

src/reanimated2/animation/decay.ts

`const IS_WEB = isWeb();` was accidentaly moved inside the `'worklet'` function in this [PR](https://github.com/software-mansion/react-native-reanimated/pull/4519) on `decay.ts`
This PR moves it outside the `'worket'` function.
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/4656

Fix isWeb is not a function

---

android/src/main/cpp/NativeProxy.cpp
android/src/main/cpp/NativeProxy.h

This PR fixes the following crash on Android Fabric:
1. Launch FabricExample on Android
2. Open BubblesExample
3. Reload the app a few times by clicking <kbd>r</kbd>

Unregister commit hook on Android

---

Common/cpp/NativeModules/NativeReanimatedModule.cpp
Common/cpp/NativeModules/NativeReanimatedModule.h
Common/cpp/Tools/PlatformDepMethodsHolder.h
src/createAnimatedComponent.tsx
src/reanimated2/PropsRegistry.ts
src/reanimated2/globals.d.ts

This PR addresses the following TODO:
https://github.com/software-mansion/react-native-reanimated/blob/1359a1141ddd538b42d3c6db51d3e7c6fb586fd7/src/createAnimatedComponent.tsx#L363-L366
Previously, we would schedule a worklet via `runOnJS` for each individual unmounted animated component. Each worklet would call JSI binding `_removeFromPropsRegistry`. This PR adds batching layer on JS context and changes the semantics of `_removeFromPropsRegistry` so that it accepts an array of view tags to remove from PropsRegistry.
`PropsRegistry.cpp`
```diff
#ifdef RCT_NEW_ARCH_ENABLED
#include "PropsRegistry.h"
+#include <iostream>
namespace reanimated {
std::lock_guard<std::mutex> PropsRegistry::createLock() const {
+  {
+    std::lock_guard<std::mutex> lock(mutex_);
+    std::cout << "map_.size() = …
```

Batch remove from props registry

---

.github/workflows/build-monorepo-nightly.yml
.github/workflows/build-monorepo.yml

Currently this CI is extremely slow and we often accidentally cancel it/have to cancel it when we want to merge more often. With this change it's only run when it's absolutely needed and on daily (nightly) basis.

Move monorepo-build CI to nightly runs

---

.github/workflows/build-monorepo-nightly.yml

Currently its displayed name is `.github/workflows/build-monorepo-nightly.yml` 😿 
Yes

Add missing name to workflow

---

src/reanimated2/Colors.ts
src/reanimated2/shareables.ts

Previously, copying RegExp objects between JS and UI threads wasn't supported. This PR adds this functionality and fixes a minor bug in `INACCESSIBLE_OBJECT` error (getter's prop wasn't a string in all cases thus printing an error message could cause another error). 
Since we can copy a RegExp object from JS thread to UI thread from now on, there was no need to keep a shareable clone of `MATCHERS` in `Colors.ts`.
<details>
<summary>App.tsx</summary>
```tsx
import React from "react";
import { Button, StyleSheet, View } from "react-native";
import Animated, { useSharedValue, withTiming } from "react-native-reanimated";
const backgroundColor = useSharedValue("rgb(255, 0, 0)");
const colors = {
colors_rgb: ["rgb(255, 0, 0)", "rgb(0, 255, 0)", "rgb(0, 0, 255)"], …
```

Add support for sharing RegExp 

---

.eslintrc.js
plugin/.eslintrc.js
plugin/tsconfig.json

With changes from #4672 developing plugin is difficult because VSCode has problem resolving correct `tsconfig` and linting doesn't work in the editor (but it works in the CLI at least). This PR removes this rule till proper solution is found.

Temporarily remove ESLint rule that breaks plugin's linting in VSCode

---

ios/native/NativeProxy.mm

This PR eliminates a shared pointer cycle that prevented `REAModule` from de-allocating and thus caused the assert in `SingleInstanceChecker` to fail.

Fix reference cycle in `checkDuplicateSharedTag`

---

android/src/main/cpp/NativeProxy.cpp
android/src/main/cpp/NativeProxy.h
ios/native/NativeProxy.mm

This PR renames `animatedRuntime` to `uiRuntime` and `wrt` with `weakUiRuntime` as well as replaces old dirty `*wrt.lock()` with a proper check.

Rename `animatedRuntime` to `uiRuntime`

---

Common/cpp/Tools/Scheduler.cpp
Common/cpp/Tools/Scheduler.h
ios/native/REAIOSScheduler.h
ios/native/REAIOSScheduler.mm

I've noticed that `weak_ptr` for `runtimeManager` in iOS scheduler has executed `lock` method but returned `shared_ptr` is not used and thus deallocation immediately. In that case, if we just want to know whether `runtimeManager` `shared_ptr` is alive it's more performant to use `expired` method on `weak_ptr`.
I removed also some dead code:
- in `scheduleOnUI` there was unnecessary block of code checking if it's executed on main thread. If it is on main thread it returns from function several lines above the block and won't be executed.
- unnecessary virtual empty destructor for `REAIOSScheduler`. Base class has already virtual destructor and marking this again does not change anything. 
Check iOS application if works fine.

iOS scheduler optimisation fix

---

src/reanimated2/shareables.ts

Fixes: https://github.com/software-mansion/react-native-reanimated/issues/4690
It may happen when one of the user dependencies provided transpiled code with debug version of the Reanimated plugin. In effect, we have a debug version of the work in your release bundle. This might lead to unexpected issues or errors. 😢
I created issue with description how to fix this issue: https://github.com/software-mansion/react-native-reanimated/issues/4737

Detected debug version of the worklet in release bundle

---

src/reanimated2/layoutReanimation/sharedTransitions/ProgressTransitionManager.ts

This PR adds missing cleanup and reparenting of shared views after modal close.
|Before|After|
|---|---|
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/79852a34-44c6-48ab-8d83-b460963c154d" /> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/679ff9ab-3e34-4395-9640-c0dac36be243" /> |

Fix modal SET progress animation on Android

---

src/reanimated2/shareables.ts

This PR adds a developer-friendly error when worklet version is undefined. Related to #4736.

Throw error when worklet version is unknown

---

android/src/main/cpp/NativeProxy.cpp
android/src/main/cpp/NativeProxy.h

This PR renames ambiguous variable `runtime_` to `rnRuntime_` in NativeProxy class on Android.

Rename `runtime_` to `rnRuntime_` in NativeProxy

---

Common/cpp/Tools/PlatformDepMethodsHolder.h
android/src/main/cpp/LayoutAnimations.cpp
android/src/main/cpp/LayoutAnimations.h
android/src/main/cpp/NativeProxy.cpp
android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
android/src/main/java/com/swmansion/reanimated/layoutReanimation/LayoutAnimations.java
ios/LayoutReanimation/REAAnimationsManager.h
ios/LayoutReanimation/REAAnimationsManager.m
ios/native/NativeProxy.mm
src/reanimated2/globals.d.ts
src/reanimated2/layoutReanimation/animationsManager.ts
src/reanimated2/layoutReanimation/sharedTransitions/ProgressTransitionManager.ts

This PR removes unused parameter `canceled` for `endLayoutAnimation` method on both platforms.
Open example with Layout Animation

Remove unused parameter from endLayoutAnimation

---

src/ConfigHelper.ts

Some [layout props from react-native](https://reactnative.dev/docs/layout-props) were missing from their respective set.
Fixes #4743.

Add missing layout props to configHelper

---

Common/cpp/LayoutAnimations/LayoutAnimationsManager.cpp
Common/cpp/LayoutAnimations/LayoutAnimationsManager.h
android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
android/src/main/cpp/LayoutAnimations.cpp
android/src/main/cpp/LayoutAnimations.h
android/src/main/cpp/NativeProxy.cpp
android/src/main/java/com/swmansion/reanimated/layoutReanimation/LayoutAnimations.java
android/src/main/java/com/swmansion/reanimated/layoutReanimation/NativeMethodsHolder.java
android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
android/src/paper/java/com/swmansion/reanimated/NativeProxy.java
ios/LayoutReanimation/REAAnimationsManager.h
ios/LayoutReanimation/REASharedTransitionManager.m
ios/native/NativeProxy.mm

The `animationManager[.js].stop(viewTag: number)`([code here](https://github.com/software-mansion/react-native-reanimated/blob/3.3.0/src/reanimated2/layoutReanimation/animationsManager.ts#L89)) method accepts only one argument. This PR removes unnecessary additional arguments passed to this method.

Remove unused parameter from cancelAnimation

---

Common/cpp/SharedItems/JSRuntimeHelper.h
Common/cpp/SharedItems/Shareables.h

This PR moves `JSRuntimeHelper` class (along with `CoreFunction` class) to a separate file in order to decouple it from `Shareables.h`. Eventually, we will unify `JSRuntimeHelper` and `RuntimeManager` into a single class so this file will be deleted in the future.

Move `JSRuntimeHelper` to a separate file

---

src/reanimated2/threads.ts

Currently, in our code we have
```ts
const IS_WEB = shouldBeUseWeb();
```
which is confusing because there's also a function called `isWeb()`.
This PR replaces all occurrences of `!IS_WEB` with `IS_NATIVE` like we already do in a few places.

Rename confusing variable

---

src/reanimated2/animation/transformationMatrix/matrixUtils.tsx

This PR fixes the following error that occurs after clicking "GO GO MATRIX" button:

Add missing worklet directive in `assertVectorsHaveEqualLengths`

---

src/reanimated2/publicGlobals.ts

So the user might read it when it's used.
b4:
after:

Make publicGlobals comments TSDoc

---

src/reanimated2/js-reanimated/index.ts
src/reanimated2/threads.ts

This PR addresses a regression introduced by me in #4780.
After long consideration, it occurred to me that both `_makeShareableClone` and `_scheduleOnJS` were originally meant to represent JSI bindings (i.e. JS functions implemented in C++ and injected via JSI), thus none of them should ever be used when in JSReanimated mode.
This PR moves the implementation of `_scheduleOnJS` to the only place where it's called which enables us to generalize it to cover more cases, in particular calling `runOnJS` on the main React Native runtime.
Kudos for @tjzel for investigating the issue and submitting a hotfix (#4790).
<details>
<summary>App.tsx</summary>
```tsx
import {StyleSheet, View, Button} from 'react-native';
import {runOnJS} from 'react-native-reanimated';
export …
```

Fix `runOnJS` calling `_makeShareableClone` when already on the JS thread

---

ios/REANodesManager.h
ios/REANodesManager.mm
ios/keyboardObserver/REAKeyboardEventObserver.m

Some users have observed following thread lock:
<details><summary>Error log</summary>
```
Thread 0 - com.apple.main-thread - (TH_STATE_WAITING)
0  libsystem_kernel.dylib +0x1c88  ___psynch_mutexwait
1  libsystem_pthread.dylib +0x2110 __pthread_mutex_firstfit_lock_wait
2  libsystem_pthread.dylib +0x9314 __pthread_mutex_firstfit_lock_slow
3  QuartzCore +0xa07cc             CA::Display::DisplayLinkItem::set_preferred_fps_range(CAFrameRateRange, bool, bool)
4  QuartzCore +0x3a918             CA::Display::DisplayLink::update_timer_locked(bool)
5  QuartzCore +0x3a504             CA::Display::DisplayLink::update_timer(bool)
6  QuartzCore +0xbf40c             CA::Display::DisplayLink::callback(_CADisplayTimer*, unsigned long long, unsigned long long, unsigned long long, bool, void*)
7  QuartzCore …
```

Initialize CADisplayLink on UI thread

---

package.json

Currently docs have some issue while linting that some file couldn't be found by the linter and is extremely annoying when trying to commit, being forced to commit without precommit check.
Guess automatically linting docs waits for better times.

Remove infuriating docs lint from precommit

---

app/src/examples/BabelVersionCheckExample.tsx
app/src/examples/BabelVersioningExample.tsx
app/src/examples/index.ts
src/reanimated2/shareables.ts

Currently the error tells us that something is wrong but we don't have a clue what could be causing it. This PR makes error more verbose, displaying code of the offending worklet. I also added some cheeky Example for that purpose.
Run new `BabelVersioningExample`
🚀

Make babel version detection more verbose

---

android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java

Fixes https://github.com/software-mansion/react-native-reanimated/issues/4422
Fixes the bug with Android freezing when Layout Animations are used in a modal.
1. clone the example repository https://github.com/ceceppa/reanimated-3-bug
2. apply the fix in this PR (or copy the code into your own project)
3. build and run on Android
4. open the model
5. close the modal
6. open the modal again -> without the fix in this PR, this will fail as the UI becomes unresponsive

Cancel animation for modals

---

src/reanimated2/mock.ts

Found a mock issue when I writing a test with jest for my own react native component which used the `BounceIn.delay` animation, it will throw an error saying: `Cannot read properties of undefined (reading 'delay')`.
After the investigation, it turns out the `BounceIn` was missing in the mock file, so I opened this PR to resolve this issue.

add the missing BounceIn to the mock file

---

src/reanimated2/core.ts

`isConfigured` was an internal check that due it's directory's `index.ts` having `export * from ./core` was available as a direct import from `react-native-reanimated`. Therefore we cannot simply remove it in a minor version - deleting it raised https://github.com/react-navigation/react-navigation/issues/11498, `react-navigation` uses this function [here](https://github.com/react-navigation/react-navigation/blob/24c03924397a6e59aba9f6b74a9c5cb4b939d9e1/packages/react-native-drawer-layout/src/views/Drawer.tsx#L56) to detect Reanimated 3 since Reanimated 2 didn't have this function.
This PR restores this function, marks it as deprecated and adds a separate `public` check to detect Reanimated 3.
🚀
We should probably locate more functions that are exported as a part of public API but they …

Restore `isConfigured` function

---

src/reanimated2/animation/transformationMatrix/matrixUtils.tsx

Since I've forgot to merge my PR before merging I have to fix main 😎
Our tool detecting unused code, `ts-prune` reports functions used only in tests and inside a module. Indeed we export 3 functions only for purpose of testing, which is considered to be an anti-pattern (but IMHO it is a very good practice to test low level functions instead of only high level ones). It seems hard to configure `ts-prune` to change it's behaviour. On the other hand I like the idea of adding
```
// ts-prune-ignore-next This function is exported to be tested
```
in each occurrence of the situation, since it always give some potentially valuble information to the reader. Also the situation (exporting function which is imported in test files only) does not happen often (only 3 times in whole codebase).
Just CI

Fix main by adding missing `ts-prune-ignore-next`

---

Example/ios/Podfile.lock
Example/package.json
Example/yarn.lock
FabricExample/ios/Podfile.lock
FabricExample/package.json
FabricExample/yarn.lock
app/package.json
app/yarn.lock

Since https://github.com/software-mansion/react-native-screens/pull/1810 got merged and included in `3.23.0` release we can use the npm published pack again.
Yes

Bump `react-native-screens`

---

Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp
Common/cpp/NativeModules/NativeReanimatedModule.cpp
Common/cpp/SharedItems/Shareables.h

This PR replaces a few occurrences of `extractShareableOrThrow` with `extractShareableOrThrow<T>` which asserts the type of the shareable along with a proper error message.

Assert shareable type

---

ios/native/REAInitializer.h
ios/native/REAInitializer.mm

Fixes https://github.com/software-mansion/react-native-reanimated/issues/4631
In https://github.com/software-mansion/react-native-reanimated/pull/4619 I removed REAInitializer because it is no longer needed. However, some brownfield apps still use it. This PR adds a mock for REAInitializer to ensure backward compatibility.
CI

Mock REAInitializer for backward compatibility

---

src/reanimated2/helperTypes.ts

A few months back RN [added in its types](https://github.com/facebook/react-native/issues/37543) that `transform` could be a `string` - but it's missing in RN `0.72.3` and causes some errors when current version of `react-native-reanimated` is used with RN `0.71`. This PR hotfixes that, allowing `transform` to be a string.
Keep in mind that it's definitely not the final form of how `useAnimatedStyle` types should look like - it will be refactored in the future.
<details>
<summary> This snippet yields errors on `0.71.12` without this change </summary>
```TSX
function Foo() {
const sv = useSharedValue(0);
const otherSv = useSharedValue(0);
const width = 200;
// error here, transform being inferred to `never`
return {
width: '200%',
alignItems: …
```

Hotfix: allow transform to be a string in useAnimatedStyle

---

src/reanimated2/fabricUtils.ts
src/reanimated2/hook/useAnimatedRef.ts

~~In types of `react-native` we can see that `getNativeScrollRef` and `getScrollableNode` could return `null` or `undefined`. This PR makes this acknowledged in `useAnimatedRef`.~~
Since #4873 cast new light on how these types should be I checked how are those methods typed in `react-native` and seeing it we decided simply to use `any` since it seems like the only safe option currently.
<details>
<summary>pic rel</summary>
</details>
CI

Allow nullables in useAnimatedRef scrollable node getters

---

ios/LayoutReanimation/REAAnimationsManager.m

This PR adds default instances for uninitialized blocks in AnimationManager on iOS. It helps avoid null exceptions in two cases:
- When reloading during Layout Animations and Shared Transitions.
- When someone has installed Reanimated but doesn't import anything from it. In this situation, these blocks will not be set, but due to swizzling in Screens, there is a possibility of calling some of these blocks.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/4836
Fixes:
1. Run Example -> open [LA] Entering and Exiting with Layout -> click toggle -> press R in console
2. Run example from https://github.com/software-mansion/react-native-reanimated/issues/4836#issuecomment-1659917226

Add default implementations for blocks from AnimationsManager on iOS

---

docs/docs/api/hooks/useAnimatedGestureHandler.md

Since `2.10.0` gesture handler enables new web implementation by default. Because of that `useAnimatedGestureHandler` doesn't work unless both `onGestureEvent` and `onHandlerStateChange` props are defined. This PR updates docs entry for `useAnimatedGestureHandler` so that people will be aware of that change.

Update `useAnimatedGestureHandler` in docs

---

Common/cpp/Fabric/FabricUtils.cpp
Common/cpp/Fabric/FabricUtils.h
Common/cpp/Fabric/ReanimatedCommitHook.cpp
Common/cpp/Fabric/ShadowTreeCloner.cpp
Common/cpp/Fabric/ShadowTreeCloner.h
Common/cpp/NativeModules/NativeReanimatedModule.cpp

I noticed that in our `ReanimatedCommitHook` on each commit we copy `shared_ptr` of `UIManager` and `ContextContainer`. I've gone through the code and such copies are not needed as object using them are short-lived without option to deallocation of needed resources.
Those copies can be pretty time consuming due to locks in `shared_ptr` implementation.
Check performance on Android and iOS

Removed unnecessary copies of UIManager and ContextContainer

---

Common/cpp/Fabric/PropsRegistry.h

Let's store last reanimated root in `PropsRegistry` as atomic pointer.
This will let us get rid of additional `std::shared_ptr` copy and will be more thread-safe.
None

Store last reanimated root as atomic ptr, avoid copying and locking

---

Common/cpp/Fabric/ReanimatedCommitHook.cpp
Common/cpp/Fabric/ReanimatedCommitHook.h
android/src/main/cpp/NativeProxy.cpp
ios/REAModule.mm

`ReanimatedCommitHook` was not unregister during shutdown of iOS module so I moved responsibility of registration and deregistration to constructor and destructor of that class making use of RAII allowing me to skip unnecessary calls.
None

Moved (de)registration of ReanimatedCommitHook to its con/de-structor

---

docs/docs/fundamentals/getting-started.mdx

You need to click each tab one by one if you use a certain package manager.
https://github.com/software-mansion/react-native-reanimated/assets/39658211/74a75188-4480-4983-9e96-7e18a79001b7
Your choice in tabs syncs after a selection 
https://github.com/software-mansion/react-native-reanimated/assets/39658211/a98c8301-79aa-4a37-82a6-c1cd7bf51dc2
Requested in https://twitter.com/samrithshankar/status/1689513343504257029?s=20

Sync tabs in docs/getting-started

---

.github/workflows/android-build.yml
.github/workflows/build-on-windows-nightly.yml
.github/workflows/build-v8-nightly.yml
.github/workflows/ios-build.yml
.github/workflows/main.yml
.github/workflows/static-example-apps-checks.yml
.github/workflows/static-root-checks.yml
.github/workflows/tvos-build.yml
.github/workflows/validate-java.yml
.github/workflows/validate-plugin.yml
README.md

This PR aims to reduce unnecessary triggering of CI by implementing a limitation. Additionally, it moves the 'Build V8' and 'Build on Windows' processes to nightly actions.
Merge this PR 🎉

Run CI only if it's needed

---

docs/src/components/InteractivePlayground/useSpringPlayground/index.tsx

withSpring docs config section (https://docs.swmansion.com/react-native-reanimated/docs/animations/withSpring#config-) missing comma in the playground after `dampingRatio` and `damping `

fix: docs withSpring playground missing comma

---

ios/RCTEventDispatcher+Reanimated.m

@hirbod reported an issue with reanimated 3.4 + expo-dev-client on ios that `useEvent` is broken. this happens because of the setup of expo-dev-client and would like to propose and discuss solution in this pr.
expo-dev-client will create multiple bridges:
- app bridge: the target app
- expo-dev-menu: the customized dev menu is also a react native app.
- expo-dev-launcher: the default start ui that for user to choose a target app is also a react native app.
when clicking the app in ios springboard, i.e. not starting the app through deep linking, the default startup ui will launch expo-dev-launcher first. the initialize flow will be
1. `RCTEventDispatcher+Reanimated +load`
2. create a bridge for expo-dev-launcher
3. even expo-dev-launcher doesn't use reanimated now, as long as other code in …

Fix event dispatcher broken on ios with expo-dev-client

---

app/src/examples/AboutExample.tsx

Previously, `getRuntime()` function in `AboutExample.tsx` would only check if Hermes is enabled, otherwise it would return "JSC". This PR extends the implementation by checking if the current JS engine is V8.
AboutExample.tsx

Detect V8 engine in AboutExample

---

android/src/main/cpp/NativeProxy.cpp

This PR eliminates a crash on Android that occurs when Reanimated tries to handle an event with `null` payload.
`EventHandler.java`
```diff
@Override
public void receiveEvent(int emitterReactTag, String eventName, @Nullable WritableMap event) {
String resolvedEventName = mCustomEventNamesResolver.resolveCustomEventName(eventName);
-    receiveEvent(resolvedEventName, emitterReactTag, event);
+    receiveEvent(resolvedEventName, emitterReactTag, null);
}

Ignore events with null payload on Android

---

.eslintrc.js
src/reanimated2/animation/util.ts

This PR adds an eslint rule that forces `import type` to always have the `type` specifier on the top level.

Add eslint rule for consistent `import type`

---

Common/cpp/Fabric/PropsRegistry.h
Common/cpp/Fabric/ReanimatedCommitHook.cpp
Common/cpp/Fabric/ReanimatedCommitMarker.cpp
Common/cpp/Fabric/ReanimatedCommitMarker.h
Common/cpp/NativeModules/NativeReanimatedModule.cpp

Proposed solution is more bullet proof solution for detecting whether currently committed shadow tree comes from reanimated.
Here are the main issues with current implementation:
- if there's another commit hook that is executed before `reanimated` one, then `propsRegistry_->isLastReanimatedRoot(newRootShadowNode)` may not work if the commit hook creates a copy of committed tree
- when `stateReconciliation` is enabled via commit options then new tree root is created and again above detection does not work.
It uses concept of `thread_local` c++ variable which has instance for each thread and RAII to ensure that the appropriate flag is set to `true` on entering commit section and reset to `false` after commit from reanimated on UI thread.
- enable state reconciliation for commit from …

Better reanimated shadow tree commit detection

---

android/gradle.properties

This PR removes `MaxPermSize` flag from `android/gradle.properties`, because is removed since Java 17 https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#removed-java-options. The next React Native version will require Java 17.
```
➜  android git:(main) java --version
openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment Homebrew (build 17.0.8+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.8+0, mixed mode, sharing)
```
```
➜  android git:(main) ./gradlew :spotlessApply
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
FAILURE: Build failed with an exception.
Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
```
cd android && …
```

Fix compatibility with Java 17

---

src/reanimated2/PlatformChecker.ts
src/reanimated2/js-reanimated/JSReanimated.ts

When SSG is used to generate a website the `window` object can't be accessed (in the server portion of the build). This PR adds an availability check for when `window` is used.

Add `window` availability check

---

src/reanimated2/NativeMethods.ts

This PR adds check whether `animatedRef` has been set or not. If ref is not defined, calling `element.scrollTo` results in crash, because `element` is set to `-1`.
Fixes #4424 
Tested on snack from [issue](https://github.com/software-mansion/react-native-reanimated/issues/4424)

Fix scrollTo crash

---

Common/cpp/Fabric/PropsRegistry.cpp

I found out that many shadow nodes are stored in `PropsRegistry` even if newer versions were passed to `update` method. This PR replaces old `ShadowNode` with new one if needed.
None

Replace old shadow nodes in PropsRegistry with new ones

---

Common/cpp/Fabric/PropsRegistry.h
Common/cpp/Fabric/ReanimatedCommitHook.cpp
Common/cpp/Fabric/ReanimatedMountHook.cpp
Common/cpp/Fabric/ReanimatedMountHook.h
Common/cpp/NativeModules/NativeReanimatedModule.cpp
android/src/main/cpp/NativeProxy.cpp
android/src/main/cpp/NativeProxy.h
apple/REAModule.mm

React Native 0.73 introduces concept of mount hooks. Such hook is useful to notify Reanimated that shadowTree commit coming from React Native has finished so that Reanimated can commit its own changes.
The solution has shown about 15% performance gain in number of successful commits per second.
None

Added optimization to shouldSkipCommit mechanism

---

Common/cpp/NativeModules/NativeReanimatedModule.cpp

During investigation of race between RN and reanimated shadow tree committing I've noticed that if JS thread commits a new tree (triggering `pleaseSkipReanimatedCommit`) after starting `commit` from reanimated, the latter `commit` may cause JS commit failures.
What's more, additional calls to `shouldReanimatedSkipCommit ` result in avoiding CPU consuming copy operations on nodes and thus seems to work more performant.
I added those checks just before each operation handling and just after full commit.
Chessboard example seemed to work a bit faster that without those changes. I used also profiler and in overall CPU spends less time in ShadowTree.
NOTICE ⚠️ 
This change requires change in RN codebase. PR has been submitted https://github.com/facebook/react-native/pull/38715
Check …

Improved skipping commits

---

android/build.gradle

This PR exposes `libreanimated.so` along with necessary headers as a prefab on Android so it can be easily consumed by other third-party libraries (e.g. VisionCamera) without a need to manually specify paths to node_modules.
```gradle
android {
buildFeatures {
prefab true
}
}
```
```cmake
find_package(react-native-reanimated REQUIRED CONFIG)
target_link_libraries(${PACKAGE_NAME} react-native-reanimated::reanimated)
```
> [!NOTE]  
> For now, we expose all header files, but this is subject to change as ultimately we want to expose only headers from public C++ API.
> [!NOTE]  
> When using `com.android.tools.build:gradle:7.3.1` the following error may occur. Please upgrade to 7.4.2 or newer.
```
Usage: prefab [OPTIONS] PACKAGE_PATH...
Error: Invalid value for "PACKAGE_PATH": Directory …
```

Expose `libreanimated` to be consumed via prefab

---

docs/docs/guides/debugging_tables/tables.tsx
docs/package.json
docs/versioned_docs/version-2.x/api/LayoutAnimations/EntryAnimations.md
docs/versioned_docs/version-2.x/api/LayoutAnimations/ExitAnimations.md
docs/versioned_docs/version-2.x/api/animations/withDecay.md
docs/versioned_docs/version-2.x/api/animations/withDelay.md
docs/versioned_docs/version-2.x/api/animations/withRepeat.md
docs/versioned_docs/version-2.x/api/animations/withSequence.md
docs/versioned_docs/version-2.x/api/animations/withSpring.md
docs/versioned_docs/version-2.x/api/animations/withTiming.md
docs/versioned_docs/version-2.x/api/hooks/useAnimatedKeyboard.md
docs/versioned_docs/version-2.x/api/hooks/useAnimatedProps.md
docs/versioned_docs/version-2.x/api/hooks/useAnimatedSensor.md
docs/versioned_docs/version-2.x/api/hooks/useDerivedValue.md
docs/versioned_docs/version-2.x/api/hooks/useSharedValue.md
docs/versioned_docs/version-2.x/api/miscellaneous/getRelativeCoords.md
docs/versioned_docs/version-2.x/api/nativeMethods/measure.md
docs/versioned_docs/version-2.x/api/nativeMethods/scrollTo.md
docs/versioned_docs/version-2.x/fundamentals/animations.md
docs/versioned_docs/version-2.x/fundamentals/layout_animations.md
docs/versioned_docs/version-2.x/fundamentals/shared-values.md
docs/versioned_docs/version-2.x/guide/debugging.mdx
docs/versioned_docs/version-2.x/guide/debugging_tables/tables.tsx
docs/yarn.lock

The relative links in v2 docs sometimes lead a 404 Not found when a user has a dangling `/` at the end of an URL:
https://github.com/software-mansion/react-native-reanimated/assets/39658211/de7aa6da-cf0f-4f45-ada4-8363b5a7817b
This can be fixed by using absolute links which are introduced in this PR:
https://github.com/software-mansion/react-native-reanimated/assets/39658211/04741f57-d281-437b-8b7d-122d839a5b3f
Requested by @aleqsio 
```
cd docs
yarn
yarn start
```

Change relative links to absolute in v2 docs

---

android/CMakeLists.txt

This PR sorts paths in `target_include_directories` as well as removes `"${COMMON_SRC_DIR}/cpp/SpecTools"` which no longer exists.
Check if CI is green.

Sort include paths in CMakeLists.txt

---

apple/LayoutReanimation/REASharedTransitionManager.m

Fixes https://github.com/software-mansion/react-native-reanimated/issues/4992
This issue may happen when someone uses an older version of RN screens without the `isModal` method. This PR adds a check to detect if this selector exists. If not, the whole SET feature is disabled.
Try to compile the App with the newest Reaniamted and the old version of rn-screens.

Fix compatibility with older rn-screens version

---

Common/cpp/SharedItems/Shareables.cpp
Common/cpp/SharedItems/Shareables.h

This PR fixes a crash that occurs during a reload of the app. `ShareableRemoteFunction` holds a reference to a remote function in `function_` field. When `ShareableRemoteFunction` is deallocated, `function_` also gets deallocated. If the runtime has already been terminated, the assert in `~jsi::Pointer` will fail.
Tested on VisionCameraExample.

Fix crash on reload in `ShareableRemoteFunction`

---

__typetests__/react-native-reanimated-tests.tsx
src/reanimated2/index.ts

This PR adds `isSharedValue` function to the public API because `@Shopify/react-native-skia` uses it:
https://github.com/Shopify/react-native-skia/blob/3563788df6fe0b75f48bc4300ab8a94f603a4662/package/src/external/reanimated/moduleWrapper.ts#L59

Expose `isSharedValue`

---

__typetests__/react-native-reanimated-tests.tsx
src/reanimated2/core.ts
src/reanimated2/index.ts

This PR adds `makeShareableCloneRecursive` to the public API.
Example use case:
```ts
const runtime = createWorkletRuntime('foo');
const worklet = () => {
'worklet';
console.log(42);
};
someJSIBindingFromThirdPartyLibrary(runtime, makeShareableCloneRecursive(worklet));
```
We need to call `makeShareableCloneRecursive` here so that the argument is an instance of `std::shared_ptr<ShareableWorklet>` and not just a `jsi::Function`. Also, we need the whole worklet closure to be shareable.
An alternative would be to expose a new function `makeShareableWorklet`.
See typetests.

Expose `makeShareableCloneRecursive`

---

Common/cpp/ReanimatedRuntime/ReanimatedHermesRuntime.h
Common/cpp/Tools/UIScheduler.h
Common/cpp/hidden_headers/Logger.h

I've noticed that some headers did not have enough includes to be self-sufficient. I've alse make a quick test using this CMake helper code that compiles each header from Common directory:
```
file(GLOB_RECURSE HEADER_FILES CONFIGURE_DEPENDS "${COMMON_SRC_DIR}/**.h")
foreach(header ${HEADER_FILES})
get_filename_component(header_name ${header} NAME)
get_filename_component(directory ${header} DIRECTORY)
string(REPLACE ".h" ".cpp" CPP_FILE ${header_name})
configure_file(${header} ${CMAKE_BINARY_DIR}/destination_dir/${CPP_FILE} COPYONLY)
add_library(${header_name}_test ${CMAKE_BINARY_DIR}/destination_dir/${CPP_FILE})
target_link_directories(${header_name}_test PRIVATE ${directory})
target_link_libraries(${header_name}_test ${PACKAGE_NAME})
add_test(NAME ${header_name}_test COMMAND …
```

Added some includes to make headers self sufficient

---

src/animationBuilder.tsx
src/reanimated2/layoutReanimation/animationBuilder/commonTypes.ts
src/reanimated2/layoutReanimation/sharedTransitions/SharedTransition.ts

1. Use typescript regex types to generate object with `current` and `target` prefixes based on a single source of truth
- This may be a good change, since we consider supporting more animation properties.
3. Extract common properties from similar types to reduce boiler-plate code, use inheritance instead of copy-pasting them
4. Get rid of `[key: string]: number | number[];` 🥳 
5. Remove lots of type casts in `SharedTransition.ts` 🥳 
`yarn type:check` & `yarn type:check-api`

Improve entry exit animation types

---

src/reanimated2/SetNativeProps.ts

This PR adds a check whether the user calls `setNativeProps` on the UI runtime. Currently, running `setNativeProps` from JS thread results in a non-relevant runtime crash.
```jsx
runOnUI,
setNativeProps,
export default function Example() {
const animatedRef = useAnimatedRef<TextInput>();
const handlePress = () => {
// runOnUI(() => {
setNativeProps(animatedRef, { backgroundColor: 'blue' });
// })();
};
return (
<Animated.View ref={animatedRef} style={styles.box} />
<Button title="set native prop" onPress={handlePress} />
</View>
);
}
const styles = StyleSheet.create({
container: {
flex: 1,
alignItems: …
```

Notify users to run `setNativeProps` on the UI runtime

---

docs/docs/core/useAnimatedProps.mdx

Fixed small typo in [useAnimatedProps doc](https://docs.swmansion.com/react-native-reanimated/docs/core/useAnimatedProps)
Should be `useAnimatedProps` instead of `useAnimatedStyle` I guess

docs: typo in useAnimatedProps.mdx

---

src/reanimated2/NativeMethods.ts

While going through our example app I stumbled upon crash in "Article progress" example. Turns out that sometimes we try to call `getBoundingClientRect` on element that has not been rendered yet. This PR fixes this problem.
Tested on "Article progress" example.

Fix `measure` crash on web

---

apple/REANodesManager.mm

The `synchronouslyUpdateViewOnUIThread` method adds all received props to the `propKeysManagedByAnimated_DO_NOT_USE_THIS_IS_BROKEN` registry. If some style prop is added to this registry, then it is unable to animate it from the commit hook. This PR prevents to addition of props managed by Reanimated to the `propKeysManagedByAnimated_DO_NOT_USE_THIS_IS_BROKEN` registry. A similar solution exists in the RN codebase: https://github.com/facebook/react-native/blob/850349b1d274f0cc2595eee2f6bb361a958bb2e2/packages/react-native/React/Fabric/Mounting/RCTMountingManager.mm#L308-L310
Related PR:
- https://github.com/facebook/react-native/commit/b2c022ec54f094f84407151bb2756e1cb7202bc4
- https://github.com/facebook/react-native/commit/c642afd97d2f0ce7657405d72538cecaefadc036
Run "Animate stack …

Clear PropKeysManagedByAnimated register

---

Common/cpp/SharedItems/Shareables.cpp
FabricExample/ios/Podfile.lock
src/reanimated2/shareables.ts

#4617 Changed the logic of `makeShareableCloneOnUIRecursive`, detecting if the object is a `HostObject` and skipping its serialization, on the assumption that it's already good to go. This caused crashes in `extractShareableOrThrow` due to how `isHostObject<T>` function works - it not only checks if the object is a `HostObject` but also if it's of type `T`.
Therefore, given a `HostObject` from `react-native`, in this case `ShadowNodeWrapper` on Fabric, it wasn't converted to our `Shareable` type and failed the second check in `extractShareableOrThrow`.
Big thanks to @piaskowyk who debugged the most of it 🥳 
See that without the change in `makeShareableCloneOnUIRecursive` the new error is thrown.
I have added some (seemingly) unnecessary `HostObject` creation elision, please check if it's …

Add missing HostObject serialization in `makeShareableCloneOnUIRecursive`

---

apple/LayoutReanimation/REASwizzledUIManager.mm

See https://github.com/Expensify/App/issues/20552#issuecomment-1687710922 for details.

Remove `setNextLayoutAnimationGroup` call

---

src/reanimated2/animation/spring.ts

Disclaimer:
I'm unsure if this is a bug in the spring implementation or should be addressed elsewhere in the code, but it does happen only with `withSpring`, and kinda randomly, I could not reproduce it with `withTiming`.
While developing the screen transition animation, I noticed that the animation would stop near the end and then we unmount the screen, but it would never just finish completely. After some investigation, realized that the reason for that is the `restDisplacementThreshold` flag in the spring animation. 
When I tried to log the values in both my `useAnimatedStyle` and `springOnFrame` callback, I realized that useAnimatedStyle is never called with the end values.
```
LOG  0
LOG  0.054379944363520116
LOG  0.17171456096392557
LOG  0.3075683139784404
LOG  0.4390611486117857 …
```

Finish clamped spring animation

---

src/reanimated2/animation/spring.ts

Revert change https://github.com/software-mansion/react-native-reanimated/pull/5051
We have decided to revert [this change](https://github.com/software-mansion/react-native-reanimated/pull/5051) since using such a fixes instead of understanding the reason of the problem may lead to future bugs.
Try to reproduce the initial issue

Revert #5051

---

src/reanimated2/shareables.ts
src/reanimated2/threads.ts
src/reanimated2/valueUnpacker.ts

fixes 
- https://github.com/software-mansion/react-native-reanimated/issues/5067 
- https://github.com/software-mansion/react-native-reanimated/issues/5075
- https://github.com/software-mansion/react-native-reanimated/issues/5069
- https://github.com/software-mansion/react-native-reanimated/issues/5091
quoting @tjzel explanation just for reference
> The problem is with Cpp HostObjects, they always return true for in operator in JS and now we have more situations where those can be used as worklets. Therefore the only proper check is actually checking if value is truthy.
_had to skip git hooks due to typing errors_
PR that created this error:
#4794

fix Maximum call stack size exceeded

---

src/reanimated2/index.ts

This PR fixes broken integration with Skia. The concept is to export publicly `startMapper` and `stopMapper` for now but in the future reexport those functions with different names so they would be more explicit about what they do.
Check if Skia works.

Fix Skia-Reanimated integration 

---

app/src/examples/DragAndSnapExample.tsx
src/reanimated2/PlatformChecker.ts
src/reanimated2/hook/useAnimatedScrollHandler.ts
src/reanimated2/index.ts

Fixes regression that occurred in #5074.
Later on we also have to rethink if we want to promote `Extrapolate` or `Extrapolation` since both are exactly the same and we only use the former.
I actually made `Extrapolation` used in our examples so such mistake in the future would be caught on CI (only regarding `Extrapolation` sadly).
> [!Note]
> I recommend using this
> ```json
> "editor.tokenColorCustomizations": {
>    "textMateRules": [
>      {
>        "scope": "entity.name.type.enum",
>        "settings": {
>          "foreground": "#a3e577"
>        }
>      },
>      {
>        "scope": "entity.name.type.class",
>        "settings": {
>          "foreground": "#e8b55e"
>        }
>      }
>    ]
>  }
>```
> In your VSCode settings so Classes, Enums and Types are not in the same …

Fix exporting enums as types and type of global in PlatformChecker

---

src/createAnimatedComponent/PropsFilter.tsx
src/createAnimatedComponent/createAnimatedComponent.tsx
src/createAnimatedComponent/utils.ts

File `createAnimatedComponent.tsx` contains our most important logic. It is already very big and since in the future we want to support ${\textcolor{teal}{\textsf{inline Styles}}}$ this file may grow a lot. Thats why we should make it clear and easy to rid - for example by splitting it across many small files.
This refactor will be made in smaller parts.
* Create folder 📁 `createAnimatedComponent` 
* Move all files used only in `createAnimatedComponent.tsx` into that folder. Move `createAnimatedComponent.tsx` as well.
* Extract all util function into separate file.
* Create class `inlinePropUpdater.tsx` which handles logic related with inline styles.
This is not fixed yet, but I suggest we should:
* Move function `_filterNonAnimatedProps` away (70 lines of code)
Run the app, nothing …

Reduce file createAnimatedComponent - part3

---

src/createAnimatedComponent/PropsFilter.tsx
src/createAnimatedComponent/createAnimatedComponent.tsx

This PR fixes a regression introduced in https://github.com/software-mansion/react-native-reanimated/pull/5102. The `filterNonAnimatedProps` method stores `this` in some registries, after the relocation of this function to another class `this` no longer points to a component.
Run web example and run any animation

Fix `this` context on Web

---

docs/docs/guides/troubleshooting.mdx

The link in the "Failed to create a worklet" error had an old installation link that gave a 404 code. The link has been replaced with a new one.

docs: Change installation url in "Failed to create a worklet" error

---

android/build.gradle
docs/docs/guides/troubleshooting.mdx
scripts/reanimated_utils.rb

This PR fixes URL form for troubleshooting docs section. From 
```
react-native-reanimated/docs/guides/Troubleshooting
```
to
```
react-native-reanimated/docs/guides/troubleshooting
```
Because in many places in source code we uses `react-native-reanimated/docs/guides/troubleshooting` form.
Inspired by https://github.com/software-mansion/react-native-reanimated/pull/5131
Check documentation build

Change troubleshooting docs section Id

---

src/reanimated2/layoutReanimation/web/animationsManager.ts

In newer version of React Native `transform` prop can be a `string`.

Fix web layout animations manager not handling `string` transform

---

scripts/reanimated_utils.rb

When I tried to activate NEW_ARCH within the project while having React Native version 0.71.12 installed, I encountered the following error during the pod-install step for the Reanimated library:
"Invalid RNReanimated.podspec file: undefined local variable or method `reanimated' for Pod:Module
Did you mean? reanimated_version."
This pull request contains a solution to this error.
You can install the latest version of Reanimated in a project with a React Native version lower than 0.72 by running the following command: RCT_NEW_ARCH_ENABLED=1 pod install.

Fixed usage reanimated_version name on reanimated_utils file

---

src/ConfigHelper.ts
src/createAnimatedComponent/InlinePropManager.ts

This PR makes the behavior of `useAnimatedStyle` and InlineStyles API consistent. Because of wrong order of checks in `getInlinePropsUpdate` potential Shared Values were treated as arrays and threw errors - this didn't happen for the same usage of Shared Value with `useAnimatedStyle`.
```TSX
const sv = useSharedValue([{ translateX: 50 }, { translateY: 50 }]);
const handlePress = () => {
sv.value = [{ translateX: 100 }, { translateY: 100 }];
};
return {
transform: sv.value,
};
});
return (
<Button title="Press me" onPress={handlePress} />
{/* This works. */}
<Animated.View style={[styles.box, animatedStyle]} />
{/* This doesn't. */}
<Animated.View style={[styles.box, { transform: …
```

Reorder checks in `getInlinePropsUpdate` and remove `transform`-specific syntax

---

src/reanimated2/component/LayoutAnimationConfig.tsx

This PR adds missing `import React from 'react'` to `LayoutAnimationConfig`. Without it the docs would fail.

Fix `LayoutAnimationConfig`

---

src/reanimated2/js-reanimated/index.ts
src/reanimated2/layoutReanimation/web/animationsManager.ts

If a component has an entering animation and is simultaneously running a standard animation (e.g., withTiming), it is possible for the component to disappear. This issue arises because the standard animation utilizes `setNativeProps`, which stores the last applied style. As a result, any changes to the style made using the syntax `element.style.visibility = 'initial'`will be overridden by `setNativeProps`.
Run example
<details>
```js
withTiming,
FadeIn,
import { View, Button, StyleSheet } from 'react-native';
export default function AnimatedStyleUpdateExample() {
const randomWidth = useSharedValue(10);
return { …
```

Fix web layout animations during standard animation

---

docs/docs/core/useAnimatedStyle.mdx
docs/docs/fundamentals/animating-styles-and-props.mdx

This PR explains what `useAnimatedStyle` is for by contrasting to limitations of [inline styling](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/glossary#animations-in-inline-styling)
It also adds missing imports on the ["Animating styles and props"](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/animating-styles-and-props) page
Fixes https://github.com/software-mansion/react-native-reanimated/issues/5115

Update `useAnimatedStyle` docs

---

src/ConfigHelper.ts
src/propsAllowlists.ts
src/reanimated2/js-reanimated/index.ts

This PR fixes regression introduced in https://github.com/software-mansion/react-native-reanimated/pull/4977. Some animated props (for example UI props) required to be updated directly as component prop - `setNativeProps(props)`, but all the rest of them still required to be updated as a component style - `setNativeProps({style: props})`.
| --- | --- |
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/60eb728e-1724-4826-9174-0d7b603595b5" /> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/9ac9aa45-6827-4572-b268-f2510c2e5503" /> |
<details>
<summary>AnimatedProps - UIProps - #4909</summary>
```js
import { Button, Text, View } from 'react-native'; …
```

Fix animated UI Props on Web

---

Common/cpp/NativeModules/NativeReanimatedModule.cpp
Common/cpp/ReanimatedRuntime/WorkletRuntimeDecorator.cpp
Common/cpp/SharedItems/Shareables.cpp
Common/cpp/SharedItems/Shareables.h
Common/cpp/Tools/UIRuntimeDecorator.cpp
Common/cpp/Tools/UIRuntimeDecorator.h

Previously, we would inject `_updateDataSynchronously` only to the UI runtime so it was not available in a regular worklet runtime. However, VisionCamera needs to use synchronous shared values in its context so I moved `_updateDataSynchronously` from `UIRuntimeDecorator` to `WorkletRuntimeDecorator`.
```ts
const mutable = makeMutable(false);
const runtime = createWorkletRuntime('foo', () => {
'worklet';
mutable.value = true;
});
```

Inject `_updateDataSynchronously` to worklet runtime

---

Common/cpp/Tools/JSISerializer.cpp

This PR fixes a crash when passing a `jsi::HostObject` with no props to `_log` or `_toString` functions caused by accessing the last element of an empty list.
```ts
'worklet';
const x = makeShareableCloneOnUIRecursive(() => {
'worklet';
console.log(42);
});
_log(x);
})();
```

Fix JSISerializer for empty jsi::HostObject

---

.github/workflows/validate-plugin.yml

Previously, validate plugin workflow would run all unit tests in the library, including those for `useAnimatedStyle` etc. which are also run in another job. However, the expected behavior is to run only unit tests related to Reanimated Babel plugin from `__tests__/plugin.test.ts`.

Run only plugin tests in validate plugin workflow

---

app/src/examples/ArticleProgressExample.tsx
src/reanimated2/NativeMethods.ts

An error is thrown when you measure en element that is not mounted yet. So I create a boolean flag which I set when component is ready to avoid this error.
Probably we also should improve error log.
Current error log:
> `[Reanimated] The view with tag ${viewTag} returned an invalid measurement response.`
New error log:
> `[Reanimated] The view with tag ${viewTag} returned an invalid measurement response. Please make sure the view is currently rendered.`
Both logs are not perfect, since in our example our measured element is a Text component, not a View one, however adding component type to log is not easy.

Fix article progress example on android

---

docs/package.json
docs/yarn.lock

This PR updates the Reanimated version in docs to the newest nightly because the current version used in the docs doesn't work well with inline style animations.
Fixes #5207
Also, I've updated Docusaurus to the newest stable version.
Inline styles doesn't update width of the box
https://github.com/software-mansion/react-native-reanimated/assets/39658211/c65e88b1-8166-4b42-a595-c5d4e820bb66
Inline styles work just fine 😃 
https://github.com/software-mansion/react-native-reanimated/assets/39658211/83cc6b30-552b-4ee7-88a7-17c6594af844
```sh
cd docs
yarn
yarn start
yarn build
yarn serve
```

Update Reanimated version in docs

---

src/reanimated2/animation/spring.ts
src/reanimated2/animation/springUtils.ts

Each time a spring animation is triggered we check if provided config is valid. When it isn't we skip animation and change the animated view to its final position after waiting the time passed as `duration` (which may be zero)
This change fixes the following bug:
* Warning when spring used with zero duration (which should be a valid usage)
* No warning for negative mass
Additional benefits are:
* Invalid config warning informs what exactly is wrong
* Types are both more accurate and less verobse
Behaviour when duration is zero:
https://github.com/software-mansion/react-native-reanimated/assets/56199675/c16caa2a-9df0-4ba0-9890-4fe81b5b090d

Improve spring config verification

---

app/src/examples/UpdatePropsPerfExample.tsx

This PR enables clipping in "Update props performance" to prevent bars from overlapping examples list:
https://github.com/software-mansion/react-native-reanimated/assets/20516055/1f6e7c64-08d3-43a8-a4f0-45dcde566994

Add `overflow: hidden` in UpdatePropsPerfExample

---

Common/cpp/SharedItems/Shareables.cpp
Common/cpp/SharedItems/Shareables.h
app/src/examples/ShareablesExample.tsx

This PR adds support for passing instances of `BigInt` to worklet runtimes.
ShareablesExample &rarr; BigIntDemo
```ts
const bigint = BigInt('1234567890');
console.log(typeof bigint === 'bigint');
console.log(bigint === BigInt('1234567890'));
})();
```

Add shareable BigInt

---

.github/workflows/build-npm-package-action.yml
createNPMPackage.sh

In #5152 I made the change that uses node script before `yarn` was called and dependencies required for `set-reanimated-version.js` were not yet installed. This PR fixes this.

Fix ./createNPMPackage

---

src/reanimated2/layoutReanimation/web/animationsManager.ts
src/reanimated2/layoutReanimation/web/componentUtils.ts
src/reanimated2/layoutReanimation/web/config.ts

While refactoring `animationsManager` file I've moved most of the logic to new functions. Turns out that VSCode tricked me and left syntax highlighting on a variable that wasn't present in `chooseAction` (namely `config`). This caused crashes while starting layout transition.
Verified that layout transitions work on [LA] examples in our example app

Fix layout transitions crashes on web

---

src/createAnimatedComponent/InlinePropManager.ts
src/reanimated2/commonTypes.ts
src/reanimated2/platformFunctions/scrollTo.web.ts

This PR improves typing of `ShadowNodeWrapper` so it's no longer possible to confuse it with a regular `object`.

Fix `ShadowNodeWrapper` type

---

app/src/examples/ShareablesExample.tsx
src/reanimated2/shareables.ts

This PR fixes the message of the following error that appears when using an object that couldn't been cloned to the UI runtime, for example instances of `Map` or `Set`.
|:-:|:-:|
| <img width="507" alt="Zrzut ekranu 2023-10-16 o 11 32 38" src="https://github.com/software-mansion/react-native-reanimated/assets/20516055/0193ebdf-a75c-48d7-a4a2-1318676185be"> | <img width="507" alt="Zrzut ekranu 2023-10-16 o 11 32 45" src="https://github.com/software-mansion/react-native-reanimated/assets/20516055/4f012976-1691-4436-9a2f-c717a4e3bd15"> |
```ts
const x = new Set();
console.log(x.has(42));
})();
```

Fix "Trying to access property `__remoteFunction`" for inaccessible objects

---

src/createAnimatedComponent/InlinePropManager.ts
src/reanimated2/index.ts
src/reanimated2/initializers.ts
src/reanimated2/isSharedValue.ts
src/reanimated2/js-reanimated/JSReanimated.ts
src/reanimated2/mappers.ts
src/reanimated2/mockedRequestAnimationFrame.ts
src/reanimated2/platformFunctions/getRelativeCoords.ts
src/reanimated2/platformFunctions/index.ts
src/reanimated2/platformFunctions/setNativeProps.ts
src/reanimated2/platformFunctions/setNativeProps.web.ts
src/reanimated2/utils.ts

This PR moves `setNativeProps` (and `getRelativeCoords`) function to `platformFunctions` directory as well as updates imports and removes circular dependencies by splitting `utils.ts` with mostly unrelated functions (which was the root cause of the issue) into separate files.

Move `setNativeProps` and `getRelativeCoords` to `platformFunctions`

---

Common/cpp/SharedItems/Shareables.cpp

This PR fixes a crash described in https://github.com/software-mansion/react-native-reanimated/issues/4613#issuecomment-1741018643.
Turns out that the condition in assert is always true in debug mode but there's an optimization for RemoteFunction in release mode which breaks it.
See repro in #4617.

Fix `runOnJS` crash in release mode again

---

Common/cpp/Tools/ThreadSafeQueue.h
Common/cpp/Tools/UIScheduler.cpp

This PR introduces the following improvements to `ThreadSafeQueue`:
* Removes unused methods
* Converts `getSize` method into `empty`
* Mark mutex and conditional variable as `mutable`
* Mark `empty` method as `const`

Remove unused methods from `ThreadSafeQueue`

---

docs/docs/fundamentals/getting-started.mdx

Having "was" confused me, and I went back to the fundamentals header, thinking I missed something. This makes it more clear I am in the right spot, and I don't need to go search for a "fundaments section".
To me, it currently reads "now that you have a strong understanding from the fundamentals section, here is a new sections with ..."

Update first sentence tense in getting-started.mdx

---

docs/docs/device/useAnimatedSensor.mdx

By mistake I've used a wrong css class to style platform compatibility table in the last section of `useAnimatedSensor` docs 
Before
After
😉

Fix typo in `useAnimatedSensor` docs

---

app/src/examples/ModifyExample.tsx
app/src/examples/index.ts
docs/docs/core/useSharedValue.mdx
src/reanimated2/commonTypes.ts
src/reanimated2/mutables.ts
src/reanimated2/valueSetter.ts

This PR fixes `modify` method of shared value so that it runs all listeners after the change even if the reference to the value does not change.
Co-authored-by: @kmagiera 
Co-authored-by: @piaskowyk 
ModifyExample.tsx

Run listeners when calling sv.modify

---

mock.js

This PR fixes error `TypeError: (0 , _reactNativeReanimated.clamp) is not a function`.
`jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'))`

Add clamp to mock

---

app/src/examples/CounterExample.tsx
app/src/examples/index.ts

1. Rename `AnimatedTextInputExample` to `CounterExample`
2. Use `defaultValue` prop instead of `value`
3. Add `font-variant: 'tabular-nums';`

Improve counter example

---

src/reanimated2/component/FlatList.tsx

This PR changes how reanimated treats inverted `FlatLists`. In #3765 our implementation was changed to mimic the react-native behavior by assigning a special style that reverts the cell inversion (inverted FlatList flips the entire view and then flips back every cell). In react-native@0.72.4 the inversion style was [changed](https://github.com/facebook/react-native/pull/38073) on android due to some performance issues. That change combined with our implementation was causing the cell to remain inverted on android (since both styles were being applied). This PR changes our implementation to instead allow the `CellRendererComponent` to receive a style prop, making react solely responsible for the cell inversion.
Check whether the Inverted FlatList Example behaves properly on android.
I …

Fix inverted `FlatList`

---

.eslintrc.js
package.json
src/reanimated2/ViewDescriptorsSet.ts
src/reanimated2/component/ScrollView.tsx
src/reanimated2/hook/useAnimatedGestureHandler.ts
src/reanimated2/hook/useAnimatedStyle.ts
src/reanimated2/hook/useScrollViewOffset.ts
src/reanimated2/layoutReanimation/web/componentUtils.ts

I added _react-hooks_ eslint plugin to repo. It is a rule that checks integrity of used hooks, as well as their dependencies and general standards of their implementation and use. I have stumbled upon a custom hook that doesn't start with _"use"_ - which has been changed. There are some conditional hook calls in the repo - I have temporarily disabled eslint errors regarding them and await any ideas on what to do there.
Delete any of the _"eslint-disable..."_ comments added in [this commit](https://github.com/software-mansion/react-native-reanimated/commit/00c37e8c0d4fe2529cbca68b9d87ec2a7ce0c35a).  To see the dependencies' fixes and suggestions change dependencies [in this line](https://github.com/software-mansion/react-native-reanimated/blob/c11b671b5dd58b0b18df941727d9d8336d9227e6/app/sr …

Add react-hooks eslint plugin

---

.github/workflows/ios-build.yml
.github/workflows/macos-build.yml
.github/workflows/tvos-build.yml

I've noticed that MacOSExample CIs are started even for JS-only PRs because `on.push.paths` was not specified.
Additionally, I fixed paths in iOS and tvOS workflows (`ios` &rarr; `apple`).

Update paths in iOS/tvOS/macOS workflows

---

src/reanimated2/mock.ts

`reduceMotion` and the `ReduceMotion` enum were added in 3.5.
https://github.com/software-mansion/react-native-reanimated/releases/tag/3.5.0
`jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'))`
`FadeInUp.duration(500).reduceMotion(ReduceMotion.Never)`

Add reduceMotion to mock

---

android/src/main/java/com/swmansion/reanimated/keyboardObserver/ReanimatedKeyboardEventListener.java

FIxes #5208 
For some reasons i don't understand, android's WindowInsetsAnimationCompat.Callback don't run any animations when keyboard height changes (maybe because there is no animation 🤔). It only works when keyboard opens/closes. I personally had a problem with emoji keyboard. User opens text keyboard, then goes into emoji (same problem in gboard gif/stickers) and keyboard gets bigger, but app doesn't. setOnApplyWindowInsetsListener on the other hand knows about new keyboard's height and in my commit i just send this update without any animation to updateKeyboard.
I've tested this on my samsung a71 with android 13 (one ui 5.1). Needs testing on 
1. <11 android without keyboard animation support
2. other os
3. other keyboards

fix useAnimatedKeyboard when keyboard type changes

---

.github/workflows/build-monorepo-action.yml

We should use stable version of CLI for nightly jobs. Now our CLI on main fails - https://github.com/software-mansion/react-native-reanimated/actions/workflows/build-monorepo-nightly.yml

Use stable version of CLI

---

.eslintignore
package.json

BEFORE:
* Lint-staged lints all files and prints all warnings and errors
NOW:
* Lint only staged files and shows both errors and warnings
* If the previous tasks success all files get lined, but only errors are printed
Drawbacks:
Lint runs twice. It should not cause burdensome delays since the first lint runs only for the staged files, so if you stage <10 files it runs very fast.

Fix lint staged

---

src/reanimated2/mock.ts

This pr is a fix for #5379 which is related to missing easing method in BaseAnimationMock class.

add missing easing method to BaseAnimationMock

---

Example/ios/Podfile.lock
Example/package.json
Example/yarn.lock
FabricExample/ios/Podfile.lock
FabricExample/package.json
FabricExample/yarn.lock
MacOSExample/ios/Podfile.lock
MacOSExample/package.json
MacOSExample/yarn.lock
app/package.json
app/yarn.lock

We've lost our searchbar on Android 😱 But once we bump `react-native-screens` it works again 💪 
|BEFORE|AFTER|
|--|--|
|![Screenshot 2023-11-09 at 10 21 15](https://github.com/software-mansion/react-native-reanimated/assets/56199675/971d8b2f-6e4c-49c7-bd2f-6b3406dc5739)|![Screenshot 2023-11-09 at 10 21 41](https://github.com/software-mansion/react-native-reanimated/assets/56199675/67ee4825-eb8b-403d-915b-a9f5efd982f2)|
I've tested on Android (Example and Fabric Exampe)

Bump react-native-screens

---

src/createAnimatedComponent/createAnimatedComponent.tsx
src/reanimated2/layoutReanimation/web/animationsManager.ts
src/reanimated2/layoutReanimation/web/componentUtils.ts
src/reanimated2/layoutReanimation/web/config.ts
src/reanimated2/layoutReanimation/web/index.ts

Sometimes entering animations flicker. This happens because we've recently merged [this PR](https://github.com/software-mansion/react-native-reanimated/pull/5278), which always sets component visibility of the component on its first render, even though now we are doing it inside `onanimationstart`.
Tested on example app on [LA] examples

Fix entering flickers in web LA

---

src/reanimated2/animation/clamp.ts

Fix withClamp on android, there was a bug when clamp limits where prefixed strings

Fix clamp with prefixes on android

---

src/reanimated2/ViewDescriptorsSet.ts
src/reanimated2/commonTypes.ts
src/reanimated2/mutables.ts

The modifications made in PR https://github.com/software-mansion/react-native-reanimated/pull/5306 cause the `_updateDataSynchronously` method to be called after every `modify()` call. However, this method is slow for larger objects because it involves copying the entire structure. This PR includes an additional option to skip force updates if desired.
| --- | --- |
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/52f3c996-6d4c-4441-9085-2f488886ebff" /> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/a48ebd44-22fd-4c7b-ae4f-37e6ca4496d6" /> |

Make forceUpdate optional

---

android/build.gradle
android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
android/src/reactNativeVersionPatch/ReactFeatureFlagsWrapper/72/com/swmansion/reanimated/ReactFeatureFlagsWrapper.java
android/src/reactNativeVersionPatch/ReactFeatureFlagsWrapper/latest/com/swmansion/reanimated/ReactFeatureFlagsWrapper.java

In Fabric version 0.73, this flag is necessary. Without it, all animations won't work properly since our animation logic heavily relies on the commit and mount hooks.

Add setFeatureFlag method

---

docs/docs/guides/compatibility.mdx

This PR adds RN 0.73 to the compatibility table as well as updates some cells with correct information.

Update compatibility table for 0.73

---

docs/docs/guides/compatibility.mdx
docs/src/components/Compatibility/index.tsx
docs/src/theme/MDXComponents.js

This PR renames `Supported` and `NotSupported` components in compatibility table to `Yes` and `No`. Shorter is better.

Rename components in compatibility table

---

src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts

This PR uses string interpolation to construct keyframe keys in `Keyframe.ts` as requested it [PR comment](https://github.com/software-mansion/react-native-reanimated/pull/5363#discussion_r1390286269). Additionally it extracts it to a helper function

Extract keyframe key construction to a function

---

src/reanimated2/globals.d.ts

This PR fixes the type of argument of `_log` function.
```ts
_log(42);
```

Fix type of `_log` function

---

__typetests__/common.tsx
src/reanimated2/component/ScrollView.tsx

Fixes #5425. 
Added a new test suite.

Fix ScrollView missing properties

---

src/reanimated2/layoutReanimation/web/animationsManager.ts

While fixing `entering` animations on web, I removed `handleEnteringAnimation` and used `setElementAnimation` instead. However, I didn't pass `transform` parameter, so it couldn't be applied.
Tested on mounting/unmounting example.

Fix existing transform on web

---

src/createAnimatedComponent/createAnimatedComponent.tsx

In implementation of web layout animations I used `getSnapshotBeforeUpdate` to get position of element before its re-render. However, this function lacks checks for platform and whether component is null or not. 
Tested on provided repro
<details>
<summary> Code from issue </summary>
```jsx
import React, {useRef, useState} from 'react'
import {StyleSheet, Text, TouchableOpacity, View, ViewStyle} from 'react-native'
import Animated from "react-native-reanimated"
import FastImage from "react-native-fast-image"
export const ReanimatedFastImage = Animated.createAnimatedComponent(FastImage)
const [value, setValue] = useState(false)
const cardImageRef = useRef<any>(null)
const onPress = () => {
setValue(!value)
}
return (
<ReanimatedFastImage …
```

Fix calling `getBoundingClientRect` on `null`

---

src/reanimated2/layoutReanimation/web/componentUtils.ts

In exiting animation, we create a dummy - clone of the original element that will be removed. When animation ends, we remove dummy from parent. The problem is, if something cancels animation, our dummy component won't be removed. 
I've stumbled upon this problem while working on custom keyframes.
Tested on example app. Mostly on Keyframe animation example (on branch with custom keyframes implementation).

Remove dummy element on animation cancel

---

src/reanimated2/hook/useSharedValue.ts

The general idea here is that we can avoid the `makeMutable` call on every single render.  This change is also compatible with hot reloading.
We (at Discord) have been running this patch on top of our own reanimated now for a few weeks and haven't noticed any side effects of the change.
There has been a bit of additional discussion I've seen surrounding this issue here: https://github.com/software-mansion/react-native-reanimated/pull/3199
N/A

Replace useRef with useState for useSharedValue

---

src/reanimated2/animation/util.ts

This PR adds a warning that is displayed in dev mode when the reduced motion accessibility feature is enabled on the device.

Add warning about reduced motion in dev mode

---

src/reanimated2/layoutReanimation/web/animationsManager.ts
src/reanimated2/layoutReanimation/web/componentUtils.ts

Right now, if element has any `transform` (for example `translateX`), exiting won't work correctly. This happens because during animations we write transform directly into components' style to avoid [problems with delay](https://github.com/software-mansion/react-native-reanimated/pull/5298). On the other hand, exiting works with `snapshots` which already take care about components position, including transforms.
In order to fix that we can ignore creating animation with transform and reset `dummy.style.transform`.
<details>
<summary> Test code </summary>
```jsx
import { StyleSheet, View, Text, Pressable } from 'react-native';
FadeIn,
FadeInDown,
FadeOutDown,
const [showExiting, …
```

Fix transform in exiting animation

---

docs/docs/guides/troubleshooting.mdx
src/reanimated2/animation/util.ts

This PR extends the reduced motion warning to inform that it is only displayed in development mode and adds a note in docs that explains why the warning is displayed and how it can be disabled.

Improve reduced motion warning

---

src/createAnimatedComponent/createAnimatedComponent.tsx

1. Move the overload with type deprecation to be the last one. It means that if user provides invalid type which isn't covered by any overload he will not get the warning about FlatList deprecation. This warning was very confusing if user wasn't using FlatList at all
2. Add overload of `ComponentType`. Since `ComponentType<P = {}> = ComponentClass<P> | FunctionComponent<P>` we have assume that it is enough to have two overloads (ComponentClass & FunctionComponent), but it isn't
|BEFORE|AFTER|
|--|--|
|Error for FastImage and deprecation for FastImage ❌ | Deprecation for FlatList only 😎|
|<img width="528" alt="Screenshot 2023-12-12 at 13 16 37" src="https://github.com/software-mansion/react-native-reanimated/assets/56199675/04a318ec-cf43-43a0-bf0a-5ad372265453">|<img width="528" …

Fix overloads in createAnimatedComponent

---

.eslintrc.js
src/createAnimatedComponent/InlinePropManager.ts
src/createAnimatedComponent/createAnimatedComponent.tsx
src/reanimated2/PropAdapters.ts
src/reanimated2/UpdateProps.ts
src/reanimated2/hook/useDerivedValue.ts
src/reanimated2/hook/utils.ts
src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts
src/reanimated2/layoutReanimation/defaultTransitions/EntryExitTransition.ts
src/reanimated2/layoutReanimation/web/componentUtils.ts

Non-null assertions are considered to be a bad practice - however this is in regard to pure TypeScript code. This is not the case in Reanimated, since we have to deal with multiple platforms and multiple threads. Therefore sometimes we know that a value is defined, without a need for unnecessary checks for `undefined` or `null` - and non-null assertions are very handy there, since they are very short.
Also, using `?` operator instead of TS `!` could lead to unexpected behavior that could be hard to understand. Consider the following example:
```TS
function dispatchCommandPaper<T extends Component>(
animatedRef: AnimatedRef<T>,
commandName: string,
args: Array<unknown> = []
) {
'worklet';
if (!_WORKLET) {
return;
}
const viewTag = animatedRef() as number;
// TS error - …
```

Improve TS in src [0/6] - Allow non-null assertion and remove some eslint directives

---

docs/docs/fundamentals/getting-started.mdx

It seems like npx sometimes uses an old cached version of the `create-expo-app` cli 
This PR adds the `latest` modifier to make sure that the invoked command have the `-e` command available

Mark `create-expo-app` as latest

---

Common/cpp/NativeModules/NativeReanimatedModule.cpp
Common/cpp/NativeModules/NativeReanimatedModule.h
Common/cpp/NativeModules/NativeReanimatedModuleSpec.cpp
Common/cpp/NativeModules/NativeReanimatedModuleSpec.h
Common/cpp/ReanimatedRuntime/WorkletRuntime.cpp
Common/cpp/ReanimatedRuntime/WorkletRuntime.h
android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
android/src/main/cpp/NativeProxy.cpp
android/src/main/cpp/NativeProxy.h
android/src/main/java/com/swmansion/reanimated/NodesManager.java
android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java
android/src/paper/java/com/swmansion/reanimated/NativeProxy.java
apple/REAModule.mm
apple/native/NativeProxy.h
apple/native/NativeProxy.mm
src/reanimated2/NativeReanimated/NativeReanimated.ts

Fixes #5421, fixes #5331.
This PR removes `installValueUnpacker` method which was called on the JS thread during the creation of `NativeReanimatedModule` but operated directly on the UI runtime. Because of this, UI runtime was already used from JS thread so any use from the UI runtime (e.g. Reanimated event handlers) would cause a crash due to a failed check in `ReanimatedReentrancyCheck::before`. Note that the check also occurred in release mode due to improperly set `NDEBUG` flag.

Fix incomplete UI runtime initialization

---

Common/cpp/ReanimatedRuntime/WorkletRuntime.cpp
Common/cpp/ReanimatedRuntime/WorkletRuntime.h
src/reanimated2/initializers.ts
src/reanimated2/threads.ts

Fix TS and initialization order for `executeUIRuntimeSync`.

---

__typetests__/common.tsx
src/reanimated2/component/FlatList.tsx

I think I ran into a typescript types regression, where the `Animated.FlatList` type was no longer generic. It always used the any type and I couldn't provide a custom item type myself anymore. I found it while upgrading from Reanimated v2 to v3. I think I managed to patch the generated .d.ts file properly locally and this is what did the trick for me.
If this isn't matching your code style or requirements, I'm happy to work with you on making this work.
Probably makes sense to see if it breaks anything in the example app but other than that 🤷

Fix FlatList item generic types

---

src/createAnimatedComponent/commonTypes.ts
src/createAnimatedComponent/createAnimatedComponent.tsx
src/reanimated2/hook/commonTypes.ts
src/reanimated2/hook/useAnimatedStyle.ts
src/reanimated2/jestUtils.ts

This file is cursed...
Hopefully not anymore.
I removed
```ts
const isAnimatedStyle = (style) => {
return !!style.animatedStyle;
};
const getAnimatedStyleFromObject = (style) => {
return style.animatedStyle.current.value;
};
```
in `jestUtils.ts` because it was dead code. This is due to how props are handled inside `createAnimatedComponent`
Because we pass `filteredProps` there will no longer be objects associated with `JestAnimatedStyleHandle` type there, since all Animated Props are filtered out.
CI & Jest tests

Use TS in `jestUtils.ts`

---

src/reanimated2/shareableMappingCache.ts

I knew I forgot something in #5530.
Fixes `TypeError: WeakMap.prototype.get can only be called on a WeakMap, js engine: hermes`

Add missing binding to `shareableMappingCache`

---

.github/workflows/format-pull-request-description.yml

The PR template description includes some comments.
It makes it difficult to read PR descriptions
This PR introduces a CI action that will run upon PR creation and remove the comments from the PR description.
`software-mansion-labs/pr-description` this is a fork of `nefrob/pr-description` with some adjustments.
Open a new PR and see if contains comments.
🍪

Added CI that removes comments from PR description

---

android/build.gradle

Synced the link with React Native.
Commit : https://github.com/facebook/react-native/commit/7e721f09ad3dafed9f490f433b2ac613786c27b2
Synced the boost download link with React Native boost download link
Commit in RN: https://github.com/facebook/react-native/commit/7e721f09ad3dafed9f490f433b2ac613786c27b2
This is already released in v0.73.2
Build the base App

Fixed boost download link

---

android/proguard-rules.pro

Keep fabric class to prevent crashes in react-native 0.73+ with new architecture and proguard.
Fixes #5514 
Related #5472, https://github.com/facebook/react-native/pull/41657
- Clone `gh repo clone ahmetbicer/mBinding-proguard-repro`
- add `-keep class com.facebook.react.fabric.** { *; }` in your app proguard-rules.pro or reanimated node_modules folder
- Run `yarn react-native run-android --mode Release`
- Build and Open without crash 🎉

Fix: Build RN 0.73.1 with New Architecture and Proguard enabled

---

__tests__/__snapshots__/plugin.test.ts.snap
__tests__/plugin.test.ts
plugin/build/plugin.js
plugin/src/buildWorkletString.ts
plugin/src/makeWorklet.ts

Pass down generator boolean in babel plugin

---

__tests__/__snapshots__/plugin.test.ts.snap
__tests__/plugin.test.ts
plugin/build/plugin.js
plugin/src/buildWorkletString.ts
plugin/src/makeWorklet.ts

Inspired by #5565. Currently we don't respect if the workletized function is an async one. This PR fixes this.
Keep in mind that even with these change **async worklets will not work properly on the UI thread**. This is because Hermes doesn't support them out of the box and they need to be transformed into generators first (you can see that in the snapshots).
Properly transforming them so they are valid on UI thread should be considered a future, very low priority task, since it wasn't requested yet by our users.
Relevant tests were added to `plugin.test.ts`.
<details>
<summary>
To see the difference between JS and UI behavior
</summary>
```tsx
import { StyleSheet, View, Button } from 'react-native';
import { runOnUI } from 'react-native-reanimated';
export …
```

Properly transpile async functions

---

src/createAnimatedComponent/commonTypes.ts
src/reanimated2/layoutReanimation/defaultAnimations/Bounce.ts
src/reanimated2/layoutReanimation/defaultAnimations/Fade.ts
src/reanimated2/layoutReanimation/defaultAnimations/Flip.ts
src/reanimated2/layoutReanimation/defaultAnimations/Lightspeed.ts
src/reanimated2/layoutReanimation/defaultAnimations/Pinwheel.ts
src/reanimated2/layoutReanimation/defaultAnimations/Roll.ts
src/reanimated2/layoutReanimation/defaultAnimations/Rotate.ts
src/reanimated2/layoutReanimation/defaultAnimations/Slide.ts
src/reanimated2/layoutReanimation/defaultAnimations/Stretch.ts
src/reanimated2/layoutReanimation/defaultAnimations/Zoom.ts
src/reanimated2/layoutReanimation/web/animationsManager.ts

As pointed in #5561, layout animations don't work with production bundle. It is caused by fragile method of obtaining animation name, i.e. using `config.name` if config is function. During bundling, name of this function may change (in linked issue to `c`, in my case to `r`), so instead of animation user will see warning that reanimated couldn't load animation. 
This PR adds static field `className` to animations builders in order to provide access to animation name, even if config name gets changed during bundling.  
1.  Create new app (`npx create-expo-app`)
2. Install Reanimated from package (`npm pack` -> `yarn add <path_to_package>`) 
3. `npx expo export -p web`
4. `npx serve dist --single`
I used reanimated from local package to make sure that `expo export` works correctly. …

[LA Web] Fix animations in production bundle

---

src/createAnimatedComponent/createAnimatedComponent.tsx

Tested in Web with
```tsx
import { Button } from 'react-native';
import Animated, { useAnimatedStyle } from 'react-native-reanimated';
const [show, setShow] = React.useState(true);
const animatedStyle = useAnimatedStyle(() => ({
width: 100,
height: 100,
backgroundColor: 'red',
}));
return (
<>
<Button title="Toggle" onPress={() => setShow(!show)} />
{show ? <Animated.View style={animatedStyle} /> : null}
</>
);
}
```

Hotfix accidental rename of `remove` to `delete`

---

FabricExample/babel.config.js
MacOSExample/babel.config.js
TVOSExample/babel.config.js

Our example app tests nested worklets, specifically the `WorkletExample` that includes the `ThrowErrorNestedWorkletDemo`. This test requires additional plugin configuration. Previously, this configuration was only present in the Example app. This PR adds this config to rest of our example apps.
Run example:

Add missing plugin config to example apps

---

src/reanimated2/hook/useHandler.ts

This PR fixes a regression introduced in #5518. `useHandler` works by maintaining a `context` object that can be accessed and modified in event handlers (e.g. within `useAnimatedGestureHandler`). Removing `makeRemote` call there made it so that any changes to the `context` object were not visible in event handlers, rendering the `context` object useless. In this PR I wrapped the context object with `makeShareable`, which works basically in the same way as `makeRemote` did.
Check whether the `[SET] Modals` example behaves properly (i.e. if the modal closing gestures are captured correctly).

Fix `useHandler` context issue

---

src/reanimated2/fabricUtils.ts

Quick PR fixing a problem that can be spotted in `Expensfiy` app where for some reason on new arch, this code was evaluated before the `nativeFabricUIManager` was added to global, making the code throw. Now it is requested only when used for the first time, making it more safe.
For some reason I could not reproduce it in the `FabricExample` in any way.

fix: lazily search for ReactFabric

---

.github/workflows/android-build.yml
.github/workflows/build-next-example.yml
.github/workflows/build-npm-package-action.yml
.github/workflows/build-v8-nightly.yml
.github/workflows/check-TS-react-native.yml
.github/workflows/check-expo-dev-client-nightly.yml
.github/workflows/close-when-stale.yml
.github/workflows/detect-broken-urls-nightly.yml
.github/workflows/docs-check.yml
.github/workflows/ios-build.yml
.github/workflows/macos-build.yml
.github/workflows/main.yml
.github/workflows/needs-more-info.yml
.github/workflows/needs-repro.yml
.github/workflows/platforms.yml
.github/workflows/static-example-apps-checks.yml
.github/workflows/static-root-checks.yml
.github/workflows/tvos-build.yml
.github/workflows/validate-cpp.yml
.github/workflows/validate-ios.yml
.github/workflows/validate-java.yml
.github/workflows/validate-plugin.yml

This PR updated CI dependencies to get rid off following warnings:
Contains update for:
- actions/checkout
- actions/setup-node
- actions/upload-artifact
I also removed node version specification where it isn't necessary.
See at CI output

Update CI deps

---

android/src/main/java/com/swmansion/reanimated/nativeProxy/NativeProxyCommon.java

The purpose of this PR is to address crashes on Android that occur after the application is reloaded. The application can be reloaded in debug mode by pressing the `r` key in the Metro console, or in release mode after an over-the-air update.
The main cause of the crashes after reload is the reference to deallocated native parts of the hybrid object, specifically NativeProxy.
https://github.com/software-mansion/react-native-reanimated/assets/36106620/6c2ba48e-6344-4acc-9de0-d0b25629a7cc
To resolve this issue, the PR removes the call to `getHybridData().resetNative()`, which invokes the destructor of the native part of the hybrid object. The problem arises because the Java part of object can still be used by the React Native runtime. The simplest way to prevent crashes is to avoid manually …

Android reloads

---

app/src/examples/ChessExample.tsx
app/src/examples/index.ts

This PR adds a simple chess game example.
https://github.com/software-mansion/react-native-reanimated/assets/20516055/cdc667d7-1746-40bc-91f5-5de6ceb1abb2

Add chess example

---

.github/workflows/validate-plugin.yml
__tests__/__snapshots__/plugin.test.ts.snap
__tests__/plugin.test.ts
plugin/build/plugin.js
plugin/src/isGestureHandlerEventCallback.ts
plugin/src/isLayoutAnimationCallback.ts
plugin/src/makeWorklet.ts
plugin/src/plugin.ts
plugin/src/processForCalleesWorklets.ts
plugin/src/processIfCallback.ts
plugin/src/processIfWorkletFunction.ts
plugin/src/processIfWorkletNode.ts
plugin/src/processWorkletObjectMethod.ts
plugin/src/types.ts

Fixes #5555.
Currently, when transforming functions with a `'worklet'` directive we are only looking for:
1. FunctionDeclaration
```ts
function foo(){'worklet'}
```
2. FunctionExpression
```ts
const foo = function (){'worklet'}}
```
3. ArrowFunctionExpression
```ts
const foo = () => {'worklet'};
```
And not taking into consideration ObjectMethod:
4.
```ts
const foo = {
bar() {'worklet'}
}
```
This PR fixes that and does a slight refactor of the upper control flow and renames some functions.
This wasn't an issue before because plugins used in Expo and React Native used to transform ObjectMethods to ObjectProperties:
```ts
const foo {
bar: function() {'worklet'}
}
```
But it's no longer always the case.
Added a step to the CI if our App is actually bundling properly and added a test.
I'm …

Fix plugin sometimes not workletizing `ObjectMethod`

---

MacOSExample/babel.config.js

This PR resolves the following error when trying to bundle MacOSExample:

Fix MacOSExample unable to bundle

---

app/src/examples/LayoutAnimations/OlympicAnimation.tsx

We had a warning in olympic example
>[Reanimated] Property "transform" of AnimatedComponent(View) may be overwritten with layout animation. Please create a wrapper with the layout animation you want to apply.
It was a correct warning, since we actually want to overwrite transform, yet I am getting rid of it with a wrapper
https://github.com/software-mansion/react-native-reanimated/assets/56199675/fe463d94-bb38-4dac-ab15-dfc44578d860

Fix olympic example

---

src/reanimated2/Colors.ts

This PR fixes syntax of `'worklet'` directive in HSVtoRGB function. Introduced accidentally here: https://github.com/software-mansion/react-native-reanimated/pull/5482
Open Color Interpolate example

Fix worklet directive in `HSVtoRGB`

---

src/reanimated2/hook/useAnimatedStyle.ts

When using the latest version of this library as part of my app i kept running into a scenario where `lastValue` in `useAnimatedStyle.ts` was `null`, therefore leading to a crash. The existing check only looked for `lastValue !== undefined`, I added an additional check for `null`.
Check out my attached screenshot from my devtools debugging session, where u can see above described scenario with `lastValue` being `null`.
Note that I did not manage to find the underlying reason for this (therefore i can also not tell you how to reproduce this), but the additional null check will avoid the app from crashing and everything else seems to work properly.

Fix missing null check for lastValue in useAnimatedStyle.ts

---

src/reanimated2/hook/useAnimatedSensor.ts

While playing with `useAnimatedSensor(SensorType.GYROSCOPE)` I was really annoyed that every time my app hot reloaded I got error like this: `Cannot assign to read-only property 'sensor'` or `Cannot assign to read-only property 'unregister'`.
There seems to be some issue that properties inside "ref.current" becomes read-only so I added code that will replace whole `ref.current` instead of replacing properties one by one at begging of `useEffect`. This seems to solve the issue.
Also it seems that this is Android only issue. I did not encounter that on iOS.
Here are screenshots of errors https://photos.google.com/share/AF1QipM1cQFJI67AGuTyth9CY3EGM6Ipy80Jp_uSivmoHf2dTU3aRDaXSLk2TliVKO2hNg?key=bVVNWE1SRHBrcFBreW5HZFpyWGlOcGxkelVKSW9n
There is simple code that will throw errors on Android on …

fix(android,animated-sensor): Fix HMR for Animated Sensor

---

src/reanimated2/commonTypes.ts
src/reanimated2/index.ts

I don't think adding it to the docs is necessary, TSDoc is sufficient IMO.

Expose `isWorklet` in public API

---

app/src/examples/CounterExample.tsx

Currently the counter is editable - meaning, the user can put in some value from keyboard - which doesn't make a lot of sense.
🔢

[Example] Fix counter being editable

---

app/src/examples/BabelVersionCheckExample.tsx

After #5499 checking for `undefined` is no longer relevant - the first two buttons were doing nothing currently.
🪨 👂

[Example] Remove redundant checks in BabelVersionCheckExample

---

app/src/examples/ChessExample.tsx

Due to the pieces being actually text, previous font size value caused them to be clipped on Android. I fixed that and fixed the style a bit.
♟️

[Example] Fix chess pieces getting clipped on Android

---

app/src/examples/PlanetsExample.tsx

Currently the planets don't follow Kepler's third law. This PR fixes it.
Also on Fabric SVG requires props to be strings, so it doesn't work there without this PR.
🪐 🌔

[Example] Fix planets on Fabric and their physics

---

src/reanimated2/layoutReanimation/web/domUtils.ts

This issue was found in [Expensify](https://github.com/Expensify/App/issues/37463). `node.children` was undefined, because `node` wasn't `HTMLElement` - it was `plaintext`. This PR introduces new check - if `node` is not `HTMLElement`, we won't perform any action.
Tested on Expensify App

[LA Web] Add check for `HTMLElement` when looking for descendant with animation.

---

android/src/main/java/com/swmansion/reanimated/NodesManager.java
android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java
android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
android/src/main/java/com/swmansion/reanimated/nativeProxy/NativeProxyCommon.java

PR moving from deprecated method `onCatalystInstanceDestroy` to `invalidate` as suggested by the core.

fix: don't use deprecated onCatalystInstanceDestroy API

---

app/src/examples/MemoExample.tsx
app/src/examples/index.ts
src/createAnimatedComponent/PropsFilter.tsx
src/createAnimatedComponent/createAnimatedComponent.tsx
src/reanimated2/hook/useEvent.ts
src/reanimated2/hook/useScrollViewOffset.ts

Currently Reanimated relies on reattaching event handlers on render. However, we give any notice to React that it should occur, because `useEvent` always returns the same reference.
With these changes, the reference for a given handler will change if it had to be rebuild and components using `memo` will get re-rendered.
Fixes #5364 
See added `MemoExample.tsx`.

Make `useEvent` return a different reference if event handler should be reattached

---

src/reanimated2/shareables.ts

No need to use type guard `object is object` since the argument is already of type `object`.
Check if TypeScript CIs pass.

Remove redundant `object is object` type guard in `isPlainJSObject`

---

Common/cpp/SharedItems/Shareables.cpp
Common/cpp/SharedItems/Shareables.h
src/reanimated2/valueUnpacker.ts

Fixes #5660, a regression introduced in #4300.
The aforementioned race condition happens this way:
1. An object using a `ShareableHandle` underneath (e.g. a shared value) is created.
2. This object is accessed on UI thread.
3. The initializer of this `ShareableHandle` get called on the UI thread.
4. At the same time, JS thread schedules an operation on this object (e.g. setting a value of shared value).
5. Access on UI thread forces the initialization. The condition of the if clause resolves to true and UI thread tries to access the runtime.
6. However, access from JS thread has locked the runtime and causes the UI runtime to wait.
7. Then, JS thread enters the same if clause body and initializes the whole shareable.
8. After initializing and releasing the runtime, UI thread gets …

Fix race condition when ShareableHandle is accessed on multiple threads

---

src/animationBuilder.tsx
src/reanimated2/layoutReanimation/animationBuilder/Keyframe.ts

Due to a bug, we drop easing in keyframe animation and it doesn't influence the actual animation at all. The goal of this PR is to fix it.
Use example `KeyframeAnimation.tsx` from our example app. Try changing easing (I suggest changing it to `easing: Easing.bounce`). Without this change can't observe any bounces.

Fix easing in Keyframe

---

src/reanimated2/hook/useScrollViewOffset.ts

Fixing regression I introduced in #5743 by making the line
`const component = animatedRef.current` 
outside of `useEfect`.
Check `Article progress` example.

Fix `useScrollViewOffset` using animated ref before its initialization

---

android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java

This PR fixes the bug that was causing z-index to behave incorrectly on Android after a layout animation was triggered. The issue was that sometimes our layout animation implementation was causing `removeView` to be called more than once for the same view. This is not a problem on plain Android, since there is a conditional check there for removal. However, react-native's implementation of `ReactViewGroup` does not check if the view is a part of this `ViewGroup` when handling removal. 
The handler code decreases the counter, that maintains the number of views that have 'z-index' defined by the user. Calling `removeView` too many times causes the counter to go into negative numbers, causing react to disable custom z-index order, even when there are views with user defined z-index.
We …

Fix android layout animation z-index bug

---

src/createAnimatedComponent/createAnimatedComponent.tsx
src/reanimated2/PropsRegistry.ts
src/reanimated2/core.ts
src/reanimated2/hook/useAnimatedRef.ts

PR removing top level check for `isFabric` since it should be evaluated after it is added to `global` which may not be done at that point.

fix: remove top level is_fabric check

---

.github/ISSUE_TEMPLATE/bug-report.yml

This PR adds macOS as new platform option in issue template.
n/a

Add macos platform to issue template

---

src/animationBuilder.tsx

TypeError: right operand of 'in' is not an object
TypeError: Cannot convert undefined value to object

Check value callback whether it is valid or not

---

src/mock.ts

Currently we don't reexport jest specific function (especially `setUpTests`) in our mock. This is due to fact that our recommended way of initializing Reanimated for testing is to do that in `jest-setup.js` file.
However, doing it just before the test suite (with `beforeAll` jest function) is just as good, if even not better considering test separation. This cannot be done if Reanimated is already mocked.
Add Reanimated to a new RN app, mock Reanimated and see that `setUpTests` cannot be used in `beforeAll`. Do it using Reanimated built from this PR and see that it works.

Add `jestUtils` to mocks

---

app/src/examples/MatrixTransform.tsx
app/src/examples/PendulumExample.tsx

The goal of this PR is to fix two of our examples - Matrix & Pendulum
Allow to pass fractional numbers to input fields. Previously we were filtering out everything except for digits, but we should allow users to pass dot as well.
Make the example more descriptive, add additional information. Use the same styling as for pednulum.
<table>
<td><b>BEFORE</b></td><td><b>AFTER</b></td></tr>
<td>
</td><td>
</td></tr>
</table>

Fix example in our example app

---

src/reanimated2/hook/useScrollViewOffset.ts

Our `useScrollViewOffset` had no support for web, so I added it using some basic web scroll listeners.
There are some funny typing shenanigans, if anyone comes up with better solutions I will happily use it.
| --- | --- |
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/77503811/fd61dd7d-3070-4d6e-a8e5-d00b25fe32db"/> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/77503811/5b49a3dd-1a34-4d01-8c09-ae4bd723c9c3" /> |
Check `useScrollViewOffset` example from Reanimated WebExample and watch console logs or copy [example code](https://docs.swmansion.com/react-native-reanimated/docs/scroll/useScrollViewOffset/#example) from our docs.
More in-depth testing can be done using the following code - it tests …

Add web implementation for useScrollViewOffset

---

Example/ios/MBFingerTipWindow.m
apple/sensor/ReanimatedSensor.m

Closes #5801.
This PR replaces all `[[NSProcessInfo processInfo] systemUptime]` calls with `CACurrentMediaTime() * 1000`.
Check if `useAnimatedSensor` with interval works properly.

Replace `systemUptime` calls with `CACurrentMediaTime()` to comply with Apple privacy requirements

---

docs/docs/animations/shared/animationToValue.mdx
docs/docs/animations/withSpring.mdx
docs/docs/animations/withTiming.mdx

Our documentation is missing information about type of `toValue`
> [!Note]
> The information added in this PR should be included in our documentation 3 times, on pages `withTiming`, `withSpring` and `withDecay`. I will copy-paste it once the text is accepted

Add information about type of `toValue` to our documentation

---

src/reanimated2/hook/useScrollViewOffset.ts

Native implementation of `useScrollViewOffset` lacked a proper cleanup of listeners when changing the reference it points to. 
NOTE: `scrollRef` is currently only an indicator whether there was a different ref set previously. I put it there because I am also currently working on some changes in `WorkletEventHandler` and soon unregister method will need a viewTag too (which will then be extracted from the `scrollRef`).
You can run the following code:
<details><summary>Code</summary>
``` TYPESCRIPT
useDerivedValue,
import { Button, StyleSheet, Text, View } from 'react-native';
export default function ScrollViewOffsetExample() {
const aref = …
```

Add proper listeners cleanup to native useScrollViewOffset

---

docs/docs/scroll/useScrollViewOffset.mdx
docs/package.json
docs/src/examples/ScrollViewOffset.jsx
docs/yarn.lock

`useScrollViewOffset` hook got a web support, so I bumped REA in docs and changed the example to showcase its features more strikingly.
https://github.com/software-mansion/react-native-reanimated/assets/77503811/78fcd6ee-7e13-42e7-9138-27f98e362aff
Open docs page for `useScrollViewOffset`.

Update useScrollViewOffset docs

---

android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensor.java

Currently default magnetic sampling interval equals 2ms, which triggers a `HIGH_SAMPLE_RATE` security exception.
This fix defaults the probing interval to 8ms.
Note: `'auto'` setting defaults to `-1`, which is then replaced by `2`.
Download a new emulator on Android Studio - I'm using `Pixel 8 UpsideDownCake`
Launch the magnetic sensor example before, and after applying this patch.

Fix default Magnetic Sensor interval causing a security exception

---

app/src/examples/ScreenTransitionExample.tsx
src/reanimated2/screenTransition/commonTypes.ts
src/reanimated2/screenTransition/presets.ts
src/reanimated2/screenTransition/styleUpdater.ts

This PR updates public API for custom gesture based screen transition. It renames field `topScreenFrame` to `topScreenStyle`.
This PR was requested by developer experience department as Software Mansion. cc @kacperkapusciak 🫡

Screen Transition update public API

---

docs/docs/advanced/useEvent.mdx
docs/docs/scroll/useAnimatedScrollHandler.mdx
docs/docs/scroll/useScrollViewOffset.mdx

In this comment https://github.com/software-mansion/react-native-reanimated/issues/5345#issuecomment-1859198802:
>Unfortunately, with current implementation handlers provided by **useAnimatedScrollHandler** or any other handlers that are an instance of WorkletEventHandler, that being: **useScrollViewOffset**, **useEvent** and **useAnimatedGestureHandler** (last one deprecated) are supposed to be passed to only one component. This is because their class instances keep the data of the latest component only. Passing them to multiple components leads to undefined behavior.
we mention that event handlers cannot be used with more than one component. This should be documented.
|Handler|Screenshot|Where in docs|
|--|--|--|
|useAnimatedScrollHandler|<img width="561" alt="image" …

Add documentation that event handlers cannot be used with more than one component.

---

src/reanimated2/hook/useScrollViewOffset.ts

It's bad for React, and we can handle creating an unused shared value from time to time.
:shipit: 
<details>
<summary>
Testing snippet
</summary>
```tsx
const scrollViewRefA = useAnimatedRef<Animated.ScrollView>();
const scrollViewRefB = useAnimatedRef<Animated.ScrollView>();
const myOffset = useSharedValue(0);
const hookOffset = useScrollViewOffset(scrollViewRefA);
const hookOffsetFromMyOffset = useScrollViewOffset(scrollViewRefB, myOffset);
const animatedStyleA = useAnimatedStyle(() => ({
borderRadius: 100 * Math.abs(Math.sin(hookOffset.value / …
```

Don't call hooks conditionally in `useScrollViewOffset`

---

app/src/examples/ShareablesExample.tsx
src/reanimated2/shareables.ts

This PR adds support for cloning JS `Error` instances from RN runtime to UI runtime (or any worklet runtime).
The copied error inherits the original name, message as well as stack trace.
Initially, I also wanted to implement cloning in the opposite direction (UI &rarr; RN) but currently `makeShareableCloneOnUIRecursive` does not support initializers and most likely will be subject to change as we plan to unify the implementation of cloning across the runtimes.
ShareableExample.tsx

Add support for cloning `Error`

---

docs/package.json
docs/yarn.lock

This PR upgrades `react-native-gesture-handler` version in documentation. 
Run docs

Bump Gesture Handler version in documentation

---

src/reanimated2/hook/useScrollViewOffset.ts

Inspired by https://github.com/software-mansion/react-native-reanimated/pull/5790, it seems like scrolls can be wrapped in other views (by for example setting their `onRefresh` property), which makes refs to them point to the wrapping view, not them. Thus I add support for such situations to the `useScrollViewOffset` hook, which is our only hook that needs to access the component itself.
<details>
<summary>
Testing code
</summary>
```tsx
import {
Text,
Pressable,
SafeAreaView,
StyleSheet,
Button,
findNodeHandle,
} from 'react-native';
const animatedRef = useAnimatedRef<Animated.ScrollView>();
const offset = useScrollViewOffset(animatedRef); …
```

Fix web useScrollViewOffset on wrapped scrolls

---

README-Fabric.md

Updates the Fabric documentation to install `react-native-reanimated@nightly` since the `next` tag isn't available anymore.
n/a

docs(README-Fabric): updated next tag to nightly

---

Common/cpp/NativeModules/NativeReanimatedModule.cpp
Common/cpp/NativeModules/NativeReanimatedModule.h
Common/cpp/Tools/JSScheduler.cpp
Common/cpp/Tools/JSScheduler.h
android/src/main/cpp/NativeProxy.cpp
apple/native/NativeProxy.mm

Use one constructor for NativeReanimatedModule with bridgeless

---

docs/src/css/colors.css

There was a typo in Figma design file that propagated a wrong color across different projects/documentations.

Fix color in the swm color palette

---

docs/docs/advanced/useEvent.mdx
docs/docs/scroll/useAnimatedScrollHandler.mdx
docs/docs/scroll/useScrollViewOffset.mdx

After some updates, our event handlers can now be used for multiple components, thus the change.
NOTE: this PR can be merged ONLY after https://github.com/software-mansion/react-native-reanimated/pull/5909 because of some yarn issues (`yarn.lock` file will be added to changes afterwards).
:shipit:

Update docs regarding event handlers' reusability

---

docs/static/examples/Marquee.js

For some reason docusarus build on CI adds a semi-colon in an incorrect place making the code from Marquee example not compile. It works on local and main but breaks on `Test build docs` CI.
This PR adds a `prettier-ignore` to prevent breaking the line in between division making it impossible for javascript interpreter to put `;` in an incorrect place.
https://github.com/software-mansion/react-native-reanimated/actions/runs/8751612886/job/24017576211?pr=5914
CI ✅

Fix "Test docs build" on CI

---

cspell.json
src/reanimated2/layoutReanimation/web/animationsManager.ts
src/reanimated2/layoutReanimation/web/componentUtils.ts
src/reanimated2/layoutReanimation/web/createAnimation.ts

#5888 introduced spell checker on our CI and it turns out that there are some typos in web LA codebase. This PR aims to remove them. 
Also I've decided to add "lightspeed", "easings" and "snapshotting" into correct words list, let me know if I should replace them with something else.
Here you can find that these forms are actually correct:
- [snapshotting](https://www.verbix.com/webverbix/english/snapshot)
- [easings](https://www.verbix.com/webverbix/english/snapshot)
- [lightspeed](https://en.wiktionary.org/wiki/lightspeed)
Check that CI passes.

Fix some typos

---

docs/docs/guides/compatibility.mdx

Bump compatibility table for 0.74 and bridgeless

---

src/createAnimatedComponent/createAnimatedComponent.tsx
src/reanimated2/layoutReanimation/web/componentStyle.ts

This PR includes the following changes:
1. Start exiting animation only if component is defined (to avoid issues related to `null`).
2. Call `fixElementPosition` only when parent is defined.
These checks are expected to eliminate `cannot read properties of null` error.
This PR originates from discussion on discord, where it was reported that layout animations crash on web when using `react-navigation` and `expo-router`. Crashes happen when `display: none;` is set. We are not sure what is the exact cause of this issue. However, our main suspect is `MutationObserver` inside `domUtils.ts`. Also, we don't know why `element` is `null`, but we believe that it can happen because of [this line](https://github.com/software-mansion/react-native-reanimated/blob/b900e224aa691bf59eec579327b038c86369552 …

[Web LA] Fix `null` elements error

---

Common/cpp/Fabric/ShadowTreeCloner.cpp

Fix for the issue: https://github.com/Expensify/App/issues/40048 which root cause of seems to be the not copied state of `ScrollView` when this code is not added. I'll try to provide a simple repro when I get some time to do it.

fix: copy state in reanimated commit hook

---

apple/REAModule.mm

As I pointed out [here](https://github.com/software-mansion/react-native-reanimated/pull/5901#discussion_r1567743828), using `[RCTBridge currentBridge]` may lead to the wrong bridge in apps that have multiple React instances, as is the case for expo-dev-client.
https://github.com/software-mansion/react-native-reanimated/blob/7e1a19ed8190763456e96939eec71c2528c1eed4/apple/REAModule.mm#L284
Fixes #5497 
Instead of using `[RCTBridge currentBridge]` we can just call `self.bridge` and ensure the correct bridge is always used 
Run FabricExample app on iOS

Prevent iOS bridgeless initialization from getting the wrong bridge

---

android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java

Fixes:
https://github.com/software-mansion/react-native-reanimated/assets/9578601/949756a7-fb89-4bbd-89a6-52d1ba759083
Stack trace:
```
FATAL EXCEPTION: main
Process: com.lukaszkosmaty.myapp, PID: 17336
java.lang.AssertionError
at com.swmansion.reanimated.NodesManager.<init>(NodesManager.java:157)
at com.swmansion.reanimated.ReanimatedModule.getNodesManager(ReanimatedModule.java:133)
at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.maybeInit(ReanimatedNativeHierarchyManager.java:47)
at com.swmansion.reanimated.layoutReanimation.ReaLayoutAnimator.isLayoutAnimationEnabled(ReanimatedNativeHierarchyManager.java:193)
at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.isLayoutAnimationDisabled(ReanimatedNativeHierarchyManager.java:269)
at …
```

Fix crashes when reloading app quickly on Android

---

apple/LayoutReanimation/REASwizzledUIManager.mm
apple/REANodesManager.mm

This PR fixes the following infinite loop:
For details, see https://github.com/expo/expo/pull/28531.
1. Build Example app on iOS Paper on 0.74.0
2. Open Bokeh example
3. Go back
4. Reload the app by pressing <kbd>r</kbd> in Metro console
5. Repeat steps 2-4 several times
6. When the app hangs, press pause button in Xcode debugger

Use `[RCTUIManager viewForReactTag:]` instead of `viewRegistry` to avoid infinite loop in `[RCTComponentViewRegistry objectForKey:]`

---

android/src/main/java/com/swmansion/reanimated/keyboard/KeyboardAnimationManager.java

Fixes #5822
To keep track of all listeners we use hash map, and notify changes on all of them. When quickly opening flat list with components that use useAnimatedKeyboard and focus on some keyboard, the flat list is still adding new components (adding new listeners), while listeners are notified in the loop about the changes to the keyboard height. Changing HashMap to ConcurrentHashMap seems to fix the issue.  
|Before|After|
|-|-|
|<video src="https://github.com/software-mansion/react-native-reanimated/assets/11800297/66d26b5e-3e81-492b-b692-50d63bc4ca0e" />|<video src="https://github.com/software-mansion/react-native-reanimated/assets/11800297/bca99310-d4e1-4cfa-a83b-de3872c93f47" />|
<details>
<summary>Test component</summary>
```jsx
import {
FlatList, …
```

Crash while using useAnimatedKeyboard in flat list

---

android/src/main/java/com/swmansion/reanimated/keyboard/Keyboard.java
android/src/main/java/com/swmansion/reanimated/keyboard/WindowsInsetsManager.java

Should fix: #5811
Keyboard height seems to be improperly calculated. Based on my investigation it seems that ` WindowInsetsCompat.Type.ime()` includes height of the keyboard + bottom navigation. What Reanimated does currently is checking if navigation bar is visible (`KeyCharacterMap.deviceHasKey(KeyEvent.KEYCODE_HOME);`) and then subtracts the bottom inset `int keyboardHeight = DiphasNavigationBar ? contentBottomInset - systemBarBottomInset : contentBottomInset;`. But to my understanding `hasNavigationBar` is always true, thus when keyboard is hidden keyboard height becomes `-contentBottomInset`. So I changed the navigation height to be `Math.max(0, keyboardHeightDip)`
Additionally in WindowInsetsManager.java I applied default paddings and added padding bottom which should help correctly …

Fix calculating keyboard height

---

apple/LayoutReanimation/REAAnimationsManager.m

Fixes https://github.com/software-mansion/react-native-reanimated/issues/5947. Fixes https://github.com/software-mansion/react-native-reanimated/issues/5968.
When `react-native-reanimated` is installed but not used directly, switching between bottom tabs from `@react-navigation/bottom-tabs` will result in a `EXC_BAD_ACCESS` crash on iOS.
This PR adds missing mock for `_clearSharedTransitionConfigForTag` as suggested by @bartlomiejbloniarz.
Try repro from https://github.com/software-mansion/react-native-reanimated/issues/5947#issuecomment-2094789350

Fix EXC_BAD_ACCESS crash on iOS in `[REAAnimationsManager clearSharedTransitionConfigForTag:]`

---

apple/LayoutReanimation/REASwizzledUIManager.mm

Fixes https://github.com/software-mansion/react-native-reanimated/issues/5973.
```
*** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<RCTUIManager 0x600002bbd340> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _uiManager.'
*** First throw call stack:
(
0   CoreFoundation                      0x00000001804ae138 __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x0000000180087db4 objc_exception_throw + 56
2   CoreFoundation                      0x00000001804adcdc -[NSException init] + 0
3   Foundation                          0x0000000180d6acf8 -[NSObject(NSKeyValueCoding) valueForUndefinedKey:] + 188
4   Foundation                          0x0000000180d69c60 -[NSObject(NSKeyValueCoding) valueForKey:] + 260
5 …
```

Fix uncaught exception 'NSUnknownKeyException' on app reload on iOS

---

docs/docs/fundamentals/glossary.mdx

This is a change of a single character in documentation. It just changes "It can be ... ran" to "It can be ... run" because the former is bad grammar.
Since this is a documentation-only change, there is no test plan.

docs: fix grammar

---

apple/REASlowAnimations.mm

This PR fixes build issues for visionOS. The `CACurrentMediaTime` API comes from QuartzCore which was not imported in this file. Unfortunately, visionOS is more strict and requires explicit imports, this shouldn't cause any issues on other platforms.
Build the app for visionOS

fix: build issues on visionOS

---

docs/src/css/examples.css

After this fix the pagination is hidden on `Examples` page but visible on `Docs` page.

fix missing NavLink in docs

---

src/createAnimatedComponent/commonTypes.ts
src/createAnimatedComponent/createAnimatedComponent.tsx

Turns out the usual component tag (used for Layout Animations, Shared Element Transitions and Animated Styles) won't always work for events if the component with nested event emitters is made animated. Thus I am splitting these two into different tag variables.
You can check out the following code (logs in console): 
<details><summary>Code</summary>
``` TYPESCRIPT
import Animated, { useAnimatedScrollHandler } from 'react-native-reanimated';
import { StyleSheet, View, Text } from 'react-native';
import { FlashList } from '@shopify/flash-list';
const AnimatedFlashList = Animated.createAnimatedComponent(FlashList);
const data = new Array(45);
export default function EmptyApp() {
const scrollHandler = useAnimatedScrollHandler(
{
onBeginDrag: () => {
'worklet'; …
```

Make animated components use different tags for events

---

docs/docs/layout-animations/custom-animations.mdx

This fixes a typo on the key of `targetValues`, `targetOriginX.originX` should be `targetValues.targetOriginX`

fix typo on object key for `targetValues` in custom-animations.mdx

---

android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java

This pull request addresses the restoration of component location after a shared transition. Previously, the component offset was restored based on the absolute position of the component on the screen. However, this method is more suitable for positioning components absolutely. When the component is reattached to its original parent, we now aim to restore the offset from the parent instead of the global offset from the screen border.
| --- | --- |
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/d4b2254a-48a0-4c7c-8075-7a8e12343b5a" /> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/46a304bb-a00b-46d3-a6d6-396c987eaf3d" /> |

Fix location after shared element transition

---

docs/src/components/HireUsSection/styles.module.css

Normal:
Hovered:
```
cd docs/
yarn
yarn start
yarn build
yarn serve
```

Add dark mode to button in `Hire us` section

---

__typetests__/common/useScrollViewOffsetTest.tsx
src/reanimated2/hook/useScrollViewOffset.ts

https://github.com/software-mansion/react-native-reanimated/pull/5942 needs `useScrollViewOffset`'s ref to be nullable - hence the PR. I also checked and a lot of cleanup code in the hook was redundant.
You can run the following code, it checks both switching between nullable and non-nullable ref, as well as two different scrolls: (add some logs in hook's registering/unregistering to see that cleanups work fine)
<details><summary>Code</summary>
``` TYPESCRIPT
useDerivedValue,
import { Button, StyleSheet, Text, View } from 'react-native';
const [refConnected, setRefConnected] = React.useState(false);
const [refSwitched, …
```

Make `useScrollviewOffset` ref nullable and simplify its code

---

__typetests__/common/AnimatedComponentTest.tsx
src/reanimated2/component/FlatList.tsx

Closes #5931 
In our implementation of Animated.FlatList we overwrite `CellRendererComponent` and providing it is not supported. Therefore I remove it from valid props
Error message should contain the information "CellRendererComponent is not supported in Animated.FlatList"
Code:
Error message:
Tests in `__typetests__/common/AnimatedComponentTest.tsx` added

Remove `CellRendererComponent` from Animated.FlatList props

---

src/reanimated2/Colors.ts
src/reanimated2/__tests__/Colors.test.ts

Fixes #5746. Not all color formats and syntax supported by RN is supported by reanimated. This PR should align with RN implementation. An example for rgb,rgba,hsl,hsl with comma and without (for view and Animated.View):
|Before|After|
|-|-|
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/11800297/fe6f9b1d-a4e3-4542-baae-9d499aa6f252" />|<video src="https://github.com/software-mansion/react-native-reanimated/assets/11800297/1c33d1d3-6e0b-483a-a88d-7c8eb467b859" />|
Reused [RN tests](https://github.com/facebook/react-native/blob/main/packages/normalize-color/__tests__/normalizeColor-test.js).
<details>
<summary>Example from the video</summary>
```jsx
import { StyleSheet, View, Text } from 'react-native'; …
```

Align handling colors with RN

---

docs/docs/animations/withDecay.mdx
docs/src/components/InteractivePlayground/index.tsx
docs/src/components/InteractivePlayground/useDecayPlayground/Example.tsx
docs/src/components/InteractivePlayground/useDecayPlayground/index.tsx

This PR includes a playground to withDecay subpage.
withDecay Playground
Command to change current working dictionary:
> cd docs
Command to download libraries:
> yarn
Command to preview feature:
> yarn start

Adding playground to withDecay subpage

---

src/reanimated2/layoutReanimation/defaultAnimations/Roll.ts

There was a typo that made our entering animation RollInLeft ignorant to modifiers:
```diff
-   { translateX: delayFunction(delay, animation(0), config) },
+   { translateX: delayFunction(delay, animation(0, config)) },
```

Make animation RollInLeft work with modifers

---

docs/src/components/InteractiveExample/index.tsx

Before when page was loading, there was a chance that `width` value wouldn't be passed to component in `InteractiveComponent` - in other words the `width` will be passed to component before it had become something other than `null`, and there won't be a rerender after width gets a number value. After this change, with `useEffect` hook, we monitor if width has changed and if so, we trigger a rerender that guarantees our component will always get correct width.

Add safer refresh on InteractiveExample

---

src/reanimated2/layoutReanimation/web/animationParser.ts
src/reanimated2/layoutReanimation/web/animationsManager.ts
src/reanimated2/layoutReanimation/web/componentUtils.ts
src/reanimated2/layoutReanimation/web/createAnimation.ts

A while ago I've noticed that layout animations on mobile throw warning if one tries to add animation into `View` that has `transform` property. Now, while working on #5277 I've decided to remove code responsible for applying existing transform on web. Here are the reasons why I believe it is good idea:
1. It unifies behavior with mobile platforms, which are main target of `reanimated`.
2. Some of `transforms` were not applied correctly and required additional calculations to be implemented (like `skew`).
3. Removing existing transforms means removing a lot of `ifs` and unnecessary code.
Tested on example app on `LA` examples.

[Web LA] Remove `existingTransform`

---

docs/docs/advanced/useComposedEventHandler.mdx

improved composed handler docs to match our standards

---

docs/docs/guides/compatibility.mdx

This PR adds a missing version label for the New Architecture in the compatibility table. Also, tiny grammar fix `Reanimated does support` -> `Reanimated supports`.

docs: update compatibility table for fabric

---

apps/fabric-example/android/build.gradle
apps/fabric-example/package.json
packages/eslint-plugin-reanimated/types/index.d.ts
yarn.lock

Fix Fabric in monorepo

---

packages/react-native-reanimated/android/src/reactNativeVersionPatch/ReactHost/72/com/swmansion/reanimated/DevMenuUtils.java

This is a copied version of https://github.com/software-mansion/react-native-reanimated/pull/6073, it was needed because of monorepo migration.
:shipit:

Fix missing imports for RN72 compatibility

---

apps/common-app/src/examples/ShareableFreezingExample.tsx
packages/react-native-reanimated/src/shareables.ts

Fixes #6066. When implementing more meaningful way of shareable freezing I overlooked the case when some properties would be unconfigurable. This PR fixes this.
New button in `ShareableFreezing` example checks that it doesn't throw anymore.

Fix configuring unconfigurable properties 

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/keyboard/Keyboard.java

This PR addresses a requested issue that randomly occurs on some Android devices:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.swmansion.reanimated.keyboard.KeyboardState.asInt()' on a null object reference
at com.swmansion.reanimated.keyboard.KeyboardAnimationManager.notifyAboutKeyboardChange(KeyboardAnimationManager.java:45)
```
This NullPointerException was likely caused by the lack of a default value for the `mState` field.

Set default keyboard state

---

packages/docs-reanimated/src/css/colors.css
packages/docs-reanimated/src/css/overrides.css
packages/docs-reanimated/src/examples/DecayBasic.tsx
packages/docs-reanimated/src/examples/SpringBasic.tsx
packages/docs-reanimated/static/examples/BottomSheet.js
packages/docs-reanimated/static/examples/SectionList.js

Before:
https://github.com/software-mansion/react-native-reanimated/assets/59940332/752191ee-8202-42f0-be3e-1255533417ba
After:
https://github.com/software-mansion/react-native-reanimated/assets/59940332/e91d5701-efeb-4255-a350-c516381b27b9
Before:
After:
Before:
After:
Before: 
After:

Fixes of dark-theme and values in docs

---

.github/workflows/build-npm-package-action.yml

Nightly build CI got hit with a recoil from monorepo integration.
Also, running `npm publish` from Reanimated package root (that contained packed `.tgz` file) would use files of Reanimated instead of the package, thus the move operation.

Fix nightly build CI

---

packages/docs-reanimated/blog/bottom-sheet.md
packages/docs-reanimated/blog/section-list.md
packages/docs-reanimated/blog/slider.md

Before some links were absolute, and other were relative. This PR makes all links from examples relative.

Make all links from Reanimated Cookbook relative

---

.github/workflows/docs-check.yml

As stated, the docs-check CI wasn't triggering on docs-related PRs. This one fixes it.
👍

Fix docs-check CI trigger path

---

apps/web-example/metro.config.js

Following the transition to a monorepo structure, our web-example app stopped working due to an asset loading issue. Turns out that the `getAssetByID` function from `react-native-web` was being called from the incorrect module. We believe this might have resulted in one module blocking an asset while another module was trying to load it, causing the application to crash.
This PR modifies the `metro.config.js` inside the `web-example` folder. It is now configured to ignore the `@react-native` module from the root, which allows assets to load correctly.
Run `web-example`.

Fix `web-example` 

---

packages/docs-reanimated/static/examples/Slider.js

**Slider Example**
Before:
After:

docs: Add missing dark themes

---

apps/common-app/src/examples/ScreenTransitionExample.tsx
apps/fabric-example/ios/FabricExample/Info.plist
apps/paper-example/ios/ReanimatedExample/Info.plist

After release of `react-native-screens` we can remove temporary mock from example app and use proper import from rn-screens.
I had to make modifications to `UIViewControllerBasedStatusBarAppearance` because we are using the native stack from `rn-screens` until the changes are upstreamed to `react-navigation` - [Pull Request Link](https://github.com/react-navigation/react-navigation/pull/11943)
Run screen transition example in example app.

Screen transition example  update - use proper import from screens instead of mock

---

packages/docs-reanimated/src/css/overrides.css

Before, on Examples page, sidebar was transparent due to insufficient css selector from past PR. In this PR we made more accurate selector to fix this problem.
Before: 
After:

docs: fix transparent sidebar

---

packages/react-native-reanimated/apple/LayoutReanimation/REASharedTransitionManager.m

This pull request aims to address the lack of Shared Element Transition in Expo Go. The issue stemmed from the initialization process of SET. In Expo Go, Reanimated gets instantiated twice (once for the Expo client and once for the actual application). During initialization, `REASharedTransitionManager` attempts to swizzle certain methods from `react-native-screens` but aims to do so only once:
```objc
static dispatch_once_t onceToken;
dispatch_once(&onceToken, ^{
...
_isConfigured = YES;
});
```
The variable `_isConfigured` was only set to true if the swizzling process completed successfully. The problem appeared when the second instance attempted to set up the `screens` integration, as it had already been done, resulting in the new instance failing to set `_isConfigured` to true, even …

Fix SET in Expo Go

---

packages/react-native-reanimated/plugin/README-dev.md

Fixes broken link in documentation - the location of file changed after migration to the monorepo

Fix broken link in documentation

---

packages/docs-reanimated/src/components/InteractivePlayground/index.tsx

On interactivePlayground preserve disabled input color, but make enabled text color adapt to color theme.
Before:
After:

Adjust Playground dark theme

---

packages/docs-reanimated/blog/slider.md

docs: Adjust expandable code

---

packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/CurvedTransition.ts
packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/EntryExitTransition.ts
packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/FadingTransition.ts
packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/JumpingTransition.ts
packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/LinearTransition.ts
packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/SequencedTransition.ts

Yesterday we've discovered that some basic transitions don't work on web anymore. Turns out that `animationName` was `undefined`, therefore transitions were not created.
This PR adds `presetName` field into transitions, so we can easily obtain their name. 
> [!NOTE]
> Similar thing was done in #5562, so I believe that we can stick to this convention.
<details>
<summary> Tested on the following code: </summary>
```jsx
BounceInLeft,
FadeOutRight,
FadingTransition,
export default function BasicLayoutAnimation() {
const [state, setState] = React.useState(false);
const [visible, setVisible] = React.useState(true);
return ( …
```

[Web LA] Fix default transitions.

---

packages/react-native-reanimated/src/js-reanimated/index.ts
packages/react-native-reanimated/src/js-reanimated/webUtils.ts
packages/react-native-reanimated/src/js-reanimated/webUtils.web.ts

This PR fixes tree shaking in JSReanimated by moving web-specific code into a separate file with `.web.ts` file extension.
https://swmansion.slack.com/archives/CGHFEK33M/p1718648665665579

Fix tree shaking in JSReanimated

---

packages/react-native-reanimated/src/hook/useFrameCallback.ts

`useFrameCallback` had a bit faulty cleanup: it used ref.current during useEffect cleanup, when the ref value could as well be unreachable (already deallocated). I added the `callbackId` memoization + removed unnecessary setting it to -1.
`useFrameCallback example` from Example App, as well as this code:
<details><summary>Code</summary>
``` TYPESCRIPT
useFrameCallback,
const t = useSharedValue<number>(0);
const height = 1300;
useFrameCallback((frameInfo) => {
t.value = frameInfo.timeSinceFirstFrame / 350;
});
const infinityStyle = useAnimatedStyle(() => {
const scale = 2 / (3 - Math.cos(2 * …
```

Fix useFrameCallback cleanup

---

packages/react-native-reanimated/src/layoutReanimation/web/componentUtils.ts

This PR aims to fixing the web exiting animation when StrictMode is enabled. With StrictMode triggering an additional simulated unmount, our listeners detected the need for an exiting animation. The problem originated from setting `visibility = 'hidden'` on the original component, which remained present, and creating a copy for animation. As a result, the original component was hidden from view in the DOM tree. The solution proposed is simply to eliminate the hiding of components. This adjustment is safe even for scenarios without StrictMode, as the component that is hidden is removed in the same frame, ensuring consistency with the previous behavior.
| --- | --- |
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/07530231-58e4-429 …

Fix web exiting animation in StrictMode

---

packages/react-native-reanimated/src/layoutReanimation/web/componentUtils.ts
packages/react-native-reanimated/src/layoutReanimation/web/config.ts
packages/react-native-reanimated/src/layoutReanimation/web/createAnimation.ts
packages/react-native-reanimated/src/layoutReanimation/web/transition/Jumping.web.ts

This PR adds `JumpingTransition` to transitions available on web 😄 
<details>
<summary>Tested on the following code (it is taken from docs so it throws some TypeScript errors, but it works fine)</summary>
```js
import React, { useState, useRef, useEffect } from 'react';
import {
View,
Text,
SafeAreaView,
StyleSheet,
TouchableOpacity,
} from 'react-native';
LinearTransition,
SequencedTransition,
FadingTransition,
FadeOut,
useDerivedValue,
withTiming,
withDelay,
JumpingTransition,
const DROPDOWN_OFFSET = 48;
const INITIAL_LIST = [
{ id: 1, emoji: '🍌', color: '#b58df1' },
{ id: 2, emoji: '🍎', color: '#ffe780' },
{ id: 3, emoji: '🥛', color: '#fa7f7c' },
{ id: 4, emoji: '🍙', color: '#82cab2' },
{ id: 5, …
```

[Web LA] Add `JumpingTransition`

---

packages/react-native-reanimated/Common/cpp/ReanimatedRuntime/WorkletRuntimeDecorator.cpp
packages/react-native-reanimated/android/CMakeLists.txt

Just wanted to enable `-Wpedantic` flag on Android like React Native does.
Tested on runOnUI / runOnJS example.

Enable `-Wpedantic` flag on Android and use `std::vector` instead of VLA to pass arguments to `_scheduleOnJS`

---

packages/react-native-reanimated/__tests__/InterpolateColor.test.tsx
packages/react-native-reanimated/src/Colors.ts

If the interpolated alpha value is really tiny, the code might emit a string like "rgba(0, 0, 0, 1e-11)". This is not valid syntax, and can cause worklet crashes. Replace these small values with 0.
This PR includes the necessary unit-test update:
```ts
it('handles tiny values', () => {
const colors = ['#00000000', '#ff802001'];
// We don't want output like "rgba(4, 2, 0, 3.921568627450981e-7)":
const interpolatedColor = interpolateColor(0.0001, [0, 1], colors);
expect(interpolatedColor).toBe(`rgba(4, 2, 0, 0)`);
});
```

Properly stringify tiny color values

---

packages/docs-reanimated/docs/core/useSharedValue.mdx

Reading from a shared value on the js thread may block the JS thread until the UI runtime finishes whatever it's doing. This isn't really communicated clearly and adding it to the docs seems like the best option as we don't want to show warnings.
I asked ChatGPT to point out problems (it did).

Add remark about reading SharedValue from the js thread

---

packages/docs-reanimated/docusaurus.config.js

After the migration to monorepo "Edit this page" button in docs stopped working - it led to 404 not found.
This PR fixes the docusaurus configuration so the edit button routes to the correct place.

docs: fix 'Edit this page' link

---

packages/docs-reanimated/docusaurus.config.js

Microoptimization over a fix in https://github.com/software-mansion/react-native-reanimated/pull/6176
The link can route directly to the edit page which saves an additional click ;)

docs: Edit this page button should go directly to edit page

---

packages/react-native-reanimated/src/platform-specific/RNRenderer.web.ts

React Native Babel preset uses a loose plugin to convert imports to commonjs, we're investigating switching to a more standard approach in Expo CLI here https://github.com/expo/expo/pull/30005 which aligns with how Metro is used at Meta.
When running on the kitchen sink, I found that there was an invalid expression in reanimated where it exports null and then destructures null. This error didn't occur previously because the commonjs plugin deferred access to the null object until later.
**Before**
```js
var _Math = _$$_REQUIRE(_dependencyMap[0]);
// Later ...
_Math.add
```
This coincidentally didn't throw because the deferred code is never accessed.
**After**
```js
var add = _$$_REQUIRE(_dependencyMap[0]).add;
```
This throws because the `null` is accessed when the module is loaded. …

fix empty export on web

---

packages/react-native-reanimated/src/platform-specific/RNRenderer.web.ts

This PR fixes the following linting error that happened on main after #6171 was merged.

Fix lint error on main

---

apps/common-app/package.json
apps/common-app/src/examples/StrictDOMExample.tsx
apps/common-app/src/examples/index.ts
apps/web-example/babel.config.js
yarn.lock

This PR adds an example and the necessary configuration for testing React Strict DOM within our Example apps.
https://github.com/software-mansion/react-native-reanimated/assets/36106620/7e1164c8-e8b6-45fc-8eb2-cbd6d70fc12a

Strict DOM example

---

apps/fabric-example/android/gradle-wrapper.properties

Looks like this file is an unwanted duplicate of `apps/fabric-example/android/gradle/gradle-wrapper.properties`.

Delete duplicate `gradle-wrapper.properties`

---

packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/FadingTransition.ts

This PR aims to fix some unexpected behaviour during `FadingTransition`.
| --- | --- |
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/e855c796-a926-48bf-b55d-80014694043d" /> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/36106620/004bd2f6-2bb7-41b2-af1d-6d98a94908c0" /> |
Expected behavior:
- The component stays in the original position.
- Starts the fade-out animation.
- Wen component is invisible, changes position to the target position.
- Starts the fade-in animation.
In the previous approach, when the `delayFunction` was not specified (when no one called `.delay()`), the component jumped to the final position after 50ms instead of waiting until the component became invisible.
I tested it …

Fix FadingTransition

---

packages/docs-reanimated/blog/accordion.md
packages/docs-reanimated/blog/bottom-sheet.md
packages/docs-reanimated/blog/flip-card.md
packages/docs-reanimated/blog/floating-action-button.md
packages/docs-reanimated/blog/marquee.md
packages/docs-reanimated/blog/section-list.md
packages/docs-reanimated/blog/slider.md
packages/docs-reanimated/blog/switch.md
packages/docs-reanimated/src/theme/MDXComponents.js

Because ExampleVideo started to be widely used in documentations mdx, we moved it to MDXComponents.js to use it without further imports.

docs: Move ExampleVideo to MDXComponents

---

packages/docs-reanimated/package.json
packages/docs-reanimated/src/theme/DocSidebar/index.js
packages/docs-reanimated/yarn.lock

Important changes from 0.0.12:
* [navbar_links ](https://github.com/software-mansion-labs/t-rex-ui/commit/cab20427bf28d8325e6cc97dc7ac329927edb019) 
* [search modal style fix](https://github.com/software-mansion-labs/t-rex-ui/commit/c1a69ac4fd81458b9bd24314aaa74a0d30b0f2bf)
* [hire us links](https://github.com/software-mansion-labs/t-rex-ui/commit/8ef15757524a395d3f12b57c85c9f561a3398120)
* [sidebar labels](https://github.com/software-mansion-labs/t-rex-ui/commit/ba1932ae6fa4a30e3fdb6144f62e6e30fdea3e73) such as `New` and `Experimental` 
Also DocSidebar was modified with newItems and experimentalItems

docs: bump `@swmansion/t-rex-ui` to 0.0.12

---

packages/react-native-reanimated/package.json

Been playing with an implementation of side effects in Expo CLI and noticed that reanimated has an unmarked side effect which causes tree shaking to remove required globals.

fix side effects

---

packages/react-native-reanimated/src/layoutReanimation/web/componentUtils.ts

Currently some of our animations flicker on google chrome browser. This PR moves setting animation into `requestAnimationFrame` callback - this way we will be sure that animation will be properly set before next repaint.
https://github.com/software-mansion/react-native-reanimated/assets/63123542/fe674d23-d1bb-44c3-a870-335c330c7073
https://github.com/software-mansion/react-native-reanimated/assets/63123542/2a4833a7-c3d9-4a59-b108-a7f4cc166f1f
Tested on default animations example

[Web LA] Fix chrome flickers

---

apps/common-app/src/examples/Game2048Example.tsx

2048 example was crashing on web because of a function being referenced before being initialised.

Fix 2048 example

---

apps/fabric-example/android/app/build.gradle
apps/paper-example/android/app/build.gradle

Yeah so it turns out `hermesCommand` path was commented out (and wrong) in PaperExample `build.gradle`.
I've seen that this change was introduced while ensuring RN0.71 compatibility so I am a bit confused..
Launch android paper example with release bundle

Fix hermesCommand path for android release bundle

---

packages/react-native-reanimated/src/Colors.ts

Our `interpolateColor` function seems to have some unnecessary color processing in it. It was added some 3-4 years ago and should not be needed by now.
There is a function called `rgbaColor` which is used in `hsvToColor` (which in turn is used only in `interpolateColor`) as well as directly in `interpolateColor`. So it's safe to say it is used ***only*** there. All it does is take r,g,b,a values, runs a small check on them and then returns a rgba string.
It has a check whether we are on UI thread or not. If we were on UI, it returned a number-formatted color (formatted for native platforms) instead of the usual rgba string. The problem is, these values are then directly returned from the function. I believe it was needed back then, but now we have a function called `processColorInProps` …

Remove unnecessary color processing in `interpolateColor`

---

packages/docs-reanimated/package.json
packages/docs-reanimated/scripts/build-og-images.jsx
packages/docs-reanimated/yarn.lock

Before OG images script only covered `/docs` folder, but after this change it also generates OG images for `/blog` folder which containes Examples.
In `/docs-reanimated` run:
```
yarn build && yarn serve

docs: Add OG images for Examples

---

packages/docs-reanimated/docs/guides/debugging-worklets.mdx
packages/docs-reanimated/docs/guides/testing-with-jest.mdx
packages/docs-reanimated/versioned_docs/version-2.x/api/miscellaneous/interpolateColors.mdx

Few docs were missing markdown header - instead they had docusaurus title property. Because of that it wasn't possible to generate og images for them. In the future these docs will be rewritten to meet current style guide. 
That's why we decided to add `# Title` in docs instead of fix for `title: ...` in generate-og-images.js script. If we were to add fix to the script it will become redundant within a month or two.
Following docs were added a header:
- interpolateColor
- Debugging worklets
- Testing with Jest

docs: Add markdown header to docs

---

.husky/pre-commit
packages/react-native-reanimated/package.json

I measured which bits of precommit take so long:
I decided to simply call it conditionally.

Speed up precommit

---

apps/common-app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/TestRunner.ts
apps/common-app/src/examples/RuntimeTests/tests/TestsOfTestingFramework.test.tsx

This PR removes the usage of `callTracker` from the internal logic. It is replaced with a simple mutable value. Additionally, the PR adds the possibility to restore the original implementation of `console.log` and `console.error` after running a test case.

[reJest] Remove calltracker usage form internal logic

---

packages/react-native-reanimated/src/Bezier.ts

This PR removes a 4-year-old TODO in the `Bezier` library, keeping `Arrays` and removing mentions of `Float32Arrays`.
This is due to `Float32Arrays` having a very specific `WebGL` use case, and generally being slower than regular `Arrays`, especially when they're dynamically re-allocated over and over again as it is the case in the `Bezier` library.
Live speed demo: [link](https://jsperf.app/float32array-slowness-test/2)
Live demo results:
not-applicable
Using `Float32Array` here has no effect on precision, and no measurable speed improvement/degradation was noted on the production-like-conditions tests that I did.

Assess and remove unnecessary usage of `Float32Array`

---

packages/react-native-reanimated/android/CMakeLists.txt

This PR temporarily fixes https://github.com/software-mansion/react-native-reanimated/issues/6234 by making the problematic `-Wpedantic` flag to be applied only in Reanimated example apps so that we can monitor the soundness of the code on the CI.
`-Wpedantic` flag was introduced in #6157 and released in 3.13.0.
Check if the CI is green.

Append `-Wpedantic` only for example apps

---

packages/docs-reanimated/docs/guides/contributing.mdx

In the [Contributing](https://docs.swmansion.com/react-native-reanimated/docs/guides/contributing) section, right now in the 4th point of Ways to contribute subsection, paragraph "contributing to code here" does not redirect to the given subsection at all. This PR fixes this by changing the id of the subsection to the correct one.
I've also changed `discord` to `Discord` in one of paragraphs, since that small `d` has caught my attention 😄.

docs: Fix linking to `Contributing to the code` section

---

packages/react-native-reanimated/package.json

This PR adds the `README.md` file back to the NPM package. After migration to a monorepo, the `README.md` file's location was changed to the parent directory. Unfortunately, you can't include a file from the parent directory in an npm package, and symlinks don't work for this either.
run `npm pack` and check if README.md is inside

Put back the README.md file in the npm package

---

packages/react-native-reanimated/src/layoutReanimation/web/animation/Bounce.web.ts
packages/react-native-reanimated/src/layoutReanimation/web/animation/Fade.web.ts
packages/react-native-reanimated/src/layoutReanimation/web/animation/Lightspeed.web.ts
packages/react-native-reanimated/src/layoutReanimation/web/animation/Pinwheel.web.ts
packages/react-native-reanimated/src/layoutReanimation/web/animation/Roll.web.ts
packages/react-native-reanimated/src/layoutReanimation/web/animation/Rotate.web.ts
packages/react-native-reanimated/src/layoutReanimation/web/animation/Zoom.web.ts

This PR adds missing `keyframe` steps definitions in default layout animations. While they are not necessary for animations to work, I've found some problems with it while implementing `withInitialValues` modifier.
It turns out if you do not specify a property in initial `keyframe` step and then you decide to change it in next `keyframe` steps, it may not work.
> [!NOTE]
> Example below was written in pure `HTML` and `CSS` on [W3Schools Tryit Editor](https://www.w3schools.com/cssref/tryit.php?filename=trycss3_keyframes). However, since this PR is about web layout animations, it applies to them in the same manner as to animations in `HTML` and `CSS`.
Consider this example:
```CSS
#box {
width: 100px;
height: 100px;
background: red;
animation: myAnimation 2s;
}
@keyframes myAnimation {
100% …
```

[Web LA] Fill in missing keyframes in default animations

---

packages/react-native-reanimated/src/layoutReanimation/web/animationsManager.ts
packages/react-native-reanimated/src/layoutReanimation/web/config.ts
packages/react-native-reanimated/src/layoutReanimation/web/createAnimation.ts

This PR adds `withInitialValues` into web layout animations.
> [!NOTE]
> This implementation required #6259. You can find more information in mentioned PR.
Implementation is based on modifying first step in `keyframe`. First we obtain default animation style and create its copy using `structuredClone`. We also add `px` suffix into `translate` and `perspective` in `initialValues`. Then we can modify styles of animation.
Here situation is more complicated. First, if `transform` was not specified in the predefined styles, we can simply assign to it the one provided in `initialValues`. Otherwise we have to merge incoming transform with predefined one.
To do this, we use `Map` that will contain final `transform`. First we iterate through predefined transforms, adding each property with its …

[Web LA] Add `withInitialValues` modifier

---

packages/docs-reanimated/docs/core/useSharedValue.mdx

Fixes `useSharedValue` type definition in docs after changes in the #4300 PR.
No tests :)

Fix useSharedValue type definition in docs

---

packages/react-native-reanimated/src/component/PerformanceMonitor.tsx
packages/react-native-reanimated/src/index.ts

PerformanceMonitor unnecessarily used accumulator and time delta calculations.
I replaced those with time range measurement and added component props to modify smoothing amount.
Additionally smoothing is now modifiable via the `PerformanceMonitorProps`, 
which are exported alongside `PerformanceMonitor`
Not consistently reproducible.
| exhibit 1 (`smoothing=5`) | exhibit 2 | exhibit 3 |
| --- | --- | --- |
| <video src="https://github.com/software-mansion/react-native-reanimated/assets/74246391/3a729ba5-1273-4529-ae5b-14ff6b7981e8"></video> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/74246391/ba3c7a96-19b5-46fb-aeb2-b27c4c66e36e"></video> | <video src="https://github.com/software-mansion/react-native-reanimated/assets/74246391/f2b24cdf-74b0-472c-8301-33 …

Improve `PerformanceMonitor`'s functionality

---

packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/EntryExitTransition.ts

The `combineTransition` method doesn't seem to be necessary. It doesn't add any additional logic, duplicates the public API, and misleadingly suggests that `combineTransition` and `EntryExitTransition` are distinct entities. In fact, it has even been removed from the documentation page [here](https://github.com/software-mansion/react-native-reanimated/pull/6144).

Deprecate `combineTransition`

---

apps/common-app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/RuntimeTestsRunner.tsx
apps/common-app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/SyncUIRunner.ts
apps/common-app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/TestRunner.ts
apps/common-app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/UpdatesContainer.ts

Previously to use function `runOnUIBlocking` we need a reference to TestRunner. 
I wanted to use `runOnUIBlocking` while implementing some other feature 
(`expect(()=>{}).toThrow()`) and found it a bit troublesome. Therefore I've decided to extract this code into separate class first.

Exract async code to separate classes

---

packages/react-native-reanimated/apple/LayoutReanimation/REASharedTransitionManager.m

This PR changes the way Progress Transitions are restarted. Since the `finishSharedTransition` method is triggered by `RNSScreens` events we shouldn't increase the restart counter, because this could cause the cleanup to never happen.
Check `[SET]` examples for regressions on iOS

Prevent disabling cleanup in progress transitions on iOS

---

apps/common-app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/matchers/Comparators.ts
apps/common-app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/types.ts
apps/common-app/src/examples/RuntimeTests/tests/advancedAPI/measure.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/animations/withSequence/arrays.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/animations/withSequence/cancelAnimation.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/animations/withSequence/numbers.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/animations/withTiming/arrays.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/animations/withTiming/basic.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/core/useAnimatedStyle/reuseAnimatedStyle.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/core/useDerivedValue/basic.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/core/useDerivedValue/chain.test.tsx

Due to some platform limitations, certain properties may not be exact values as originally set, for example, opacity. This PR introduces new comparators, `CLOSE_DISTANCE` and `FLOAT`, which can be used in cases where we can't achieve the exact value as originally set.

[reJest] Fixes problem with opacity comparation

---

packages/docs-reanimated/docs/layout-animations/layout-transitions.mdx

This PR includes changes for layout transitions imports in docs.
Since Transition import re-named to LinearTransition, docs needs to be changed as well

update layout transitions docs

---

packages/docs-reanimated/src/components/InteractivePlayground/useSpringPlayground/Example.tsx
packages/docs-reanimated/src/components/InteractivePlayground/useTimingPlayground/Example.tsx

Before on docs using `withSpring` and `withTiming` playgrounds (Customising animations, withSpring, withTiming):
After:
1. Run `yarn && yarn build && yarn serve`
2. Check `Customising animations`, `withSpring`, `withTiming` documentation pages (they are must, but full docs checkup is recommended)

fix: docs: Access before initialization on withSpring and withTiming

---

packages/docs-reanimated/docs/utilities/getRelativeCoords.mdx
packages/docs-reanimated/src/examples/RelativeCoords.tsx

To be up to date we rewritten [getRelativeCoords](https://docs.swmansion.com/react-native-reanimated/docs/utilities/getRelativeCoords/) and implemented InteractiveExample.
- [#6165](https://github.com/software-mansion/react-native-reanimated/pull/6165) - needs to be merged before - it bumped `react-native-reanimated` to latest where `getRelativeCoords` work
Before:
https://github.com/software-mansion/react-native-reanimated/assets/59940332/6372409d-6eb7-4d8c-b339-13ea8090b509
After:
https://github.com/software-mansion/react-native-reanimated/assets/59940332/a4335d87-0dc3-4dab-93da-86f7ffbb9ba0

docs: Rewrite getRelativeCoords documentation page

---

apps/common-app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/RuntimeTestsRunner.tsx
apps/common-app/src/examples/RuntimeTests/RuntimeTestsExample.tsx

- Lazy evaluation of imports; it was impossible to uncheck a test suite.
- More explicit UI; it was hard to tell what test suites were enabled.
- QoL information the user has to reload the app to re-run tests.
- Minor code readability improvements.
https://github.com/user-attachments/assets/2a3135ab-a3ce-4433-a8b1-eeb3cf3fde13

refactor: Improve UX of runtime tests menu

---

packages/react-native-reanimated/src/ReducedMotion.ts

Fixes #6269 
`prefers-reduced-motion` was introduced in Chromium 74: https://chromestatus.com/feature/5597964353404928
The code on `main` branch seems not to care about the case when there is no definition of `prefers-reduced-motion`.

[Web] Fix animations on Chromium 73 and older (#6269)

---

apps/common-app/src/examples/RuntimeTests/RuntimeTestsExample.tsx
apps/common-app/src/examples/RuntimeTests/tests/plugin/contextObjects.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/plugin/fileWorkletization.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/plugin/fileWorkletization.ts
packages/react-native-reanimated/__tests__/__snapshots__/plugin.test.ts.snap
packages/react-native-reanimated/__tests__/plugin.test.ts
packages/react-native-reanimated/plugin/build/plugin.js
packages/react-native-reanimated/plugin/src/contextObject.ts
packages/react-native-reanimated/plugin/src/file.ts
packages/react-native-reanimated/plugin/src/globals.ts
packages/react-native-reanimated/plugin/src/plugin.ts
packages/react-native-reanimated/src/shareables.ts

This pull request introduces the concept of _Context Objects_ on the Worklet Runtime.
Context Object is a shareable object that doesn't lose its `this` binding when it goes to the Worklet Runtime. To define an object as a Context Object, the user has to define property `__workletContextObject` on it. The value of this property doesn't matter.
```ts
// Explicit Context Object
const obj = {
foo() { return 1; },
bar() { return this.foo(); },
__workletContextObject: true,
}
```
Context Objects are also auto-detected when Babel processes files marked with a worklet directive. If a top level object has a method that references `this` inside we treat is as a Context Object.
```ts
'worklet';
// Implicit Context Object
const obj = {
foo() { return 1; },
bar() { return this.foo(); },
};
``` …

Workletizable Context Objects

---

apps/common-app/src/examples/RuntimeTests/ReanimatedRuntimeTestsRunner/RuntimeTestsRunner.tsx
apps/common-app/src/examples/RuntimeTests/tests/animations/withTiming/objects.test.tsx

The height of information "Reload the app to run the tests again" was causing broken tests on android. This height was included in results of `getViewProp("top")` including snapshots**BEFORE:**
**AFTER:**

Remove header to fix broken tests on android

---

apps/common-app/src/examples/RuntimeTests/tests/animations/withDecay/basic.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/animations/withSequence/callbackCascade.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/animations/withSpring/variousConfig.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/animations/withTiming/transformMatrices.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/core/useDerivedValue/basic.test.tsx

Prefer waitForAnimationUpdates over wait to make the animation faster and more reliable

Prefer `waitForAnimationUpdates` over `wait`

---

apps/common-app/src/examples/ReducedMotionExample.tsx

Previously, animations were defined in the global scope, so if they were run once, they couldn't be run again. I simply replaced static animations with a lambda that creates a new animation every time.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/21de2620-24f2-4d27-8e82-3217ddeab07e" /> | <video src="https://github.com/user-attachments/assets/ac178ce6-c6d5-4cc0-9029-43341b20b278" /> |
Run `ReducedMotion` example

Fix Reduced Motion example

---

packages/react-native-reanimated/src/Easing.ts
packages/react-native-reanimated/src/layoutReanimation/web/componentUtils.ts
packages/react-native-reanimated/src/layoutReanimation/web/config.ts

After #6163 was merged, each `worklet` function follows new naming convention. Since `easings` are `worklets`, their `name` property has also been changed. In web layout animations we were applying `easing` based on its name, therefore changing it resulted in only default `linear` easing being available on web.
This PR adds new `Symbol` into easing functions so that we can once again get their name and apply correct easing to animations.
Tested on _**BasicLayoutAnimation**_ example with `Easing.exp`

[Web LA] Fix `easing`

---

packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
packages/react-native-reanimated/src/layoutReanimation/web/animationsManager.ts
packages/react-native-reanimated/src/layoutReanimation/web/componentUtils.ts
packages/react-native-reanimated/src/layoutReanimation/web/transition/Curved.web.ts

While preparing presentation about web LA I've found out that `exiting` animation has strange order of operations - first animation is started and then position of the element is adjusted (by scroll and other factors). In theory, this may lead to flickers so I believe it will be better to start animation after we adjust position.
Tested on example app

[Web LA] Start `exiting` after position fix

---

packages/react-native-reanimated/src/layoutReanimation/animationsManager.ts
packages/react-native-reanimated/src/mutables.ts

Currently Web and Native implementations of `makeMutable` are bundled together and are hard to read. I split them for more clarity in the code, and also to prepare `makeMutable` for its further changes.

refactor: split makeMutable to web and native implementations

---

packages/react-native-reanimated/plugin/build/plugin.js
packages/react-native-reanimated/plugin/src/class.ts

Starting to sort polyfills after we transform a class into a class factory sometimes causes unwanted entries in the list of elements to sort. This fixes it.

fix: class factory included in sort

---

packages/docs-reanimated/src/components/InteractivePlayground/index.tsx

Range slider's thumb was not centered, we fixed that 🚀 
Before:
After:
Sliders are on playgrounds - i.e. `withSpring` or `withTiming`

fix: docs: Recenter slider thumb

---

packages/react-native-reanimated/__tests__/__snapshots__/plugin.test.ts.snap
packages/react-native-reanimated/__tests__/plugin.test.ts
packages/react-native-reanimated/plugin/build/plugin.js
packages/react-native-reanimated/plugin/src/file.ts

Since Reanimated Babel Plugin breaks hoisting and [newer Typescript hoists CommonJS exports by default](https://github.com/microsoft/TypeScript/pull/57669) we sometimes need to dehoist those exports.

feat: Move commonjs exports down for worklet files

---

packages/react-native-reanimated/src/Animated.ts
packages/react-native-reanimated/src/Easing.ts
packages/react-native-reanimated/src/UpdateProps.ts
packages/react-native-reanimated/src/animation/commonTypes.ts
packages/react-native-reanimated/src/animation/styleAnimation.ts
packages/react-native-reanimated/src/animation/timing.ts
packages/react-native-reanimated/src/animation/util.ts
packages/react-native-reanimated/src/commonTypes.ts
packages/react-native-reanimated/src/component/FlatList.tsx
packages/react-native-reanimated/src/helperTypes.ts
packages/react-native-reanimated/src/hook/commonTypes.ts
packages/react-native-reanimated/src/hook/useAnimatedStyle.ts
packages/react-native-reanimated/src/index.ts
packages/react-native-reanimated/src/js-reanimated/index.ts
packages/react-native-reanimated/src/layoutReanimation/animationBuilder/ComplexAnimationBuilder.ts
packages/react-native-reanimated/src/layoutReanimation/animationBuilder/Keyframe.ts
packages/react-native-reanimated/src/layoutReanimation/animationBuilder/commonTypes.ts
packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/CurvedTransition.ts
packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/EntryExitTransition.ts

As a preparation for `react-native-worklets` we need to untangle our code a bit and follow dependency inversion more thoroughly.

refactor: Untangle types file dependencies

---

apps/common-app/src/examples/LayoutAnimations/ListItemLayoutAnimation.tsx
packages/docs-reanimated/docs/layout-animations/list-layout-animations.mdx

This PR adds information about `keyExtractor` to the **Remarks** section in the documentation. 
I decided to add this remark after seeing [this](https://github.com/software-mansion/react-native-reanimated/discussions/6322) discussion in which the `itemLayoutAnimation` takes no effect.

docs: Add keyExtractor remark to itemLayoutAnimation documentation

---

packages/react-native-reanimated/src/hook/useFrameCallback.ts

https://github.com/software-mansion/react-native-reanimated/pull/6143 was supposed to improve cleanup of `useFrameCallback` but also deleted a needed line - setting `callbackId` of callback registry to -1. Seems like some code is dependent on this value and it caused some crashes such as this one: https://github.com/software-mansion/react-native-reanimated/pull/6143. I haven't found a reliable way to reproduce the issue since we got the info from issue creator's sentry. Nonetheless, analysis of the code has shown that we need to set the `callbackId` to -1 on cleanup, otherwise we perform operations that shouldn't be done anymore (e.g there's this check: https://github.com/software-mansion/react-native-reanimated/blob/818ed78870bf41b6255abdd16b153444761101b2/packages/react-native-reanimated …

Bring back useFrameCallback cleanup

---

apps/common-app/src/examples/RuntimeTests/ReJest/TestRunner/UpdatesContainer.ts
apps/common-app/src/examples/RuntimeTests/ReJest/matchers/Matchers.ts
apps/common-app/src/examples/RuntimeTests/ReJest/matchers/snapshotMatchers.ts

Unify code for snapshot comparison on Android and IOS.
Also a lot of outdated code was cleaned out, as we have decided not to return snapshots of multiple views, but always for a certain predefined one.

Unify snapshots comparison

---

apps/common-app/src/examples/RuntimeTests/ReJest/TestRunner/TestRunner.ts
apps/common-app/src/examples/RuntimeTests/ReJest/TestRunner/TestSummaryLogger.ts
apps/common-app/src/examples/RuntimeTests/ReJest/types.ts

This is a part of a plan to clean up TestRunner. Logging and managing the summary was the easiest functionality for extracting

Extract summary & logging from TestRunner.

---

apps/common-app/src/examples/RuntimeTests/ReJest/TestRunner/TestRunner.ts
apps/common-app/src/examples/RuntimeTests/ReJest/utils/SyncUIRunner.ts

Since the very beginning of testing framework we had the following bug - if a given test doesn't include any render then the tests freeze. After debugging I've found that we should have initiated `_wasRenderedNull` with the opposite value:
```diff
- private _wasRenderedNull: boolean = false;
+ private _wasRenderedNull: boolean = true;
```

Bugfix - don't require render in every test

---

packages/docs-reanimated/docs/utilities/interpolateColor.mdx

To be up to date we rewritten [interpolateColor](https://docs.swmansion.com/react-native-reanimated/docs/utilities/interpolateColor/).
https://github.com/user-attachments/assets/7014c81e-252d-4557-9eb8-5b145cc2c701

docs: Rewrite interpolateColor page

---

apps/common-app/package.json
apps/common-app/src/examples/AnimatedTabBarExample.tsx
apps/common-app/src/examples/LayoutAnimations/HabitsExample.tsx
yarn.lock

I noticed that `@fontawesome` dependency is present in the repository but is used in 2 demo screens only - the size of unpacked dependencies are following:
- `@fortawesome/fontawesome-svg-core`: 397 kB
- `@fortawesome/free-solid-svg-icons`: 5.09 MB
- `@fortawesome/react-native-fontawesome`: 33.4 kB
I believe that plain text emojis (which are present on eg. examples list) could be used instead of fontawesome icons.
Open `Tab bar` and `Habits` example from the example app

Remove fontawesome dependency from example app

---

.husky/pre-commit

chore: Add verbosity to precommit

---

apps/common-app/src/examples/RuntimeTests/ReJest/RuntimeTestsApi.ts
apps/common-app/src/examples/RuntimeTests/ReJest/TestRunner/TestRunner.ts
apps/common-app/src/examples/RuntimeTests/ReJest/matchers/Matchers.ts
apps/common-app/src/examples/RuntimeTests/ReJest/matchers/rawMatchers.ts
apps/common-app/src/examples/RuntimeTests/ReJest/types.ts
apps/common-app/src/examples/RuntimeTests/ReJest/utils/stringFormatUtils.ts
apps/common-app/src/examples/RuntimeTests/tests/TestsOfTestingFramework.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/utilities/relativeCoords.test.tsx

Change the way to verify that a certain value is nullable to match the existing API.
Actually jest exposes two separate functions:
* `expect(x).toBeNull()`
* `expect(x).toBeUndefined()`
So I had some doubts about having `expect(x).toBeNullable()` instead, but I've decided to keep the existing version.

Unify nullable comparison

---

packages/docs-reanimated/docs/fundamentals/getting-started.mdx

This PR adds a hint to the installation guide to rerun prebuild whenever someone is installing Reanimated in a Expo development client project.

docs: add info about prebuild to installation steps

---

packages/docs-reanimated/docs/reanimated-babel-plugin/options.md

After the change to monorepo link leads to 404

docs: fix broken link in reanimated babel plugin docs

---

packages/docs-reanimated/docs/advanced/useHandler.mdx

To be up to date we rewritten [useHandler](https://docs.swmansion.com/react-native-reanimated/docs/advanced/useHandler/).

docs: Rewrite useHandler page

---

packages/docs-reanimated/blog/bottom-sheet.md
packages/docs-reanimated/blog/marquee.md

Reanimated Cookbook has a pure didactical purpose. While we provide the full code some of the developers might think that they have to reimplement the components every time.
In the ecosystem there are ready-to-use convenient packages that the developers could use out of the box to solve their problems
This PR adds two recommendations about the Bottom Sheet and Marquee example.

docs: add disclaimer about ready-to-use packages in Reanimated Cookbook

---

packages/react-native-reanimated/src/js-reanimated/JSReanimated.ts

PR restoring proper types for `Navigator`.
When this code would be removed, VSCode takes me to definitions from TS, which show it the same way:

fix: proper types for userAgent and vendor

---

packages/react-native-reanimated/android/build.gradle

This PR fixes existing prefab integration and extends it for `libworklets.so` along with its header files.
I have personally tested out these changes in react-native-live-markdown.

Expose `worklets` as prefab

---

packages/react-native-reanimated/Common/cpp/worklets/SharedItems/Shareables.cpp

Regarding this [issue](https://github.com/software-mansion/react-native-reanimated/issues/6220) the PR solves it by creating a jsi key string from utf8.
Fixes #6220.
Tested on demo provided in issue mentioned above.

Fix handling UTF-8 object keys

---

packages/docs-reanimated/src/examples/MakeMutable.tsx

I used `useColorScheme` hook from `react-native` instead of the one from the `@mui/material` library, which returned `'dark'` color scheme name irrespective of the actual selected theme.
This PR changes the hook to the correct one which fixes the text color in the light mode.
|-|-|
| ![Screenshot 2024-08-05 at 18 18 19](https://github.com/user-attachments/assets/0d17a4ab-84e5-4b93-beba-2731e2e1e4d1) | ![Screenshot 2024-08-05 at 18 16 25](https://github.com/user-attachments/assets/11be3467-123d-40c8-ba21-ac06c2a6c3df) |
Works fine, as before.
|-|-|
| ![Screenshot 2024-08-05 at 18 17 42](https://github.com/user-attachments/assets/88995ff6-ab2f-4a98-a490-45e746dbbfcf) | ![Screenshot 2024-08-05 at 18 17 …

fix: Light mode colors in the make mutable example in docs

---

apps/common-app/src/examples/PendulumExample.tsx

(cherry picked from commit 21967b1b0d3dc7e5e0d53b08a7436069e8dd3726)
Inputting empty string into the mass field would crash the app on android.
This PR fixes this issue.
- open `Pendulum` example
- switch to `non-duration based config`
- delete all data from the `mass` input field

Fix pendulum example to not crash on empty mass input field

---

apps/next-example/babel.config.js
apps/next-example/next.config.js
apps/next-example/package.json
apps/web-example/package.json
yarn.lock

It doesn't work anymroe due to some nodes paths.

Fix next js build CI

---

packages/docs-reanimated/docs/advanced/useHandler.mdx
packages/docs-reanimated/src/examples/UseHandlerEventExample.tsx

Few copy changes and added an example to [useHandler](https://docs.swmansion.com/react-native-reanimated/docs/advanced/useHandler/) docs.

docs: Add example to useHandler docs

---

packages/docs-reanimated/docs/advanced/useHandler.mdx

This PR fixes docs building by changing name of imported file to uppercase.

fix: Change import to uppercase

---

packages/docs-reanimated/docs/scroll/useAnimatedScrollHandler.mdx
packages/docs-reanimated/src/examples/AnimatedScrollHandler.tsx

Before:
https://github.com/user-attachments/assets/52ada01c-be98-4fa7-be53-0dcd088b380d
After:
https://github.com/user-attachments/assets/484b618d-1b03-4c5d-b18e-babce4f701d3

docs: Rewrite useAnimatedScrollHandler page

---

packages/docs-reanimated/docs/advanced/useEvent.mdx
packages/docs-reanimated/src/examples/UseHandlerEventExample.tsx

To be up to date we rewritten [useEvent](https://docs.swmansion.com/react-native-reanimated/docs/advanced/useEvent/).

dosc: Rewrite useEvent page

---

packages/react-native-reanimated/src/component/LayoutAnimationConfig.tsx
packages/react-native-reanimated/src/createAnimatedComponent/JSPropsUpdater.ts
packages/react-native-reanimated/src/createAnimatedComponent/NativeEventsManager.ts
packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
packages/react-native-reanimated/src/hook/useAnimatedRef.ts
packages/react-native-reanimated/src/platformFunctions/findNodeHandle.ts
packages/react-native-reanimated/src/platformFunctions/findNodeHandle.web.ts

In many places we use `findNodeHandle` function to get native view that is represented by React component. The problem is that usage of this function on `web` leads to warnings (which are shown via `console.error`), that this function in deprecated and should not be used.
I've already done 3 PRs that remove usage of `findNodeHandle` on `web`, but it keeps reappearing. That's why I've decided to create our version of this function. On native platforms it is just export from `react-native`. On `web` it returns component that is passed into the function.
>[!CAUTION]
>Note that `findNodeHandle`(or to be exact, `findDOMNode`) will be [removed in next major version of React](https://react.dev/reference/react-dom/findDOMNode) (i.e. React 19)
Verifed on our web-example that it uses web version of …

[Web] Add `findNodeHandle` web version

---

.github/workflows/reanimated-compatibility-check-nightly.yml
README.md

Currently we don't really check the compatibility we declared in our compatibility table. This pull requests adds a GitHub action that will check it nightly.
🚀

feat: Add Reanimated compatibility GitHub action

---

.github/workflows/babel-plugin-static-check.yml
.github/workflows/docs-reanimated-build-check.yml
.github/workflows/docs-reanimated-publish.yml
.github/workflows/example-android-build-check.yml
.github/workflows/example-ios-build-check.yml
.github/workflows/example-macos-build-check.yml
.github/workflows/example-next-build-check-and-test.yml
.github/workflows/example-tvos-build-check.yml
.github/workflows/expo-devclient-build-check-nightly.yml
.github/workflows/monorepo-app-reanimated-build-check-nightly.yml
.github/workflows/react-native-nightly-reanimated-build-check-nightly.yml
.github/workflows/reanimated-android-validation.yml
.github/workflows/reanimated-apple-validation.yml
.github/workflows/reanimated-common-validation.yml
.github/workflows/reanimated-typescript-compatibility-test-nightly.yml
.github/workflows/static-framework-reanimated-build-check-nightly.yml
.github/workflows/url-validation-nightly.yml
.github/workflows/windows-hosted-app-reanimated-build-check-nightly.yml
.github/workflows/yarn-validation.yml

1. **Fix paths**
- Workflow files have been renamed, but the paths inside the workflows weren't updated
- Due to this mismatch the workflow is not triggered once it is edited
4. **Fix caching**
- Remove caching when building apps (it wasn't working well)
There are failing tests, but their fail in not depending on this PR

Fix github workflows

---

.yarn/patches/react-native-pager-view-npm-6.3.3-7b62f58674.patch
yarn.lock

Our patch to `react-native-pager-view` for `RN 0.75-rc.6` works, but seems like it isn't the best way to do that, as stated [here](https://github.com/callstack/react-native-pager-view/issues/850#issuecomment-2275240214). In short, removing the `override` keyword will cause tab bar navigation crashes. Instead, I adjusted the functions' signature, so that they actually override something.
Try building android examples

Update RN pager view patch file

---

packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx

This PR adds partial support for `LayoutAnimationConfig`, i.e. `skipEntering`. 
>[!NOTE]
>`skipExiting` is not added in this PR as waiting for children animation is not yet supported on `web`.
<details>
<summary>Tested on example from docs:</summary>
```tsx
LayoutAnimationConfig,
PinwheelIn,
PinwheelOut,
const [outer, setOuter] = React.useState<boolean>(true);
const [inner, setInner] = React.useState<boolean>(true);
return (
<View style={styles.buttonColumn}>
<Button
onPress={() => {
setOuter(!outer);
}}
title={toggleString(outer) + ' outer'}
/>
<Button
disabled={!outer}
onPress={() => { …
```

[Web LA] Add `skipEntering` 

---

packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx

The problem was reported in [this](https://github.com/software-mansion/react-native-reanimated/issues/6432) issue and [this](https://github.com/software-mansion/react-native-reanimated/discussions/6359) discussion seems to report the same problem.
In short, the crash was caused by incorrect check in `_getViewInfo` in `createAnimatedComponent` which assigned the `_component` to the `viewTag` only for web but not for chrome debugger. I replaced `IS_WEB` check with `shouldBeUseWeb`, which also checks whether the current environment is a chrome debugger.
- I created a bare app with `npx @react-native-community/cli init ReactNativeDebugger --version 0.75.1`
- Installed latest reanimated and downloaded [react-native-debugger](https://github.com/jhen0409/react-native-debugger?tab=readme-ov-file) …

fix: Chrome debugger crash caused by incorrect viewTag

---

packages/docs-reanimated/docs/advanced/setNativeProps.mdx
packages/docs-reanimated/docs/animations/withClamp.mdx
packages/docs-reanimated/docs/animations/withDelay.mdx
packages/docs-reanimated/docs/animations/withRepeat.mdx
packages/docs-reanimated/docs/animations/withSequence.mdx
packages/docs-reanimated/docs/animations/withSpring.mdx
packages/docs-reanimated/docs/animations/withTiming.mdx
packages/docs-reanimated/docs/fundamentals/glossary.mdx
packages/docs-reanimated/docs/layout-animations/custom-animations.mdx
packages/docs-reanimated/versioned_docs/version-2.x/fundamentals/shared-values.md

Some links were missing the `/` at the beginning, thus, they were appended to the current page link instead of replacing it. As a result, the **Page Not Found** page was displayed instead of navigating to the desired page in docs.
Just open reanimated docs and press on links that were changed in this PR. You will see that before these changes, links do not navigate to the desired page in docs.

docs: Fix incorrect links in docs

---

packages/react-native-reanimated/apple/reanimated/REASlowAnimations.h

This PR adds missing import for the header file. 
This was breaking visionOS builds. 
The `CFTimeInterval` comes from Core Foundation so we need to have foundation imported to make this work. 
CI Green

fix: add missing include

---

apps/common-app/src/examples/RuntimeTests/RuntimeTestsExample.tsx
apps/common-app/src/examples/RuntimeTests/tests/advancedAPI/measure.test.tsx
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NativeMethodsHelper.java

Implement measurement of relative coordinates on Android.
I've added more logic to runtime tests to include parent component changes in calculations.
<details><summary> Example code to log measurement </summary>
```tsx
import type { MeasuredDimensions } from 'react-native-reanimated';
measure,
runOnUI,
const EXPECTED_MEASUREMENT = {
height: 100,
pageX: 302,
width: 80,
x: 120,
y: 150,
};
const animatedRef = useAnimatedRef<Animated.View>();
const measurement = useSharedValue<MeasuredDimensions | null>(null);
const handlePress = () => {
'worklet';
measurement.value = …
```

Implement missing measurements on android

---

apps/common-app/src/examples/InvalidValueAccessExample.tsx
apps/common-app/src/examples/index.ts
packages/react-native-reanimated/src/mutables.ts
packages/react-native-reanimated/src/reactUtils.ts

This PR adds warnings shown when the SharedValue `.value` property is accessed (read or written) while the component is being rendered.
The initial render is ignored as all reanimated hooks are executed for the first time during the initial render (e.g. `useAnimatedStyle` builds the initial component style).
- open the **Invalid read/write during render** example in the example app,
- press on the **Re-render** button to trigger re-render, which will access `.value` property of the shared value from the component function body,
- see warnings about invalid read and invalid write

Add mutable value read/write during render warning

---

packages/docs-reanimated/src/css/overrides.css

docs: Styling for mobile Platform Compatibility

---

packages/react-native-reanimated/metro-config/tsconfig.json
packages/react-native-reanimated/tsconfig.json

Including both `src` and `metro-config` in `tsconfig.json` of Reanimated package sometimes falsely suggests TypeScript that there should be `lib/module/src` and `lib/module/metro-config` directories.
🚀

chore: Add separate tsconfig for metro-config

---

apps/fabric-example/android/app/build.gradle
apps/paper-example/android/app/build.gradle

It turns out that after
- #6488
The location of `@react-native/codegen` in our monorepo changed and examples had trouble building.

chore: Fix codegen dir in examples

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp

`-Wall` and `-Werror` in NDK 27 make deprecation warnings fail the compilation process. NDK 27 isn't yet used in React Native, therefore this is more of a feature than a fix.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/6466

chore: Fix deprecated `this` captures in lambdas for NDK 27

---

packages/docs-reanimated/docs/core/useDerivedValue.mdx
packages/docs-reanimated/prettier.config.js
packages/docs-reanimated/versioned_docs/version-2.x/tutorials/LayoutAnimations/animated_list.mdx
packages/docs-reanimated/yarn.lock

After bumping Prettier in the monorepo docs should have it bumped too since they inherit `prettier.config.js`.
Fixes CI failing in:
- #6467 
- #6468

chore: Bump prettier in docs

---

packages/react-native-reanimated/src/mock.ts

Fixes https://github.com/software-mansion/react-native-reanimated/issues/6335
This PR adds mock for `useEvent`

Add useEvent mock

---

packages/docs-reanimated/docs/device/useAnimatedKeyboard.mdx
packages/docs-reanimated/versioned_docs/version-2.x/api/hooks/useAnimatedKeyboard.md
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModuleSpec.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModuleSpec.h
packages/react-native-reanimated/Common/cpp/reanimated/Tools/PlatformDepMethodsHolder.h
packages/react-native-reanimated/android/src/main/cpp/reanimated/NativeProxy.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/NativeProxy.h
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/keyboard/Keyboard.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/keyboard/KeyboardAnimationCallback.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/keyboard/KeyboardAnimationManager.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/keyboard/WindowsInsetsManager.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nativeProxy/NativeProxyCommon.java
packages/react-native-reanimated/apple/reanimated/native/PlatformDepMethodsHolderImpl.mm
packages/react-native-reanimated/src/NativeReanimated/NativeReanimated.ts
packages/react-native-reanimated/src/commonTypes.ts
packages/react-native-reanimated/src/core.ts
packages/react-native-reanimated/src/hook/useAnimatedKeyboard.ts

Resolves #6043. For StatusBar we have a flag that removes top padding when we want to render RN stuff "under" StatusBar. A similar problem was raised in  #6043, but for NavigationBar, so I added another flag `isNavigationBarTranslucentAndroid` that removes bottom padding as well. Currently, I see no way to make it automatic. I tried one approach to remove the flags in #5889, but it doesn't seem to be the performant solution. 
|Before|After without flag|After with flag|
|-|-|-|
|<img width="602" alt="before" src="https://github.com/user-attachments/assets/0032efbe-342a-4e06-81ee-f7351bb032f7">|<img width="602" alt="after-without-flag" src="https://github.com/user-attachments/assets/6f259329-9bf4-4bbb-8ce4-32d671e65a5a">|<img width="602" alt="after-with-flag" …

feat: add support for isNavigationBarTranslucentAndroid

---

packages/docs-reanimated/package.json
packages/docs-reanimated/yarn.lock

With @swmansion/t-rex-ui update, we can now use [`unreleased`](https://github.com/software-mansion-labs/t-rex-ui/pull/25) and [`deprecated`](https://github.com/software-mansion-labs/t-rex-ui/pull/23) label

docs: Bump `@swmansion/t-rex-ui` to 0.0.14

---

packages/docs-reanimated/docs/guides/web-support.mdx

Not a lot of changes, mostly some stylistic ones, because after consultations everything was up to date.
https://github.com/user-attachments/assets/aa5dd2bb-2ddd-4cc1-9fae-f77a19691cd1

docs: Rewrite Web Support page

---

packages/docs-reanimated/docs/guides/testing-with-jest.mdx
packages/docs-reanimated/src/examples/TestExample.tsx

To be up to date we've rewritten [Testing with Jest](https://docs.swmansion.com/react-native-reanimated/docs/guides/testing/), mostly stylistic changes were made due to not updating Jest integration for a long time.
https://github.com/user-attachments/assets/f29ca612-375b-4fc8-920a-2f900d5a2e2b

docs: Rewrite Testing with Jest page

---

packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp

When an exiting animation is finished, we mark some views for removal. Then we trigger `pullTransaction` to apply those removals. However, it might happen that RN also tries to perform some transaction at the same time. In the algorithm responsible for triggering exiting animations, if we encounter a view marked for removal, we handle it right there by calling `endAnimationsRecursively`. However, we also have to add this view to the `toBeRemoved` list. Otherwise its neighbors will have incorrect indices, and when one of them is removed the app will crash. 
Test `[LA] View Flattening` example with:
```js
setInterval(() => {
setVisible((prev) => !prev);
}, 0);
}, []);
```

Fix wrong exiting animation indices [New Architecture]

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReaLayoutAnimator.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java

This PR moves class `ReaLayoutAnimator` from `ReanimatedNativeHierarchyManager.java` to its own file `ReaLayoutAnimator.java`. That's because the signature of one of the methods in `ReanimatedNativeHierarchyManager` was changed in RN 0.76 and we'll need to create a sourceset for this very class. I also added `@Override` annotation to ensure we're overriding this method.

Move `ReaLayoutAnimator` to a separate file

---

.github/workflows/V8-reanimated-build-check-nightly.yml

Now V8 supports react native 0.75 so we can turn on our CI 🎉 
Check CI ✅

Enable V8 nightly CI

---

packages/react-native-reanimated/android/empty.cpp

This PR removes `empty.cpp` as it is no longer needed.
There are no current usages of `empty.cpp` in our codebase.
It all started here:
https://github.com/software-mansion/react-native-reanimated/blob/dea5cc2c713724ee1705daea62d18733c4ce4127/android/CMakeLists.txt#L317-L325

Remove empty.cpp

---

packages/react-native-reanimated/android/src/paper/java/com/swmansion/reanimated/NativeProxy.java
packages/react-native-reanimated/android/src/reactNativeVersionPatch/RuntimeExecutor/73/com/swmansion/reanimated/NativeProxy.java
packages/react-native-reanimated/android/src/reactNativeVersionPatch/RuntimeExecutor/74/com/swmansion/reanimated/NativeProxy.java
packages/react-native-reanimated/android/src/reactNativeVersionPatch/RuntimeExecutor/latest/com/swmansion/reanimated/NativeProxy.java

refactor: Obtain JsCallInvoker directly from context

---

packages/react-native-reanimated/android/build.gradle

This PR merges `packagingOptions` in build.gradle. There's no need to have two separate blocks.

Merge `packagingOptions` in build.gradle

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp

Turns out preliminary support for NDK27 in
- #6495
broke support for NDK23. This PR brings back support for NDK23 which is used in React Native 0.72.
Fixes
- #6512

fix: Restore backwards C++ compatibility for NDK23

---

packages/docs-reanimated/src/components/InteractivePlayground/useEnteringExitingAnimationPlayground/index.tsx
packages/react-native-reanimated/src/index.ts

If docs need to extract internal types like this we better just export them publicly.
Fixes CI on:
- #6556
- #6557
🚀

feat: Expose BaseLayoutAnimationConfig

---

packages/react-native-reanimated/android/build.gradle

This PR removes unused function `resolveTaskFactory` in build.gradle.

Remove `resolveTaskFactory` in build.gradle

---

packages/react-native-reanimated/src/Colors.ts

This PR will significantly enhance the developer experience when animating SVGs, as with these changes, the `SVGAdapter` is no longer required (at least for animating **colors**). It's related to the following PR: https://github.com/software-mansion/react-native-svg/pull/2471
At this point, the changes will not impact the current behavior and need to be tested within the `react-native-svg` repository until the release. Once the RNSVG release is out, I will add an example to the Reanimated repository.

Add SVG color properties to list of color attributes to parse

---

packages/react-native-reanimated/src/Colors.ts

Add support for animating the `outlineColor` prop, introduced in `react-native` via https://github.com/facebook/react-native/pull/46284, by including it in the ColorProperties list.

Add `outlineColor` to ColorProperties list

---

packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.h

Since RN 0.76 the first surface is created after our `initializeTurboModule` method is called on iOS. This change is probably a result of [this PR](https://github.com/facebook/react-native/commit/a778979ed604d1dc7707faf4a3836e3deba136c6#diff-ebba7a8b74cc36d5a03437c3999863076246c6c4eb5559fd1a58719b720fd755). This breaks our initialization of `layoutAnimationsProxy_`, so now we lazy initialize it for every surface in the Commit hook.
Check if layout animations work in the `fabric-example` app.

Lazy initalize layout aniamtions in the Commit Hook

---

.github/workflows/reanimated-android-validation.yml
.github/workflows/reanimated-common-validation.yml

This PR bumps the python version in validation CI, so the `:=` operator used by `cpplint 2.0.0` is properly supported.
Also we temporarily freeze the `cpplint` version to 1.6.1 due to https://github.com/cpplint/cpplint/issues/293

Bump python version and freeze cpplint

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp

There was a small typo in #6553 which caused building with c++17 to still fail.
Build works again with RN 0.72 which uses c++17.
- Fixes https://github.com/software-mansion/react-native-reanimated/issues/6512#issuecomment-2407118212
- Fixes #6584

fix: build error with c++17

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp
packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/platform-specific/jsVersion.ts

Picking:
- #6590
I picked GitHub Actions from main to this branch from main so CIs would actually run on this pull request. Some of them are expected to fail (like cpp linting), since they got changed but these changes weren't picked into this branch.

release: 3.15.5

---

packages/react-native-reanimated/src/layoutReanimation/animationBuilder/Keyframe.ts

Replace `parseInt` with `Number`, as the second function correctly handles empty string and undefined.
```
Number(null) = 0
Number('') = 0
parseInt(null) = NaN
```

Use `Number` instead of `parseInt`

---

apps/fabric-example/ios/Podfile.lock
apps/macos-example/macos/Podfile.lock
apps/paper-example/ios/Podfile.lock
apps/tvos-example/ios/Podfile.lock
packages/docs-reanimated/docs/guides/compatibility.mdx
packages/react-native-reanimated/package.json
packages/react-native-reanimated/scripts/set-reanimated-version.js
packages/react-native-reanimated/src/layoutReanimation/animationBuilder/Keyframe.ts
packages/react-native-reanimated/src/platform-specific/jsVersion.ts

This PR bumps the Reanimated version to 3.16.0 and updates the compatibility table (there is also a minor Keyframe fix). This PR doesn't follow the usual release PR scheme, as we want to change the way we do releases. Now the `next` reanimated version will be used on main and release package will be made from a separate branch.

Bump reanimated version to 3.16.0

---

packages/react-native-reanimated/apple/reanimated/LayoutReanimation/REASnapshot.m

Previously we were passing a window to function convertPoint, that accepts only view. It was causing a crash, therefore we should pass the contentView of the window.
Tested on several examples:
* Olympic example
* [LA] Basic Layout Animation
* [LA] Entering and Exiting with Layout 
* [LA] Carousel

Fix crash on macos when using Layout Animations

---

packages/react-native-reanimated/scripts/reanimated_utils.rb

This PR removes `config[:reanimated_node_modules_dir]` because it looks like it's unused (at least I hope so).
Apart from this, the value is incorrect (it's `/Users/tomekzaw/RNOS/react-native-reanimated/packages` on my setup but should be `/Users/tomekzaw/RNOS/react-native-reanimated/packages/react-native-reanimated`).

Remove `config[:reanimated_node_modules_dir]` in reanimated_utils.rb

---

apps/next-example/pages/_app.js
apps/next-example/pages/index.js
apps/next-example/pages/noreanimated.js
apps/next-example/pages/reanimated.js
apps/next-example/pages/ssg.js
apps/next-example/pages/ssr.js
apps/next-example/pages/test.js

Linter wants JSDoc types but it's not worth to add them IMO

chore: Silence next-example linter warnings

---

apps/fabric-example/common-app
apps/fabric-example/package.json
apps/paper-example/common-app
apps/paper-example/package.json

Similar to https://github.com/software-mansion/react-native-svg/pull/2512, it fixes resolving local images on Android by creating a symlink to the common directory, allowing images to be resolved without the `../` segment.
Run example app on Android and add
```tsx
<Image source={require('./assets/doge.png')} />
```
in `EmptyExample.tsx`

fix: create symlink to common-app

---

.github/workflows/V8-reanimated-build-check-nightly.yml
.github/workflows/react-native-nightly-reanimated-build-check-nightly.yml
.github/workflows/reanimated-compatibility-check-nightly.yml
.github/workflows/static-framework-reanimated-build-check-nightly.yml
.github/workflows/windows-hosted-app-reanimated-build-check-nightly.yml

Turns out installing from commit didn't work well and CI often times didn't check what it was supposed to test.
Failing V8 CI is good now, since it fails on actual compilation steps.
🚀

fix: Installation of Reanimated from commit on CI

---

packages/react-native-reanimated/createNPMPackage.sh
packages/react-native-reanimated/scripts/set-reanimated-version.js

I accidentally set the return value from 0 to 1 [here](https://github.com/software-mansion/react-native-reanimated/pull/6557/files/1aa3df2b0b458564ba5cfc2f04e67b803a2ee862#diff-15a6e10b865e98436e358bd843ebe5291db5141758f6dbffaecd6f009b5daee6L38) which in turn makes `createNPMPackage.sh` not pack the package when called without parameters.
🚀

fix: Return value of set-reanimated-version.js script

---

packages/react-native-reanimated/src/UpdateProps.ts

Some view props, like colors are processed on JS level, so we process it in updateProps function:
https://github.com/software-mansion/react-native-reanimated/blob/f03ab1465b8347a0c56ad05a23173b3ac079a9c5/packages/react-native-reanimated/src/UpdateProps.ts#L34
However we don't implement our copy of [processTransformOrigin](https://github.com/facebook/react-native/blob/6aeca53b3ed4530e57a31d7a5593ae16b550b985/packages/react-native/Libraries/StyleSheet/processTransformOrigin.js#L19) and passing transformOrigin in a form of string crashes the app with a confusing error "Exception in HostFunction: <unknown>, js engine: reanimated"
Yet, if transformOrigin is provided as an array of 3 numbers (just as you would get after calling processTransformOrigin on it) everything works fine, so I've added …

Add warning when passing incorrect transformOrigin

---

packages/react-native-reanimated/src/ReanimatedModule/NativeReanimated.ts
packages/react-native-reanimated/src/ReanimatedModule/index.ts
packages/react-native-reanimated/src/ReanimatedModule/js-reanimated/JSReanimated.ts
packages/react-native-reanimated/src/ReanimatedModule/reanimatedModuleInstance.ts
packages/react-native-reanimated/src/ReanimatedModule/reanimatedModuleInstance.web.ts
packages/react-native-reanimated/src/ReanimatedModule/reanimatedModuleProxy.ts
packages/react-native-reanimated/src/commonTypes.ts
packages/react-native-reanimated/src/privateGlobals.d.ts
packages/react-native-reanimated/src/worklets/WorkletsModule/JSWorklets.ts
packages/react-native-reanimated/src/worklets/WorkletsModule/NativeWorklets.ts
packages/react-native-reanimated/src/worklets/WorkletsModule/index.ts
packages/react-native-reanimated/src/worklets/WorkletsModule/workletsModuleInstance.ts
packages/react-native-reanimated/src/worklets/WorkletsModule/workletsModuleInstance.web.ts
packages/react-native-reanimated/src/worklets/index.ts

Preparing for #6539 
This PR has no real runtime impact

chore: Add noop typescript worklets module

---

packages/docs-reanimated/docusaurus.config.js

This PR introduces persistance between system color theme and user selected color theme.
Before:
https://github.com/user-attachments/assets/94a00142-b3fd-4b5e-8e29-f1bdb69363d7
After:
https://github.com/user-attachments/assets/b36cb663-b322-4eff-a507-6f6d8a3264cc

docs: Manage system color scheme changes

---

packages/docs-reanimated/src/components/Hero/StartScreen/index.tsx
packages/docs-reanimated/src/components/Hero/StartScreen/styles.module.css

The current `Beyond the limitations` slogan on landing, altho very marketingy, isn't at all descriptive about what Reanimated actually does. 
This PR changes the message to `Create smooth animations with an excellent developer experience.` which better describes what we do here.
Requested by @tomekzaw about two years ago 🙃 
```sh
cd packages/docs-reanimated
yarn
yarn start
```

docs: update landing copy

---

apps/common-app/src/examples/RuntimeTests/RuntimeTestsExample.tsx
apps/common-app/src/examples/RuntimeTests/tests/animations/withTiming/basic.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/core/useDerivedValue/basic.test.tsx
apps/common-app/src/examples/RuntimeTests/tests/core/useSharedValue/animationsCompilerApi.test.tsx
apps/common-app/src/examples/SharedElementTransitions/LayoutAnimation.tsx
packages/react-native-reanimated/src/animation/util.ts
packages/react-native-reanimated/src/mutables.ts

When I added compiler-safe API for shared values, I accidentally forgot that animations exist and that their assignment to shared values has to be handled separately.
Fixes
- #6613
Added relevant runtime test suite and adjusted some others.

fix: Animation assignment with compiler-safe API

---

packages/docs-reanimated/docs/guides/worklets.mdx
packages/docs-reanimated/docs/threading/runOnUI.mdx

This PR explains the worklet behaviour on the Web and separates the [Worklets guide](https://docs.swmansion.com/react-native-reanimated/docs/guides/worklets) into easier to reference and scan sections.

docs: worklets on the Web are just JavaScript functions

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.h
packages/react-native-reanimated/Common/cpp/worklets/NativeModules/NativeWorkletsModule.h
packages/react-native-reanimated/Common/cpp/worklets/Tools/SingleInstanceChecker.h
packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm
packages/react-native-reanimated/apple/worklets/apple/WorkletsModule.mm

Moving `SingleInstanceChecker` to Worklets and applying it there.
🚀

chore(Worklets): SingleInstanceChecker

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedPackage.java

Replace the deprecated `TurboReactPackage` with the newer `BaseReactPackage` to improve compatibility with future React Native releases. Note that this change requires at least react-native@0.74+, but this should not be an issue as, according to the compatibility table, Reanimated@3.17.0 only supports versions 0.74 and above.
Similar change has been introduced in the SVG package https://github.com/software-mansion/react-native-svg/pull/2541
CI should pass

Update ReanimatedPackage to supported stable API

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModuleSpec.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModuleSpec.h
packages/react-native-reanimated/Common/cpp/worklets/NativeModules/NativeWorkletsModule.cpp
packages/react-native-reanimated/Common/cpp/worklets/NativeModules/NativeWorkletsModule.h
packages/react-native-reanimated/Common/cpp/worklets/NativeModules/NativeWorkletsModuleSpec.cpp
packages/react-native-reanimated/Common/cpp/worklets/NativeModules/NativeWorkletsModuleSpec.h
packages/react-native-reanimated/src/ReanimatedModule/NativeReanimated.ts
packages/react-native-reanimated/src/ReanimatedModule/js-reanimated/JSReanimated.ts
packages/react-native-reanimated/src/ReanimatedModule/reanimatedModuleProxy.ts
packages/react-native-reanimated/src/commonTypes.ts
packages/react-native-reanimated/src/shareables.ts
packages/react-native-reanimated/src/worklets/WorkletsModule/JSWorklets.ts
packages/react-native-reanimated/src/worklets/WorkletsModule/NativeWorklets.ts
packages/react-native-reanimated/src/worklets/WorkletsModule/workletsModuleProxy.ts

Moving `makeShareableClone` function from `NativeReanimatedModule` to `NativeWorkletsModule`.
CI

refactor(Worklets): Move shareable creation to Worklets

---

packages/react-native-reanimated/src/mock.ts

The API for sharedValue has changed from using .value to get() and set() methods. As a result, the mock that previously returned an object with a single value property no longer works in the tests.
This is a PR for the mocks, so it's not necessary for it.

Fix bug in useSharedValueMock

---

packages/react-native-reanimated/package.json
yarn.lock

Fixes https://github.com/software-mansion/react-native-reanimated/issues/6665
Applying the change I made to `react-native-builder-bob`:
- https://github.com/callstack/react-native-builder-bob/pull/695
It restores `classic` runtime for the `@babel/react-native` preset used for generating ESModule code. The behavior was changed when we bumped builder-bob:
- https://github.com/software-mansion/react-native-reanimated/pull/6485
I ran the `diff` for the version of `lib` without `jsxRuntime: classic` and with it - the differences are only in regards to `_jsx` usage. You can read more here:
- https://github.com/software-mansion/react-native-reanimated/issues/6665

fix: restore `classic` runtime for @babel/preset-react

---

packages/react-native-reanimated/src/shareables.ts

This PR restores the `nativeStateSource` argument in `makeShareableCloneRecursive` calls, that got lost in #5724

Restore `nativeStateSource` in `makeShareableCloneRecursive`

---

packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxySpec.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxySpec.h
packages/react-native-reanimated/Common/cpp/reanimated/RuntimeDecorators/RNRuntimeDecorator.cpp
packages/react-native-reanimated/Common/cpp/reanimated/RuntimeDecorators/RNRuntimeDecorator.h
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.mm
packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.h
packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm
packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.h

`NativeReanimatedModule` is the name of the ObjC/Java modules generated from `REAModule` and `ReanimatedModule`. It's confusing that we name some Cpp object the same way. With this change Cpp `NativeReanimatedModule` becomes `ReanimatedModuleProxy`, the same name we use to refer to it from JavaScript.
CI

refactor: rename cpp NativeReanimatedModule to ReanimatedModuleProxy

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

This PR fixes the following crash that happens during a reload due to `jsi::Value` outliving the UI runtime.
The offending `jsi::Value` comes from `operationsInBatch_` inside `ReanimatedModuleProxy` (formerly `NativeReanimatedModule`.
In `~ReanimatedModuleProxy` we manually clear data structures containing `jsi::Value` prior to resetting `uiWorkletRuntime_` which effectively terminates the runtimes. It looks like we forgot about `operationsInBatch_`.
1. Launch FabricExample app
2. Reload the app several times
3. Repeat steps 1 and 2 several times

Clear `operationsInBatch_` before terminating UI runtime

---

packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm

The following crash happened to me during an app reload. The top stack frame points to `getValueUnpackerCode` but the actual offender is inside `createReanimatedModuleBridgeless` where `workletsModuleProxy` returned from `[workletsModule getWorkletsModuleProxy]` is `nullptr`.

Assert that `workletsModuleProxy` is found

---

packages/react-native-reanimated/src/mutables.ts

Turns out it can be understood that you should be using `get` in render instead of `.value`.

chore: rephrase render shared value read warning

---

packages/react-native-reanimated/android/src/main/cpp/worklets/CMakeLists.txt

Using v8 javascript engine was causing react-native-reanimated gradle build to fail: https://github.com/software-mansion/react-native-reanimated/issues/3570
Changing the `V8_SO_DIR` according to the recommendation from @reinismu fixes this: https://github.com/Kudo/react-native-v8/issues/208#issuecomment-2255387059
Fixes #3570
I'm not sure how the current CI is passing (https://github.com/software-mansion/react-native-reanimated/issues/3570#issuecomment-2367494988), but that would be the way to test it.

Workaround for V8EXECUTOR_LIB NOTFOUND error in worklets CMakeLists.txt

---

packages/react-native-reanimated/Common/cpp/worklets/SharedItems/Shareables.cpp

Fixes https://github.com/Expensify/react-native-live-markdown/issues/574. See root cause analysis in https://github.com/Expensify/react-native-live-markdown/issues/574#issuecomment-2526377216.
This PR fixes a crash caused by calling `ShareableHandle::toJSValue` with second remote runtime after initializing `remoteValue_` with a `jsi::Value` belonging to the first remote runtime.
I assume that this is a rare scenario so we only memoize the value for the first remote runtime and we recreate the value for all subsequent runtimes.
Reproduction:
<details>
<summary>EmptyExample.tsx</summary>
```tsx
import { Text, StyleSheet, View } from 'react-native';
import {
createWorkletRuntime,
runOnRuntime,
const regex = /\d/; …
```

Fix crash caused by using `ShareableHandle` in multiple remote runtimes

---

apps/fabric-example/ios/Podfile.lock
apps/macos-example/macos/Podfile.lock
apps/paper-example/ios/Podfile.lock
apps/tvos-example/ios/Podfile.lock
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/NativeReanimatedModule.cpp
packages/react-native-reanimated/Common/cpp/worklets/SharedItems/Shareables.cpp
packages/react-native-reanimated/apple/reanimated/apple/Fabric/REAInitializerRCTFabricSurface.h
packages/react-native-reanimated/apple/reanimated/apple/LayoutReanimation/REASharedTransitionManager.m
packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm
packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/platform-specific/jsVersion.ts

Cherry-picking:
* https://github.com/software-mansion/react-native-reanimated/pull/6774
* https://github.com/software-mansion/react-native-reanimated/pull/6700
* https://github.com/software-mansion/react-native-reanimated/pull/6796
* https://github.com/software-mansion/react-native-reanimated/pull/6779
Package build: https://github.com/software-mansion/react-native-reanimated/actions/runs/12239592997

Release 3.16.4

---

apps/fabric-example/ios/Podfile.lock
apps/macos-example/macos/Podfile.lock
apps/paper-example/ios/Podfile.lock
apps/tvos-example/ios/Podfile.lock
packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/createAnimatedComponent/JSPropsUpdater.ts
packages/react-native-reanimated/src/createAnimatedComponent/NativeEventsManager.ts
packages/react-native-reanimated/src/createAnimatedComponent/commonTypes.ts
packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
packages/react-native-reanimated/src/fabricUtils.ts
packages/react-native-reanimated/src/platform-specific/RNRenderer.ts
packages/react-native-reanimated/src/platform-specific/RNRenderer.web.ts
packages/react-native-reanimated/src/platform-specific/findHostInstance.ts
packages/react-native-reanimated/src/platform-specific/findHostInstance.web.ts
packages/react-native-reanimated/src/platform-specific/jsVersion.ts

cherry-pick of: https://github.com/software-mansion/react-native-reanimated/pull/6736

Release 3.16.5

---

packages/react-native-reanimated/Common/cpp/reanimated/RuntimeDecorators/RNRuntimeDecorator.cpp
packages/react-native-reanimated/Common/cpp/worklets/WorkletRuntime/RNRuntimeWorkletDecorator.cpp

`RNRuntimeWorkletDecorator` executes before `RNRuntimeDecorator` already.
Works fine 👍

refactor: move _WORKLET injection to Worklets decorator

---

packages/react-native-reanimated/src/core.ts
packages/react-native-reanimated/src/initializers.ts

`initializeUIRuntime` gets called in top level, therefore the JS engine may decide to execute it before `ReanimatedModule` is resolved, which is generally bad. This fixes that.
See `CounterExample` before and after.

fix: assert ReanimatedModule is loaded before initializing UI runtime

---

packages/docs-reanimated/blog/flip-card.md
packages/docs-reanimated/static/examples/FlipCard.js

FlipCard example was "flickering" and not showing current card (on iOS and Android). Change in styles fixed that.
It was discovered in #6722 
Before:
https://github.com/user-attachments/assets/373980e1-c86d-4521-bfe3-fe1e312ba920
After:
https://github.com/user-attachments/assets/32b47476-27c2-4eb8-9300-362c45ffb238

docs: Fix FlipCard example on Android/iOS

---

packages/docs-reanimated/src/theme/AnnouncementBar/Content/index.js
packages/docs-reanimated/src/theme/AnnouncementBar/Content/styles.module.css
packages/docs-reanimated/src/theme/AnnouncementBar/index.js
packages/docs-reanimated/src/theme/AnnouncementBar/styles.module.css

There was a **change request** from our design team considering the mobile styles of the State of React Native 2024 banner. 
ps. CSS is hard

docs: fix State of React Native 2024 banner styles

---

packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.h

Currently we use the `setMountingOverrideDelegate` function to pass `LayoutAnimationProxy` to every surface, when we find out that a new surface was created. However, the `setMountingOverrideDelegate` function actually doesn't override the `MountingOverrideDelegate` - it stores all of them. This would lead to us processing the same transaction multiple times, so now we skip each already configured surface.

Fix  `MountingOverrideDelegate` initialization

---

apps/fabric-example/ios/Podfile.lock
apps/macos-example/macos/Podfile.lock
apps/paper-example/ios/Podfile.lock
apps/tvos-example/ios/Podfile.lock
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.h
packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/platform-specific/jsVersion.ts

Release 3.16.6 with #6841 fix for layout animations on the New Architecture

Release 3.16.6

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedPackage.java

This PR adds a comment in `ReactModuleInfo` constructor in ReanimatedPackage.java.
We set `canOverrideExistingModule` to `true` because Reanimated overrides `UIManagerModule`.

Add comment for `canOverrideExistingModule` in `ReactModuleInfo` constructor on Android

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

This PR removes `#include <react/utils/CoreFeatures.h>` in ReanimatedModuleProxy.cpp which breaks build on RN 0.77.
See also https://github.com/facebook/react-native/pull/45626

Remove `CoreFeatures.h` include

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

This PR removes `shouldYield` commit option that was used in `ShadowTree::commit` in `ReanimatedModuleProxy::performOperations`.
The reason for the change is that `shouldYield` commit option has been removed in RN 0.77 in https://github.com/facebook/react-native/pull/47191.

Remove `shouldYield` commit option

---

packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx

This PR addresses the issue of respecting reduced motion settings for Layout Animations on Fabric. In addition it avoids double initialisation of entering animation for Fabric.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/6863
https://github.com/user-attachments/assets/af80a2e7-dbac-453a-ba1b-fca3549245fb
| --- | --- |
| <video src="https://github.com/user-attachments/assets/caa7f8f0-4980-43a0-9433-880bf44d8c7d" /> | <video src="https://github.com/user-attachments/assets/0a9c04a0-66ab-4430-aa33-0cd305193ffe" /> |
<details>
<summary>Test Example code</summary>
```js
import { Text, StyleSheet, View, Button } from 'react-native';
import Animated, { FadeIn, FadeOut, LinearTransition } from 'react-native-reanimated'; …
```

Fix respecting Reduced Motion Settings in Layout Animations on Fabric

---

packages/react-native-reanimated/src/logger/logger.ts

If you run NextJs application in edge runtime, library throws an error
`__reanimatedLoggerConfig is not defined`
we needs to declare global or globalThis on every usage in workers on edge runtime.
**It was found and made in collaboration with @vault-developer** 
Tested with patch-package and it worked

fix: __reanimatedLoggerConfig is not defined on edge runtime

---

packages/react-native-reanimated/src/platform-specific/findHostInstance.ts

The method findHostInstance in react-native@0.77 has been moved from a named export to the default export. This PR fix compatibility issue.
Run application with `react-native@0.77`

Compatibility with 0.77 for findHostInstance

---

packages/react-native-reanimated/android/src/main/cpp/reanimated/android/LayoutAnimations.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/LayoutAnimations.h
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp

Breaks circular reference in the `LayoutAnimations`.
`LayoutAnimations ` is a `HybridClass` with a C++ counterpart holding a global reference to the Java object. This structure creates a circular reference between C++ and Java, which the garbage collector cannot clean up. To resolve this issue, I manually removed the reference between C++ and Java by resetting the global ref during the destructor of the `NativeProxy`.
- tested in Expo Go ✅

fix: Break circular reference in `LayoutAnimation`

---

apps/web-example/babel.config.js
apps/web-example/metro.config.js
apps/web-example/package.json
yarn.lock

This PR fixes the following errors that occur when trying to run web-example using `yarn start --reset-cache`:
```
Web Bundling failed 174ms apps/web-example/index.js (1 module)
ERROR  index.js: Cannot find module '@stylexjs/babel-plugin'
Require stack:
- /Users/tomekzaw/RNOS/react-native-reanimated/apps/web-example/babel.config.js
- /Users/tomekzaw/RNOS/react-native-reanimated/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/tomekzaw/RNOS/react-native-reanimated/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/tomekzaw/RNOS/react-native-reanimated/node_modules/@babel/core/lib/config/files/index.js
- /Users/tomekzaw/RNOS/react-native-reanimated/node_modules/@babel/core/lib/index.js
- /Users/tomekzaw/RNOS/react-native-reanimated/apps/web-example/node_mod …
```

Add missing `@stylexjs/babel-plugin` in web-example

---

packages/docs-reanimated/docs/guides/compatibility.mdx

This PR adds Reanimated 3.16.7 row and React Native 0.77 column in the compatibility table in the docs.

Update compatibility table

---

.github/workflows/reanimated-compatibility-check-nightly.yml

This PR adds React Native 0.77 for Paper and Fabric to the test matrix in compatibility check workflow for GitHub Actions.

Update versions in compatibility check workflow

---

packages/react-native-reanimated/src/ReanimatedModule/NativeReanimated.ts

This PR adds check for the New Architecture and web.

chore: Throw an error when the New Architecture is not available

---

packages/react-native-reanimated/scripts/set-reanimated-version.js

This PR changes the logic of generating nightly release version name.
Before this change, the next published version would be `4.0.0-beta.1-nightly-20250121-9a907dd8b`.
After this change, it will be `4.0.0-nightly-20250121-9a907dd8b` (without `-beta.1` part).

Drop pre-release tag for nightly version

---

packages/react-native-reanimated/src/css/component/AnimatedComponent.tsx
packages/react-native-reanimated/src/css/index.ts
packages/react-native-reanimated/src/css/managers/CSSManager.ts
packages/react-native-reanimated/src/css/managers/CSSManager.web.ts
packages/react-native-reanimated/src/css/stylesheet.ts
packages/react-native-reanimated/src/css/types/props.ts
packages/react-native-reanimated/src/css/utils/__tests__/props.test.ts
packages/react-native-reanimated/src/css/utils/props.ts

This PR adds missing `CSSStyle` type export which must have been accidentally removed and fixes `CSSStyle` type optional template param to properly support passing type specifier, like `ViewStyle`, `TextStyle` or `ImageStyle`.

fix: Add missing CSSStyle type export

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/TabNavigatorObserver.java

Fixes https://github.com/software-mansion/react-native-reanimated/issues/6724
Turns out that `TabNavigatorObserver's` `onFragmentUpdate` didn't handle `NullPointerException`, which in turn sometimes crashed release builds on android.
I wasn't able to create a simple reproduction but I have at least one SWM project that used the exact same code to patch Reanimated and it took care of their android crashes.

Add unhandled exception to TabNavigatorObserver catch block

---

packages/react-native-reanimated/apple/reanimated/apple/keyboardObserver/REAKeyboardEventObserver.mm

fix: return correct height for detached keyboard on iOS (fixes #5584, #6440)
fix: don't clobber keyboard height when keyboard did not animate on iOS
fix: convert keyboard position to window coordinate space on iOS (Stage Manager compatibility)
fix: don't prematurely update keyboard height during dismissal on iOS
fix: don't jump to height when iOS keyboard is rapidly opened/closed (fixes #6727)
fix: correct height when keyboard opened from shortcuts bar on iOS
Can be tested with the useAnimatedKeyboard example.
1. Enable iPad for the example project.
2. Launch the useAnimatedKeyboard example.
3. Open the keyboard, then undock or float the keyboard. The view should not transform when undocked or floating.
4. Dock the keyboard
5. Hide the keyboard, note that the view should now be …

useAnimatedKeyboard fixes (iOS)

---

packages/react-native-reanimated/android/src/main/cpp/reanimated/CMakeLists.txt

This PR fixes issue introduced in #6807

fix: Too long line in CMakeLists.txt error on CI

---

packages/react-native-reanimated/android/build.gradle

This PR removes unused variable `REANIMATED_MAJOR_VERSION` and `getReanimatedMajorVersion` in build.gradle.

Remove unused `REANIMATED_MAJOR_VERSION` in build.gradle

---

packages/react-native-reanimated/src/component/PerformanceMonitor.tsx

This PR adds `fontVariant: ['tabular-nums']` in `<PerformanceMonitor />` component in order to prevent text jumps and for the sake of better readability.
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<video src="https://github.com/user-attachments/assets/01d6941c-4a6d-41a4-9a2b-af4cc43e03ed" />
</td>
<td>
<video src="https://github.com/user-attachments/assets/bb76c2ef-da66-4bcf-ab36-9a9734b02922" />
</td>
</tr>
</tbody>
</table>

Use tabular nums in performance monitor

---

packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsManager.cpp

This PR adds a `contains` check for layout animation config. When we schedule the start of an animation, we check if an animation is configured for the given view. But it might happen that before the `LayoutAnimationsManager::startLayoutAnimation` function gets executed, the view gets removed. When the view is removed we clear the config, so the `startLayoutAnimation` function will get a `nullptr` config, resulting in a crash.
fixes #6908

Fix layout animation crashes on the New Architecture

---

packages/docs-reanimated/docs/guides/migration-from-3.x.md

docs: migration from 3.x

---

packages/react-native-reanimated/android/build.gradle

This PR potentially fixes undefined symbol linking errors happening in RN apps when Reanimated is required by other third-party libraries like Live Markdown or Vision Camera caused by incorrect order of task execution caused by incomplete dependency graph which can be fixed by adding `targets` function call in `externalNativeBuild` to specify shared libraries.

Add missing `targets` in build.gradle

---

packages/react-native-reanimated/RNReanimated.podspec

This PR removes `folly_compiler_flags` in favor of `folly_flags` which already contains `-Wno-comma -Wno-shorten-64-to-32` as well as moves `-DREACT_NATIVE_MINOR_VERSION` flag from `folly_flags` to `version_flags`.

Move `-DREACT_NATIVE_MINOR_VERSION` from `folly_flags` to `version_flags` in RNReanimated.podspec

---

packages/react-native-worklets/RNWorklets.podspec

`respond_to?(:install_modules_dependencies, true)` returns true on RN 0.71+ and currently we support RN 0.74+ so it's high time to remove the conditional in RNWorklets.podspec and always call `install_modules_dependencies`.

Use `install_modules_dependencies` by default in RNWorklets.podspec

---

packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.mm

This PR adds the missing call to `calculateTimestampWithSlowAnimations`, which is necessary to properly handle slow animations on iOS.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/e09f3e50-5a12-472d-aea1-71d98c1638bb" /> | <video src="https://github.com/user-attachments/assets/d3a6d047-d443-4f3b-9947-b6f96ee9d479" /> |
Runa animation and toggle slow animation on iOS.

Fix slow animation on iOS

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java

After update to Reanimated 3.16.x we started to have hundreds of crashes due to this error:
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference.
```
More info could be found in this issue #4472 
I am not able to reproduce issue locally since it's happening for some small percentage of users. According to stack trace I am pretty sure it will help but I am not sure if it's proper fix because I don't have deeper understanding of surrounding code.

fix: layout animation NPE crash

---

packages/react-native-reanimated/createNPMPackage.sh

`yarn build` is now necessary when preparing Reanimated package.
🚀

chore: use yarn build when making Reanimated package

---

packages/react-native-reanimated/src/layoutReanimation/animationBuilder/Keyframe.ts

Our current implementation of keyframe parsing mutates the keyframe definition object (e.g. we remove the easing function).  If we try to call `build()` on a `Keyframe` object more than once, we will end up with a different animation after the first time. This is bad because we want people to memoize their Keyframes. I decided to fix this problem by caching the calculated animation. This fixes this problem, and also allows us to reuse the result of parsing.

Add Keyframe animation caching

---

packages/react-native-reanimated/Common/cpp/reanimated/Tools/ReanimatedVersion.cpp

This PR fixes build crash because of missing namespace usage.
Just build the app in the release mode (I tested on android).

fix: Release build failing because of missing worklets namespace

---

packages/docs-reanimated/docs/guides/compatibility.mdx
packages/docs-reanimated/versioned_docs/version-3.x/guides/compatibility.mdx

This PR updates compatibility table in versioned 3.x docs and adds RN 0.77 column in Paper and Fabric sections.

Update compatibility table in 3.x docs

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java

Fixes https://github.com/software-mansion/react-native-reanimated/issues/6896
When adding support for fabric, we have inadvertently kept previous listeners still active for fabric. This way, we registered twice with the same `NodesManager` for React Native's `FabricEventDispatcher`, resulting in pretty much all the events doubling in number on android. I added a simple check that takes care of it.
Paste the following into `EmptyExample` and run `FabricExample`. Check logs making sure that both `start` and `end` are logged only once per gesture.
```TSX
import { View, Text } from 'react-native';
import Animated, { useAnimatedScrollHandler } from 'react-native-reanimated';
function EmptyExample() {
const [w, sW] = useState(0);
const scrollHandler = …
```

Make Fabric event receivers init only once

---

packages/docs-reanimated/docs/guides/building-for-android-on-windows.md
packages/docs-reanimated/versioned_docs/version-3.x/guides/building-for-android-on-windows.md

This PR adds "Building for Android on Windows" troubleshooting guide to Reanimated docs.
Thanks @Richard-HeadCoach for pointing out the solution: https://github.com/software-mansion/react-native-reanimated/issues/6872#issuecomment-2612775221

docs: Building for Android on Windows

---

packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/core.ts
packages/react-native-reanimated/src/initializers.ts

Turns out that `sideEffects` field was ignored and `isWeb()` check evaluated to static false, removing `initializers.ts` from the bundle.
Fixes
- #6740
- #6839
Tested it on RNGH web example app using Expo52

fix: initializer file not loaded in Expo52

---

packages/react-native-reanimated/android/build.gradle

This PR sets version for `react-native-reanimated` project in build.gradle so it is passed to prefab tool.
1. Build example app.
2. Run `find . -name prefab.json`
3. Confirm that `"version": "4.0.0-beta.1"` is present in `prefab.json`

Set version for prefab in build.gradle

---

packages/react-native-reanimated/android/build.gradle
packages/react-native-worklets/android/build.gradle

Fixes #6703.
Based on @Thend007's patch from https://github.com/software-mansion/react-native-reanimated/issues/6703#issuecomment-2636946861.

Fix error "Could not find method isReanimatedExampleApp()"

---

packages/react-native-reanimated/src/ReanimatedModule/NativeReanimated.ts
packages/react-native-reanimated/src/errors.ts
packages/react-native-reanimated/src/requestAnimationFrame.ts
packages/react-native-worklets/src/worklets/initializers.ts

I introduced a regression in #6973 by moving JS implementation of `requestAnimationFrame` to Worklets. Native version of `requestAnimationFrame` is injected in Reanimated's `UIRuntimeDecorator.cpp` so `requestAnimationFrame` must be overwritten in Reanimated, not in Worklets.
Since all the native implementation is in Reanimated and it would be a hard task to extract it right now, I decided to keep it for the time being unless we decide where it should land eventually.
The only difference is the lack of batching with my regression introduced. You can `console.log(currentCallbacks.length)` to see that the batching is restored.

fix: move requestAnimationFrame back to Reanimated

---

packages/docs-reanimated/docs/guides/supported-properties.mdx

This PR just updates the table with docs after adding support for new RN props in CSS animations and transitions in the #6944 PR.

docs: Add new supported props from RN 0.77 to supported props table

---

packages/react-native-reanimated/scripts/duplicate-worklets-code.sh

QoL change. If you removed some file in `react-native-worklets` it would persist in `react-native-reanimated`, potentially causing problems.
🚀

chore: remove duplicated directories when building Reanimated

---

apps/common-app/src/apps/reanimated/examples/StickyHeaderExample.tsx
apps/common-app/src/apps/reanimated/examples/index.ts

This PR adds an example with sticky header implemented using `useAnimatedScrollHandler` (although `useScrollViewOffset` is also recommended) and `useAnimatedStyle` to align the vertical translation of a view with `ScrollView` content offset.
Source code has been adapted from the repro in https://github.com/software-mansion/react-native-reanimated/issues/6992 by @Flewp.

Add sticky header example

---

apps/fabric-example/package.json
apps/macos-example/package.json
apps/next-example/package.json
apps/tvos-example/package.json
apps/web-example/package.json

With current monorepo setup `fabric-example` etc. (not counting `common-app`) are linked in `node_modules` so they could be imported in another workspace, which is unnecessary. This doesn't really bother us, but sometimes when you need to find something in `node_modules` it's annoying that these show up.
🚀

chore: remove apps from node_modules

---

packages/docs-reanimated/versioned_docs/version-3.x/layout-animations/list-layout-animations.mdx

Fix a tiny typo in the docs
n/a

Fix typo in docs

---

packages/react-native-reanimated/src/layoutReanimation/web/animationsManager.ts

This PR fixes the transform computation for layout transitions on the web. It includes adjustments for the layout shift to the initial transform that occurs after a component's scale changes.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/2decffaf-532b-4226-a307-c8b2b1e23375" /> | <video src="https://github.com/user-attachments/assets/574de97c-b51c-456f-8036-5de66801a669" /> |
<details>
<summary>Test Example code</summary>
```js
import { Button } from '@/apps/css/components';
import Animated, { LinearTransition } from 'react-native-reanimated';
const [toggle, setToggle] = useState(true);
return (
<View …
```

Fix web layout transition

---

packages/react-native-reanimated/RNReanimated.podspec

This PR fixes the following iOS build errors reported by @kkafar when `USE_FRAMEWORKS=dynamic` is set:
```
Undefined symbol: facebook::jsi::dynamicFromValue(facebook::jsi::Runtime&, facebook::jsi::Value const&, std::__1::function<bool (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)> const&)
```
This is just the minimal fix, I will remove `install_modules_dependencies_legacy` in an upcoming PR.
1. Add `ENV['USE_FRAMEWORKS'] = 'dynamic'` in `fabric-example/ios/Podfile`
2. Run `bundle install && bundle exec pod install`
3. Open fabric-example in Xcode using `xed ios`
4. Build fabric-example app

Fix iOS build with `USE_FRAMEWORKS=dynamic`

---

packages/react-native-reanimated/android/build.gradle
packages/react-native-worklets/android/build.gradle

Starting from Android 15 devices can use 16KB page size instead of 4KB. Apps that take advantage of this require additional linker flag.
This PR adds aforementioned flag so that apps that use Reanimated don't crash.
>[!NOTE]
> More info can be found [here](https://developer.android.com/guide/practices/page-sizes)
Tested on fabric-example on AVD with 16KB page size.

[Android] Add support for 16KB page size

---

packages/react-native-reanimated/android/build.gradle
packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
packages/react-native-worklets/android/build.gradle

This PR contains cherry-picked commits that should be backported to 3.17
- https://github.com/software-mansion/react-native-reanimated/pull/6978
- https://github.com/software-mansion/react-native-reanimated/pull/7037

Backport changes to 3.17

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

This PR cherry-picks the following PRs to `3.17-stable` branch:
* https://github.com/software-mansion/react-native-reanimated/pull/7033

Cherry-pick for 3.17.0

---

packages/react-native-reanimated/src/createAnimatedComponent/commonTypes.ts
packages/react-native-reanimated/src/css/component/AnimatedComponent.tsx
packages/react-native-reanimated/src/platform-specific/findHostInstance.ts

A reference provided by the component via `getAnimatableRef()` should always take precedence over a reference received through `_setLocalRef()`
Fixes https://github.com/expo/expo/issues/32781
| --- | --- |
| <video src="https://github.com/user-attachments/assets/853e5a4c-4e8b-42cd-ab06-a26cb9db9e08" /> | <video src="https://github.com/user-attachments/assets/b87c758f-901e-488d-9ff0-7f5b44f76aac" /> |
Based on repro: https://github.com/jakex7/expo-32781
<details>
```js
import { BlurView } from "expo-blur";
import React, { useEffect } from "react";
import { Image, StyleSheet, Text, View } from "react-native";
withRepeat,
withTiming,
} from "react-native-reanimated"; …
```

Handle component internal animated ref

---

.github/workflows/example-android-build-check.yml
.github/workflows/example-ios-build-check.yml
.github/workflows/example-macos-build-check.yml
.github/workflows/example-tvos-build-check.yml
packages/react-native-reanimated/RNReanimated.podspec
packages/react-native-worklets/RNWorklets.podspec
packages/react-native-worklets/scripts/worklets_utils.rb

Turns out setting CIs is hard. Previously because of `== 'true'` condition the desired steps were falsely skipped.
See that CI are green now.

fix(worklets): compilation on iOS

---

packages/react-native-reanimated/src/mock.ts

`Keyframe` is used with a constructor in our api, so the mocks should reflect that.

Fix `Keyframe` mock

---

packages/docs-reanimated/docs/core/useAnimatedStyle.mdx
packages/docs-reanimated/versioned_docs/version-3.x/core/useAnimatedStyle.mdx

Refers to the issue: #7067
This PR adds missing information about animated styles behavior to the remarks section of the `useAnimatedStyle` documentation page.
We should add proper precedence support in the future, but for now, until we figure out a valid solution to this problem, we should include information about this behavior in docs.
Build docs and open the `useAnimatedStyle` hook docs.

docs: Add missing information about animated styles precedence

---

packages/react-native-reanimated/src/jestUtils.ts

cherry-pick: https://github.com/software-mansion/react-native-reanimated/pull/6746

cherry-pick: Fix getAnimatedStyle error when called with component that doesn't have animated styles #6746

---

packages/docs-reanimated/docs/css-animations/animation-name.mdx

This is just a mistake in docs. `to` is the correct keyword https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes#to
`end` just doesn't work. `to` works like a charm.

docs: fix animationName "to" keyword

---

apps/fabric-example/ios/Podfile.lock
apps/macos-example/macos/Podfile.lock
apps/paper-example/ios/Podfile.lock
apps/tvos-example/ios/Podfile.lock
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.h
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h
packages/react-native-reanimated/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.h
packages/react-native-reanimated/Common/cpp/worklets/WorkletRuntime/WorkletRuntime.cpp
packages/react-native-reanimated/Common/cpp/worklets/WorkletRuntime/WorkletRuntime.h
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
packages/react-native-reanimated/android/src/main/cpp/worklets/android/AndroidUIScheduler.cpp
packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm
packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/platform-specific/jsVersion.ts

Previously I only partially cherry-picked #6900, but after more testing of reloads on Android it turned out I had to cherry-pick all of it.

release: 3.17.0

---

apps/fabric-example/android/settings.gradle

This PR adds a comment in `fabric-example/android/settings.gradle` with code snippet that enables building React Native from source copied from [React Native docs](https://reactnative.dev/contributing/how-to-build-from-source#update-your-project-to-build-from-source).

Add build from source snippet in fabric-example on Android

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h
packages/react-native-reanimated/Common/cpp/reanimated/Tools/PlatformDepMethodsHolder.h
packages/react-native-reanimated/android/src/fabric/java/com/swmansion/reanimated/ReaCompatibility.java
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nativeProxy/NativeProxyCommon.java
packages/react-native-reanimated/android/src/paper/java/com/swmansion/reanimated/ReaCompatibility.java
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.h
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.mm
packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.h
packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.mm

Currently, there are two ways to update native view props and styles in Reanimated. The default path (so-called slow path) is to apply all props changes to the ShadowTree via C++ API and let React Native mount the changes. However, if all props updated in given batch are non-layout props (i.e. those that don't require layout recalculation, like background color or opacity) we use a fast path that calls `synchronouslyUpdatePropsOnUIThread` from React Native and applies the changes directly to platform views, without making changes to ShadowTree in C++. Turns out, some features like view measurement or touch detection system use C++ ShadowTree which is not consistent with what's currently on the screen. Because of that, we're removing the fast path (turns out it's not that fast, especially …

Remove non-layout style and prop updates path via `synchronouslyUpdatePropsOnUIThread`

---

packages/react-native-reanimated/android/CMakeLists.txt
packages/react-native-reanimated/android/build.gradle
packages/react-native-reanimated/android/src/main/cpp/reanimated/CMakeLists.txt
packages/react-native-worklets/android/build.gradle

This PR removes logic related to JS runtime (including Hermes dependency) from build.gradle in react-native-reanimated.
I also moved dependency on `preBuild` task outside of `afterEvaluate` to align it with React Native and other third-party libraries.

Remove JS runtime logic from Reanimated build.gradle

---

apps/common-app/src/apps/reanimated/examples/CubesExample.tsx

Fixes https://github.com/orgs/software-mansion/projects/45?pane=issue&itemId=99380895
You can see that everything works
https://github.com/user-attachments/assets/c5a152b7-e3e0-48ac-9c42-2f6941406228

fix: Cubes example invalid matrix transform usage error

---

packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSTransition.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSTransition.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/registry/CSSTransitionsRegistry.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/registry/CSSTransitionsRegistry.h
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/updates/UpdatesRegistry.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/updates/UpdatesRegistry.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

This PR fixes:
> 4. [CSS] Transitions aren't triggered / run between invalid states (it is strange as transitions on the transition routes screen work but they are triggered by the state change from the setInterval. Only transitions triggered manually don't work)
from the #7065 PR.
(I am not sure about the exact cause but I deduced that based on my observations)
It looks like the Shadow Tree committing logic changed in RN and, when we prevented react from committing its changes to the Shadow Tree (which is what we actually do to prevent applying changes before the CSS transition starts), it was unaware of which values are were passed in the view props on the JS side. Because of that, when the next commit from React was triggered, it included old props (not props that were last passed as …

fix: CSS transitions glitches after upgrade to RN 0.78

---

packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.h
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitShadowNode.h
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedMountHook.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedMountHook.h
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ShadowTreeCloner.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ShadowTreeCloner.h
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/updates/UpdatesRegistryManager.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/updates/UpdatesRegistryManager.h
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsManager.cpp
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsManager.h
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.h
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsUtils.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxySpec.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxySpec.h
packages/react-native-reanimated/Common/cpp/reanimated/RuntimeDecorators/RNRuntimeDecorator.cpp
packages/react-native-reanimated/Common/cpp/reanimated/RuntimeDecorators/UIRuntimeDecorator.cpp
packages/react-native-reanimated/Common/cpp/reanimated/RuntimeDecorators/UIRuntimeDecorator.h
packages/react-native-reanimated/Common/cpp/reanimated/Tools/PlatformDepMethodsHolder.h
packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.cpp
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/RNRuntimeWorkletDecorator.cpp
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntimeDecorator.cpp

Co-authored-by: Krzysztof Piaskowy <krzysztof.piaskowy@swmansion.com>
This PR removes all `#ifdef RCT_NEW_ARCH_ENABLED` in Reanimated C++ codebase common for all native platforms.

Remove `RCT_NEW_ARCH_ENABLED` macros and unused functions in Common C++

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedPackage.java
packages/react-native-worklets/android/src/main/java/com/swmansion/worklets/WorkletsPackage.java

We used to pass `true` as `canOverrideExistingModule` argument because of the fact that we used to overwrite `UIManagerModule` to handle layout animations. Since we no longer need to do that, this PR restores the recommended value for `canOverrideExistingModule`.

Restore original value of `canOverrideExistingModule`

---

packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
packages/react-native-worklets/android/src/main/cpp/worklets/android/AndroidUIScheduler.cpp
packages/react-native-worklets/android/src/main/cpp/worklets/android/AndroidUIScheduler.h
packages/react-native-worklets/android/src/main/cpp/worklets/android/AnimationFrameCallback.h
packages/react-native-worklets/android/src/main/cpp/worklets/android/WorkletsModule.cpp
packages/react-native-worklets/android/src/main/cpp/worklets/android/WorkletsModule.h

This PR removes unnecessary `#include` macros on Android.

Remove redundant includes on Android

---

apps/common-app/src/apps/reanimated/examples/ColorExample.tsx

Fixes ColorsExample:
- we cannot animate just `shadowColor` on web; `boxShadow` works fine instead (we can replace `shadowColor` with `boxShadow` for all platforms in the future),
- shadow properties don't work on Android, we have to use `elevation`
| iOS | Android | Web |
|-|-|-|
| <video src="https://github.com/user-attachments/assets/9fb6f4a1-bbe7-4334-a585-2aefb1fe5871" /> | <video src="https://github.com/user-attachments/assets/51c7d15d-daf4-4c5d-82be-2bd4c18f5fd4" /> | <video src="https://github.com/user-attachments/assets/d20fe4ba-54fd-4c8a-971a-18bc3f350cc6" /> |

fix: ColorsExample shadow color animation on web and android

---

packages/react-native-reanimated/apple/reanimated/apple/REAModule.h
packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.h
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.mm
packages/react-native-reanimated/apple/reanimated/apple/REASlowAnimations.mm
packages/react-native-reanimated/apple/reanimated/apple/keyboardObserver/REAKeyboardEventObserver.h
packages/react-native-reanimated/apple/reanimated/apple/keyboardObserver/REAKeyboardEventObserver.mm
packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.h
packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm
packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.h
packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.mm
packages/react-native-reanimated/apple/reanimated/apple/sensor/ReanimatedSensor.h
packages/react-native-worklets/apple/worklets/apple/IOSUIScheduler.h
packages/react-native-worklets/apple/worklets/apple/SlowAnimations.mm
packages/react-native-worklets/apple/worklets/apple/WorkletsMessageThread.h
packages/react-native-worklets/apple/worklets/apple/WorkletsMessageThread.mm
packages/react-native-worklets/apple/worklets/apple/WorkletsModule.h
packages/react-native-worklets/apple/worklets/apple/WorkletsModule.mm

This PR removes unnecessary imports on iOS as well as some unused typedefs and class member fields.
See if the CI is green.

Remove redundant includes on iOS

---

packages/docs-reanimated/docs/guides/compatibility.mdx
packages/docs-reanimated/versioned_docs/version-3.x/guides/compatibility.mdx

Just adds the new version to the compatibility table
The table is becoming large that it doesn't fit in page and has to be scrolled 😞 
https://github.com/user-attachments/assets/5f67806e-1fb4-4f09-99a8-194610eaa9f5
https://github.com/user-attachments/assets/124e8217-dcc4-40f2-aa34-0e6aff26333d

docs: Add 3.17.1 to compatibility table in docs

---

packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm

We used to have multiple versions of `createReanimatedModule` function and the common logic was moved to `commonInit` function. Now there's only one version so we can merge `commonInit` logic back to `createReanimatedModule` function.
See if CI is green and make sure that fabric-example works correctly.

Merge `commonInit` function into `createReanimatedModule` function in NativeProxy on iOS

---

packages/react-native-worklets/apple/worklets/apple/WorkletsModule.h
packages/react-native-worklets/apple/worklets/apple/WorkletsModule.mm

This PR aligns the logic of getting `JSCallInvoker` in Worklets with the current implementation in Reanimated. The key line of code here is `@synthesize callInvoker = _callInvoker;`.
Additionally, I removed `@synthesize moduleRegistry = _moduleRegistry;` which is unused.

Obtain `jsCallInvoker` using `RCTCallInvokerModule` in Worklets on iOS

---

apps/fabric-example/ios/Podfile
apps/macos-example/macos/Podfile
apps/tvos-example/ios/Podfile
packages/react-native-reanimated/scripts/reanimated_utils.rb
packages/react-native-worklets/scripts/worklets_utils.rb

We don't use example apps names so I thought it would be better to set `IS_REANIMATED_EXAMPLE_APP` environmental variable instead of `REANIMATED_EXAMPLE_APP_NAME` to align the naming with `isReanimatedExampleApp` setting used on Android.

Replace `REANIMATED_EXAMPLE_APP_NAME` with `IS_REANIMATED_EXAMPLE_APP` on iOS

---

packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.h

This PR removes `commonInit` function in `NativeProxy.h` that I forgot to remove in https://github.com/software-mansion/react-native-reanimated/pull/7139.

Remove redundant `commonInit` declaration in NativeProxy.h

---

packages/react-native-reanimated/apple/reanimated/apple/REAAssertJavaScriptQueue.h
packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.mm
packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm

This PR adds `RCTAssertMainQueue()`, `RCTAssertUIManagerQueue()` and `REAAssertJavaScriptQueue()` calls in various initialization methods in `REAModule`, `NativeProxy` and `NodesManager` on iOS along with the implementation of `REAAssertJavaScriptQueue`. This way we can make sure that the methods are called on appropriate threads as well as track this information in the codebase.
Analogous asserts will be added in `react-native-worklets` in a separate PR: https://github.com/software-mansion/react-native-reanimated/pull/7137
✅ Tested in debug and release mode

Add asserts for queue during Reanimated initialization on iOS

---

packages/react-native-worklets/apple/worklets/apple/AnimationFrameQueue.mm
packages/react-native-worklets/apple/worklets/apple/AssertJavaScriptQueue.h
packages/react-native-worklets/apple/worklets/apple/WorkletsMessageThread.mm
packages/react-native-worklets/apple/worklets/apple/WorkletsModule.mm

This PR adds `RCTAssertMainQueue()` and `REAAssertJavaScriptQueue()` calls in various initialization methods in `WorkletsModule`, `AnimationFrameQueue` and `WorkletsMessageThread` on iOS along with the implementation of `AssertJavaScriptQueue`. This way we can make sure that the methods are called on appropriate threads as well as track this information in the codebase.
I wasn't able to come up with an assert for "com.meta.react.turbomodulemanager.queue" in `invalidate` methods since `NSThread.currentThread.name` returns `nil` so I just added `// Called on com.meta.react.turbomodulemanager.queue` comments.
✅ Tested in debug and release mode

Add asserts for queue during Worklets initialization on iOS

---

packages/react-native-worklets/apple/worklets/apple/AnimationFrameQueue.mm
packages/react-native-worklets/apple/worklets/apple/AssertTurboModuleManagerQueue.h
packages/react-native-worklets/apple/worklets/apple/WorkletsModule.mm

This PR replaces `// Called on com.meta.react.turbomodulemanager.queue` with proper `AssertTurboModuleManagerQueue()` calls along with implementation of `AssertTurboModuleManagerQueue`.
Build and launch fabric-example on iOS.

Add asserts for `TurboModuleManager` queue

---

packages/react-native-reanimated/android/src/main/cpp/reanimated/android/EventHandler.h
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/OnLoad.cpp

This PR extracts `EventHandler` declaration on Android from `NativeProxy.h` to a new separate file `EventHandler.h` as well as updates all its usages and adds necessary includes.
Build fabric-example for Android

Extract `EventHandler` from NativeProxy.h

---

packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/OnLoad.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/SensorSetter.h

This PR extracts `SensorSetter` declaration on Android from `NativeProxy.h` to a new separate file `SensorSetter.h` as well as updates all its usages and adds necessary includes.
Build fabric-example for Android

Extract `SensorSetter` from NativeProxy.h

---

packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm
packages/react-native-worklets/apple/worklets/apple/WorkletsModule.mm

This PR improves and aligns the logic that obtains the reference to React Native runtime in Reanimated and Worklets.
Build and launch fabric-example.

Improve obtaining RN runtime reference

---

packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.mm

⚠️ This is potentially a very breaking change in some setups!
This PR removes `requiresMainQueueSetup` method in `REAModule` that was responsible for marking that Reanimated module should be initialized on the main queue.
This method was added as a side effect 3 years ago in https://github.com/software-mansion/react-native-reanimated/pull/3555 in order to make the warning go away and to keep the identical initialization behavior.
Looks like this is a perfect moment to get rid of this chunk of the code and hopefully it should work just fine.
Please let us know immediately if you have any troubles with running Reanimated without `requiresMainQueueSetup`.

Remove `requiresMainQueueSetup` with `YES`

---

packages/react-native-worklets/apple/worklets/apple/AnimationFrameQueue.mm

This PR removes recently added queue asserts as requested by @tjzel in https://github.com/software-mansion/react-native-reanimated/pull/7137#discussion_r1977756357 and https://github.com/software-mansion/react-native-reanimated/pull/7137#discussion_r1977756948.

Remove queue asserts in `AnimationFrameQueue`

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NativeProxy.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java
packages/react-native-worklets/android/src/main/java/com/swmansion/worklets/WorkletsModule.java

This PR adds assertions for JS and UI threads in initialization methods of Reanimated and Worklets on Android.
Build and launch fabric-example on Android.

Add thread asserts during initialization on Android

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java

Currently, `mOperations` in `ReanimatedModule` is never populated, so it can be removed together with `UIThreadOperation` interface and `willDispatchViewUpdates` interface methods from `UIManagerModuleListener` and `UIManagerListener` interfaces, along with all the remaining methods which are currently no-ops. This means we also need to remove `addUIManagerEventListener` and `removeUIManagerEventListener`. Turns out, we don't need `FabricUIManager` as well. After all these changes there will be only one runnable to execute in `invalidate` method so I also simplified `mUnsubscribe` assignment.
Build, launch and play with fabric-example on Android.

Remove implementation of `UIManagerListener` and `UIManagerModuleListener` interfaces in `ReanimatedModule` on Android

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java

This PR removes `mUnsubscribe` member field that is populate with a `Runnable` that holds `ReactApplicationContext` in its closure. Instead, we obtain `ReactApplicationContext` via `getReactApplicationContext()` directly in `invalidate` method.
Besides, I've renamed `reactCtx` to `reactContext` for the sake of readability and consistency.
I've also confirmed that the `ReactApplicationContext` instance in `initialize` is the same one as in `invalidate`:
| `initialize` | `invalidate` |
|:-:|:-:|
| <img width="648" alt="Screenshot 2025-03-05 at 13 22 35" src="https://github.com/user-attachments/assets/f2ce7754-a24e-416f-b270-f7255ff74d56" /> | <img width="655" alt="Screenshot 2025-03-05 at 13 22 47" src="https://github.com/user-attachments/assets/be56b94b-f987-4cdd-b6a1-f1f845084835" /> | …

Avoid storing `ReactApplicationContext` in cleanup lambda capture in `ReanimatedModule`

---

packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.h
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.mm

This PR removes `bridge` and `surfacePresenter` arguments in `[REANodesManager initWithModule:]` as they are unused.

Remove unused arguments in `REANodesManager` initializer

---

packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm

Looks like `getUIManager` method is used only once so let's move its logic directly into `installTurboModule` method so we can optimize the code further in the future.

Merge `getUIManager` into `installTurboModule` in `REAModule`

---

packages/react-native-reanimated/apple/reanimated/apple/REAModule.h

This PR removes `RCTUIManagerObserver` protocol from `REAModule` class since `REAModule` no longer implements any of the interface methods.
This change was suggested by @piaskowyk.

Remove `RCTUIManagerObserver` protocol from `REAModule`

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java

This PR simplifies the logic of creating and passing `NodesManager` instance on Android.
The conditional in `getNodesManager` has literally always been there 🤯 
Build and launch fabric-example on Android.

Create `NodesManager` instance in `ReanimatedModule` constructor instead of in getter method

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/Utils.java

Chrome Debugger is now deprecated and will be removed in RN 0.79 so we don't want to support it in Reanimated 4.
This PR removes Chrome Debugger-related checks in Android codebase (we already don't have any checks on iOS).
I assume this is still a safe change in terms of error reporting since we still have `isChromeDebugger()` check in TypeScript.
Build and launch fabric-example on Android.

Remove `Utils.isChromeDebugger` on Android

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NativeProxy.java

There's no need to use `ReactApplicationContext#getNativeModule` because we already have `workletsModule` passed in the arguments.
Build and launch fabric-example on Android.

Use `WorkletsModule` instance from `NativeProxy` constructor arguments instead of using `getNativeModule` call

---

packages/react-native-worklets/android/src/main/java/com/swmansion/worklets/WorkletsModule.java

This method is no longer used (confirmed with @tjzel) so let's remove it.
Build fabric-example for Android.

Remove unused `getAndroidUIScheduler` method

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NativeProxy.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java

Currently, `NodesManager` is obtained from `ReanimatedModule` via `getNativeModule` call in `NativeProxy` constructor. This PR makes this already existing coupling a bit more apparent by explicitly passing current `NodesManager` instance (as `this`) to `NativeProxy` constructor. Ultimately, we'd like to remove two-directional referencing between Java classes such as `ReanimatedModule`, `NodesManager` and `NativeProxy`. I also removed `getNodesManager` method which became unused.
Build, launch and reload fabric-example on Android.

Explicitly pass `NodesManager` to `NativeProxy` on Android

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java

In https://github.com/software-mansion/react-native-reanimated/pull/7186 we moved `NodesManager` creation in `ReanimatedModule` from `getNodesManager` getter method to `ReanimatedModule` constructor. This means that `mNodesManager` will be always initialized with a non-null value so we can remove the checks in other methods.
Build, launch and reload fabric-example on Android.

Remove `NodesManager` null checks on Android

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NativeProxy.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java

Currently, we first create `ReanimatedModule` and `NodesManager` in its constructor. Then, calling `ReanimatedModule.installTurboModule` invokes `NodesManager.initWithContext` which creates `NativeProxy` and injects JSI bindings in its constructor. The part I don't like here is that `NodesManager` stays unconfigured for some time (between constructor and `initWithContext` calls). Also, there's some time period when `ReanimatedModule` exists but `NativeProxy` doesn't exist yet, even though it will be necessary, so why don't we just instantiate it earlier?
After this change, all three `ReanimatedModule`, `NodesManager` and `NativeProxy` instances will be created at the same time (but without injecting JSI bindings). Then, calling `installTurboModule` will delegate the call to already …

Call `NodesManager.initWithContext` and thus create `NativeProxy` in `ReanimatedModule` constructor

---

packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java

Since `initWithContext` method is called immediately after `NodesManager`, this PR moves all the logic of `initWithContext` method into the constructor as well as removes its usage.
Build, launch and reload fabric-example app.

Merge `initWithContext` method into `NodesManager` constructor

---

packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm
packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.h
packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.mm

This PR removes unused argument `reaModule` in `makePlatformDepMethodsHolder` function on iOS.

Remove unused `REAModule` argument in `makePlatformDepMethodsHolder`

---

packages/react-native-reanimated/apple/reanimated/apple/REAModule.mm
packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.h
packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm

There's no need to pass `REAModule` to `createReanimatedModule` since only `REANodesManager` is used there. Instead of accessing `reaModule.nodesManager` in `createReanimatedModule`, let's directly pass `_nodesManager`.

Pass `REANodesManager` instead of `REAModule` to `createReanimatedModule`

---

packages/react-native-reanimated/package.json

Currently, if you search on npm for "react native reanimated", you are no the top result ! You need to type "react-native-reanimated" (with dashes) to be at the top. But without dashes, you should still be visible. I would expect this tiny improvement to help about this.
I would expect this keywords to help. We can only be sure after next release.

(package.json) add keywords to package.json to improve npm search result

---

packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.h
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.mm
packages/react-native-reanimated/apple/reanimated/apple/ReanimatedModule.h
packages/react-native-reanimated/apple/reanimated/apple/ReanimatedModule.mm
packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.h
packages/react-native-reanimated/apple/reanimated/apple/native/NativeProxy.mm
packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.h
packages/react-native-reanimated/scripts/validate-apple.sh

This PR renames `REAModule` to `ReanimatedModule` in order to align its name with already existing `WorkletsModule`.
Additionally, I renamed `createReanimatedModule` to `createReanimatedModuleProxy` since the function returns a `std::shared_ptr<ReanimatedModuleProxy>`.
Build and launch fabric-example on iOS.

Rename `REAModule` to `ReanimatedModule` and `createReanimatedModule` to `createReanimatedModuleProxy`

---

packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.h
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.mm
packages/react-native-reanimated/apple/reanimated/apple/ReanimatedModule.mm

This PR removes unused `@property ReanimatedModule *reanimatedModule` in `REANodesManager` as well as removes unused argument in its initializer method.
Build and launch fabric-example on iOS.

Remove unused `reanimatedModule` property in `REANodesManager`

---

packages/react-native-reanimated/apple/reanimated/apple/ReanimatedModule.mm

This PR removes leftover `[[NSNotificationCenter defaultCenter] removeObserver:]` call.
The original `addObserver:` call was removed in https://github.com/software-mansion/react-native-reanimated/pull/6837.
Build, launch and reload fabric-example on iOS.

Remove leftover `removeObserver` call in `ReanimatedModule` on iOS

---

packages/react-native-reanimated/src/UpdateProps.ts
packages/react-native-reanimated/src/createAnimatedComponent/JSPropsUpdater.ts
packages/react-native-reanimated/src/frameCallback/FrameCallbackRegistryUI.ts
packages/react-native-reanimated/src/layoutReanimation/animationsManager.ts
packages/react-native-worklets/src/index.ts
packages/react-native-worklets/src/threads.ts

`runOnUIImmediately` is not conforming with a well defined event loop model of the UI Runtime, so we should remove it.
I considered that we can replace it with:
1. `runOnUI`
2. `executeOnUIRuntimeSync`
3. Additional batching mechanism on the side of Reanimated, using `runOnUI`.
Of those I went for **1.** for the sake of simplicity and didn't notice any regressions. **2.** would be the second choice since it actually preserves the logic but could be potentially slowing down the initialization process.
Please submit any suggestions on how to test this change more thoroughly. 
Run an example and see that all animations run well 🚀

refactor: remove runOnUIImmediately

---

packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/groups/RecordPropertiesInterpolator.cpp

Quick fix for invalid props in the CSS animation style object.
Issue was introduced during `jsi::Value` to `folly::dynamic` refactor by mistake.
You can see that before this change the blue box was initially missing (because its width was set to `null`). Afterwards, everything seems to work fine.
|-|-|
| <video src="https://github.com/user-attachments/assets/d8981633-0368-46d3-bc8d-14907cc524b6" /> | <video src="https://github.com/user-attachments/assets/cc5ef663-1901-4016-836e-a2adff6fba33" /> |

fix: Filter out null values from the CSS animation style

---

packages/react-native-reanimated/android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/worklets/WorkletsModule.java
packages/react-native-reanimated/android/src/paper/java/com/swmansion/reanimated/NativeProxy.java

chore(Reanimated3):cherry-pick #7197

---

packages/react-native-reanimated/src/animation/util.ts

In current implementation calling `cancelAnimation` on Web results in an error since it invokes `runOnUI`.

fix(Reanimated): `cancelAnimation` on web

---

packages/react-native-reanimated/__typetests__/common/AnimatedComponentTest.tsx
packages/react-native-reanimated/src/commonTypes.ts

`MaybeSharedValueRecursive` will result in `Type installation is excessively deep and infinite` error when used with recursive read-only arrays. This PR changes the inference to readonly arrays.
See included test case

Infer only readonly arrays in `MaybeSharedValueRecursive`

---

packages/react-native-reanimated/src/Colors.ts

Fixes #7198 - the color set to `placeholderTextColor` was never processed because it was not on the list. The issue persisted on Fabric and Paper.
Use example code from issue.

fix: Add `placeholderTextColor` to processColor list

---

packages/react-native-reanimated/createNPMPackage.sh
packages/react-native-worklets/createNPMPackage.sh

After the changes to the releasing scripts I introduced a regression where calling `createNPMPackage.sh` without parameters would result in an error.
#7107 
🚀

fix: createNPMPackage.sh not working without parameters

---

packages/react-native-reanimated/src/animation/styleAnimation.ts
packages/react-native-reanimated/src/animation/util.ts

This PR aims to help users avoid confusion by warning them when using layout animation properties that are not officially supported. It was motivated by arising amount of issues related to "X prop not working in custom layout animation" - we want to make it clear for users c:
Related to: #7042 
<details>
<summary>example code</summary>
```tsx
import { View, Button, StyleSheet, SafeAreaView } from 'react-native';
import Animated, { withTiming, withDelay } from 'react-native-reanimated';
const WIDTH = 200;
const customEntering = (targetValues) => {
'worklet';
const animations = {
originX: withTiming(targetValues.targetOriginX, { duration: 3000 }),
opacity: withTiming(1, { duration: 2000 }),
borderRadius: withDelay(1500, withTiming(40, { duration: …
```

backport: Add warning for unsupported layout animation props (#7135)

---

packages/react-native-reanimated/android/build.gradle
packages/react-native-worklets/android/build.gradle

Now we have two packages so `compile_commands.json` should be hoisted in the respective package directory.
🚀

feat: clangd for worklets

---

packages/react-native-reanimated/src/css/component/utils.ts

This PR just removes imports of types that aren't exported from `react-native`. Interestingly, these imports were added automatically and TS didn't complain about them.

chore: Remove internal style type imports from react-native

---

packages/react-native-reanimated/src/css/platform/native/config.ts
packages/react-native-reanimated/src/css/platform/web/config.ts
packages/react-native-reanimated/src/css/types/common.ts

This PR excludes deprecated props that aren't supported by CSS animations (and shouldn't be used in animated styles as well, as they are deprecated) from the `PlainStyle` type.
The issue was originally reported by @softwarebyze and was related to CSS transitions allowing to e.g. pass the `translateX` string for the `transitionProperty`, which is not supported and `transition` string should be used instead.

fix: Exclude deprecated, unsupported properties from style type

---

packages/docs-reanimated/docusaurus.config.js

Updated according to [this docusaurus docs page](https://docusaurus.io/docs/2.x/api/plugins/@docusaurus/plugin-google-gtag#:~:text=gtag%3A%20%7B,%7D%2C)
`plugin-google-gtag` comes preinstalled with docusaurus so no need to install a new package

docs: update analytics id

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

In RN 0.77 a [batching mechanism for commands was introduced](https://github.com/facebook/react-native/commit/6f1c2a512e44d25edefea53e864f688018745c07) behind a feature flag. It was enabled in RN 0.77, but mistakenly disabled in RN 0.78. Now, in RN 0.79 it is back.
The mechanism makes it so that our `scrollTo` calls are only applied from `RuntimeSecheduler_Modern::updateRendering` on event loop tick. So when there was nothing happening on the JS thread, our updates wouldn't be propagated to the platform (That's why adding a console.log to each frame would fix scrolling in the repro). To fix that we bypass batching, by calling `schedulerDidDispatchCommand` directly on the `SchedulerDelegate`.
This issue is a different thing that the one reported in #6999 by @MatiPl01. It is most probably …

Fix lost `scrollTo` updates

---

packages/react-native-reanimated/__tests__/animatedProps.test.tsx
packages/react-native-reanimated/src/UpdateProps.ts
packages/react-native-reanimated/src/createAnimatedComponent/commonTypes.ts
packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
packages/react-native-reanimated/src/hook/commonTypes.ts
packages/react-native-reanimated/src/hook/useAnimatedStyle.ts
packages/react-native-reanimated/src/jestUtils.ts

It turned out animated props when tested in Jest kept their initial value. It was caused by lack of support for animatedProps, which this PR adds.

backport: Add suport for animatedProps

---

packages/react-native-reanimated/src/animation/util.ts

In current implementation calling `cancelAnimation` on Web results in an error since it invokes `runOnUI`.

chore(Reanimated3): cherry-pick #7269

---

.yarn/patches/react-native-builder-bob-npm-0.33.1-383d9e23a5.patch
packages/react-native-reanimated/package.json
packages/react-native-worklets/package.json
yarn.lock

Fixes #6665. Read the issue for more context.
`react-native-builder-bob` applies `@babel/preset-react` on the emitted code, effectively ignoring our TSConfig setting of `jsx: 'react-native'`. `jsx: 'react-native'` is beneficial for library consumers because it allows for greater manipulation of emitted JSX.
https://www.typescriptlang.org/tsconfig/#jsx
Also bringing back `jsxRuntime: 'automatic'` for the same reasons.
https://babeljs.io/docs/babel-plugin-transform-react-jsx#react-automatic-runtime
<details>
<summary>
See the diff to understand resulting changes
</summary>
```diff
diff --color -ru package-old/lib/module/component/FlatList.js package-new/lib/module/component/FlatList.js
--- package-old/lib/module/component/FlatList.js	1985-10-26 09:15:00
+++ …
```

chore(Reanimated3): cherry-pick #7266

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h
packages/react-native-reanimated/Common/cpp/reanimated/Tools/PlatformDepMethodsHolder.h
packages/react-native-reanimated/android/src/fabric/java/com/swmansion/reanimated/ReaCompatibility.java
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/nativeProxy/NativeProxyCommon.java
packages/react-native-reanimated/android/src/paper/java/com/swmansion/reanimated/ReaCompatibility.java
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.h
packages/react-native-reanimated/apple/reanimated/apple/REANodesManager.mm
packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.h
packages/react-native-reanimated/apple/reanimated/apple/native/PlatformDepMethodsHolderImpl.mm

This PR cherry-picks https://github.com/software-mansion/react-native-reanimated/pull/7014 to Reanimated 3.17-stable.

cherry-pick: Remove non-layout style and prop updates path via `synchronouslyUpdatePropsOnUIThread`

---

packages/react-native-reanimated/__tests__/Animation.test.tsx
packages/react-native-reanimated/__tests__/props.test.tsx
packages/react-native-reanimated/src/createAnimatedComponent/PropsFilter.tsx
packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
packages/react-native-reanimated/src/jestUtils.ts

Cherry pick of #7021. Main reason for it was that the early return of `currentStyles` (if `style` is an array) caused to not apply `jestAnimatedStyle`. Becasue of that execution of tests using `style` arrays would fail.
I decided to cherry-pick whole PR not only desired fragments to keep integrity between `main` and `3.17-stable`.

(chery-pick) feat: prevent flattening style arrays

---

packages/docs-reanimated/docs/guides/testing-with-jest.mdx
packages/docs-reanimated/versioned_docs/version-3.x/guides/testing-with-jest.mdx

Thanks to @tjzel suggestion and my remembering about AvailableFrom flag I've added it to `toHaveAnimatedProps` that will be available from `3.17.2`

docs: Add AvailableFrom flag to `toHaveAnimatedProps`

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

Cherry pick #7292

---

packages/react-native-reanimated/src/createAnimatedComponent/commonTypes.ts
packages/react-native-reanimated/src/createAnimatedComponent/createAnimatedComponent.tsx
packages/react-native-reanimated/src/platform-specific/findHostInstance.ts

cherry-pick: fix: Crash caused by passing animated ref to the animate component

---

packages/react-native-reanimated/src/animation/util.ts

#7303 backport of fix of my wrongdoings.
Quick fix for incorrect `height` prop spelling which resulted in this warning being shown in the console:
```
[Worklets] 'height' property is not officially supported for layout animations. It may not work as expected.
```

backport: fix: Misspelt height prop name in supported layout animation props

---

packages/react-native-reanimated/package.json
yarn.lock

This PR unfixes the current `react-native-is-edge-to-edge` version.
The current version has `peerDependencies` that prevents the Expo team from creating a canary release:
```
Conflicting peer dependency: react-native@0.78.2
```
npm installs this version to respect the `>=0.73.0` requirement, even if `react-native@0.79.0-rc.0` is already a project dependency.
PS: I'm on my phone and without a computer access, if someone can run yarn and fix the pipeline before merging, it would help 🙏

Bump react-native-is-edge-to-edge to 1.1.7

---

packages/react-native-reanimated/src/css/component/AnimatedComponent.tsx

Fixes #7340 
In css AnimatedComponent, to render function, we were passed both `props` and `this.props`, when only `props` were necessary as they have filtered props passed to a component as well as nativeID and jest styles. Knowing that, the real issue was passing `this.props`caused web error `React does not recognize the animatedProps prop on a DOM element.`, as `this.props` contained `animatedProps` (totally not needed for the component to have)
<details>
<summary>Code example</summary>
```tsx
import { Button } from 'react-native';
import Svg, { Path } from 'react-native-svg';
withTiming,
const AnimatedPath = Animated.createAnimatedComponent(Path);
export default function …
```

fix: Remove doubled props passing to AnimatedComponent

---

packages/docs-reanimated/docs/core/useAnimatedProps.mdx
packages/docs-reanimated/versioned_docs/version-3.x/core/useAnimatedProps.mdx

As number custom components with custom props rise, and part of them is color-related, it is no longer efficient to expand our ColorProperties.ts list any longer. That's why we decided to give user the information how to manually process color so the `useAnimatedProps` would work.

docs: Add information about color processing for custom props

---

apps/common-app/src/apps/reanimated/examples/ColorExample.tsx
packages/react-native-reanimated/src/hook/useAnimatedStyle.ts
packages/react-native-reanimated/src/processBoxShadow.ts

This PR fixes boxShadow sometimes not working on web. To work boxShadow in the form of string must have `offsetX`, `offsetY`, `blurRadius` and `spreadDistance`. When one of these props was missing the boxShadow wasn't being processed ergo was staying as string - that's why it sometimes **worked** on web. This PR checks if we are on web and if no we then can process the boxShadow.
Additionally I've replaced `shadow` with `boxShadow` in ColorExample.tsx
Check ColorExample on web

fix: boxShadow sometimes not working for web

---

packages/react-native-reanimated/package.json
yarn.lock

This PR unfixes the current `react-native-is-edge-to-edge` version.
The current version has `peerDependencies` that prevents the Expo team from creating a canary release:
```
Conflicting peer dependency: react-native@0.78.2
```
npm installs this version to respect the `>=0.73.0` requirement, even if `react-native@0.79.0-rc.0` is already a project dependency.
PS: I'm on my phone and without a computer access, if someone can run yarn and fix the pipeline before merging, it would help 🙏

(cherry-pick) Bump react-native-is-edge-to-edge to 1.1.7 (#7346)

---

apps/common-app/src/examples/ColorExample.tsx
packages/react-native-reanimated/src/hook/useAnimatedStyle.ts

…w sometimes not working for web (#7338)This PR fixes boxShadow sometimes not working on web. To work boxShadow in the form of string must have `offsetX`, `offsetY`, `blurRadius` and `spreadDistance`. When one of these props was missing the boxShadow wasn't being processed ergo was staying as string - that's why it sometimes **worked** on web. This PR checks if we are on web and if no we then can process the boxShadow.
Additionally I've replaced `shadow` with `boxShadow` in ColorExample.tsx
Check ColorExample on web

(cherry-pick) fix: boxShadow sometimes not working on web

---

packages/react-native-reanimated/src/layoutReanimation/defaultAnimations/Pinwheel.ts
packages/react-native-reanimated/src/layoutReanimation/defaultAnimations/Zoom.ts

This PR fixes issues with rotation transformation after RN upgrade to 0.79. Rotation strings without units are no longer supported so the `rad` unit must me specified explicitly for them to work.
|-|-|
| <video src="https://github.com/user-attachments/assets/93e0fbdc-519c-4b69-b710-045be29a991c" /> | <video src="https://github.com/user-attachments/assets/6752842f-8e07-4fb9-831a-33c0978a92bf" /> |
|-|-|
| <video src="https://github.com/user-attachments/assets/cb43cbb3-bb54-4a46-8014-22f0db3ba58d" /> | <video src="https://github.com/user-attachments/assets/dc45f65f-cc93-41a3-b4a9-b0e06e75143c" /> |
<details>
<summary>Code snippet</summary>
```tsx
import …
```

fix: Layout animations with rotation not working in RN 0.79

---

apps/common-app/src/apps/reanimated/examples/PinExample.tsx
packages/react-native-reanimated/src/hook/useAnimatedRef.ts

Fixes scrollable node obtaining in the `useAnimatedRef` and 2 related examples on web.
https://github.com/user-attachments/assets/6b4f0c95-d387-4849-8cf5-9979c9515fb7
https://github.com/user-attachments/assets/aa90e070-1140-4f4e-b3f6-5efeeb57ba2b
https://github.com/user-attachments/assets/164b7dc3-7e14-4fce-9491-bb05921a08ba

fix: FlashList scroll from UI on web

---

packages/react-native-worklets/apple/worklets/apple/SlowAnimations.mm

During recent changes, multiplying the `currentTimestamp` value by `MILLISECONDS_IN_SECOND` on physical device was lost. Restoring the correct behavior.
Run any app examples on simulator and physical device and see no difference with this PR.

fix: timestamp on physical device in s instead of ms

---

packages/react-native-reanimated/src/createAnimatedComponent/PropsFilter.tsx

This PR fixes #7375.
After removing style flattening the old implementation started being invalid because the `_initialStyle` object that was created during the initial render of the component contained props from all animated styles. If a view had more than just one animated style, this object contained props from all of these styles.
Let's say we had these 3 animated styles:
```tsx
const aStyle1 = useAnimatedStyle(() => ({})); // empty
const aStyle2 = useAnimatedStyle(() => ({
height: 100
}));
const aStyle3 = useAnimatedStyle(() => ({
width: 100
}));
<Animated.View style={[aStyle1, aStyle2, aStyle3]} />
```
The style array on the first render looked like this:
```
[{}, { height: 100 }, { height: 100, width: 100 }] // subsequent objects contain all props from previous objects because of …
```

fix: Initial animated style updater style is applied on re-render

---

packages/react-native-reanimated/apple/reanimated/apple/ReanimatedModule.h
packages/react-native-worklets/apple/worklets/apple/WorkletsModule.h

This PR adds `RCTInvalidating` protocol in `ReanimatedModule` and `WorkletsModule` since they both already implement `invalidate` methods with custom cleanup code on iOS according to the suggestion in https://reactnative.dev/docs/next/the-new-architecture/native-modules-lifecycle.
I haven't noticed any major changes after this change, here's the stack trace before and after:
Reload app during bokeh example a few times.

Add `RCTInvalidating` protocol in `ReanimatedModule` and `WorkletsModule` on iOS

---

packages/react-native-reanimated/src/errors.ts
packages/react-native-reanimated/src/privateGlobals.d.ts
packages/react-native-worklets/src/WorkletsError.ts
packages/react-native-worklets/src/errors.ts
packages/react-native-worklets/src/index.ts
packages/react-native-worklets/src/privateGlobals.d.ts

Turns out that exporting `createCustomError` function is error-prone and sometimes the errors don't work properly. The solution to that is duplicating the code - it's quite small so it shouldn't be a problem.
Trigger `WorkletsError` and `ReanimatedError` and see they work properly now.

fix: separate implementation for custom errors

---

packages/react-native-reanimated/src/index.ts

This PR fixes web example crash caused by the export that loaded the `packages/react-native-reanimated/src/specs/NativeReanimatedModule.ts` file which calls `TurboModuleRegistry.get<Spec>('ReanimatedModule')`. Because `TurboModuleRegistry` is `undefined` on web, the app crashed just after starting.
I removed this export because it is not necessary and we will use the native `ReanimatedView` only internally for the native implementation of the `AnimatedComponent`.
- `yarn build` in `packages/react-native-reanimated`
- `yarn start` in `apps/web-example`

fix: Remove unnecessary export causing web example crash

---

packages/react-native-reanimated/__tests__/props.test.tsx
packages/react-native-reanimated/src/hook/useAnimatedStyle.ts
packages/react-native-reanimated/src/processBoxShadow.ts

This PR updates the `parseBoxShadowString` function to handle `boxShadow` strings with missing optional arguments (`blurRadius`, `spreadDistance`, `color`).
It now gracefully handles input like:
- `10px 10px white` (defaults `blurRadius` and `spreadDistance` to `0px`)
- `10px 10px 5px white` (defaults `spreadDistance` to `0px`)
- `10px 10px` (defaults remaining values, uses black as color)
The default happen on Native side where RN process it and defaults the missing values. 
I've also added unit test with stripped string that make sure styles behave correctly.
I've also moved the string type check into the `processBoxShadow.js` file, since we want to support `boxShadow` values that are arrays of objects where individual properties can be strings with units. (The possibility to support …

fix: Support optional arguments in boxShadow string

---

packages/react-native-reanimated/package.json
yarn.lock

Patch was accidentally removed in [this](https://github.com/software-mansion/react-native-reanimated/commit/47701784d77a063e4a569f7797bc95f74bd9b7f6#r155405465) PR.

fix: Restore accidentally removed builder bob patch

---

packages/react-native-reanimated/__tests__/props.test.tsx
packages/react-native-reanimated/src/hook/useAnimatedStyle.ts
packages/react-native-reanimated/src/processBoxShadow.ts

Cherry pick of #7386 
This PR updates the `parseBoxShadowString` function to handle `boxShadow` strings with missing optional arguments (`blurRadius`, `spreadDistance`, `color`).
It now gracefully handles input like:
- `10px 10px white` (defaults `blurRadius` and `spreadDistance` to `0px`)
- `10px 10px 5px white` (defaults `spreadDistance` to `0px`)
- `10px 10px` (defaults remaining values, uses black as color)
The default happen on Native side where RN process it and defaults the missing values.
I've also added unit test with stripped string that make sure styles behave correctly.
I've also moved the string type check into the `processBoxShadow.js` file, since we want to support `boxShadow` values that are arrays of objects where individual properties can be strings with units. (The …

(cherry-pick) fix: Support optional arguments in boxShadow string (#7386)

---

packages/react-native-reanimated/src/layoutReanimation/defaultAnimations/Pinwheel.ts
packages/react-native-reanimated/src/layoutReanimation/defaultAnimations/Zoom.ts

cherry-pick: Layout animations with rotation not working in RN 0.79

---

packages/docs-reanimated/docs/guides/compatibility.mdx
packages/docs-reanimated/versioned_docs/version-3.x/guides/compatibility.mdx

This PR adds missing `3.17.3` version and the new `3.17.4` version to compatibility tables in docs.
I decided to mark only `3.17.4` as supporting RN 0.79 because of the issue with some layout animations using rotation values without units which stopped working on RN 0.79. Here is a PR with the fix: #7400
https://github.com/user-attachments/assets/8d83fccf-3413-4384-95e6-f95ec375c3d3
https://github.com/user-attachments/assets/96893a75-3f2d-4dff-b314-8f6acb02553d

docs: Update compatibility table in docs, add 3.17.4

---

packages/react-native-reanimated/apple/reanimated/apple/ReanimatedModule.mm
packages/react-native-worklets/apple/worklets/apple/WorkletsModule.h
packages/react-native-worklets/apple/worklets/apple/WorkletsModule.mm

There are some issues like [this](https://github.com/software-mansion/react-native-reanimated/issues/7367) where it is not obvious what was the reason of exception. It turned out to be having `bridge` which both `Reanimated` and `Worklets` do not accept. For easier problem solving, I suggest adding an explicit check for this scenario.
I also added compliance to JSI spec for `Worklets` module to be in line with `Reanimated`.
Run the linked repro or manually enable bridge mode e.g. [here](https://github.com/facebook/react-native/blob/7ff5db3c462c369a8210674ab53642c3f34e9c37/packages/react-native/Libraries/AppDelegate/RCTDefaultReactNativeFactoryDelegate.mm#L121) to see that it does not work.

feat: add check for bridgeless in both packages

---

packages/react-native-reanimated/src/Colors.ts

Adjusted cherry-pick of the #7336 PR.

cherry pick: Fix numeric colors processing

---

packages/eslint-plugin-reanimated/package.json
packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/ReanimatedModule/NativeReanimated.ts
packages/react-native-reanimated/src/platform-specific/jsVersion.ts
packages/react-native-reanimated/src/platform-specific/workletsVersion.ts
packages/react-native-worklets/package.json
packages/react-native-worklets/plugin/package.json
yarn.lock

Extra QoL assertions for the user if they had installed the wrong version of `react-native-worklets` with Reanimated 4.
Try downgrading the version of `react-native-worklets` in its `package.json` and see that relevant error is thrown.

feat(Reanimated): react-native-worklets compatibility assertions

---

packages/react-native-reanimated/RNReanimated.podspec
packages/react-native-worklets/RNWorklets.podspec

PR analogous to https://github.com/facebook/react-native/pull/50897 fixing `HERMES_ENABLE_DEBUGGER` not being added to configs that are not strictly named `Debug`. Should fix https://github.com/software-mansion/react-native-reanimated/issues/7412. Thanks @tomekzaw and @piaskowyk for helping with it.
Run app from https://github.com/software-mansion/react-native-reanimated/issues/7412 and see that it doesn't crash.

fix: add hermes debugger for all debug variants

---

packages/react-native-reanimated/src/hook/useAnimatedRef.ts

Fixing a bug where `useAnimatedRef` would return `null` tag even though the tag was obtained, reported in #7449. The issue probably stems from Shared Value read/write refactor where this change should be included.
Also fixing unnecessary reads of `.value`.
Run examples that use `useAnimatedRef`, like PinExample and see that they work properly.

fix: useAnimatedRef returns wrong tag on ref attach

---

packages/react-native-reanimated/android/build.gradle
packages/react-native-worklets/android/build.gradle

Fixes:
```
Starting an external process 'node --print require.resolve('react-native/package.json')' during configuration time is unsupported
``` 
when `configuration-cache` is enabled.
Replace `execute` with `providers.exec`. You can read more about it here: https://docs.gradle.org/8.13/userguide/configuration_cache.html#config_cache:requirements:external_processes. 
- build project with `configuration-cache` flag ✅

fix: use `providers.exec` to enable `configuration-cache`

---

packages/react-native-reanimated/src/jestUtils.ts

`jest` was used in the global scope and it failed when using that code with Expo SDK 53, probably their setup does not expose `jest` in basic configuration.

fix: use jest if it is available

---

packages/react-native-reanimated/src/hook/useAnimatedStyle.ts

Ensure that `last[propName]` is initialised to fix an exception on web. This bug was introduced by changes in #6749.
I noticed this issue after upgrading to the latest version of react-native-reanimated. In my case, the library was trying to index `last['transform']` which didn't exist for whatever reason.

fix: ensure last[propName] is defined in style updater

---

.clang-format
.eslintignore
.github/ISSUE_TEMPLATE/bug-report.yml
.github/workflows/helper/configureDevClient.js
.github/workflows/helper/configureV8.js
.github/workflows/monorepo-static-checks.yml
package.json
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ComponentDescriptors.h
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedShadowNode.h
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedViewState.h
scripts/releasing.js
tsconfig.json

QoL CI since now we keep some scripts etc. in the root. I also fixed problems found by `yarn lint` and `yarn format` and added necessary configs.
🪨

feat(CI): monorepo static checks

---

apps/common-app/src/apps/reanimated/examples/ShareablesExample.tsx
packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.cpp
packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.h
packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxySpec.cpp
packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxySpec.h
packages/react-native-worklets/Common/cpp/worklets/SharedItems/Shareables.cpp
packages/react-native-worklets/Common/cpp/worklets/SharedItems/Shareables.h
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntimeDecorator.cpp
packages/react-native-worklets/src/WorkletsModule/JSWorklets.ts
packages/react-native-worklets/src/WorkletsModule/NativeWorklets.ts
packages/react-native-worklets/src/WorkletsModule/workletsModuleProxy.ts
packages/react-native-worklets/src/privateGlobals.d.ts
packages/react-native-worklets/src/shareables.ts

The first in a series of PRs that are intended to refactor the logic of the `makeShareableClone` function.
The current implementation does not have a single source of truth, as we have two type checking logics for the passed value, one on the `JS` side and one on the `Cpp` side.
The idea of the refactor is to implement one source of truth on the `JS` side and call the corresponding method on the `Cpp` side e.g:
```js
if (typeof value === ‘string’) {
return global._makeShareableString(value);
}
```
In addition, in this PR I have rewritten the `Shareables` example to make it more readable and easier to use.
`Shareables` example
<video src="https://github.com/user-attachments/assets/5d61009d-e31b-44fc-b4fd-c21a8c417612" />

refactor(Worklets)(makeShareableClone): add makeShareableString

---

packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.cpp
packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.h
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntime.cpp
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntime.h
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntimeDecorator.cpp
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntimeDecorator.h

In the new bundling method we won't copy implicit global identifiers. However, Reanimated & Worklets still depend on copying `__DEV__` from the global object. This PR injects `__DEV__` to Worklet Runtimes while maintaining previous behavior, it's needed for future PRs of worklets.
Run an app in dev & prod and see that it works properly.

feat: inject __DEV__ to worklet runtimes

---

packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.cpp
packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.h
packages/react-native-worklets/android/src/main/cpp/worklets/android/WorkletsModule.cpp
packages/react-native-worklets/android/src/main/cpp/worklets/android/WorkletsModule.h
packages/react-native-worklets/apple/worklets/apple/WorkletsModule.mm

Currently, we instantiate `worklets::JSScheduler` in platform-specific Android/iOS code.
This PR moves `std::make_shared<worklets::JSScheduler>(...)` call to `WorkletsModuleProxy` constructor initializer list to avoid code duplication.
As a result, we only need to pass `jsCallInvoker` (which is still necessary for `NativeWorkletsModuleSpec`) instead of both `jsCallInvoker` and `jsScheduler`.

Move `JSScheduler` creation to `WorkletsModuleProxy` constructor

---

packages/react-native-worklets/android/CMakeLists.txt

This PR removes unused and uninitialized `REANIMATED_VERSION` macro in `react-native-worklets/android/CMakeLists.txt`.

Remove unused `REANIMATED_VERSION` in react-native-worklets CMakeLists.txt

---

packages/react-native-reanimated/src/PlatformChecker.ts
packages/react-native-reanimated/src/ReanimatedModule/js-reanimated/JSReanimated.ts
packages/react-native-reanimated/src/createAnimatedComponent/PropsFilter.tsx
packages/react-native-reanimated/src/platformFunctions/dispatchCommand.ts
packages/react-native-reanimated/src/platformFunctions/measure.ts
packages/react-native-reanimated/src/platformFunctions/scrollTo.ts
packages/react-native-reanimated/src/platformFunctions/setGestureState.ts
packages/react-native-reanimated/src/platformFunctions/setNativeProps.ts
packages/react-native-worklets/src/PlatformChecker.ts
packages/react-native-worklets/src/initializers.ts
packages/react-native-worklets/src/shareables.ts

React Native New Architecture itself doesn't support **Chrome Debugger** (not to be confused with **Chrome DevTools** which is the recommended to debug React Native apps way now) so we can finally get rid of all its traces in our codebase.

Remove `isChromeDebugger` completely

---

packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.h
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NativeProxy.java
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java

Move Java and C++ version checks to `NativeProxy` constructor on Android

---

packages/react-native-reanimated/RNReanimated.podspec

This PR removes `folly_flags` in RNReanimated.podspec since they break compatibility with RN 0.80.0-rc.0.
Instead, `folly-config.h` file from `RCT-Folly` dependency is used which is the default way to configure Folly.
This change is backward-compatible with at least 3 previous versions of react-native.

[0.80] Remove `folly_flags` in RNReanimated.podspec

---

apps/common-app/src/apps/reanimated/examples/OpacityTransformExample.tsx
apps/common-app/src/apps/reanimated/examples/index.ts

This PR adds "opacity & transform" example which is a benchmark for animating `opacity` and `transform` styles.
<table>
<thead>
<tr>
<th>Android</th>
<th>iOS</th>
</tr>
</thead>
<tbody>
<tr>
<td><video src="https://github.com/user-attachments/assets/5f2cb9c3-463e-454f-9a06-6042429aa445" /></td>
<td><video src="https://github.com/user-attachments/assets/1d02f4f0-d796-479f-ae91-2d586bf608e8" /></td>
</tr>
</tbody>
</table>

Add opacity and transform example

---

packages/react-native-reanimated/src/mock.ts

This adds a basic mock for `useScrollViewOffset` to the existing provided mocks for the library as documented for use here: https://docs.swmansion.com/react-native-reanimated/docs/guides/testing/#setup
The reason I think this is worth adding is because upon following this Expo documentation for jest setup to Expo's default tab template, the test will fail calling out this hook. With so many people starting with the Expo tabs template today, I think it's important that following that documentation results in a minimal test passing
Here is a reproducer with the patch applied already: https://github.com/frankcalise/jest-mock-dev-menu
If you want to see it fail, you can remove the patch or restore the mock source so that `useScrollViewOffset` is commented out.

fix(mock): add mock for useScrollViewOffset

---

packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp
packages/react-native-reanimated/apple/reanimated/apple/ReanimatedModule.mm
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/RNRuntimeWorkletDecorator.cpp

This PR moves `WorkletRuntimeCollector::install` call from `react-native-reanimated` platform-specific code to C++ codebase in `react-native-worklets` since `WorkletRuntimeCollector` is still required when `react-native-worklets` is installed without `react-native-reanimated`. I've decided to call it from `RNRuntimeWorkletDecorator::decorate` which is already platform-agnostic so there's no code duplication.

Move `WorkletRuntimeCollector::install` from Reanimated to Worklets

---

packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp

There are essentially 2 changes in the PR. Right now when you do a reload in a simple app with reanimated installed, you will see in AS profiler that instances of all `NativeProxy`s are still in the memory. It is caused by `javaPart_` never being released  thus keeping java part after reload. 
Due to this destructor of `NativeProxy` is not called ever. After adding `javaPart_ = nullptr` in `invalidateCpp`, it works and destructor is called. But calling `reanimatedModuleProxy_->cleanupSensors();` there makes the app crash since we already reset the `reanimatedModuleProxy_` in `invalidateCpp`.
We can go other way probably and move 
```
reanimatedModuleProxy_->cleanupSensors();
reanimatedModuleProxy_.reset();
```
to destructor but seems like `invalidateCpp` is the cleanup method now.
Side …

fix: cleanup sensors in invalidate and make nativeProxy not leak

---

packages/react-native-reanimated/src/helperTypes.ts
packages/react-native-reanimated/src/index.ts
packages/react-native-reanimated/src/layoutReanimation/animationBuilder/index.ts

This PR adds exports for some layout animations types that are used internally. I added exports of types that I was ask for in [this](https://github.com/software-mansion/react-native-reanimated/discussions/7537#discussioncomment-13195445) diescussion.

feat: Export some internal layout animations types

---

packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ShadowTreeCloner.cpp

This PR changes the way reanimated clones `ShadowNodes`. Due to the new `runtimeShadowNodeReference` mechanism, react "sees" the updates we apply in the commit hook. This is a problem, because then we are unable to remove an animation, as no one will remember the state that would be displayed without the animation. Instead an intermediate state would be displayed. To fix that, we disable transferring of ShadowNode references for when we clone them from reanimated.

Don't transfer reanimated updates to ReactJS

---

packages/react-native-reanimated/src/hook/useAnimatedStyle.ts

After interal conversation with @piaskowyk we decided to move this check inside the for loop. It modifies code from #7485, and ensures the initial state is guaranteed and guarded.
<details>
<summary>Both, commented and no, styles should work</summary>
```tsx
import { transform } from "@babel/core";
import { MotiView } from "moti";
import { useState } from "react";
import { Button, StyleSheet, View } from "react-native";
import Animated, {withSpring,useAnimatedStyle} from "react-native-reanimated";
const [doAnimate, setDoAnimate] = useState(false);
const handlePress = () => setDoAnimate(prev => !prev);
const animatedStylez = useAnimatedStyle(() => {
return (
{
transform: [{translateX: doAnimate ? withSpring(100) : 0}],
}
)
})
// return (
//   <View …
```

fix: Move check of last state inside loop

---

packages/react-native-reanimated/src/reactUtils.tsx

This caused Next production build crashes described in the #7543 issue.

cherry-pick: Add missing optional chaining operator in current react owner check

---

packages/react-native-reanimated/src/helperTypes.ts
packages/react-native-reanimated/src/index.ts
packages/react-native-reanimated/src/layoutReanimation/animationBuilder/index.ts

This PR adds exports for some layout animations types that are used internally. I added exports of types that I was ask for in [this](https://github.com/software-mansion/react-native-reanimated/discussions/7537#discussioncomment-13195445) diescussion.

cherry-pick: Export some internal layout animations types (#7546)

---

apps/fabric-example/ios/Podfile.lock
apps/macos-example/macos/Podfile.lock
apps/tvos-example/ios/Podfile.lock
packages/react-native-worklets/package.json

Releasing `react-native-worklets` 0.3.0 for the upcoming beta of Reanimated. For the time being I decided not to draft any GitHub releases. We have to brainstorm how do we release `react-native-reanimated` and `react-native-worklets` in parallel.
I tested the release within the repo and on a bare RN app.

release(Worklets): 0.3.0

---

packages/react-native-reanimated/android/src/main/cpp/reanimated/android/NativeProxy.cpp

There are essentially 2 changes in the PR. Right now when you do a reload in a simple app with reanimated installed, you will see in AS profiler that instances of all `NativeProxy`s are still in the memory. It is caused by `javaPart_` never being released thus keeping java part after reload.Due to this destructor of `NativeProxy` is not called ever. After adding `javaPart_ = nullptr` in `invalidateCpp`, it works and destructor is called. But calling `reanimatedModuleProxy_->cleanupSensors();` there makes the app crash since we already reset the `reanimatedModuleProxy_` in `invalidateCpp`.
We can go other way probably and move
```
reanimatedModuleProxy_->cleanupSensors();
reanimatedModuleProxy_.reset();
```
to destructor but seems like `invalidateCpp` is the cleanup method now.
Side note: …

(cherry-pick) fix: cleanup sensors in invalidate and make nativeProxy not leak (#7515)

---

packages/react-native-reanimated/src/hook/useAnimatedStyle.ts

After interal conversation with @piaskowyk we decided to move this check inside the for loop. It modifies code from #7485, and ensures the initial state is guaranteed and guarded.
<details>
<summary>Both, commented and no, styles should work</summary>
```tsx
import { transform } from "@babel/core";
import { MotiView } from "moti";
import { useState } from "react";
import { Button, StyleSheet, View } from "react-native";
import Animated, {withSpring,useAnimatedStyle} from "react-native-reanimated";
const [doAnimate, setDoAnimate] = useState(false);
const handlePress = () => setDoAnimate(prev => !prev);
const animatedStylez = useAnimatedStyle(() => {
return (
{
transform: [{translateX: doAnimate ? withSpring(100) : 0}],
}
)
})
// return (
//   <View …
```

(cherry-pick) fix: Move check of last state inside loop (#7506)

---

packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSAnimation.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSAnimation.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/progress/AnimationProgressProvider.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/progress/AnimationProgressProvider.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/progress/RawProgressProvider.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/registry/CSSAnimationsRegistry.cpp

This PR fixes incorrect fill mode being applied in alternate animations. The previous implementation didn't take it into account that the every second animation iteration in alternate animations is revered. As a result, the animation was either treated like the animation with the `normal` direction (for `alternate`) or `reverse` (for `alternate-reverse`).
I removed the forwards fill mode getter and fixed the progress calculation after resetting animation progress when its settings change. As a result, if the animation is finished, I can just read the progress from the progress provider, without assuming that it is always 1 for finished animations as it might be 0 for alternate ones.
When `animationDirection` is set to `alternate` or `alternate-reverse` and the animation has the `forwards` …

fix: Incorrect fill mode in alternate animations

---

apps/common-app/src/apps/css/components/examples/ExampleCard.tsx

It worked before with the `flexBasis` change instead of `width` but must have stopped working after one of the latest RN upgrades.
It is not our issue as the same problem was happening on plain `View` components without any layout animations.
|-|-|
| <video src="https://github.com/user-attachments/assets/9246b356-5923-4eea-a6f0-d805eae48fe3" /> | <video src="https://github.com/user-attachments/assets/56294362-9f79-48b5-8edf-00963ecf74fb" /> |

fix: Expandable card items resizing in the example app

---

packages/react-native-reanimated/src/css/managers/CSSManager.web.ts

There were invalid `if` statements that din't call the `update` method on the `CSSAnimationsManager` and `CSSTransitionManager` making it impossible to remove the animation/transition attached to the view.
|-|-|
| <video src="https://github.com/user-attachments/assets/37285c63-4d38-46ad-886a-37b5aed9aa94" /> | <video src="https://github.com/user-attachments/assets/4cc9f5cb-7779-408c-86d9-8f02433633ca" /> |

fix: CSS animation and transition removal issue on web

---

apps/fabric-example/ios/Podfile.lock
apps/macos-example/macos/Podfile.lock
apps/tvos-example/ios/Podfile.lock
packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/platform-specific/jsVersion.ts

Release PR for the next reanimated 4 beta.
|| iOS | Android | Web | Next.js| MacOS | TVOS (iOS) | TVOS (android) |
|-|-|-|-|-|-|-|-|
| Builds | ✅ | ✅ | ✅ | ✅ | ❌* | ✅ | ✅❌** |
| Runs   | ✅ | ✅ | ✅ | ✅ |❌ | ✅ | ✅❌ |
*We don't support MacOS yet
**This got likely broken in #7497 cause by this: `"@react-native/gradle-plugin": "0.80.0-rc.2"` (I will fix that later on in a separate PR as this is an issue with our local examples setup).
- #7563
- #7564
- #7565
- #5862
- #7571

release: Reanimated 4.0.0-beta.4

---

packages/react-native-reanimated/Common/NativeView/CMakeLists.txt
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ComponentDescriptors.h
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedShadowNode.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-reanimated/__tests__/animatedProps.test.tsx
packages/react-native-reanimated/src/css/component/AnimatedComponent.tsx
packages/react-native-reanimated/src/index.ts
packages/react-native-reanimated/src/initializers.ts
packages/react-native-reanimated/src/mock.ts

This PR adds a possibility to access the `ReanimatedModuleProxy` from the `ReanimatedShadowNode`. It also fixes android linking issue to make it possible to access all reanimated library stuff.
You can open any example in the example app and see that it renders fine. 
You can also uncomment the following line in the `packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ComponentDescriptors.h`:
```cpp
// LOG(INFO) << "We can access the proxy: " << proxy->getCssTimestamp();
```
and see that the proxy can be accessed.

feat: Inject reanimated module proxy to reanimated shadow node

---

packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSAnimationConfig.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSAnimationConfig.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSKeyframesConfig.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSKeyframesConfig.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSTransitionConfig.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSTransitionConfig.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/common.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/common.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/easing/EasingFunctions.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/easing/EasingFunctions.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/easing/cubicBezier.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/easing/cubicBezier.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/PropertyInterpolator.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/groups/ArrayPropertiesInterpolator.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/groups/ArrayPropertiesInterpolator.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/groups/RecordPropertiesInterpolator.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/groups/RecordPropertiesInterpolator.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/transforms/TransformOperation.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/transforms/TransformOperation.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/transforms/TransformsStyleInterpolator.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/transforms/TransformsStyleInterpolator.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/values/ValueInterpolator.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/util/keyframes.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/util/keyframes.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

Since we are moving implementation to a custom shadow node which gets `folly::dynamic` object in props, we no longer can create CSS transition/animation configs from a `jsi::Value`. Because of that, I needed to adjust the implementation of all config parsers and the `updateKeyframes` method in interpolators.

chore: Adjust CSS config parsers implementation to work with folly::dynamic

---

packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSAnimation.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSAnimation.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSTransition.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSTransition.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/progress/AnimationProgressProvider.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/progress/AnimationProgressProvider.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/registry/CSSAnimationsRegistry.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/registry/CSSTransitionsRegistry.cpp

This PR separates CSS animation and transition progress updates from the frame props calculation. This change is needed because we don't want to update the progress of the animation/transition while reading the current frame props in our custom shadow node implementation.

chore: Separate css progress updates from frame props calculation

---

packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedShadowNode.cpp
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/managers/CSSAnimationsManager.cpp
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/managers/CSSAnimationsManager.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSAnimation.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSAnimation.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/registry/CSSAnimationsRegistry.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/registry/CSSAnimationsRegistry.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

This PR removes the shadow node instance stored in the `CSSAnimation` props. This is needed as we won't store the shadow node in the animation itself anymore. We are getting this instance when the node is cloned and can simply pass it via props to calculate the current animation frame.

chore: Remove ShadowNode from CSSAnimation dependencies

---

packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSAnimationConfig.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSAnimationConfig.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSAnimation.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSAnimation.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

This PR adds the new CSS animation config parser function and the new `CSSAnimationConfig` struct for the config properties. The new config will be used by the new `CSSAnimationsManager` implementation because the format of props passed to the `ReanimatedView` is different than the format used before.

feat: New CSS animation config parser function for the new CSS animations manager

---

packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ComponentDescriptors.cpp
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ComponentDescriptors.h
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedShadowNode.cpp
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedViewStateData.cpp
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedViewStateData.h

- fixes the initialization of the `ReanimatedViewComponentDescriptor` (it used some strange initialization logic pulling the `proxy` instance from the context container before, which didn't sometimes work. In general, the `ReanimatedModuleProxy` is usually initialized first, but it is not the case during hot reloads, when the order of initialization of `ReanimatedViewComponentDescriptor` and `ReanimatedModuleProxy` can be different. Because of that, we ended up with an uninitialized `ReanimatedModuleProxy` instance with invalid shadow nodes without properly initialized state object that depends on the `proxy`)

fix: Reanimated Component Descriptor initialization on reloads

---

apps/common-app/src/apps/css/examples/transitions/screens/testExamples/Playground.tsx
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedNodeProps.cpp
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedNodeProps.h
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedShadowNode.cpp
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/ReanimatedShadowNode.h
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/managers/CSSAnimationsManager.cpp
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/managers/CSSAnimationsManager.h
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/managers/CSSTransitionManager.cpp
packages/react-native-reanimated/Common/NativeView/react/renderer/components/rnreanimated/managers/CSSTransitionManager.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/common/definitions.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSAnimationConfig.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSAnimationConfig.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSTransitionConfig.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSTransitionConfig.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/common.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/common.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSTransition.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/core/CSSTransition.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-reanimated/apple/reanimated/apple/view/ReanimatedView.mm

This PR adds custom Reanimated ShadowNode props type with direct parsing from `jsi::Value` to the desired config type.
It also adjust implementations of managers and config structs to optimize props comparison (checking if they are the same) and parsing directly from the `rawValue` (being converted to the `jsi::Runtime` and `jsi::Value` pair).

feat: Custom Reanimated ShadowNode props

---

apps/fabric-example/ios/Podfile.lock
apps/macos-example/macos/Podfile.lock
apps/tvos-example/ios/Podfile.lock
packages/react-native-reanimated/RNReanimated.podspec
packages/react-native-worklets/RNWorklets.podspec

PR analogous to https://github.com/facebook/react-native/pull/50897 fixing `HERMES_ENABLE_DEBUGGER` not being added to configs that are not strictly named `Debug`. Should fix https://github.com/software-mansion/react-native-reanimated/issues/7412. Thanks @tomekzaw and @piaskowyk for helping with it.
Run app from https://github.com/software-mansion/react-native-reanimated/issues/7412 and see that it doesn't crash.

chore(Reanimated3): cherry-pick #7428

---

packages/react-native-worklets/Common/cpp/worklets/NativeModules/WorkletsModuleProxy.cpp

In #7486 I made the function `createJSIWorkletsModuleProxy` which uses uninitialized shared_ptr on first invocation - it was intentional, but turns out that this uninitialized shared_ptr was the inteded `nullptr` on iOS but a garbage memory on Android. I'm moving the line to the constructor outside of initializer list to fix this.
I tested Android in both debug and release and it didn't crash anymore.

fix: unitialized shared_ptr on android

---

apps/fabric-example/android/app/src/main/java/com/fabricexample/MainApplication.kt
packages/react-native-reanimated/apple/reanimated/apple/view/ReanimatedView.mm

This PR fixes 2 issues introduced by the RN 0.80 upgrade in the #7497 PR.
1. Fixes codegen not working on iOS - the native implementation of the `ReanimatedView` wasn't bound to JS and the native view didn't work (I didn't receive any updates in the custom shadow node, etc.)
2. Adds mistakenly removed custom font in the fabric example on Android.

fix: Issues after RN 0.80 upgrade

---

packages/react-native-worklets/src/shareables.ts

Quick fix for the issue introduced in the #7548 PR.
Open the drawer navigator in the fabric example app and see this crash when there is no `'worklet'` directive.

fix: Crashes by adding missing worklet directive to plain object check

---

package.json
yarn.lock

TVOS example was crashing because of the `resolutions` field used in the top-level `package.json`, which was overriding version of the `@react-native/gradle-plugin` dependency in all example apps to `0.80-rc.3`, whilst TVOS example still uses RN 0.79.
I tested all example apps (except the MacOS example that we don't support on fabric yet) and everything seems to work fine.
```
import com.facebook.react.common.annotations.internal.LegacyArchitectureLogger;
^
symbol:   class LegacyArchitectureLogger
location: package com.facebook.react.common.annotations.internal
```

fix: TVOS example crashing right after launch

---

packages/docs-reanimated/docs/guides/compatibility.mdx
packages/docs-reanimated/versioned_docs/version-3.x/guides/compatibility.mdx

docs: Add 3.18 to compatibility

---

packages/react-native-reanimated/src/hook/useScrollViewOffset.ts

This PR fixes an old [issue](https://github.com/software-mansion/react-native-reanimated/issues/7170) related to the `useScrollViewOffset` throwing error on the `getTag()` call when the `animatedRef` is not initialized (wasn't passed to the component).
<details>
<summary>Source code</summary>
```tsx
useAnimatedReaction,
type BoxProps = {
color: string;
};
function Box({ color }: BoxProps) {
return <View style={[styles.box, { backgroundColor: color }]} />;
}
const aref = useAnimatedRef<Animated.ScrollView>();
const x = useScrollViewOffset(aref);
useAnimatedReaction(
() => x.value, …
```

fix: Crash in useScrollViewOffset if animatedRef is not initialized

---

.github/workflows/npm-reanimated-publish-nightly.yml
packages/react-native-reanimated/RELEASE.md

After the release of 3.18.0 we forgot to update the branch used for releasing the nightlies of Reanimated 3.
🚀

fix(Reanimated3): bump branch for nightly releases

---

apps/common-app/src/apps/reanimated/examples/EmptyExample.tsx
packages/react-native-reanimated/src/hook/commonTypes.ts
packages/react-native-reanimated/src/hook/useAnimatedRef.ts
packages/react-native-reanimated/src/hook/useScrollViewOffset.ts

This PR fixes `useScrollViewOffset` hook not updating the returned SharedValue if the scrollable to which the ref is attached is rendered with some delay.
The previous implementation didn't work because the `animatedRef` was uninitialized when the `useEffect` hook in the `useScrollViewOffset` was called if the ref wasn't passed to any component. The `useEffect` was not triggered after the ref was passed to the component later on, even though (at least as I understand) the `animatedRef?.current` in the `useEffect` dependencies changed, because this change happened after hook dependencies were recalculated.
Since the code od the component executes from the top to the bottom during render, the `useEffect` hook dependencies array was created before the `animatedRef.current` was set in the …

fix: useScrollViewOffset not working after delayed ref initialization

---

packages/docs-reanimated/src/components/RadonBanner/index.tsx
packages/docs-reanimated/src/components/RadonBanner/styles.module.css

In the production environment Docusaurus serves the HTML statically and then hydrates the HTML shell with React. This caused the banner to randomly pick the banner copy twice (different text was picked "on the server" and then again "on the client") causing an ugly jump/rerender. 
There was no way to catch that bug in dev mode as Docusaurus only runs the page "client side" during development.
I've fixed the problem by only running the code only on the client side and masking the hydration step with a slide and fade animation.
In the following recordings I'm repeatedly refreshing the page.
https://github.com/user-attachments/assets/7739e2f0-56d1-489d-b7ed-7442c1be4a6e
https://github.com/user-attachments/assets/b5330d5f-2d7f-40f8-898d-a1c933c4cc1f

docs: fix Radon IDE banner

---

packages/react-native-reanimated/Common/cpp/reanimated/AnimatedSensor/AnimatedSensorModule.cpp
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsManager.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-worklets/Common/cpp/worklets/Registries/WorkletRuntimeRegistry.h
packages/react-native-worklets/Common/cpp/worklets/SharedItems/Shareables.cpp
packages/react-native-worklets/Common/cpp/worklets/SharedItems/Shareables.h
packages/react-native-worklets/Common/cpp/worklets/Tools/SingleInstanceChecker.h
packages/react-native-worklets/Common/cpp/worklets/Tools/WorkletsJSIUtils.cpp
packages/react-native-worklets/Common/cpp/worklets/Tools/WorkletsJSIUtils.h
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletHermesRuntime.h
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntime.cpp

This PR converts all usages of `assert()` into `react_native_assert()` which offers better logging as well as adds missing error messages.

Use `react_native_assert` instead of `assert`

---

packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.h

This PR fixes sticky header on both Android and iOS.
Together with @bartlomiejbloniarz we found out that sticky header issue can be fixed by commenting out `// isPaused_ = true;` line. However, this can lead to starvation of commits coming from React. So the best workaround so far is to pause Reanimated commits only in `ReanimatedCommitHook` only for commits coming from React and skip pausing them for other commits like state updates after scroll.
Note that this PR uses the new signature of `shadowTreeWillCommit` method which is available from RN 0.80.
<video src="https://github.com/user-attachments/assets/ad36b502-88c5-4215-9ee6-51c26e9bb05c" alt="after" />

Fix sticky header

---

package.json
yarn.lock

Resolution for `@react-native/community-cli-plugin` was forgotten in #7657.
Experimental bundling no longer fails on `_fbBatchedBridge` missing.

fix(Worklets): re-apply yarn patch for experimental bundling

---

packages/react-native-reanimated/src/createAnimatedComponent/AnimatedComponent.tsx

Just a fix for an error shown when any animated component was rendered.
|-|-|
| <video src="https://github.com/user-attachments/assets/efd41da1-5076-4f57-a3ab-9ada738655f5" /> | <video src="https://github.com/user-attachments/assets/a38957bf-fabb-4813-bc62-19b171f6ad57" /> |

fix: Quick fix for getSnapshotBeforeUpdate error

---

packages/react-native-worklets/plugin/index.js
packages/react-native-worklets/plugin/src/plugin.ts

QoL change that makes it so we don't replace the stack traces and get an actually informative error.
Before:
After:
CI

feat(Worklets): improve errors in Worklets Babel Plugin

---

README.md

This PR just removes this pollution from README shown on npm caused by invalid CI state badges:

chore: Remove CI state badges from readme

---

packages/react-native-worklets/package.json

It was added in https://github.com/software-mansion/react-native-reanimated/pull/7644 but I forgot about it in https://github.com/software-mansion/react-native-reanimated/pull/7657.
Without it experimental bundling won't work on iOS.
This codegen field has no effect with `experimentalBundling` disabled.

chore(Worklets): add missing codegen for iOS experimental bundling

---

packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/CSSKeyframesConfig.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/PropertyInterpolator.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/groups/ArrayPropertiesInterpolator.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/groups/ArrayPropertiesInterpolator.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/groups/RecordPropertiesInterpolator.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/groups/RecordPropertiesInterpolator.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/transforms/TransformOperation.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/transforms/TransformOperation.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/transforms/TransformsStyleInterpolator.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/transforms/TransformsStyleInterpolator.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/interpolation/values/ValueInterpolator.h
packages/react-native-reanimated/Common/cpp/reanimated/CSS/util/keyframes.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/util/keyframes.h

This PR is necessary to add support for component-specific interpolators. I would have to store keyframes config object as a `folly::dynamic` instead of creating the style interpolator right away, because I cannot determine on which component type the animation will be attached.
Only after attaching the animation to the view, I can pick the right interpolators config object and create the style interpolator from the persisted keyframes (I cannot persist a `jsi::Value`, so that's why I need this change to `folly::dynamic`).
This PR is a part of PRs set that will add support for CSS animations used on `react-native-svg` components.

chore: Change updateKeyframes to work with folly::dynamic instead of jsi::Value

---

packages/react-native-reanimated/src/publicGlobals.ts
packages/react-native-worklets/src/index.ts
packages/react-native-worklets/src/publicGlobals.ts

These globals are defined by Worklets so it makes sense to move them.
I retained the `publicGlobals.ts` file in Reanimated in case we need it in the future.
🚀

chore: move publicGlobals

---

apps/common-app/src/apps/reanimated/examples/LayoutAnimations/MoveWithExiting.tsx
apps/common-app/src/apps/reanimated/examples/index.ts
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp

This PR fixes how we handle the case when a view is supposed to be removed but its parent is being moved due to view flattening, and has an exiting animation configured. Currently this scenario would lead to a state where the children are not removed (because there is an exiting animation configured), but the animation would not start (because the view is not deleted- it's only moved). This would lead to the children being left on the screen forever.
Test the `[LA] Move with exiting` example.

Fix zombie view when parent is moved

---

packages/react-native-reanimated/src/index.ts
packages/react-native-reanimated/src/layoutReanimation/defaultTransitions/EntryExitTransition.ts

Some time ago, we've decided to remove `combineTransition` function for Reanimated 4. We've already taken it out of the documentation.
The `combineTransition` function isn't necessary; you can achieve the same effect using the syntax below.
```js
EntryExitTransition.entering(entering).exiting(exiting);
```
More details here: https://docs.swmansion.com/react-native-reanimated/docs/layout-animations/layout-transitions#entryexit-transition

Remove `combineTransition`

---

packages/react-native-reanimated/android/CMakeLists.txt
packages/react-native-worklets/android/CMakeLists.txt

This PR includes `react-native-flags.cmake`and calls `target_compile_reactnative_options` in CMakeLists.txt  which sets necessary flags and definitions instead of setting them manually.

Set compile options using `target_compile_reactnative_options` from `react-native-flags.cmake`

---

packages/react-native-reanimated/android/build.gradle
packages/react-native-reanimated/package.json
packages/react-native-reanimated/scripts/reanimated_utils.rb
packages/react-native-reanimated/scripts/validate-worklets-build.js
packages/react-native-reanimated/scripts/validate-worklets-version.js
packages/react-native-reanimated/src/platform-specific/workletsVersion.ts

`process.exit` function can be unavailable in runtime. Therefore runtime script must not use it.
@tomekzaw 🚊 🚋 🚌

fix(Reanimated): Worklets version validation scripts failing in runtime

---

packages/react-native-reanimated/src/css/platform/web/style/processors/colors.ts

This PR fixes incorrect `hwb` color parsing in the web CSS color parser implementation. The previous implementation just removed `,`, which didn't work right when there was no whitespace in the color string.
e.g. `hwb(311,15%,15%)` was converted to `hwb(31115%15%)` instead of `hwb(311 15% 15%)`
| Before* | After |
|-|-|
| <img width="621" height="980" alt="Screenshot 2025-07-15 at 00 14 03" src="https://github.com/user-attachments/assets/ce261616-408d-469f-ab67-71e192f2b255" /> | <video src="https://github.com/user-attachments/assets/53c1539c-4839-4684-9005-41417fd1478d" /> |
*I attached a screenshot as there was no animation at all because of the invalid color format
<details>
<summary>
Code snippet
</summary>
```tsx
export default function …
```

fix: hwb color parsing on web

---

packages/react-native-reanimated/src/createAnimatedComponent/AnimatedComponent.tsx
packages/react-native-reanimated/src/createAnimatedComponent/commonTypes.ts

This PR adds handling for removing or changing layout animations over a component's lifecycle. In the previous approach, we saved the layout animation during mounting and never changed it.
Note that this only makes sense for layout and exiting animations - we can't change the entering animation during a component's lifetime.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/7763
| --- | --- |
| <video src="https://github.com/user-attachments/assets/ed51b466-4702-4d8e-b1a5-44f1c9528e0a" /> | <video src="https://github.com/user-attachments/assets/ef1cf798-5954-4ba2-82c1-ca2a97c19901" /> |
<details>
```js
import { useState } from 'react';
import {
Button,
SafeAreaView,
StyleSheet,
Text,
} from 'react-native';
import Animated, …
```

Fix dynamic updates of layout animations

---

apps/common-app/src/apps/reanimated/examples/LayoutAnimations/DurationZero.tsx
apps/common-app/src/apps/reanimated/examples/index.ts
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.h

This PR changes the way we apply layout animations. Now we call the `notifyDelegateOfUpdates` method only once per frame, instead of doing that for every updated component separately. This improves performance, fixes animations with `duration=0` and possibly helps with some timing issues, when the view could be updated before it's mounted (#7493 - but it's probably not fully solved by this PR).
Checks all LA related examples.

[Fabric LA] Add progress batching

---

packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp

This PR fixes crashes that became apparent after #7798. The issue is that we would add DELETE mutations for some views multiple times, because in some code-paths we were not marking deleted views as DELETED. I think that the issue was not manifesting before #7798 because then we would handle removals separately for each view.
Spam the `[LA] Entering and Exiting with Layout` example and check for crashes.

[Fabric LA] Mark deleted nodes as DELETED

---

apps/common-app/src/apps/reanimated/examples/OldMeasureExample.tsx
packages/react-native-reanimated/src/hook/useHandler.ts

`useHandler` requires worklet functions to be passed after changes applied in the #7604 PR. The example on the web was missing the `'worklet'` directive, thus it crashed when the screen was open.

fix: Accordion example crashing on web

---

packages/docs-reanimated/docs/guides/compatibility.mdx
packages/docs-reanimated/versioned_docs/version-3.x/guides/compatibility.mdx

This PR adds reanimated `3.19.0` to the compatibility table in docs
https://github.com/user-attachments/assets/177ef13e-6863-4ae6-849b-70a821e899d6

docs: Add 3.19 to compatibility table

---

packages/react-native-reanimated/src/animation/util.ts

I noticed that the `backgroundColor` can be animated with layout animations and we even have an example in our example app that does this thing. This PR just adds this prop to the list of supported props to prevent the annoying warning from showing up.
https://github.com/user-attachments/assets/4e3f7c57-119b-420e-98b0-61d360e04e73

fix: Add backgroundColor to layout animations supported props

---

packages/react-native-worklets/android/src/legacyBundling/com/swmansion/worklets/WorkletsModule.java

Change the assert of `context.assertOnNativeModulesQueueThread();` to `context.assertOnJSQueueThread` in `installTurboModule` method.
The assert works just as previously (but I hope better).

chore(Worklets): change queue assert in WorkletsModule.java

---

packages/docs-reanimated/docs/guides/migration-from-3.x.md

This PR removes infobox from migration guide.

Remove infobox about v4 beta from migration guide

---

packages/react-native-reanimated/Common/cpp/reanimated/Fabric/ReanimatedCommitHook.cpp

This PR reverts the conditional skip of reanimated commits (#7668). This breaks sticky headers, but fixes starvation issues, that would manifest on C++ state updates.
To fix the stick header one must use the `DISABLE_COMMIT_PAUSING_MECHANISM` feature flag in reanimated and the `preventShadowTreeCommitExhaustionWithLocking` in react-native.

Undo conditional skip of reanimated commits

---

package.json
packages/docs-reanimated/docs/guides/contributing.mdx
packages/react-native-reanimated/RELEASE.md

Currently `yarn build` in root install Pods in all apps, effectively discouraging us from using it. The problem is that it also sets up pre-commit Husky, which is handful. This PR makes `yarn build` lighter.
🚀

chore: amend monorepo build script

---

packages/react-native-reanimated/Common/cpp/reanimated/Fabric/PropsRegistry.h

I forgot to add the `#include <memory>` header in the modified file which caused cpplint errors shown in CI.

fix: cpplint missing header include error

---

packages/react-native-reanimated/Common/cpp/reanimated/AnimatedSensor/AnimatedSensorModule.cpp
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsManager.cpp
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsManager.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-worklets/Common/cpp/worklets/NativeModules/JSIWorkletsModuleProxy.cpp
packages/react-native-worklets/Common/cpp/worklets/SharedItems/Shareables.cpp
packages/react-native-worklets/Common/cpp/worklets/SharedItems/Shareables.h
packages/react-native-worklets/Common/cpp/worklets/Tools/WorkletEventHandler.h
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/RuntimeManager.cpp
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/RuntimeManager.h
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntime.cpp
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntime.h
packages/react-native-worklets/Common/cpp/worklets/WorkletRuntime/WorkletRuntimeDecorator.cpp

This PR is the first part of a series of PRs that refactor the naming convention. This PR renames `Shareable` to `Serializable` for now only on the cpp side.
`Shareables` Runtime tests

refactor(Worklets): Rename `Shareable` to `Serializable` - part 1

---

packages/react-native-reanimated/src/jestUtils.ts
packages/react-native-reanimated/src/specs/ReanimatedNativeComponent.ts
packages/react-native-reanimated/src/specs/ReanimatedViewProvider.native.ts
packages/react-native-reanimated/src/specs/ReanimatedViewProvider.ts
packages/react-native-reanimated/src/specs/index.ts

Since we currently don't use the native view, we can simply remove the export to fix the Jest issue. We can then move these changes to the branch with native view integration by @MatiPl01
Fixes https://github.com/software-mansion/react-native-reanimated/issues/7718

Remove native view export

---

.github/ISSUE_TEMPLATE/bug-report.yml

Turns out, the quotes were there for a reason.

Add missing quotes in bug report issue template

---

.github/ISSUE_TEMPLATE/bug-report.yml

Turns out, if the dropdown is required, the first option is selected by default.

Swap acknowledgements dropdown options in bug report issue template

---

packages/react-native-reanimated/android/CMakeLists.txt
packages/react-native-reanimated/android/build.gradle
scripts/lint-cmake.sh

This PR fixes the following linking error `on Android due to undefined symbols when trying to build fabric-example via Android Studio after running Clean project after the app was built successfully.
```
ld.lld: error: undefined symbol: worklets::stringifyJSIValue(facebook::jsi::Runtime&, facebook::jsi::Value const&)
```
Previously, we would include `react-native-worklets::worklets` prefab but still build `libworklets.so` from source. Because of the way how Android Gradle Plugin works (ask @lukmccall for more details), `libworklets` would sometimes be treated like a header-only library with no shared object files, causing the aforementioned linking error.
The proposed solution is to abandon prefabs in favor of linking `libworklets.so` manually (using `add_library`) as well as passing …

Fix linking error after Gradle clean project on Android

---

.github/workflows/reanimated-release-checks.yml

I noticed that one of the workflows wan't triggered because of the invalid path:
I asked @tjzel about that and he told me that the name of the workflow changed. I updated it to the correct name in this PR.

fix: Invalid workflow name

---

packages/react-native-reanimated/src/css/managers/CSSAnimationsManager.web.ts

@m-bert noticed that animations aren't cleaned up from the Reanimated's CSS stylesheet when components are unmounted. As a result, we ended up having multiple instances of animations that were no longer used.
<video src="https://github.com/user-attachments/assets/9e7d9987-80eb-44b0-8519-ee5a2978f2b0"></video>
<video src="https://github.com/user-attachments/assets/cb52aaca-7dab-4dfb-bd0a-98fe7e90a09a"></video> 
<details>
<summary>Code snippet</summary>
```tsx
import { useState } from 'react';
import { Button } from 'react-native';
const [show, setShow] = useState(false);
return (
<>
<Button title="Show" onPress={() => setShow(!show)} />
{show && (
<Animated.View
style={{
backgroundColor: 'green',
flex: 1, …
```

fix: CSS animations not being removed from the stylesheet on web

---

packages/react-native-reanimated/src/layoutReanimation/web/componentUtils.ts
packages/react-native-reanimated/src/layoutReanimation/web/domUtils.ts
packages/react-native-reanimated/src/layoutReanimation/web/transition/Curved.web.ts

Turns out that on slower devices when animation lags, it can be removed from DOM before it finishes. This results in callbacks not being called and `dummy` being left instead of removed. 
This PR:
1. Adjusts timeout value for slower devices,
2. Removes dummy elements when their animation is removed from DOM
<details>
<summary>Tested on the following code, with 20x throttling enabled in chrome dev tools:</summary>
```jsx
import { useState } from 'react';
import { Button, View } from 'react-native';
import Animated, { Keyframe, Easing } from 'react-native-reanimated';
function Square() {
const [visible, setVisible] = useState(false);
const easing = Easing.bezier(0.76, 0.0, 0.24, 1.0).factory();
const animation = new Keyframe({
from: { transform: [{ translateX: '0%' }] },
to: {
transform: [{ …
```

[Web LA] Adjust animation cleanup to slower devices

---

packages/docs-reanimated/docs/guides/compatibility.mdx

docs: Add missing 4.0.1 to compat table

---

apps/common-app/src/apps/reanimated/examples/EmptyExample.tsx
packages/react-native-reanimated/src/createAnimatedComponent/JSPropsUpdater.ts
packages/react-native-reanimated/src/initializers.ts

This PR should fix the issue when the `global._tagToJSPropNamesMapping` was accessed before being created.

fix: Make sure that tagToJSPropNamesMapping is initialized before being used

---

packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.cpp
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.h
packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsUtils.cpp

This PR removes code inside `#if REACT_NATIVE_MINOR_VERSION < 78` and outside of `#if REACT_NATIVE_MINOR_VERSION >= 78`.

Remove ifdefs for pre-0.78

---

packages/react-native-reanimated/src/css/managers/CSSAnimationsManager.web.ts

(cherry-pick) fix: CSS animations not being removed from the stylesheet on web

---

packages/react-native-reanimated/src/animation/spring/springUtils.ts

Fixes #7947
When fixing various thing in withSpring in #7803 I moved over to a coherent coordinate system for the animation. This means that when animating a value from 700 to 600, the animation internally animated from 100 to 0. For 600 to 700 it's -100 to 0. I accidentally didn't reflect that change for `overshootClamping` checks.
```tsx
import React, { useEffect, useState } from 'react';
import { Button, StyleSheet, Text, View } from 'react-native';
withSpring,
const [toggle, setToggle] = useState(false);
const height = useSharedValue(600);
return {
height: withSpring(height.value, {
overshootClamping: true,
}), …
```

fix(Reanimated): withSpring overshoot clamping coordinates

---

packages/react-native-reanimated/src/Colors.ts

I don't think we need `makeShareable` here.
1. `ColorExample` works as expected
2. Cannot modify `ColorProperties` and `names` as expected because they are frozen once passed to worklet via closure
```tsx
setTimeout(() => {
console.log('Adding beautifulColor to ColorProperties');
ColorProperties.push('beautifulColor');
}, 5000);
```

Remove unnecessary `makeShareable` call for color names and properties

---

packages/react-native-reanimated/Common/cpp/reanimated/CSS/common/values/CSSColor.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/interpolators/registry.cpp

This PR fixes 2 issues:
1. Release build [failing](https://github.com/software-mansion/react-native-reanimated/actions/runs/16658346570/job/47149005018#step:12:3141) because of the missing implementation of the `isValidColorString` method - I mistakenly put it within the `#ifdef DEBUG` block
2. Error thrown during the app development on hot reloads when the new code was added in the app - caused by the check if interpolators for the specific component have already been registered. I just removed this check as it is unlikely that someone registers different interpolators for the view with the same name and I don't know if there is a better solution to fix the hot reloads issue.

fix: Small CSS issues introduced in recent PRs

---

apps/common-app/src/apps/reanimated/examples/FilterExample.tsx
apps/common-app/src/apps/reanimated/examples/index.ts

This PR adds example for animating `filter` view style prop (https://reactnative.dev/docs/view-style-props#filter) via `useAnimatedStyle`.
Note that on iOS only `brightness` and `opacity` filters are supported.
| Android | iOS |
|:-:|:-:|
| <img width="300" src="https://github.com/user-attachments/assets/978dcae0-24a4-4843-bfcf-d78be4b7ae88" /> | <img width="300" src="https://github.com/user-attachments/assets/0b57295d-faf3-4054-9b96-31bed8db9a87" /> |

Add filter example

---

.clang-tidy
packages/react-native-reanimated/Common/cpp/reanimated/CSS/config/interpolators/registry.cpp

Fixes https://github.com/software-mansion/react-native-reanimated/actions/runs/16658361282/job/47149055694#step:7:914
I also moved `.clang-tidy` file to the monorepo root for it to also be used in worklets.
CI should pass now.

chore: satisfy clang-tidy CI

---

packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

fix: Add missing check for the new architecture in 3.19

---

packages/react-native-reanimated/src/layoutReanimation/web/animationParser.ts
packages/react-native-reanimated/src/layoutReanimation/web/createAnimation.ts

Fixes: #7950
This PR fixes the problem with easings configured via the custom `Keyframe` layout animation on web. The problem results from the adopted convention in which we expect the keyframe easing to be defined in the second keyframe of the keyframes pair between which the easing should be applied.
This is different from how CSS animations work and slightly confusing but, since changing this behavior will introduce a breaking change, I decide to just adjust the web implementation to shift keyframe easings one keyframe before, which in result makes it possible to create a valid CSS animation from out LA `Keyframe` object.
Before this PR the custom easing was not applied and the animation progressed with a default easing.
|-|-|
| <video …

fix: Keyframe LA easing not working properly on web

---

packages/react-native-reanimated/Common/cpp/reanimated/CSS/common/values/CSSColor.cpp
packages/react-native-reanimated/Common/cpp/reanimated/CSS/common/values/CSSColor.h

This issue was introduced in the #7784 PR and was caused by the `getDouble()` call on the `folly::dynamic` value. I assumed that all values that come from JS are double (since this is how JS represents all numbers) but, in fact, the value was stored as the 64-bit integer in the `folly::dynamic` and the `.getDouble()` call caused crashes.
To fix the issue, I decided to use the safer method `.asInt`, which will convert the number to the integer type (if it is not already an int) instead of throwing error. I also changed the `double` constructor to the `int64_t` constructor as the integer type is more correct than the `double` type.
https://github.com/user-attachments/assets/6b5dc444-7049-4687-a36d-55dd7c9f33ac
https://github.com/user-attachments/assets/d9c22957-ba62-41ab-897f-8e31ebac90c0 …

fix: CSS transition color crashes

---

packages/react-native-reanimated/src/layoutReanimation/animationsManager.ts

(cherry-pick) fix: LA Manager initialized too late on the UI runtime

---

apps/common-app/src/apps/reanimated/examples/SynchronousPropsExample.tsx
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp
packages/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NativeProxy.java

(cherry-pick) Add support for percentage values for border radius in fast path on Android

---

packages/react-native-reanimated/Common/cpp/reanimated/Fabric/updates/UpdatesRegistryManager.cpp
packages/react-native-reanimated/Common/cpp/reanimated/Fabric/updates/UpdatesRegistryManager.h
packages/react-native-reanimated/Common/cpp/reanimated/NativeModules/ReanimatedModuleProxy.cpp

This PR aims to fix the following issue #8001.
I was unable to reproduce this issue but I suspect that these lock calls were missing before, which resulted in crashes when the `removableShadowNodes_` map was modified while the `handleNodeRemovals` method in the mount hook was called

fix: Make node marking as removable safer

---

packages/react-native-reanimated/src/layoutReanimation/web/config.ts
packages/react-native-reanimated/src/layoutReanimation/web/createAnimation.ts

The previous implementation used an invalid type for the `KeyframeDefinitions` type assuming that all keys in `KeyframeDefinitions` are numbers. Because of that, it also converted all keys to numbers via the `.map(Number)` mapping which gave `NaN` offset values in the `offsets` array. As a result, the easing shift didn't work properly as `NaN` aren't valid offsets so we were getting `undefined` instead of the valid keyframe definition object.
https://github.com/user-attachments/assets/1dd8933c-1811-41c7-ada1-4a87c29404c3
https://github.com/user-attachments/assets/7b62f9ad-8d29-4e0f-99e4-89faf2cc19c6

fix: Invalid web LA keyframe processing when from/to offset is used

---

apps/fabric-example/ios/Podfile.lock
apps/macos-example/macos/Podfile.lock
apps/paper-example/ios/Podfile.lock
apps/tvos-example/ios/Podfile.lock
packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/platform-specific/jsVersion.ts

This PR sets reanimated version to `3.19.1`. This version includes changes listed in this cherry-pick issue: #7989
|| Fabric (iOS) | Fabric (Android) | Paper (iOS) | Paper (Android) | Web | MacOS (Paper) | TVOS (iOS) | TVOS (android) |
| Builds           | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | 
| Works            | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ | ✅ |

release: Reanimated 3.19.1

---

apps/fabric-example/ios/Podfile.lock
apps/tvos-example/ios/Podfile.lock
packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/platform-specific/jsVersion.ts
yarn.lock

This PR sets reanimated version to `4.0.2`. This version includes changes listed in this cherry-pick issue: #7960
|| Fabric (iOS) | Fabric (Android) | Web | TVOS (iOS) | TVOS (Android) |
|-|-|-|-|-|-|
| Builds           | ✅ | ✅ | ✅ | ✅ | ✅ |
| Works            | ✅ | ✅ | ✅ | ✅ | ✅ |

release: Reanimated 4.0.2

---

packages/docs-reanimated/docs/guides/compatibility.mdx
packages/docs-reanimated/versioned_docs/version-3.x/guides/compatibility.mdx

This PR adds the 2 new versions of reanimated to compatibility tables in docs: `3.19.1` and `4.0.2`

docs: Update compatibility tables in after releases

---

apps/common-app/src/apps/reanimated/examples/GetViewPropExample.tsx
packages/react-native-reanimated/__typetests__/common/useAnimatedRefTest.tsx
packages/react-native-reanimated/package.json
packages/react-native-reanimated/src/ReanimatedModule/NativeReanimated.ts
packages/react-native-reanimated/src/ReanimatedModule/js-reanimated/JSReanimated.ts
packages/react-native-reanimated/src/ReanimatedModule/reanimatedModuleProxy.ts
packages/react-native-reanimated/src/commonTypes.ts
packages/react-native-reanimated/src/core.ts
packages/react-native-reanimated/src/createAnimatedComponent/commonTypes.ts
packages/react-native-reanimated/src/css/component/AnimatedComponent.tsx
packages/react-native-reanimated/src/fabricUtils.ts
packages/react-native-reanimated/src/hook/commonTypes.ts
packages/react-native-reanimated/src/hook/useAnimatedRef.ts
packages/react-native-reanimated/src/hook/useScrollOffset.ts
packages/react-native-reanimated/src/platform-specific/findHostInstance.ts
packages/react-native-reanimated/src/platformFunctions/dispatchCommand.ts
packages/react-native-reanimated/src/platformFunctions/getRelativeCoords.ts
packages/react-native-reanimated/src/platformFunctions/measure.ts
packages/react-native-reanimated/src/platformFunctions/measure.web.ts
packages/react-native-reanimated/src/platformFunctions/scrollTo.ts
packages/react-native-reanimated/src/platformFunctions/scrollTo.web.ts
packages/react-native-reanimated/src/platformFunctions/setNativeProps.ts
packages/react-native-reanimated/src/platformFunctions/setNativeProps.web.ts
yarn.lock

This PR improves types used for the animated ref value. The previous implementation required the value to be an instance of the `React.Component`, which worked in most cases. This broke in `FlashList` v2 because the `ref` prop doesn't extend the `React.Component` type and instead it included just types of a few methods that can be used to obtain the view instance.

fix: Improve animated ref value type

---

apps/common-app/src/App.tsx

It looks like the web implementation of the drawer navigator is invalid when the `drawerPosition: 'right'` is set. It must be using the `left: <window-width>` to position the drawer on the right side of the window, which doesn't respect changes of the window size. The correct approach would be to use `right: 0` instead but, since this is an external library and I don't want to waste time on fixing that, I decide to just switch the position to the `left` on the web.
https://github.com/user-attachments/assets/3f217d30-330b-4f43-9c12-81e5b2d468ca
https://github.com/user-attachments/assets/c4438f31-798a-47fb-98b3-81d25799e64f

fix: Web example drawer navigator behavior

---

packages/react-native-reanimated/src/createAnimatedComponent/NativeEventsManager.ts

Currently my app is failing with `Cannot read property '__nativeTag' of null`, checking for null fixes the issue.

Fix "Cannot read property '__nativeTag' of null"

---

packages/react-native-reanimated/src/css/native/__tests__/registry.test.ts
packages/react-native-reanimated/src/css/native/keyframes/__tests__/CSSKeyframesRegistry.test.ts
packages/react-native-reanimated/src/css/native/managers/CSSManager.ts
packages/react-native-reanimated/src/css/native/managers/__tests__/CSSAnimationsManager.test.ts
packages/react-native-reanimated/src/css/native/normalization/animation/__tests__/animationName.test.ts
packages/react-native-reanimated/src/css/native/registry.ts

This PR fixes unpredictable behavior when CSS animation/transition was passed to the SVG component. The behavior was unpredictable because, when the support for SVGs was disabled, on the JS side we used the base style builder as a fallback (the one that is used for React Native components). As a result, some properties, such as the `color` property, were passed to the native side where we tried to create an interpolator for them, but, since there were no native interpolators registered in CPP, we got a weird error message that the respective interpolator was not found.
To make the error message more user-friendly, I decided to change this behavior and no longer use the base style builder as a fallback for all unsupported components. Instead, I check if the component is supported and throw …

fix: Throw error when CSS is used on unsupported components

---

packages/react-native-worklets/RNWorklets.podspec

To support USE_FRAMEWORKS=dynamic RNWorklets are missing an explicit dependency on React-hermes.
This commit adds the dependency since it is not set when calling `install_modules_dependencies`.
This can be tested by enabling USE_FRAMEWORKS="dynamic" in the Pod-file in a test project.

[ios][worklets] add explicit dependency on React-hermes

---

packages/docs-reanimated/docs/guides/feature-flags.md
packages/docs-worklets/docs/guides/feature-flags.md

This PR moves the description of `EXPERIMENTAL_MUTABLE_OPTIMIZATION` Reanimated feature flag from Worklets docs to Reanimated docs.

docs: move `EXPERIMENTAL_MUTABLE_OPTIMIZATION` feature flag description

---

packages/react-native-worklets/RNWorklets.podspec
packages/react-native-worklets/scripts/worklets_utils.rb

This PR fixes static feature flags resolution on iOS in `react-native-reanimated` due to a name clash of `get_static_feature_flags` functions defined both in `reanimated_utils.rb` and `worklets_utils.rb` which would result in the latter being called for both libraries. Adding `worklets_` prefix for consistency with other functions resolves the issue.

Fix static feature flags resolution on iOS

---

packages/react-native-worklets/RNWorklets.podspec

To support USE_FRAMEWORKS=dynamic RNWorklets are missing an explicit dependency on React-hermes.
This commit adds the dependency since it is not set when calling install_modules_dependencies.
This can be tested by enabling USE_FRAMEWORKS="dynamic" in the Pod-file in a test project.

cherry-pick(Worklets): add explicit dependency on React-hermes #8120

---

packages/react-native-reanimated/src/createAnimatedComponent/NativeEventsManager.ts

(cherry-pick) Fix "Cannot read property '__nativeTag' of null"  (#8093)

---

packages/react-native-worklets/RNWorklets.podspec
packages/react-native-worklets/scripts/worklets_utils.rb

This PR fixes static feature flags resolution on iOS in `react-native-reanimated` due to a name clash of `get_static_feature_flags` functions defined both in `reanimated_utils.rb` and `worklets_utils.rb` which would result in the latter being called for both libraries. Adding `worklets_` prefix for consistency with other functions resolves the issue.

cherry-pick(Worklets): Fix static feature flags resolution on iOS #8130

---

packages/react-native-reanimated/scripts/validate-worklets-build.js
packages/react-native-reanimated/scripts/validate-worklets-version.js
packages/react-native-reanimated/src/platform-specific/workletsVersion.ts

Fix worklets version checking in runtime:
We can dynamically resolve imports with `require(packageJsonPath)`. I changed the implementation to accept the Reanimated version as a parameter.

Fix worklets version checking in runtime

---

packages/react-native-reanimated/src/layoutReanimation/animationsManager.ts
packages/react-native-reanimated/src/mutables.ts

The layout animation manager calls `makeMutableUI`—[see here](https://github.com/software-mansion/react-native-reanimated/blob/main/packages/react-native-reanimated/src/layoutReanimation/animationsManager.ts#L69). It generally works great, but when we switch to the experimental mutable implementation, `experimental_makeMutableUI` expects a second argument, a synchronizable, that will act as a "dirty flag." However, the animation manager doesn't provide that value due to a misalignment in TypeScript:
```typescript
export const makeMutableUI = USE_SYNCHRONIZABLE_FOR_MUTABLES
? // eslint-disable-next-line camelcase
(experimental_makeMutableUI as typeof makeMutableUI_) // <-- here
: makeMutableUI_; // <-- accepts only one argument
```
This causes a situation where we try to call `setDirty` on …

Use legacy_makeMutableUI in animation manager

---

.husky/pre-commit

This PR updates the Husky error message in cases where someone hasn't installed the node modules, which often happens. Husky tries to format the documentation, for example, during the merging process.
Before:
After:

Improve husky error message

---

packages/react-native-reanimated/__tests__/__snapshots__/animatedProps.test.tsx.snap
packages/react-native-reanimated/src/css/component/AnimatedComponent.tsx

While testing the web example app, I noticed the following error:
It was caused by the fact that we passed unfiltered component props together with filtered props. To fix the issue, I just check whether the `render` method on the base animated component class is called with the props object or not. If it does, then I don't pass `this.props` (unfiltered props).

fix: Stop passing unfiltered props to the rendered component

---

packages/docs-worklets/src/components/HomepageUseCasesSection/UseCase/styles.module.css

fix(Worklets): Adjust phone mockup padding on mobile devices

---

apps/common-app/package.json
apps/fabric-example/ios/Podfile.lock
yarn.lock

I was facing [this](https://github.com/callstack/react-native-pager-view/issues/979) issue multiple times which was very annoying while working on native changes in reanimated. Usually, the only thing that worked was a full cleanup of the project and reinstallation of all dependencies and pods.
I hope that the issue is fixed in v7. At least, I think we can give it a try and see if it works after the upgrade.
I tested if the pager example in our example app works so I think it is safe to bump the version to v7.

chore: Bump react-native-pager-view to v7

---

packages/react-native-worklets/src/PlatformChecker/index.ts
packages/react-native-worklets/src/threads.ts

Fixes #8285.
When initializing "PlatformChecker" in lazy import environments `globalThis.__RUNTIME_KIND` will be executed before it's defined in `runtimeKind` file. By changing it to function invocation we enforce that it's properly initialized.
Also setting serialized values manually for `runOnUI` and `runOnUIAsync` has to be done only when not in web implementation.
See fixed issue.

chore(Worklets): fix PlatformChecker init

---

packages/react-native-reanimated/src/createAnimatedComponent/NativeEventsManager.ts
packages/react-native-reanimated/src/helperTypes.ts

Cherry-pick of the https://github.com/software-mansion/react-native-reanimated/pull/8093

(cherry-pick) Fix `Cannot read property '__nativeTag' of null`.

---

packages/react-native-reanimated/Common/cpp/reanimated/LayoutAnimations/LayoutAnimationsProxy.h

Fixes impossibility to build the iOS app becuase of the incorrectly placed prop.

fix: Move android-only prop definition to ifdef block

---

packages/docs-reanimated/versioned_docs/version-3.x/guides/compatibility.mdx

I decided to change this after the `3.19.2` release in order not to update docs after each patch version release, which is quite cumbersome.

docs: Change explicit 3.19 version range to 3.19.x
