software-mansion/react-native-reanimated

- Example/imageViewer/index.js
- Example/package.json
- Example/yarn.lock
Wish to handle inteaction between handlers with new RNGH ref's API (with `createRef`)
Update library and fix `imageViewer` example
> Update package.json and change string ids to React.createRef

- Example/App.js
- Example/colors/index.js
- README.md
- android/src/main/java/com/swmansion/reanimated/nodes/OperatorNode.java
- ios/Nodes/REAOperatorNode.m
- src/ConfigHelper.js
- src/base.js
- src/derived.js
This PR adds new "round" and "color" nodes.
Color nodes can be used to map to color props in view (e.g. backgroundColor)
Round is required for the color math to function properly (each color component needs to be an integer).
Added demo app where you can pan view around that changes color depending on the position on HSV palette.
> Add round and color nodes

- android/src/main/java/com/swmansion/reanimated/nodes/TransformNode.java
This "static" keyword slipped in by accident (perhaps when refactoring processTransforms to be a static method). It was causing all transform node configs to be overwritten by the most recent one and hence preventing multiple installed animated views from functioning on Android.
> Fix issue with transform config being shared between all nodes

- src/core/AnimatedNode.js
- src/core/AnimatedProps.js
- src/core/AnimatedStyle.js
- src/core/AnimatedTransform.js
- src/createAnimatedComponent.js
When reanimated component gets re-rendered we used to create new Prop node which in turn created Style and Transform node if present.
This turns out to be a huge waste of resources as new nodes would generate additional bridge traffic while they often represent the same prop mapping.
We now extract prop, style and transform node configuration which uniquely represents node behavior and try to match that with node used previously. If config matches we reuse the node instead of creating a new one.
This also fixes #13
> During rerender try to reuse prop, style, transform nodes when possible

- src/core/AnimatedValue.js
I believe this was a simple oversight.
If it's not, then a comment would seem warranted as to why.
> Use strict equals to compare animation values

- src/derived/color.js
This enables `color` to work in the event that the `alpha` value for a color is a derived node rather than explicitly an `AnimatedValue`
> Color alpha should work with AnimatedNode

- react-native-reanimated.d.ts
Hey there! I worked with @ckknight to update the TS definitions to be more in line with `react-native`'s current definitions for `Animated` so that upgrading to `react-native-reanimated` is 100% a drop-in-replacement.
> Update TypeScript definitions

- src/core/AnimatedProps.js
- src/core/AnimatedStyle.js
- src/core/AnimatedTransform.js
- src/createAnimatedComponent.js
It was impossible to manipulate component via props which seems to be the most obvious way of applying changes into existing components
1. Attaching props has been moved to `shouldComponentUpdate` method in order to handle case when props are being change. 
2. Adding possibility to applying primitive types to transform map
3. Remove checking if primitive types are changed in `TransformNode` which is no longes necessary if we handle this changes in reactive way 
4. Add possibility to change reference to View in Animated View which is common situation if we use props to manage some properties
Changes has been explained also in inline comments
It fixes https://github.com/kmagiera/react-native-reanimated/issues/28, https://github.com/kmagiera/react-native-reanimated/issues/62 and maybe …
> Props and style sensitive for props changes

- package.json
- react-native-reanimated.d.ts
Fix some issues with Typescript definitions.
Add newly added operations such as floor()/ceil() and update onChange().
Also make sure that they are distributed when react-native-reanimated is published.
@ckknight Could you take a look at this ?
> Update and fix typescript definitions

- src/createAnimatedComponent.js
I noticed this error when porting this code to RN implementation. Sometimes the flag is called `_refHasChanged` and sometimes `_refHasChanges` which causes it to stay true forever if set.
Edit: Actually the fact that it stays true forever hid a bug, `setNativeView` needs to always be called in `componentDidUpdate` because it is possible that `_propsAnimated` changed and the new instance does not have the view set. In this case we need to call it even if the ref did not change. `setNativeView` already no-ops if the ref is the same so no need to do any checks.
> Always call `setNativeView` in `componentDidUpdate`

- src/core/AnimatedEvent.js
Make to be compatible with RN https://github.com/facebook/react-native/blob/5c2720b089dd0fb277771b0ac8b0e7788c493e5d/Libraries/Animated/src/AnimatedEvent.js#L96
and handle not sending events to native via bridge via RNGH
> Add __isNative AnimatedEvent

- src/ConfigHelper.js
Hopefully this should be a native prop and not a UI prop — text color animates after I call `addWhitelistedNativeProps({ color: true })`
Closes #99
> Add color as a whitelisted native prop

- Example/.babelrc
- Example/README.md
- Example/android/app/build.gradle
- Example/android/settings.gradle
- Example/cli.config.js
- Example/ios/ReanimatedExample.xcodeproj/project.pbxproj
- Example/package.json
- Example/yarn.lock
- ios/Nodes/REAPropsNode.m
- package.json
- yarn.lock
Inspired by: https://github.com/callstack/react-native-paper/tree/master/example
and https://blog.callstack.io/adding-an-example-app-to-your-react-native-library-d23b9741a19c
cc: @satya164 😻, thanks!
> Make it possible to develop without copying library to node_modules

- Example/src/interpolate/AnimatedBounds.js
Since we allow more types to be handled, null is no loner casting to 0 on android
> Fix interpolate example on Android

- react-native-reanimated.d.ts
Trying to use reanimated with typescript results in bunch of `Namespace 'Animated' has no exported member 'EasingFunction'` errors because `Animated.EasingFunction` is not being exported.
> EasingStatic references Animated.EasingFunction but it's not being exported

- react-native-reanimated.d.ts
Adds the `<Animated.Code>` component and a props type for a render or `exec` prop. Is it right that this should always return an `AnimatedNode<number>`?
Render prop or `exec` should be exclusive, based on how its implemented (`exec` takes precedence), but my TypeScript experience is too limited to figure that out.
> Add Animated.Code component to TS types

- android/build.gradle
With the latest react-native version RN >= 0.57 the android build tools were updated and now using `compile` in the build.gradle file generates the following error:
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
> Update build.gradle to remove compile warning

- src/core/AnimatedEvent.js
@osdnk I'm sorry about this but accessing Proxy will result in a ReferenceError on Android and iOS 8 & 9
> Revert back to typeof to avoid ReferenceError: Can't find variable Proxy

- android/build.gradle
If a project uses a different sdk for compiling they will run into issues with this project since the versions are hard coded. This applies a change similar to some other libraries to take the versions specified for the project or fallback to the currently hardcoded versions.
> Use versions from project configuration if available.

- src/createAnimatedComponent.js
Proptypes are no longer supported by RN and has been removed from core of RN in favor of Flow.
It fixes this commit and merging it was a mistake.
https://github.com/kmagiera/react-native-reanimated/commit/e75377aa98a2baaf9e9c23e73663d340934b4b0e
> Remove prop-types from AnimatedComponent

- Example/progressBar/index.js
I think it's more natural if animation do not perform so often. Once per second looks better imho and it's a better example of this library usage. 
Also, removed animations if "fetch" is finished
> Improve progress example

- README.md
The example `runTiming()` method in the readme ignores new destination values passed in while the clock is running. It should instead update the `config. toValue` field each time a new `dest` value is passed in.
> Fix bug in example runTiming() method

- Example/Interactable.js
Issue has been described here https://github.com/kmagiera/react-native-reanimated/issues/182
Using imperative snapTo in `Interactable.View` sometimes didn't lead to any effect. 
It was caused by a fact that clock was not running and therefore changes haven't been evaluated properly. If GH responsible for dragging hadn't beed activated, clock was not running and then snapping without dragging was expected to run  with clock stopped. 
Added extra condition for it.
> Add additional check for running clock for imperative snapTo

- react-native-reanimated.d.ts
This PR allows using `.start()` without passing a callback to it (like `Animated` from `react-native` does 😅).
> [TypeScript] "start" callback should be optional

- .eslintrc.js
- src/Animated.js
- src/core/AnimatedCode.js
- src/core/Core.test.js
Added improved error messages to Animated.Code when wrong props are passed to the component. Also, unified the types both the exec and children can accept. Both `exec` and `children` can now accept a node or a function returning a node.
Example:
```
const node = block([...]);
const nodeFn = () => node;
// All of the following lines are now valid
<Animated.Code exec={node} />
<Animated.Code exec={nodeFn} />
<Animated.Code>{node}</Animated.Code>
<Animated.Code>{nodeFn}</Animated.Code>
```
I've created some tests to assert the error is being thrown when wrong prop types are provided. I've create a separate suite for testing Animated* components. I'm not really skilled in writing tests so this might be wrong. 
Also, I've added the `jsx-uses-react` eslint rule to prevent false negatives when …
> Better error messages when using Animated.Code

- README.md
- react-native-reanimated.d.ts
- src/derived/index.js
- src/derived/useCode.js
I'm not sure about the current stance on adding hooks to `react-native-reanimated`, but this adds an `Animated.useCode` hook with an API halfway between `useEffect` and `Animated.Code`, that serves as an alternative to `Animated.Code`. Instead of passing in a callback, the user passes in a reanimated node to execute, along with an array of dependencies. Since we use `useEffect` under the hood, any change in the dependency array also causes the node to be updated.
One piece of behavior that I'm still iffy on is what happens if a dependency array isn't passed in. The idea is that one is always passed in (the typings reflect this), but right now, not passing one in causes the node to be re-run on every render. I think this is expected enough that we can leave it as is.
Also, this is kind of …
> Add Animated.useCode hook as an alternative to Animated.Code

- src/Transitioning.js
Previously we used `static contextType` in order for react to propagate context as a variable to components. Apparently this API isn't supported in still popular versions of react. This PR changes it to use old `Provider` API with render props which works across all of the most recent versions.
> Use legacy context API to support older versions of react

- react-native-reanimated.d.ts
The TS type signature for `concat` only allows string nodes right now, but it should also allow number nodes, JS string values, and JS number values, e.g.
```typescript
set(rotateX, concat(translateY, "deg"))
```
This PR changes the instances of `AnimatedNode<string>` in `concat`'s parameter types to `Adaptable<string> | Adaptable<number>`. This works since we internally run `adapt` on the arguments of `concat`.
> Add numbers and non-node values to concat type

- android/src/main/java/com/swmansion/reanimated/nodes/JSCallNode.java
On Android JSCall exception is thrown type of node's value was string
Added condition for checking if type of node is a string and then handle it properly.
> Allow call's input to be a string on Android

- ios/Transitioning/REAAllTransitions.m
Converting a type with boxed constraints caused `Illegal type 'CATransform3D' (aka 'struct CATransform3D') used in a boxed expression`.
Thanks @sochalewski for the tip.
Fixes #236
> Convert CATransform3d using [NSValue valueWithCATransform3D]

- ios/Transitioning/REATransitionAnimation.m
We would like iOS simulator's "slow animation" mode to work with Transitions. Apparently it only applies to UIView animations and not to lower level Core Animations. However there is a way to detect that mode is turned ON and slow down animations manually by adjusting their duration. This solution is compied direclty from RN core where it's been done for Animated.
> Support 'slow animation' setting for Transitioning API

- README.md
This might have been fixed in a newer version of reanimated (I'm using the version shipped with expo32) but currently `min` and `max` only accept exactly two arguments.
> 📚Minor documentation fix

- Example/Interactable.js
`dragEnabled` is used as a property name, not `enabled`
> 💚 Fix typo

- .travis.yml
In React Native Gesture Handler repo we have integration with travisCI to test if our Example apps are building and some detox e2e tests on iOS. I thought that it is not much work to add CI here as we already have config and project config is similar so it would most likely work out of the box with little tweaks.
Added yaml config file and travis CI integration
> Add CI integration

- README.md
After looking at the color example and also testing it, it looks like set returns a node that represents this value. If my assumption is correct, I'd like to make the set description more clarified.
> Clarify set node description

- mock.js
- package.json
I was recently using reanimated in react-navigation where I needed to mock it to be able to run it in Jest. It'll be great if the mock was in the library so we don't have to duplicate it in every project.
I looked through the typescript definitions and added a mock function for almost everything. I didn't use anything specific to a test runner such as Jest, so it should be possible to use the mock with any test runner.
> Add a mock implementation for test runners

- Example/metro.config.js
glob-to-regexp does not [escape backslash as of version 0.4](https://github.com/fitzgen/glob-to-regexp/pull/13) which causes issues on windows machines because path.resolve value contains backslashes. replacing backslashes with slashes only on windows machines fixes the issue.
Here's the resulting regular expressions produced by glob-to-regexp **before** making changes:
```
/^C:\Users\sjjd\Documents\Repos\Official\react-native-reanimated\/node_modules\/.*$/
/^C:\Users\sjjd\Documents\Repos\Official\react-native-reanimated\Example\/node_modules\/metro\/node_modules\/fbjs\/.*$/
```
Here's the resulting regular expressions produced by glob-to-regexp **after** making changes:
```
/^C:\/Users\/sjjd\/Documents\/Repos\/Official\/react-native-reanimated\/node_modules\/.*$/ …
```
> Fix example app's metro config on windows machines

- android/src/main/java/com/swmansion/reanimated/nodes/BezierNode.java
- src/core/AnimatedBezier.js
This check appears to be important in one issue. It guarantees that the function generated by a Bezier function is a surjection and is inspired by CSS on web. However, there are cases where it could be useful because it gives a wider range of parametrization. 
E.g.: 
``Easing.bezier(0.5, 0.3, -0.37, 1)`` leads to: 
Which will be very useful while imitating this path:
http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/res/res/interpolator/fast_out_extra_slow_in.xml
We want to add it in react-navigation 
Nothing more but removing errors' throwing.
> Get rid of Bezier's arguments check

- src/core/AnimatedNode.js
Since `__addChild` etc. are called so many times, using a for loop makes it faster by around 10ms at least (on iOS simulator, on device it might be even more).
> Replace forEach with for loop

- ios/REANodesManager.m
This PR is a proof of concept on how to address issues like #160 #309. 
As outlined in [my comment](https://github.com/kmagiera/react-native-reanimated/issues/160#issuecomment-502143873), the problem with the current batched updates are that reanimated lags behind event processing by at least one event, in some cases up to 3-4. If using something like react-native-gesture-handler this is generally not noticeable as reanimated will be responsible for positioning all elements, but when deriving an animated value from a scroll event this would cause the elements positioned by reanimated to be out of sync with the scroll view. 
To address the lag, this PR introduces a concept of "direct events", that will bypass the queue and apply its effects immediately. Due to my unfamiliarity with the …
> Bypass animation queue for onScroll events

- react-native-reanimated.d.ts
It looks like because all style properties are optional, they're failing the conditional type in `AnimateStyle`, because `string | undefined` does not `extend string`.
> Fix: Support optional string style types

- mock.js
Ran into the issue here:
https://github.com/react-native-community/react-native-tab-view/issues/845
This is because `ScrollView` doesn't have `.getNode()` but `Animated.ScrollView` does. 
This change fixes the error. I think this is the correct fix.
cc @simonbuerger
> Fix: jest mock should use Animated.ScrollView

- README.md
fixed broken code block at README.md by replacing "´" (backtick?) to "`"
> doc: fix broken code block

- react-native-reanimated.d.ts
Creates a type name that is non-specific to one animation function. This is useful when an animation state is shared between animation functions (spring + decay for instance).
> Remove prevPosition in SpringState

- react-native-reanimated.d.ts
Making `event` easier to use by adding event type args.
Followed [spec](https://github.com/kmagiera/react-native-reanimated#event-handling-with-reanimated-nodes).
```ts
import { PanGestureHandler, PinchGestureHandler, RectButton, NativeViewGestureHandler, State, TapGestureHandlerStateChangeEvent, TapGestureHandler, LongPressGestureHandler, LongPressGestureHandlerStateChangeEvent, PanGestureHandlerGestureEvent, PinchGestureHandlerGestureEvent } from 'react-native-gesture-handler';
const {
event,
cond,
eq,
set
} = Animated
const value = new Animated.Value(0);
// in case an event has multiple args
event<[LongPressGestureHandlerStateChangeEvent, PanGestureHandlerGestureEvent]>([
{
nativeEvent: {
state: (state) => cond(eq(state, State.ACTIVE), …
```
> add event type to event mapping

- mock.js
Following https://github.com/kmagiera/react-native-reanimated/issues/355 , `createAnimatedComponent` is not present in `mock.js` file and makes jest test crashes.
> Add createAnimatedComponent to mock

- react-native-reanimated.d.ts
*Rationale*
Currently `Animated.View`, `Animated.Text`, `Animated.Image`, `Animated.ScrollView` are exported as `const`ants with a `React.ComponentClass` type. This means they cannot be used as generics in (for example) `React.Ref<Animated.View>`, and that the useful `getNode()` method is not typed.
PR addresses this by changing the constants to `React.Component` class exports, decorated with the `getNode()` method
> [TypeScript] Specify component typings as React.Component classes

- src/core/AnimatedBlock.js
- src/core/InternalAnimatedValue.js
This PR optimizes the way we create and cleanup value nodes.
When adapting constants (e.g. when doing `interpolate({ inputRange: [0,1]})` we generate new nodes for start and end of the range) we've been creating new animated value nodes. This kind of nodes can never be updated on the native side and hence there is no need to send its final value back to JS when they get detached.
On top of there there are several constant values that are frequently used across the library and product code with reanimated. Those can only be instantiated once and reused in all the places. That list includes `0`, `1` and `-1` for now.
These two changes reduce the number of nodes instantiated by one third on `colors/index.js` example (from 88 down to 57) and reduce the number of nodes we call `getValue` for …
> Optimize constant nodes creation and cleanup

- Example/android/build.gradle
Ran into the following error when building on android with RN 0.61.1:
```
* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Cannot get property 'supportLibVersion' on extra properties extension as it does not exist
```
> Update android Example project build.gradle to build with RN 0.61

- README.md
Following [#111](https://github.com/kmagiera/react-native-reanimated/pull/111), `movable` example was disappeared. But [readme.md](https://github.com/kmagiera/react-native-reanimated/blob/master/README.md#event-handling-with-reanimated-nodes) points to deprecated example link.
> Fix invalid url in readme.md (example in event handling)

- react-native-reanimated.d.ts
Typescript 3.7-beta failed to compile it with `Node` type.
> fixed EventArgFunc typings

- mock.js
i'm getting errors in my tests from this mock as the `new Value(0)` call throws for arrow functions, this seems to work when i updated my mock.js in node_modules.
> fix: mock.js NOOP to allow for "new" constructor call

- README.md
- react-native-reanimated.d.ts
- src/derived/useCode.js
fixes #343 
This can enable us to save some unnecessary node creation but more importantly, it will enable us to benefit from the Exhaustive Deps eslint rule. This rule expect a callback as first parameter: https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/src/ExhaustiveDeps.js#L64
This rule is incredibly useful to avoid bugs when using hooks that have dependencies.
@osdnk what do you think?
> 🎣Allow to pass a callback as parameter of useCode()

- README.md
Following https://github.com/kmagiera/react-native-reanimated/issues/355#issuecomment-533455387 it's true that there is no easily accessible documentation about how to set up Jest tests with reanimated.
@kmagiera Are you fine to have it in the README or would you like to see it somewhere else ?
> Add Jest doc to the README

- package.json
- src/Animated.test.js
- src/Transitioning.js
- src/animations/DecayAnimation.js
- src/animations/SpringAnimation.js
- src/animations/SpringUtils.js
- src/animations/TimingAnimation.js
- src/animations/backwardCompatibleAnimWrapper.js
- src/core/AnimatedFunction.js
- src/core/InternalAnimatedValue.js
- src/core/createEventObjectProxyPolyfill.js
- yarn.lock
Fixes several issue with the ESLint setup in the project (see #420). The entries for the configured configs and plugins were missing from `devDependencies` (which made assumptions on the local state of the developer machine).
It also includes a couple of minor fixes/updates to other devDependencies (in separate commits). For example, `@types/react-native` had an invalid version specifier.
Finally, all Lint errors have been fixed and the project now passes lint checks cleanly.
Fixes #420
<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the PR head branch. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the …
> Fix ESLint dev setup and errors

- ios/Transitioning/REATransitionAnimation.m
- src/animations/backwardCompatibleAnimWrapper.js
After implamenting "Slow Transitions" feature an issue was introduced with Transitioning API as you can see here https://github.com/tomasgcs/react-native-reanimated/commit/4ef8b81df3f8981cb1dbd9ef0b7867165f2236c0#diff-a7ea5763fc80cde0b741dca6a5095a18R46
Previously `beginTime` variable was not set at all which was equal to 0, but after this specific line was added the value is different, and it causes animations to delay even if `delayMs` value is not set, this happens only when animation is is being executed multiple times.
Not sure why this is happening but most likely that `CACurrentMediaTime()` introduces delay even if it takes current time. In my case it is very important to run animations as fast as possible so I've sumbitted a fix here.
> Fixes transitioning API delay when delayMs is not set

- android/build.gradle
Trying to open or build the `android/` folder was not possible, due to a missing `buildscript` block:
```
ERROR: Plugin with id 'com.android.library' not found.
```
After adding the reference to the source of the `library` plugin, the following error showed up:
```
ERROR: Failed to resolve: androidx.transition:transition:1.1.0
```
This was caused by missing entries in the `repositories` block. Added the necessary references to resolve the errors.
It is now possible to individually open and build the `android/` folder in Android Studio (or build it on command line, after generating a Gradle wrapper).
Note that these changes will not affect consumer (app) projects - The Android Gradle plugin is included _conditionally_, meaning the dependency classpath _only_ gets added when the project is …
> Fix Android Gradle setup

- Example/README.md
closes: #480 
- Add instructions to `pod install` before `react-native run-ios`
> Update docs for running examples on iOS

- Example/widthAndHeight/index.js
Android doesn't support negative fontSize and crashes when animating Animated.View, so we set it to 0 when negative
Fixes #294
> Fix width and height example crashing on android

- docs/pages/09.code.md
- react-native-reanimated.d.ts
- src/derived/useCode.js
And makes the code clearer (it seems clearer to me 😜)
> Allow useCode 1st parameter to return undefined, null or an array

- android/src/main/java/com/swmansion/reanimated/transitions/ChangeTransition.java
- android/src/main/java/com/swmansion/reanimated/transitions/TransitionUtils.java
Fix relating to #272. Stops children from disappearing on transition.
> fixed children disappearing on transition.change

- Example/package.json
- Example/yarn.lock
Updating gesture-handler removes warning with usage of deprecated `[RCTRootView cancelTouches]`
> Bump gesture handler from 1.4 to 1.5

- .babelrc
- .travis.yml
- babel.config.js
- jest.config.js
- package.json
- src/__mocks__/ReanimatedModule.js
- src/core/Core.test.js
- src/derived/interpolate.test.js
- src/derived/useCode.js
- yarn.lock
> Fix tests' config

- src/derived/interpolate.js
WHY:  
resolves: https://github.com/software-mansion/react-native-reanimated/issues/235
To compute a proper value for an input, we divide in code by input range size which is incorrect for ranges that have sizes equal to zero.  This pull-request fixes this bug.
How it's implemented in Animated:
https://github.com/facebook/react-native/blob/master/Libraries/Animated/src/nodes/AnimatedInterpolation.js#L140
> Make interpolate consistent with react-native animated lib

- android/src/main/java/com/swmansion/reanimated/nodes/OperatorNode.java
Related to: https://github.com/software-mansion/react-native-reanimated/issues/495
> [Android] Fix EQ and NEQ operators. 

- Example/ios/Podfile.lock
- Example/test/index.js
- android/src/main/java/com/swmansion/reanimated/nodes/ClockNode.java
- android/src/main/java/com/swmansion/reanimated/nodes/ClockOpNode.java
- android/src/main/java/com/swmansion/reanimated/nodes/ParamNode.java
- ios/Nodes/REAClockNodes.h
- ios/Nodes/REAClockNodes.m
- ios/Nodes/REAParamNode.h
- ios/Nodes/REAParamNode.m
- src/core/AnimatedParam.js
- src/core/AnimatedStartClock.js
- src/core/AnimatedStopClock.js
Proc can accept clock as params but previously it was not possible to make clock ops (start and stop) on this bc of some assumptions in native code.
I this PR I handle this case in all places on both platforms.
You can verify it with a test example in the example app.
Tested and verified that there are no regressions.
> Make clock ops workable inside procs

- docs/pages/03.start.md
Add `pod install` instruction in Getting Started page.
Regarding this issue https://github.com/software-mansion/react-native-reanimated/issues/519
> add Pod install instruction in Getting Started page

- react-native-reanimated.d.ts
Without this patch, the following is considered a type error:
```tsx
cond(0, 3, cond(0, 1, 2))
```
```
Argument of type '3' is not assignable to parameter of type 'Adaptable<1 | 2>'.
```
> Fix: bug in cond() TS typing

- src/core/AnimatedEvent.js
In 'Pan, rotate and zoom (via native event function)' example we call set() inside event() node using a function. Inside event() we create proxyHandler
which override `get` and `set` method. Set wasn't returning any value, so implicitly returned `undefined` which is a falsy value resulting in a crash.
Now we return true if we updated `__val` and false otherwise
Closes issue #521
(https://github.com/software-mansion/react-native-reanimated/issues/521)
Proxy#set docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/set
> Add return values to Event function Proxy

- ios/REANodesManager.m
- src/createAnimatedComponent.js
The issue has been discovered while testing onScroll listener with react-native-webview. After investigating it turned out that there are two problems:
1) WebView was expecting a listener to be assigned to the native component and only with the listener preset the events would be dispatched
2) On iOS we weren't translating event names properly. Some older component still follow "topSth" naming convention while we were solely relying on "onSth" convention for direct event.
In order to address (1) we now assign an empty listener to component properties that have Animated.event object assigned. This way native component knows there is a listener assigned and can start dispatching events that we hijack on the native side.
To fix (2) we matched the orifinal Animated implementation and adapted …
> Fix issue with some events not propagating correctly via Animated.event

- src/core/AnimatedParam.js
- src/core/AnimatedSet.js
- src/core/AnimatedValue.js
- src/core/InternalAnimatedValue.js
- fix #481
- throw errors for better debugging when types are passed incorrectly
> [web][fix] Add setValue to InternalAnimatedValue

- src/core/AnimatedEvent.js
- src/core/AnimatedNode.js
- the purpose of this PR is to remove the non-standard method call in favor of an API that has more parity with native. This should also fix some issues where gesture updates freeze.
This change won't be backwards compatible and will require a version of RNGH with this https://github.com/software-mansion/react-native-gesture-handler/pull/905. However RNGH will be fully backwards compatible with reanimated. This shouldn't be a huge issue as reanimated barely works on the web currently.
> [web] Changed how values are updated with Animated.event to prevent freezing

- Example/Interactable.js
stopClock was not working on this example.
I base the fix out of this comment: 
https://github.com/software-mansion/react-native-reanimated/issues/182#issuecomment-519632308
I had trouble with the prettier/husky the format might not be perfect:
> fix: clockStop not working #467 #182

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
- ios/REANodesManager.m
In procs it happens, that parent might not be present and this should not be breaking
> Fix procs handling by removing parentNode check

- src/createAnimatedComponent.js
Would be nice to add displayName for the createAnimatedComponent.
> Add displayName to createAnimatedComponent

- android/src/main/java/com/swmansion/reanimated/nodes/OperatorNode.java
Fixes regression made by https://github.com/software-mansion/react-native-reanimated/commit/59bd12106286aa967bfb7ad534373e8c2289c550
Closes https://github.com/software-mansion/react-native-reanimated/issues/551
We have observed that while evaluating neq or eq, the second param might be `null`. After https://github.com/software-mansion/react-native-reanimated/pull/498 it started causing  `NullPointerException` so I made a special check for that. Additionally, I allowed the first param to be nullable as well.
> Handle issue in eq and neq when any of params is null

- src/core/AnimatedCallFunc.js
- src/core/AnimatedNode.js
- src/core/AnimatedParam.js
- src/core/AnimatedValue.js
- fixes "test" example - all boxes animate across the screen
- fixes "interpolate" example - now boxes don't jitter when you drag them
- fixes "colors" example - now colors interpolate smoothly rather than snap to highest RGB
- fixes "image viewer" example - no more jittering when the user stops panning
- fixes snapping to edges in "chat heads" example - doesn't fix the bug where other chat heads don't follow main one
- changes "different spring configs" to go from jittery circles to not moving circles (¯\\_(ツ)\_/¯)
- doesn't fix any of the interactable examples
Adding more JS support for the features added by this PR https://github.com/software-mansion/react-native-reanimated/pull/354 we should be more careful in the future not to add native-only features.
> [web] Added support for callID

- src/core/InternalAnimatedValue.js
In the `different spring config's` example, the value `const transX = new Value();` resolves to NaN on web, but `null` (and then a proper number) on native. Perform the `undefined -> null` conversion upfront so all platforms function as expected.
> Fix case where `new Animated.Value()` is NaN on web

- src/core/AnimatedAlways.js
- src/core/AnimatedBezier.js
- src/core/AnimatedBlock.js
- src/core/AnimatedCall.js
- src/core/AnimatedCallFunc.js
- src/core/AnimatedClockTest.js
- src/core/AnimatedConcat.js
- src/core/AnimatedCond.js
- src/core/AnimatedDebug.js
- src/core/AnimatedFunction.js
- src/core/AnimatedNode.js
- src/core/AnimatedOperator.js
- src/core/AnimatedSet.js
- src/core/AnimatedStartClock.js
- src/core/AnimatedStopClock.js
Because there is no node registry on web, we don't want to sanitize the nodes to be just the ID. Unifying the sanitation means we can choose exactly how we want to reference nodes based on platform. 
This will be used for assigning [transform values with `Animated.event` in RNGH](https://github.com/software-mansion/react-native-gesture-handler/blob/8e189f21632bc4d8bc95b0bb2c79d530427c1859/web/GestureHandler.js#L408)
> Unify sanitizing nodes for platform

- src/core/InternalAnimatedValue.js
Reverts software-mansion/react-native-reanimated#548
`undefined` is not casting to null and that's the reason for the https://github.com/software-mansion/react-native-reanimated/issues/563 regression.  
rel: https://github.com/software-mansion/react-native-reanimated/issues/561
> Revert "Fix case where `new Animated.Value()` is NaN on web"

- src/core/AnimatedClock.js
- src/core/AnimatedParam.js
Fixes https://github.com/software-mansion/react-native-reanimated/issues/558
rel: https://github.com/software-mansion/react-native-reanimated/issues/561
Regression made with: #534 
In this PR I get rid of the cycle of requires which cause warnings by fixing one of the imports
> Remove cycle of requires in AnimatedParam

- src/core/AnimatedValue.js
The current implementation of setValue is not accepting value as a node so for now, I'd like to revert to the old mechanism in this case in order to limit a regression
> Fallback to old mechanism of setting value if value is a node or string

- src/core/AnimatedClock.js
This value is not used anywhere and might lead to confusions
> Remove useless exports of the main clock

- ios/REANodesManager.m
It's a follow-up of this PR #560 fixing this issue i=on iOS. Calling selectors on nil is not an error, but assertion throws and following #560 we should allow it.
> Remove RCTAssertParam from REANodesManager.m

- mock.js
I ran into a number of issues using `react-native-reanimated/mock` while migrating from react native Animated Api. These changes seem to fix everything for me.
- Missing `Transitioning` and `Transition` components
- Missing `createTransitioningComponent` higher order function
- `AnimatedValue` has no `interpolate` function (backwards compatibility issue)
- Created a mock for the `color` `AnimatedNode`
- `react-native-reanimated/mock` exports Animated as the default export when it needs to be both export as default and have it's child properties as named exports.
> updates to reanimated mock

- mock.js
Was facing some errors while testing with jest and found this quick fix.
> fix TypeError: Cannot read property ' __value' of undefined

- mock.js
**Issue:** Previously `Transitioning.View` in the mock used the `createMockComponent`. The issue is that this function doesn't return a component which has the `animateNextTransition()` function. So when doing `ref.current.animateNextTransition()` in your tests, this line will crash because of the function not existing.
**Fix:** This commit ensures that `Transitioning.View` is mocked by using `createTransitioningComponent` function which provides the `animateNextTransition` function to the ref.
> Fix Transitioning.View in mock.js

- package.json
- yarn.lock
Adding release-it to make releases easier.
Added a custom check for changes in ios/ and android/ folders, which prevents releasing patches when minor ver. should apply. Unfortunately, release-it doesn't support hook return codes, so it crashes :/
Hopefully, the comment above check is sufficient to know what went wrong.
> Add release-it

- src/core/createEventObjectProxyPolyfill.js
As #639 says, when we set __isProxy prior to traversing its children, one of `traverse` calls uses __isProxy as key, so we have obj[__isProxy] === true, so we try to set true.__isProxy
Fixes #639
> Set __isProxy after traversing children in createEventObjectProxyPolyfill

- react-native-reanimated.d.ts
When using `createAnimatedComponent` with Typescript, it would blow away the type of the inner component. This means that JSX code completion and type inference would no longer work.
This solves this by passing back the same type that was input, so that the exported component will have the expected prop types.
> Use component type in createAnimatedComponent

- android/src/main/java/com/swmansion/reanimated/nodes/OperatorNode.java
Fixes #609 
Android was throwing an error when number was compared to undefined (due to null to Double cast), whereas iOS was returning false in such situation.
In order to make the behavior the same I added check for null value in lessThan and greaterThan operator nodes. If value is null the operator returns false, if not it proceeds with comparison.
> Fix greaterThan and lessThan operators platform differences

- android/src/main/java/com/swmansion/reanimated/nodes/ConcatNode.java
Fixes #677
When using `concat` node on `Value` which is an integer, Reanimated created a string with leading zeroes on Android and string without leading zeroes on IOS.
This PR fixes this and also fixes the localization of formatted numbers.
```jsx
import { SafeAreaView, TextInput } from 'react-native';
const { Value, concat, createAnimatedComponent } = Animated;
const price = new Value(44.5);
const AnimatedTextInput = createAnimatedComponent(TextInput);
return (
<>
<SafeAreaView>
<AnimatedTextInput
underlineColorAndroid="transparent"
editable={false}
{...{ text: concat('', price), style: { color: 'black' } }}
/>
</SafeAreaView>
</>
);
};
```
Pre-fix Screenshot:
Post-fix …
> Hide leading zeroes on int number in concatNode

- react-native-reanimated.d.ts
`TransformsStyle["transform"]` is an array prop so we should infer it's element type, apply `Animated.Adaptable` and construct it back. Otherwise `Animated.Adaptable` applies to `Array` keys (`length`, `map`, `forEach`, etc).
Truly fixes #297
> Fixed incorrect transform style prop typings

- react-native-reanimated.d.ts
Currently the return type for `block()` is the same as the parameter type. This is a problem because the parameter type can be quite heterogeneous. For instance:
```
block([
set(value, 1),
not(value)
])
```
Has a return type of `Value | Node`. With this patch, it will have a return type of `Node`
> fix(TypeScript): Fix return type for block()

- package.json
Adding ios/build as a negated pattern in the `files` section of `package.json` prevents releasing build artifacts in npm after accidentally building ios project in the root folder.
> Add ios/build to npm package.json blacklist

- android/src/main/java/com/swmansion/reanimated/nodes/ConcatNode.java
It turned out that IOS doesn't take locale into consideration when formatting `NSNumber`, so this commit fixes that on android
- Add `Locale.ENGLISH` to enforce formatting with a dot
- Add `setGroupingUsed(false)` to prevent grouping thousands (1000.0 doesn't get formatted into 1,000)
Fixes #718
> Fix formatting numbers in concat node

- .github/workflows/main.yml
Workflow fails with error:
```
yarn run v1.22.4
$ component-docs build && gh-pages -d dist
- Building pages…
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
✔ Successfully built pages in 13784ms (dist)
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
```
> Add bot publishing creds to workflow

- .github/workflows/autosquash.yml
- .github/workflows/main.yml
Placing `git config --local` commands before checkout wasn't the best idea, so I moved it right before docs generation.
I also added the autosquash workflow to simplify the merging process, mainly by generating useful commit messages consisting of PR description instead of listing all commits (we squash them anyway).
We need to add `AUTOSQUASH_TOKEN` to secrets which will be Personal Access Token or App Token (described in a comment inside workflow).
> Adjust workflow

- .github/workflows/main.yml
The previous change would try to run `gh-pages -d dist` command which failed and this should be done on next step by workflow anyway.
> Adjust workflows 2

- ios/REANodesManager.m
It's already declared a few lines below
here: https://github.com/software-mansion/react-native-reanimated/blob/dup/ios/REANodesManager.m#L32
> Remove duplicated interface of RCTUIManager

- react-native-reanimated.d.ts
Reverts software-mansion/react-native-reanimated#696
Reverting, introduced bug #719 - described in [comment](https://github.com/software-mansion/react-native-reanimated/issues/719#issuecomment-611435860)
Quick fix, may be improved by typings in #723
> Revert "Use component type in createAnimatedComponent"

- .travis.yml
- Example/ios/Podfile.lock
Travis job for osx was failing when log was too big
`.travis.yml`
- add `-quiet` option to `xcodebuild`
- use `xcbeautify` to format output
- add missing keys to root job
- remove deprecated `sudo` key
> Make osx build quieter, update Podfile.lock

- docs/pages/05.value.md
- react-native-reanimated.d.ts
- src/Animated.js
- src/useValue.js
When working with functional components this is easy to make bugs with statement, that I already saw several times from different people:
```ts
function MyComponent() {
const value = new Value(...);
}
```
This will lead to creating new value instance for every re-render. And components, that use internal value of previous instance will be reset to the new one, and this will lead to visual bugs. So one should always keep the same instance wrapping it either in `useRef(new Value(...))` or `useMemo(() => new Value(...), [])`
This PR adds hook, that could be used in very often simple case of creating instance of `Value` without extra wrap:
```ts
function MyComponent() {
const value = useValue(0);
}
```
> Add useValue hook

- Example/.gitignore
- Example/src/src/interpolate/InterpolateColorsExample.js
- Example/src/src/interpolate/index.js
- docs/pages/11.baseNodes/color.md
- docs/pages/11.baseNodes/interpolate.md
- docs/pages/11.baseNodes/interpolateColors.md
- react-native-reanimated.d.ts
- src/derived/index.js
- src/derived/interpolateColors.js
Lets users animate colors with `react-native-reanimated` without the need of additional helper functions like [this one](https://github.com/software-mansion/react-native-reanimated/issues/181#issuecomment-528245794) or [this one](https://github.com/wcandillon/react-native-redash/blob/master/packages/core/src/Colors.ts#L136). 
Also will help avoid people from running into a problem "_why does this color doesn't animate?_ :(" like I did today in the morning in one of my projects. :)
Fixes https://github.com/software-mansion/react-native-reanimated/issues/181 .
> feat: Add `interpolateColors` function

- docs/pages/10.event.md
- docs/pages/12.animations/springUtils.md
Links are broken since files from Examples were moved to Examples/src in https://github.com/software-mansion/react-native-reanimated/pull/709
Fixed links to examples folders
> Fix: links to examples in docs

- ios/Nodes/REAOperatorNode.m
Fixes #797
iOS operators implementation used `CGFloat` which is a typedef for `double` / `float` depending on OS architecture. This caused some precision errors on big numbers, so this PR fixes that by changing the type to double.
Transitions and Bezier node wasn't changed, because they're responsible for visuals and not calculations - doesn't need to be exact.
- change type from `CGFloat` to `double` in operator macros.
- change `fmodf` to `fmod` in `modulo` node
Tested on [snack](https://snack.expo.io/@levibuzolic/reanimated-math) provided by @levibuzolic
> Use double instead of CGFloat in iOS operators

- README.md
**Update README's Example section** adding instructions about the cocoapods dependencies installation step when running the test app on iOS devices, that information was missing and could lead to issues while setting up the Example project. Also separating the iOS instructions from Android instructions to make it clear what step belongs to each of the platforms.
> Update README's Example section

- react-native-reanimated.d.ts
Update for this change:
https://docs.swmansion.com/react-native-reanimated/docs/migration#1-interpolate-reanamed-to-interpolatenode
interpolate -> interpolateNode
N/A
> Rename interpolate to interpolateNode in d.ts

- docs/src/theme/DocPage/styles.module.css
Some items on docs sidebar didnt fit (api section)
Fixes sidebar width from default 300px to 22rem.
Fixes # .
> Adjust docs sidebar width

- src/reanimated2/animations.js
Noticed my velocity isn't getting applied to withSpring. Then noticed it resets it on start.
This change fixes this. ChatHeads example works great with that change.
- Fix usage of passed velocity to withSpring
> V2 fix withSpring user config velocity usage

- docs/docs/installation.md
Based on the [playground diff](https://github.com/software-mansion-labs/reanimated-2-playground/commit/f6f2b77496bc00601150f98ea19a341f844d06a3), `AppDelegate.m` should be changed to *.mm filename and hence renamed to `AppDelegate.mm`.  But the docs seem to add a second change, which is to also use "a" instead of "e" in the otherwise correct spelling of "delegate" and hence `AppDelagate.mm`.
Figured that this was an unintentional misspelling that may lead to some small but unnecessary confusion and worth fixing.
In installation docs, change new filename from `AppDelagate.mm` to `AppDelegate.mm` in order to remain consistent with the change in Reanimated Playground example and avoid confusion.
> Fix misspelling in installation.md

- src/reanimated2/NativeReanimated.js
Since we expect this module exists on the native site and not supporting the opposite case, I believe it's worth throwing as soon as possible and use a dedicated method for that to clearly say that native module is missing.
replace `TurboModuleRegistry.get` -> `TurboModuleRegistry.getEnforcing`
> Use getEnforcing when loading Reanimated turbo module

- src/reanimated2/Colors.js
This example fixes color interpolation. If the shared value is a number, it is a pass-through via UpdateProps. This small change enables this example: https://www.dropbox.com/s/zy7rv95ax5w5bzp/demo.mov?dl=0 that leverages color interpolation on a View but also an SVG component.
> V2: Fix Color interpolation 🎨

- Common/cpp/Tools/RuntimeDecorator.cpp
- plugin.js
The Typescript [fix](https://github.com/software-mansion/react-native-reanimated/pull/862) revealed another issue with overzealous babel polyfills. The pull-request solves two most important problems caused by  @babel/plugin-transform-object-assign and @babel/plugin-transform-parameters.
Fixes problem with nested worklets by adding 'global' to our blacklist and providing dummy __reanimatedWorkletInit implementation on UI side.
Additional info: 
1 "Object.assign" 
Babel plugin "@babel/plugin-transform-object-assign" transforms Object.assign() call into (0, _extend.default)() where _extend is a module with Object.assign polyfill. Because the plugin do that we capture _extend object and bad things happen.  This pr renames "Object" to "Object__DO_NOT_TRANSFOR" in each Object.assign call on …
> Avoid unnecessary babel polyfills and fix problem with nested worklets.

- docs/src/theme/Navbar/index.js
Fix `Navbar` component to correctly use `className` instead of `class`
> Use className instead of class in Navbar (docs)

- mock.js
Fixes #621 
We also came across this issue when trying to write our jest tests for our components that use `react-navigation` v5 and material top tabs.
- Added default value for getValue in parity with `#val`  https://github.com/software-mansion/react-native-reanimated/blob/9c0e3c8a6fff9283f9365d87fd205898caa6a3b9/src/val.js#L2
- Properly map call nodes in parity with `#call` https://github.com/software-mansion/react-native-reanimated/blob/9c0e3c8a6fff9283f9365d87fd205898caa6a3b9/src/core/AnimatedCall.js#L48
> Fix getValue() and call() in the mock

- react-native-reanimated.d.ts
Hi there 👋
First, thanks for this great library and the work in maintaining it :)
While i was working with `react-native-svg` a drop in FPS on Android, and after investigate all possible solutions and following #537 (@owinter86 ), that it perform not as expected.
but then going throw the code base, i notice that only `addWhitelistedNativeProps` was exported but not `addWhitelistedUIProps`.
- Exported `addWhitelistedUIProps` type
without using `addWhitelistedUIProps`
with using `addWhitelistedUIProps`
> chore: export addWhitelistedUIProps type

- Common/cpp/SharedItems/Shareable.cpp
- Common/cpp/headers/NativeModules/NativeReanimatedModule.h
- src/reanimated2/Hooks.js
- src/reanimated2/animations.js
- src/reanimated2/core.js
This change makes it possible to start animations using `withTiming` and similar methods directly on the RN JS thread.
For that to work the following changes were made:
1) On the c++ side, when updating mutable value we now need to call setter. As the value is kept on the "remote" side we run the setter on the UI thread using scheduler
2) On the JS side we need to distinguish between cases when `withTiming` and similar methods are called to determine initial style in `useAnimatedStyle` vs when they are called to be set under `.value` prop. To do that we wrap initial updater calls in `useAnimatedStyle` with a method that sets updates global variable, then read that variable and depending on its state we either return the initial value or the animation.
3) All animation definitions needed …
> Enable starting animations from RN thread.

- Common/cpp/Registries/WorkletsCache.cpp
- package.json
- plugin.js
- yarn.lock
WHY:
Because we want reproducible builds.
HOW:
Use a hash function from https://www.npmjs.com/package/string-hash-64.
REMOVE DEBUG CONSOLE.LOG !!!!!!!!!
> Use function hash as workletID instead of a random number.

- src/reanimated2/Hooks.js
This PR fixes the problem when animations would be prematurely stopped when part of a nested style object (e.g. transforms).
An example is when we'd use the following structure in `useAnimatedStyle`:
```
{
transform: [
{ scale: withSpring(something) },
{ translateX: somethingElse }
]
}
```
In this case when running updates, and when the spring from scale hasn't finished yet, we'd not take into the account updates made to translateX.
The root cause of that was that we were using `Object.every` when iterating over array. Every would return prematurely when one item return false (which is the case when scale animation is running -> it returns false).
In order to apply the style correctly we need to visit all elements of arrays or objects. This PR changes use of `Object.every` to just a loop …
> Fix issue with skipping animations on nested style objects.

- src/reanimated2/animations.js
This PR fixes the problem with timing animations being interrupted in `useAnimatedStyle` (e.g. as a result of some shared value triggering style update).
An example where the problematic behavior can be seen is when we have the following animated style structure:
```
{
opacity: withTiming(toggle.value ? 1 : 0.5),
transform: [ { translateX: valueFromGesture.value } ],
}
```
In the above case, when gesture is active, the style will update in each frame. As a consequence, we will start new timing animation in each frame which is fine. The problem is that timing animation would not handle such interruption well.
What we'd ended up seeing, is that newly spawned timing animation will progress very slowely. This is due to the fact that easing curve makes the animation start slowely. When …
> Fix issue with interrupting timing animations.

- Example/ios/ReanimatedExample/AppDelegate.mm
- docs/docs/installation.md
- docs/versioned_docs/version-2.0.0-alpha/installation.md
Just a small change which enables dev menu on iOS. Useful, for instance, when in need of switching fast refresh on and off or reloading an app.
> enable ios dev menu

- Common/cpp/SharedItems/Shareable.cpp
- Common/cpp/Tools/RuntimeDecorator.cpp
- Example/ios/Podfile.lock
- plugin.js
1 Pass closure by global object instead of "this expression".   
2 Use function name in function expression.
Before:
```JS
function () { const { } = this.closure_;
```
After
``` JS
function name () { const {} = jsThis.closure_; { name(sth)}
```
Additional Info:
"jsThis" is a global's property that is changed just before function call and reverted after.
We have to restore a previous value because it may be needed later.
Example
```JS 
function worklet1(x) {
'worklet';
worklet2();
// sth from closure
}
```
remember old jsThis -> set worklet1's jsThis -> call worklet1 -> remember old jsThis (worklet1's) 
-> set worklets2's jsThis -> call worklet2 -> restore old jsThis -> restore old jsThis.
Why do we need this change?
Example:
```JS
function fib(n) {
'worklet';
console.log("fib", n);
if (n …
```
> Support recursive worklets

- docs/docusaurus.config.js
- docs/src/theme/Layout/index.js
Use `Reanimated` string in the page title to not clutter it with `React Native` prefix which helps when you have one than one docs open.
> Use 'Reanimated' in docs title

- src/reanimated2/animations.js
WHY:
When we call withTiming twice in a row then nothing will happen because the first animation won't be started and as a result, we will copy undefined values from it.
> [withTiming] Check if previousAnimation has been started

- src/animations/timing.js
When investigating [react-native-tab-view bug](https://github.com/react-native-community/react-native-tab-view/issues/967) I noticed that we implicitly rely on `nextPosition` NaN value evaluating to falsy value in `cond` check when the duration is zero (division by 0 in `nextProgress` and `progress`). 
This PR adds explicit check for it and as a byproduct, we create much fewer nodes in duration=0 case.
This may be discussable when using Reanimated directly, but when some library exposes API which can change `duration` I think it's worth doing that check explicitly.
Another strategy may be throwing an error, tell me WDYT.
- Added explicit check for `config.duration === 0` when using `timing` node
> Exit `timing` immediately when duration is zero

- Common/cpp/SharedItems/FrozenObject.cpp
- Common/cpp/SharedItems/MutableValue.cpp
- Common/cpp/SharedItems/MutableValueSetterProxy.cpp
- Common/cpp/SharedItems/RemoteObject.cpp
- android/src/main/cpp/headers/NativeProxy.h
WHY:
resolves: https://github.com/software-mansion/react-native-reanimated/issues/941
HOW:
return null when event is null.
> Fix problem with null events and remove pragmas from source files.

- Common/cpp/SharedItems/MutableValue.cpp
- src/reanimated2/Hooks.js
WHY:
We have to notify mappers about their dirtiness right away because they won't execute otherwise.
(Actually, they will but on next render).
> Fix mappers' execution.

- plugin.js
Some of the plugins that are used by metro-react-native-preset or by babel itself don't update correctly bindings properties in scopes. Because we use bindings in order to find all the missing variables to capture them we have to work with scopes that reflect a current state in AST.
Example:
``` JS
let {x, y} = obj;
``` 
is changed to 
```JS
let _obj = obj,
x = _obj.x,
y = _obj.y;
```
by babel-plugin-transform-destructuring.
However, in binding, we only find [x, y].
Work on a copy of worklet tree with proper bindings:
``` JS
const copyWithCorrentBindings = Parser.parse('(' + fun.toString() + '\n)');
traverse(copyWithCorrentBindings, {...visitors}); 
```
----------------------------------------------------
Most of the babel presets used by React Native developers contains plugins that …
> Fix problem with wrong closure and add possibility to blacklist other plugins.

- android/src/main/JNI/Application.mk
Building on every ABI takes time and it's less efficient for our needs.
> Use only x86 ABI when building on CI

- Example/reanimated1/colors/index.js
- Example/reanimated1/differentSpringConfigs/index.js
- Example/reanimated1/imageViewer/index.js
- Example/reanimated1/imperative/index.js
- Example/reanimated1/interactablePlayground/examples/IconDrawer.js
- Example/reanimated1/interactablePlayground/real-life-examples/RealChatHeads.js
- Example/reanimated1/progressBar/ProgressBar.js
- Example/reanimated1/rotations/index.js
- Example/reanimated1/src/interpolate/AnimatedBounds.js
- Example/reanimated1/src/interpolate/Basic.js
- Example/reanimated1/src/interpolate/InterpolateColorsExample.js
- Example/reanimated1/src/interpolate/WithDrag.js
- Example/reanimated1/startAPI/index.js
- Example/reanimated1/test/index.js
Reanimated 2 changes `interpolate` and `Easing` to `interpolateNode` and `EasingNode` respectively.
When making that change examples weren't updated and didn't work.
This PR fixes this
- Renamed interpolate and Easing functions
- Removed dead code from examples
> Fix Reanimated 1 examples

- docs/pages/09.code.md
- src/core/AnimatedCode.js
`Animated.Code` and `Animated.useCode` were doing basically the same thing, but `Animated.Code` was written using class components and most of its code was error checking. This PR removes `Code` implementation and uses `useCode` instead, which ensures that they're behaving in the same way. We can safely assume that Reanimated users are using RN >0.59.
Fixes #332 
- used `useCode` in `Animated.Code` implementation
- added `dependencies` property to `Animated.Code` which serves same purpose as second argument in `useCode`
This change was checked against `Animated.Code` example in Example app and with the following example:
```js
import { SafeAreaView, Text } from 'react-native';
const { useCode } = …
```
> Make Animated.Code use Animated.useCode internally

- src/core/AnimatedValue.js
- src/derived/interpolate.js
```
Invariant Violation: outputRange cannot include 0deg. (0deg,360deg)
This error is located at:
in Test (at App.js:46)
in RCTSafeAreaView (at SafeAreaView.js:55)
in SafeAreaView (at App.js:45)
in App (at renderApplication.js:40)
in RCTView (at AppContainer.js:101)
in RCTView (at AppContainer.js:119)
in AppContainer (at renderApplication.js:39)
checkValidNumbers
interpolate.js:84:6
interpolate
interpolate.js:107:20
interpolate
AnimatedValue.js:31:23
componentWillMount
Test.js:36:47
```
I think it's used often, but there's an error.
The goal is to be compatible with Animated, so I added it once.
But I don't know the structure of this project.
So I added FIXME.
```typescript
<Animated.View
style={[
styles.box,
{ transform: [{ rotate: concat(this.trans, 'deg') }] },
]}
/>
```
I found out …
> Add the converting code of deg at animated value

- mock.js
Fixes https://github.com/software-mansion/react-native-reanimated/issues/612
> fix missing `Value.interpolate` in jest mock

- Example/src/LightboxExample.js
- src/createAnimatedComponent.js
Fixes #701, fixes #452
This issue gave me motivation #701 
React Native in 0.62 changed the way to perform operations on Animated components like ScrollView.
I tried to take a look at
https://github.com/facebook/react-native/commit/66e72bb4e00aafbcb9f450ed5db261d98f99f82a
And build something similar.
I managed to reuse some of Facebook's code.
> Use forward ref in createAnimatedComponent

- src/core/AnimatedBlock.js
- src/core/InternalAnimatedValue.js
Reanimated doesn't have any use case for holding `null` value in the `Animated.Value` besides using `defined` node to set it to some initial state, so we're relying on `undefined` being treated as that "empty" value. 
In order to prevent some obscure errors when `null` is used we introduce explicit check for creating Value with `null` - it works when instantiating new Value and using imperative `value.setValue()`. 
We don't need to change the `set` node, because it expects `double | AnimatedValue` to be used as it's second argument.
> Forbid using null in Animated.Value

- Example/ios/Podfile.lock
- Example/ios/ReanimatedExample/AppDelegate.h
- Example/ios/ReanimatedExample/AppDelegate.mm
- docs/docs/installation.md
- ios/REAModule.h
- ios/REAModule.m
- ios/native/NativeProxy.h
- ios/native/NativeProxy.mm
Initialize global bridge variable in AppDelegate.jsExecutorFactoryForBridge. It's cleared in REAModule.invalidate. 
Checked if reload works on iOS.
resolves: https://github.com/software-mansion/react-native-reanimated/issues/979
> Simplify installation process on iOS.

- src/reanimated2/animations.js
The commit message really says it all: remove the undefined (and unused) toValue variable from withDecay.
> Remove the undefined (and unused) toValue variable from withDecay

- docs/docs/installation.md
Update info about:
- useTurboModule step on Android (We no longer use TurboModuleManager on Android)
- The constructor signature of TurboModuleManager  has changed on iOS
> Update installation guide.

- ios/Nodes/REANode.m
Fixes #793 
Previously, `nil`s were replaced with 0's when memoized inside `[Node value]` (`NSMutableDictionary` doesn't support `nil`s as keys) and `defined(new Value(0))` returned true.
Now we store NSNull there and return `nil`, which fixes calling defined on the node with the undefined value.
Tested on iOS and android, `defined` returns the correct value in both.
```js
const {block, debug, defined, Value, useCode} = Animated;
const Example = () => {
useCode(() =>
block([
debug('undefined:', defined(new Value())),
debug('0:', defined(new Value(0))),
debug('1:', defined(new Value(1))),
]),
);
return null;
};
export default Example;
```
> Fix defined node

- src/Animated.js
- src/reanimated2/interpolation.js
I've found out I'm using it many times in my codebase (and supportive libraries) and thus it became difficult for me to get it renamed automatically (bc there were different imports' names etc). So I've added an error thrown while calling `interpolate` with a node (duck-typed).
Throwing an error in the first argument seems to be a reanimated node. 
Also, I observer that currently it's not possible to use new features with default imports. I've added it because we were doing it previously.
> Throw an error when trying to use new `interpolate` with nodes

- Example/src/MeasureExample.js
- Example/src/ScrollToExample.js
This PR gets rid of the reload error caused by using hooks conditionally and in the same time changes functionality slightly(heights of all the items are calculated on every render) but as for test it should be fine. Also visible limit bar has been added to `scrollTo` example
> fix measure reload, add scrollTo visual limit

- src/core/AnimatedCode.js
#952 notably simplified `Animated.Code`, but introduced regression - when passing nodes directly it shows a warning coming from `useCode`. To fix that we wrap those nodes into a function.
Fixes #1008 
- Check if passed nodes are wrapped in a function
- Re-add some error handling for `Animated.Code`
Changes were tested against `useCode` example (nodes extracted from the function)
> Fix passing nodes directly to the Animated.Code

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/SharedItems/MutableValue.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/Tools/Mapper.cpp
- Common/cpp/headers/SharedItems/MutableValue.h
- Common/cpp/headers/SpecTools/ErrorHandler.h
- android/src/main/cpp/AndroidErrorHandler.cpp
- android/src/main/cpp/headers/AndroidErrorHandler.h
- ios/native/IOSErrorHandler.h
- ios/native/IOSErrorHandler.mm
- src/reanimated2/Hooks.js
- src/reanimated2/animations.js
Improve error handling by adding some cases in `Hooks.js` and `animations.js` regarding lack of `.value` field when passing shared value objects.
As a little refactor changed `const char*` to `std::string` in ErrorHandler due to obeying coding best practices.
Also moved catching errors higher in the calling hierarchy, which is not a problem since when there is no error set in error handler it just rethrows.
> @karol/fix error handling

- src/createAnimatedComponent.js
Fixes #219 
Fixes #762
Previously components were flickering when mounted due to asynchronously updating component styles.
In `createAnimatedComponent()` we filtered out styles with Animated nodes, then component rendered with default values,
then nodes were initialized on the native side and applied their styles.
This issue was mostly observed when layout styles were changed, for example when setting height like in the example below.
This fix relies on updating the value of `Value` when nodes are detached (`__detach()` in `InternalAnimatedValue`) because it updates its value on the JS side. Without that this fix would only work on the first mount (when initial values are used).
Example:
```js
import {Button, Text, View} from 'react-native';
import Animated …
```
> Fix flickering on mount

- docs/versioned_docs/version-1.x.x/nodes/stopClock.md
Previously, docs were not consistent with implementation (which doesn't prevent the clock from updating when stopped).
> Update stopClock's docs

- android/build.gradle
Fixes #1024 
Solution was taken from https://github.com/facebook/react-native/issues/28298.
I was able to successfully build all required files on Fedora 32
```bash
android-npm/react-native-reanimated-62.aar
android-npm/react-native-reanimated-63.aar
react-native-reanimated-2.0.0-alpha.4.tgz
```
- Change `wrapNoInt` template function invocation to it's code, after downloading folly
> Fix CI for Android

- react-native-reanimated.d.ts
`Easing` was renamed to `EasingNode` after the release of v2 but types weren't updated.
> Rename `Easing` to `EasingNode` in TS types

- src/reanimated2/animations.js
Update implementation of `cancelAnimation` to make it work from both UI and JS threads. Before this change, cancelling animation would only work from UI thread. Now, we use a simple trick of assigning the current (static) value to the shared value which results in the animation being cancelled.
This PR updates the implementation of `cancelAniamtion` to make the provided sharedValue reassign its `.value` prop to its current `.value`. This results in the animation (if it is running on the shared value) to stop at the current point. This change isn't ideal as it may have a side-effect of triggering mappers that depend on the provided value. The previous implementation wouldn't trigger mapper updates as it wasn't modifying the `.value` prop but only some underlying animation-related data kept …
> Make cancel animation work from JS thread.

- Example/src/AnimatedTabBarExample.js
fixes React's warning `Warning: Each child in a list should have a unique "key” prop` by adding keys in `map` function calls
> Fix key warning in tabbar

- react-native-reanimated.d.ts
I believe that it is optional in the JS implementation.
> Make `interpolate` `type` optional

- Example/src/MeasureExample.js
- Example/src/ScrollToExample.js
- src/reanimated2/Hooks.js
- src/reanimated2/NativeMethods.js
Create new hook `useAnimatedRef` to provide a functionality of animated reference which acts as a normal reference on the javascript thread but at the same time holds a view tag of the component which it is referring to through a shared value.
It was created to simplify code of `scrollTo` example but may be used in other cases as well.
> Add useAnimatedRef

- react-native-reanimated.d.ts
Fixes #1021.
This commit fixes regression introduced in #959 (f5eaf18) by specializing a generic parameter.
The previous implementation was failing with error:
```
node_modules/react-native-reanimated/react-native-reanimated.d.ts:237:36 - error TS2314: Generic type 'Adaptable' requires 1 type argument(s).
```
because `Adaptable` generic type was not specialized.
References:
www.typescriptlang.org/docs/handbook/utility-types.html#parameterst
www.typescriptlang.org/docs/handbook/utility-types.html#returntypet
> Update proc type

- src/derived/diffClamp.js
Fixes #570.
Fixes #767.
Creating procs of stateful functions (like diff or diffClamp) make them effectively a singleton, which means that every instance of it shares nodes (Value nodes in particular). 
In Reanimated most of derived nodes are proc'ed and stateful ones are `diff()`, `diffClamp()`, `acc()` and `onChange()`. We export those as plain JS functions, creating state out of proc'ed functions. This works because every use of them creates a new, non-shared state. When one of those functions is used in proc context, they're created once – they share state.
The example below shows this behavior.
```js
const {Value, block, proc, set, useCode, debug, add} = Animated;
const procStateful = proc(x => {
const state = new Value(0.5);
return …
```
> Make diffClamp non-proc'ed

- src/animations/backwardCompatibleAnimWrapper.js
Fixes #899.
When using backward compatible API to animate unmount of component it showed "Error: Trying to remove a child that doesn't exist" error. This was happening because by the time animation wrapper called `__detach()` on passed value, the Animated component would detach it by `componentWillUnmount()` lifecycle method (detaching styles when the component unmounts). This change checks for if Value is still initialized natively and only then calls `__removeChild(value)`.
```jsx
import React, {useState} from 'react';
import {SafeAreaView, Button} from 'react-native';
import Animated, {timing, Value, Easing} from 'react-native-reanimated';
export default function Example() {
const [showRect, setShowRect] = useState(true);
const opacity = new Value(1);
const t = () =>
timing(opacity, { …
```
> Check if node is initialized when detaching

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
Previously, we were using deprecated c-tor of `GuardedRunnable`. This PR switches to c-tor taking exception handler as an argument.
References:
- [C-tors, notice that deprecated one is using internally `reactContext.getExceptionHandler()`](https://github.com/facebook/react-native/blob/d3ac9fa0c3780b43b73de97831b75cf0a7efe9c4/ReactAndroid/src/main/java/com/facebook/react/bridge/GuardedRunnable.java#L19-L26)
> Update deprecated use of `GuardedRunnable`

- android/src/main/java/com/swmansion/reanimated/nodes/ParamNode.java
- ios/Nodes/REAParamNode.m
Fixes #809.
Fixes #789.
Fixes #594.
The current implementation of procs creates proxies for every parameter used (which can be any animated node).
Those proxies hold a ref to the params as nodes, forwarding every method which can be used on them (`setValue()` for Values, `start()` and `stop()` for clocks, etc). When proc is called, a context for every param is created (which allows using procs in procs (in particular creating recursive functions)). Those contexts are used for memoization to ensure we don't reevaluate nodes that were calculated previously. 
The problem was in updating this memoized value when using `AnimatedParam.setValue()` - it only updated the value of the underlying node and left `AnimateParam` value unchanged. It's updated in current call ID in opposition to Value …
> Fix setting values inside procs

- ios/native/RENativeMethods.mm
While testing new measure function noticed pageY is returning the same value as pageX
- Fixed typo in RENativeMethods.mm in measure function
> Fix typo in iOS measure implementation

- react-native-reanimated.d.ts
This fixes the scroll handler types which were missing the context parameter.
It also makes the context type stricter, forcing the user to type their contexts. In my use-cases, forcing me to type my contexts has been helpful to auto-detect potential bugs in my code.
> Fix scroll handler types and make context types stricter

- Example/test/FastRefreshTest.js
- Example/test/TestApp.js
- src/reanimated2/Hooks.js
This is supposed to provide a proper way to handle React Native's [Fast refresh](https://reactnative.dev/docs/fast-refresh) and also rerender of a component containing certain animations.
On component rerender all of the worklets which are included into that component are not rebuilt. This introduces following problems:
1. If someone changes worklet's body it will not be updated using React Native's [Fast refresh](https://reactnative.dev/docs/fast-refresh)
2. When worklet uses component's state and this state changes(causing rerender) that worklet will use outdated state value
<details>
<summary>ad. 2 example</summary>
``` JS
const Comp = () => {
const [state, setState] = useState(0)
const udv = useDerivedValue(() => {
return state
})
return (
<>
<Button title="press" onPress={ () => { …
```
> Handle rerender behaviour

- docs/docs/api/nativeMethods/measure.md
- docs/docs/api/nativeMethods/scrollTo.md
Added following note to `measure` and `scrollTo` docs:
> Due to time constraints we weren't able to finish this page.
> Add note to docs

- Example/src/ScrollEventExample.js
One `<View style={styles.half}>` should be enough to get the job done
Remove unnecessary wrapper clone
> Remove unnecessary wrapper in scroll example

- android/src/main/java/com/swmansion/reanimated/nodes/TransformNode.java
After changing original nested ternary in #538 to if-else chain double case didn't have an assignment, so it was crashing with a null value for transform style error.
```jsx
import {SafeAreaView, Text} from 'react-native';
return (
<SafeAreaView>
<Animated.View
style={{
transform: [{translateX: 100.2}],
}}>
<Text>Test </Text>
</Animated.View>
</SafeAreaView>
);
};
```
> Fix non-animated properties in `transform`

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
Previously, `NodesManager` registered (passing this) as an event listener before ending initialization in c-tor.
`NodesManager` is created by `ReanimatedModule` (when calling `getNodesManager()` for the first time) on [UI thread](https://github.com/software-mansion/react-native-reanimated/blob/9af276693d136b712259fe9dd0126aee6c78bd4b/android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java#L77-L80).
When `onEventDispatch()` is called on non-UI thread it calls `startUpdatingOnAnimationFrame()`, which in turn uses `mChoreographerCallback`.
`mChoreographerCallback` is initialised **after** listener is registered which causes NPE in React Choreographer's `postFrameCallback()` method after trying adding callback to the queue.
Fixes #604.
References: …
> Fix initialisation of NodesManager

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
This change breaks projects using Reanimated with RN 0.59 where the second overload of the `GuardedRunnable` c-tor didn't exist. Reverting this ensures backward compatibility.
> Revert "Update deprecated use of `GuardedRunnable`"

- src/reanimated2/Colors.js
This PR fixes a problem with processColor method crashing when executed on the JS thread.
The reason for the crash was that the cached object containing matches wasn't initialized on the JS thread but only on the UI thread. We used RemoteObject for that purpose, as we needed to make sure that RegEx instances we put in that object are constructed in the right VM (those objects cannot be simply moved between UI and JS). In order for matchers to be available on the JS thread, we also need to have them instantiated on the JS thread.
This PR changes the matchers caching logic such that we select the correct cache with matchers depending on the thread we run in, and we also instantiate the matchers on both JS and UI threads in order to cache them in the correct cache.
I tested this by importing …
> Fix color processing on the JS thread

- ios/native/RENativeMethods.mm
The issue has been described here https://github.com/software-mansion/react-native-reanimated/issues/1108
The problem happens when we call `scrollTo` inside `onScroll` worklet.
Inside iOS implementation we call synchronously `scrollToOffset` with on `RCTScrollView` 
https://github.com/software-mansion/react-native-reanimated/blob/master/ios/native/RENativeMethods.mm#L40
Then the scroll actually happens emitting `onScroll` event at the same time:
https://github.com/facebook/react-native/blob/fcb667059d3156327c141eadeed7f3cb771d8f79/React/Views/ScrollView/RCTScrollView.m#L1037
Then it calls a method in the event emitter https://github.com/facebook/react-native/blob/ffdfbbec08b1afb1970d2cfe75a78a203d4a79a4/React/Base/RCTEventDispatcher.m#L134
However, this line of code has been already …
> Fix app freezing when calling scrollTo inside onScroll

- src/reanimated2/animations.js
I cannot get overshootClamping to work in v2 and it seems to be because of this condition no? I couldn't make sense of it from a logical perspective. My apologies with I missed something.
> Fix `overshootClamping` in `withSpring`

- src/reanimated2/animations.js
I use this extra parameter so that when I'm "pausing" the loop, I can remember in which direction it was going. The direction is updated at the end of each iteration via callback().
```ts
repeat(
withTiming(1 - dest.value, {
duration: 1000,
easing,
}),
-1,
true,
() => (dest.value = 1 - dest.value)
)
```
> Add callback parameter to repeat()

- react-native-reanimated.d.ts
According to docs, both those values have defaults so they should be optional.
Only changed types in types definition, no executable code is changed.
Please refer to [documentation](https://docs.swmansion.com/react-native-reanimated/docs/next/api/withTiming)
> Mark `WithTimingConfig` TS type fields as optional

- docs/docs/api/repeat.md
- src/reanimated2/Hooks.js
- src/reanimated2/animations.js
Add callbacks for `delay`, `sequence` and `repeat`.
- for `delay` the callback of the inner animation's now going to be called after that animation ends(finished or being cancelled)
- for `sequence` there are two cases:
- the sequence finishes - after every animation passed to it that animation's callback is being called
- the sequence is being cancelled - for those animations which have not been called yet due to cancellation the callbacks are being called(with `finish = false`)
- in repeat, the callback passed to the inner animation will be called on every repeat. The first argument tells us whether the animation finished or was cancelled. The second one hold animation's current value(when the animation has been cancelled it is `undefined`). The callback passed to `repeat` is called in …
> Add callbacks for animations

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
`NativeProxy.prepare`(followed by `installJSIBindings`) is called twice one call after another. First call is in `NativeProxy` constructor and the other one is in `NodesManager.initWithContext` right after the `NativeProxy` object is created.
This PR removes one of the calls.
> Remove redundant call on Android

- Common/cpp/Tools/Scheduler.cpp
- Common/cpp/headers/Tools/Scheduler.h
- android/build.gradle
- android/src/main/JNI/Android.mk
- android/src/main/cpp/AndroidScheduler.cpp
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/headers/AndroidScheduler.h
- android/src/main/cpp/headers/NativeProxy.h
- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/java/com/swmansion/reanimated/Scheduler.java
- ios/native/REAIOSScheduler.h
- ios/native/REAIOSScheduler.mm
fixes: https://github.com/software-mansion/react-native-reanimated/issues/1131
Pass CallInvokerHolder to the NativeProxy just like we do with jsContext. The only hack used here is creating an empty shared library `libturbomodulejsijni` that's loaded by `CallInovokerHolderImpl.java`. It's not directly used by The `CallInovokerHolderImpl` so it's safe.
TODO:
> Use CallInvoker to fix Promises in callbacks.

- Example/test/AnimatedReactionTest.js
- Example/test/TestApp.js
- plugin.js
- src/reanimated2/Hooks.js
Added a new hook - `useAnimatedReaction` which takes 2 arguments(both are worklets):
1. `prepare` - prepares data for the second argument. Value returned from this function is the only one argument passed to the following one
2. `react` - takes one argument which is a result from the previous function's invocation and just performs some specified operations
This hook has been added to allow performing some actions on some shared values' change. The key idea is all of the shared values included in the first worklet are the `inputs` set. Every time any of those change both worklets are triggered in the order specified above. Also the second worklet may modify any shared values excluding those used in the first worklet.
```
useAnimatedReaction(
() => {
'worklet';
return (x.value + y.value) / …
```
> Use animated reaction

- Example/src/LightboxExample.js
The react-native-reanimated@alpha.5 release introduced measure function in the worklet. Previously we used RN's async measure for that. Now we can measure things just before the actual animation. This change helps us to run the animation 10-25ms faster on my Pixel 3.
- Migrate lightbox example to native measure
> Use native measure in lightbox example

- Common/cpp/Registries/MapperRegistry.cpp
- Common/cpp/SharedItems/MutableValue.cpp
- Common/cpp/Tools/Mapper.cpp
- Common/cpp/headers/SharedItems/MutableValue.h
- Common/cpp/headers/Tools/Mapper.h
Fixing: https://github.com/software-mansion/react-native-reanimated/issues/1181
The problem linked above caused crashes in random places and after 1.5d of debugging I came up with an idea that there must be sth wrong with the memory management. Because of the problem could be reproduced with just one mapper and one animation it was clear for me that the root cause of the problem is in the notification of mapper dirtiness. We may want to notify the mapper which has been unregistered. In order to fix the problem, I added a code that removes listeners of unregistered mappers.
> Fix Navigation crash

- plugin.js
fixes: https://github.com/software-mansion/react-native-reanimated/issues/1185
During development, there is always a state where UAGH has an empty object. This pr handles that edge case.
> Handle empty object in UAGH.

- Common/cpp/SharedItems/ShareableValue.cpp
- plugin.js
Some people like to capture huge objects such as `Animated`. These objects may contain symbols that weren't handled in the past. The problem with symbols can be partially solved by converting symbols to strings. (it's better than nothing). 
Symbols cannot be converted to symbols and it can be seen in the following example: 
A->C, B->C, and C is a symbol. Then  after conversion A->C != B->C.  Another reason to merge the pr is to speed up Reanimated. Converting objects can take a lot of time. By capturing used values only we significantly reduce this time.
I've added `ClosureGenerator` class that's responsible for capturing used paths only. It takes a path with the name of the variable that would be fully captured in the previous implementation and iterates upwards in the babel nodes tree …
> Capture only used values and convert symbols to strings.

- react-native-reanimated.d.ts
Even though we use the term "finished" in the documentation, for some reason in TS types we had "isCanceled" as a callback param name which led to confusion for users.
This PR fixes it.
Fixes https://github.com/software-mansion/react-native-reanimated/pull/1199 and https://github.com/software-mansion/react-native-reanimated/issues/1198
- v2 types: Fix animation callback name (isCanceled => isFinished)
> v2 types: Fix animation callback parameter name

- src/createAnimatedComponent.js
- src/reanimated2/Hooks.js
- src/reanimated2/WorkletEventHandler.js
The following problem has been reported: the events are being reattached even when the handlers are not being rebuilt(which basically means reattaching is pointless). That resulted in a significant slowdown. The solution in this PR is to reattach events only for those handlers which body changed(basing on dependencies passed(or not) to the hook).
`createAnimatedComponent.js` - reattach conditionally
`WorkletEventHandler.js` - add `reattachNeeded` flag
> Fix reattaching

- android/src/main/java/com/swmansion/reanimated/NativeMethodsHelper.java
In `scrollTo` on Android, horizontal scroll views were not supported. This PR fixes it.
You can create a horizontal scroll view by adding `horizontal` prop like this:
`<Animated.ScrollView ref={sv1} style={svStyle} horizontal>`
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1108
> Fix scrollTo for horizontal scroll on Android

- docs/docusaurus.config.js
The banner doesn't disappear when the link is clicked and this behavior is misleading. I changed the "Docs" version picker title to more intuitive "Versions", so docs for v1 could be easily found.
> Remove banner in docs

- src/createAnimatedComponent.js
This PR fixes using `useAnimatedStyle` hook when styles are in nested arrays with depth > 1.
Before something like this worked:
```
<Animated.View style={ animatedStyle } />
<Animated.View style={[ { width: 100, height: 80, backgroundColor: 'black' }, animatedStyle]} />
```
but something like this did not:
```
<Animated.View style={[ { width: 100, height: 80, backgroundColor: 'black' }, [animatedStyle]]} />
```
From now on it's possible to nest the arrays in `style` prop as deep desired, example:
```
<Animated.View
style={[
{ width: 100, height: 80, backgroundColor: 'black', margin: 30 },
[
{ backgroundColor: 'green' },
[
{ backgroundColor: 'yellow' },
[
{ backgroundColor: 'red' },
[
{ backgroundColor: 'blue' },
[{ backgroundColor: 'purple' }, style],
],
],
],
],
]}
/>
```
This fixes …
> Fix handling useAnimatedStyle in nested styles

- react-native-reanimated.d.ts
In the latest release (alpha.6) dependencies have been added to hooks in order to make sure worklets stay up to date with the rest of the react code. But they are missing in types. This PR fixes it.
- Add hooks deps to TS types
> Add hooks deps to TS types

- Common/cpp/SharedItems/FrozenObject.cpp
- Common/cpp/SharedItems/RemoteObject.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/headers/SharedItems/FrozenObject.h
- Common/cpp/headers/SharedItems/RemoteObject.h
- Example/ios/Podfile.lock
Currently, when we want to use an object in two worklets then we have to covert the object twice. To avoid it this pr saves our jsi::HostObject as a hidden property (Object.defineProperty enumerable: false). Additionally, this pr introduces a different approach to representing FrozenObject and RemoteObject. JSC has problems with jsi::Objects that are created from HostObjects so instead of using them directly we expose frozen(not true with RemoteObject) jsi::Object and save jsi::HostObject as a hidden property.  
During makeSherable operation add a hidden property to all objects converted to FrozenObject and WorkletFunction. 
`const char *HIDDEN_HOST_OBJECT_PROP = "__reanimatedHostObjectRef";`
Remove get/set from RemoteObject and return jsi::Object on UI side and frozenObj on JS side. …
> Improve caching.

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/SharedItems/MutableValue.cpp
- Common/cpp/SharedItems/MutableValueSetterProxy.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/Tools/JSIStoreValueUser.cpp
- Common/cpp/headers/SharedItems/MutableValue.h
- Common/cpp/headers/SharedItems/RemoteObject.h
- Common/cpp/headers/SharedItems/ShareableValue.h
- Common/cpp/headers/Tools/JSIStoreValueUser.h
Because we cache jsi::Value in our host objects and we don't have control over their destruction we sometimes leave dangling jsi values. It results in reload problems. To fix the problem this pull-request changes all direct references to indirect weak ones that can be easily cleared on UI runtime destruction. StoreUser is a class responsible for those indirect references. Every our host object that uses jsi::value from UI runtime extends StoreUser class. Each indirect reference is bond to UI runtime and a host object lifecycles and is released on runtime or the host object destruction, whatever comes first.
> Fix reload once again.

- README.md
Installation link was broken on Readme. Page not found on [swmansion.com](https://docs.swmansion.com/react-native-reanimated/docs/installation)
- Installation link changed in Readme
> Fix broken installation link on README.md

- Common/cpp/SharedItems/RemoteObject.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/headers/SharedItems/RemoteObject.h
In useAnimatedStyle we hardly rely on RemoteObject ability to return the same object everytime we call ToJSValue on UI thread. The pr brings back the ability by reverting all remote object changes introduced by #1236.
> Revert RemoteObject changes.

- src/ConfigHelper.js
Add tint color to native props white list, that closes https://github.com/software-mansion/react-native-reanimated/issues/1183
> Add tint color to native props

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
While implementing https://github.com/expo/expo/pull/10383 I noticed that if Reanimated doesn't initialize `NodesManager` properly (while React fetches JSI modules from `ReanimatedJSIModulePackage`), when refreshing the app, `NodesManager` tries to call `onCatalystInstanceDestroy` on `mNativeProxy == null`.
- Wrapped `mNativeProxy.onCatalystInstanceDestroy` with `if (mNativeProxy != null)`.
> [android] Do not try to call methods NativeProxy if it's null

- docs/docs/about.md
The original link leads to a 404 page
The previous link leads to a 404: https://docs.swmansion.com/react-native-reanimated/docs/1.x.x/
Update the link to match the page from using the dropdown on the v2 docs: https://docs.swmansion.com/react-native-reanimated/docs/
> Fix dead link to v1 docs

- src/ConfigHelper.js
Added `shadowColor` to `NATIVE_THREAD_PROPS_WHITELIST` in order to make shadow box work with `useAnimatedStyle`
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1296 for iOS
> Add shadow color to native props

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
This PR adds TS typings for the introduced in #1310 API
- Added TypeScript definitions for useWorkletCallback and createCallback
- Added TS tests for useWorkletCallback and createCallback
> Add createWorklet and useWorkletCallback types

- plugin.js
- src/reanimated2/plugin.test.js
Addresses this comment here: https://github.com/software-mansion/react-native-reanimated/issues/823#issuecomment-688721886
Widens the support for identifying the reanimated2 hooks to also support BuckleScript type imports
```
import * as Reanimated from 'react-native-reanimated'
Reanimated.useAnimatedStyle(...)
```
The tests covering the babel plugin are pretty bare-bones, so I'm happy to extend those tests, or perform any manual tests needed before this goes any further.
- Support wildcard ES6 import style with babel plugin
> Support wildcard type ES6 imports

- plugin.js
- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
- src/reanimated2/Hooks.js
The pull-request adds two methods which are the new ways for telling babel that is should transform the function into a worklet. The first is `useWorkletCallback`:
```JS
useWorkletCallback(() => {...});
```
which is equivalent to
```JS
useCallback(() => {
'worklet'
})
``` 
The second one is `createWorklet` which just lets us omit 'worklet' mark.
```JS
const worklet = createWorklet(() => {
...
});
```
behaves the same as
```
const worklet = () => {
'worklet'
...
}
> Add another ways to mark function as worklet.

- docs/docs/animations.md
- docs/docs/shared-values.md
Updates docs to include imports in most examples under Fundamentals, and fixes an incorrect import under Fundamentals>Animations>Spring. The error is 
`import {
withSpring,
Animated,
} from 'react-native-reanimated';`
when it should be
`import Animated, {
withSpring,
} from 'react-native-reanimated';`
> Updated docs fundamentals to include imports

- .github/ISSUE_TEMPLATE/---bug-report-v2.md
There are a few issues where the problem was in the node version. The minimum required version of React Native itself is 12, but many users use 10.
> Add NodeJS version to issue template

- android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java
Copying a fix over from https://github.com/expo/expo/pull/10509
In `ReanimatedModule`, check if `mNodesManager` is null before calling `onCatalystInstanceDestroy`
No redbox when disabling remote JS debugging.
> Check if mNodesManager is null before calling onCatalystInstanceDestroy

- createNPMPackage.sh
Fixes #1321.
This ensures that we build every arch variant. Right now if `CI` is set we skip everything but x86 (test inside Application.mk). This was used to make CI builds faster.
> Unset `CI` env var when building npm package

- Common/cpp/Tools/JSIStoreValueUser.cpp
- Common/cpp/headers/Tools/JSIStoreValueUser.h
I believe the problems mentioned in https://github.com/software-mansion/react-native-reanimated/issues/1284 are caused by parallel read/writes operations made on hash map. We can create shared value on different threads so we should also take care of concurrent updates.
> Make StoreUser concurrent.

- plugin.js
Make `isNaN` available inside a worklet.
> Add isNaN to the globals

- docs/docs/installation.md
Mentioned in #1314.
It appears that Proguard strips code inside `com.facebook.react.turbomodule` package so we should prevent it from doing that. 
A correct fix would be to add `@DoNotStrip` annotations inside the RN core.
> Add note about Proguard in docs

- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/Tools/RuntimeDecorator.cpp
- plugin.js
- src/reanimated2/core.js
- src/reanimated2/js-reanimated/index.js
When you call a function on UI thread you can't be sure if you call a worklet or a callback from JS thread. To make it more transparent we introduce `runOnJS` method which calls a callback asynchronously. If you call a callback without this method then an exception will be thrown.
add a hidden property to every hostFunction named `callAsync` and call it in runOnJS.
resolves: https://github.com/software-mansion/react-native-reanimated/issues/1258
> Add runOnJS logic.

- Example/test/SimpleTest.js
- src/reanimated2/animations.js
`runOnJS` change made it harder to create animation callback which runs on JS thread. Previously it worked with code like this:
```
import { View } from 'react-native';
import {
withTiming,
const App = function({ componentId }) {
const progress = useSharedValue(-1);
progress.value = withTiming(
10,
null,
(isFinished) => {
console.log('clb', _WORKLET, isFinished);
}
);
}, []);
return <View style={{ backgroundColor: 'red', width: 100, height: 100 }} />;
};
```
This would just print `'clb', false, true` which meant that it runs on JS thread and the argument `isFinished` is passed correctly.
Now such code throws an error
```
Tried to synchronously call function …
```
> Decorate callbacks

- src/reanimated2/animations.js
This PR changes the default "end" thresholds used for spring animations. The thresholds are used to signal the end of animation when the spring is no longer in motion. 
This change will affect how soon completion callback is called when provided, or how soon the next animation starts when spring is used as a part of animation sequence.
The new defaults seem to make much more sense as typically the units that are being animated are pixels. When speed is 2px/sec the movement is hardly noticeable. The same applies for displacement, there was no need to use `0.001` when `0.01` continuous movement yields 0.16px/s which is an order of magnitude slower than the speed threshold. However, keeping this constant a bit more secures us from also quite typical cases when users animate within 0-1 range.
> Adjust default spring thresholds

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
- src/reanimated2/Hooks.js
This PR makes `useSharedValue` more consistent with other hooks when needed. Now it would change on every rerender when the value passed to the hook changes.
So in the following scenario
```
const [state, setState] = useState(0);
const sv = useSharedValue(state);
```
every time `state` changes(and component rerenders) `sv`'s value is updated to what's in `state`.
This is inconsistent with for instance `useState`, for which the state has to be set explicitly to get modified. However the default behavior persisted for backward compatibility.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1293
> Shared value rerender upgrade

- Example/test/SimpleTest.js
- plugin.js
- src/reanimated2/animations.js
After `runOnJS`, `callbackDecorator` has been introduced but due to inconsistencies and misleading sources of invoking animations' callbacks I decided the best thing to do is automatically workletizing all of them so they'd be launched on UI side.
This PR reverts `callbackDecorator` changes and updates `functionHooks` array(used for automatic workletization) in babel plugin.
> Workletize animations' callbacks

- Common/cpp/Registries/EventHandlerRegistry.cpp
There was TODO to migrate from inline eval. 
I'm not sure it's faster/slower right now, but I guess it will be faster.
— use createFromJsonUtf8 instead of inline eval in processEvent
> Use createFromJsonUtf8 in processEvent

- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/headers/SharedItems/ShareableValue.h
It's only a temporary solution. In the future, we will display a full JS stack trace.
> Make runOnJS more descriptive.

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/Registries/EventHandlerRegistry.cpp
- Common/cpp/headers/NativeModules/NativeReanimatedModule.h
- Common/cpp/headers/Registries/EventHandlerRegistry.h
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/headers/NativeProxy.h
- android/src/main/java/com/swmansion/reanimated/CopiedEvent.java
- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/java/com/swmansion/reanimated/NodesManager.java
Copied from https://github.com/software-mansion/react-native-reanimated/pull/1149
Previously, we were handling dispatched events like so:
```java
@Override
public void onEventDispatch(Event event) {
if (UiThreadUtil.isOnUiThread()) {
handleEvent(event);
} else {
mEventQueue.offer(event);
startUpdatingOnAnimationFrame();
}
}
```
Event handling in RN works by utilizing `EventDispatcher.dispatchEvent(event)` which
1. runs `onEventDispatch` callback on any registered listener
2. adds `event` to internal event queue
3. adds frame callback which dispatches and disposes events on JS thread
This approach introduced timing issues - RN's `EventDispatcher` dispatches events on JS thread and Reanimated handles events on UI thread. There's a possibility that `EventDispatcher` will dispose event …
> Fix event handling

- Example/src/LightboxExample.js
- src/reanimated2/animations.js
- src/reanimated2/core.js
This PR fixes lightbox example(there was a problem with `runOnJS`). 
It also introduces a fix to a bug which occurred on Android(may also appear on ios but such situation hasn't been encountered). The problem was when animation transform received negative numbers, the regex didn't work properly(putting `-` sign as a prefix instead of treating it as a part of the number).
In the meantime I found a bug in animations on the web which will be fixed in this PR as well.
> Fix negative transform

- RNReanimated.podspec
Latest Xcode 12 fails to build while without a module to depend on `React-Core` directly hence this change is necessary for all native modules on iOS. This change requires React Native 0.60.2 or newer. For more details please check: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
> [v1] fix Xcode 12 compatibility

- docs/docs/installation.md
- package.json
- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
- src/reanimated2/Colors.js
- add runOnJS typescript types
- fix link in docs' installation section
- `interpolateColor` - thanks to @mrousavy 
- add TS types tests
- add TS types
- replace `enum` with string union
> Add runOnJS types

- src/reanimated2/animations.js
related(https://github.com/software-mansion/react-native-reanimated/issues/1400)
> Fix "cannot access `repeat()` before initialisation" error on the web

- src/reanimated2/Hooks.js
This PR is a response for the problem with `useAnimatedReaction` hook. The problem is with using reference inside of that hook, because it persists the mapper's input values between rerenders. This may even work if we don't change the type of the input but the problem occurred when the input changed from `undefined` to `number`.
Reproducing code is in the issue.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1399
> Remove ref from useAnimatedReaction hook

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
Added missing types for `makeMutable` function as the function is safe to use (see https://github.com/software-mansion/react-native-reanimated/issues/1404)
In `./react-native-reanimated.d.ts`
> Add types for `makeMutable()`

- Common/cpp/SharedItems/ShareableValue.cpp
Fix the following typo after `CALLBACK_ERROR_SUFFIX` in error message + minor formatting.
> Fix typo in synchronous function call error message

- src/createAnimatedComponent.js
Fixes #1443.
Used `hasOwnProperty` instead of `in` operator which should work pretty much the same here.
> Fix access to 'viewDescriptor' property in `createAnimatedComponent`

- mock.js
processColor is exported since alpha.6 and should be available via the mock.
> Make `processColor()` available via the mock

- .github/ISSUE_TEMPLATE/---bug-report-v2.md
- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/workflows/issue-validator.yml
Adds new github action which validates every issue when they are `labeled`/`unlabeled`/`edited`(no need to launch it when an issue is created since it's being triggered by `labeled` event anyway).
For every specific label there are some sections required
- `bug` label requires sections:
- Description
- Steps To Reproduce
- Expected behavior
- Actual behavior
- Package versions
- `Feature request` label requires sections:
- Description
- Motivation
- `Question` label requires section:
- Description
A section is defined by any type of header(which is made using any number of `#` signs in the beginning of the line)
When there are any requirements that aren't fulfilled, the bot adds a comment and it keeps updating it/adding new ones until they are. It adds a new comment if there are no …
> Add issue validator

- plugin.js
- src/reanimated2/core.js
Workletize polyfills for spread operator. Blacklisting plugins which polyfill spread operator would be a perfect solution. Unfortunately, It's not possible with our current blacklisting solutions as the plugin is added by other plugins that we cannot blacklist. For instance Typescript plugin. We still want to provide the spread operator inside our worklets. In order to do this, I replace spread polyfills with workletized versions of them in `global.__reanimatedWorkletInit` method.
core.js
```Js
import React, { useState, useEffect } from 'react';
import { withTiming, withRepeat, useSharedValue, useDerivedValue, runOnUI } from 'react-native-reanimated'; 
export default function Animation() {
runOnUI(worklet_worklet)();
return (
<View …
```
> Fix spread operator.

- Common/cpp/Registries/EventHandlerRegistry.cpp
We don't want to process events with the `NativeMap` field set to `null`. Even though we use the `Nullable` annotation it still causes crashes on Android in some cases.
<details>
<summary>Tested with the following code</summary>
```
import { SafeAreaView, View, Text, StatusBar, Modal } from 'react-native';
return (
<>
<StatusBar barStyle="dark-content" />
<SafeAreaView>
<Modal animationType="slide" transparent={true} visible={true}>
<View style={{ flex: 1 }}>
<Text>Content modal</Text>
</View>
</Modal>
</SafeAreaView>
</>
);
};
```
</details>
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1444
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1447
> Don't process event with null native map

- ios/native/REAIOSScheduler.mm
Currently, we use scheduler's instance variable `module` in order to recognize if scheduling still makes sense ().  However, if the scheduler has been cleaned we are actually accessing the field of the freed object. In order to get rid of the problem, I've changed the code so we capture module variable instead of the pointer to scheduler instance.
fixes: https://github.com/software-mansion/react-native-reanimated/issues/1459
Capture a local copy of weak module ref. (REAIOSScheduler.mm)
Rapidly change sth in worklets. (hard to reproduce)
> Fix crash in scheduler.

- Common/cpp/SharedItems/ShareableValue.cpp
Improve error handling.
By using a proper `module` we omit the crash which used to occur on error catching before - the module is caught by copy instead of by reference in lambda thus there are no crashes when the `module` is no longer accessible but is used in the inner scope.
<details>
```
import { runOnUI } from 'react-native-reanimated';
import { View } from 'react-native';
export default function AnimatedStyleUpdateExample() {
const val = {};
const wrklt = (x) => {
'worklet';
x.f();
};
'worklet'
val.f(4); // will call https://github.com/software-mansion/react-native-reanimated/blob/master/Common/cpp/SharedItems/ShareableValue.cpp#L347
wrklt(9); // will call https://github.com/software-mansion/react-native-reanimated/bl …
```
> Improve error handling

- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
For the new expo versions, there is no such option as `--web-only`. Therefore we decided to remove it at the same time keeping it as a fallback instruction in the scripts for backward compatibility.
This originally showed up in our playground repo as an issue: https://github.com/software-mansion-labs/reanimated-2-playground/issues/19
It's been resolved and checked there: https://github.com/software-mansion-labs/reanimated-2-playground/pull/25/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R11
Now it's going to work for older and newer expo versions.
> Fix web app startup for Example app

- src/reanimated2/Hooks.js
When calling an animation inside the worklet passed to `useAnimatedStyle` hook, the initial value for the animation is set by calling `initialUpdaterRun` on the JS side and `lastAnimation` is not set yet. Until now we've been missing a case for that.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1477
In `Hooks.js` add a case for setting a starting value for an animation to the one from initialization(`initialUpdaterRun` in `useAnimatedStyle`)
<details>
```
import React, { useCallback, useMemo } from 'react';
import { GestureResponderEvent, Pressable, PressableProps, StyleSheet } from 'react-native';
import Reanimated, { useAnimatedStyle, useSharedValue, withSpring } from 'react-native-reanimated';
export interface PressableScaleProps …
```
> Fix animations with initial value

- Common/cpp/SharedItems/ShareableValue.cpp
- src/reanimated2/core.js
For now, if we attempt to set a shared value's value to the same value multiple times it'll go through the entire process of updating the value and also will trigger all the mappers that treat this shared value as an input.
Short pseudo code:
```
const sv = useSharedValue(50)
const uas = useAnimatedStyle(() => {
return { width: sv.value }
})
for (let i = 0; i < 1000; ++i) {
sv.value = 100;
}
```
The worklet in `useAnimatedStyle` is going to be triggered 1000 extra times even though the input(and the output) is going to be the same.
Closes #1499 
Added checks for the same values in `workletValueSetter` and only conditionally update the shared value's value.
<details>
``` …
```
> Prevent executing mappers for the same value

- Common/cpp/SharedItems/ShareableValue.cpp
- plugin.js
- src/reanimated2/__snapshots__/plugin.test.js.snap
This PR refers to a situation in which there is a javascript error in a worklet that's being executed by jsi.
On iOS with JSC, it works as expected which means it throws a `std::exception` from jsi's `call` invocation.
Unfortunately on Android, it does not. This c++ code is being scheduled on the UI thread by the scheduler and the error that appears in `Scheduler.java` is: `com.facebook.JNI.UnknownCppException: Unknown`.
This comes with two problems:
1. Our example app crashes with `A/libc: Fatal signal 6 (SIGABRT), code -6`
This may be a problem with how we build the example app(As @tmikov suggested maybe e.g. linking problem)
2. When reanimated is installed in any other app it shows Redbox with an error message: `Unknown` - this gives almost no information on what went wrong.
The good …
> Handle worklet errors on hermes

- src/reanimated2/Colors.js
cachedMatchers is lazy loaded and it is frozen when the worklet is being created - it means that is blocked to changes, is possible to call getMatchers() when object is freezed then cachedMatchers has no assigned regexs.
Fixes #1472
Fixes #1478
- Added eager initialization of cachedMatchers
<details>
<summary>Problematic code</summary>
```
import React, { Component, useEffect } from 'react';
import { StyleSheet, View, Button } from 'react-native';
withTiming,
isColor,
export default function Dwa() {
const vv = useSharedValue(10);
const stylez = useAnimatedStyle(() => {
if (vv.value > 20) {
isColor('123');
}
return { height: vv.value };
});
return (
<Button
title="One" …
```
> cachedMatchers initialization

- plugin.js
It turned out that using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) doesn't work for older node versions(confirmed for 12.x.x) but does work for newer ones(14.14.0). As we want to make it compatible with those versions we had to get rid of that feature and replace it with an equivalent solution.
Instead of using conditional chaining just watch out for a `TypeError` when reading from the object.
> Get rid of optional chaining in plugin

- src/reanimated2/__mocks__/NativeReanimated.js
- src/reanimated2/core.js
- src/reanimated2/js-reanimated/index.web.js
I have a 'console.info is not a function' error on the web
This seems there is no needed to add a custom console to global.console on web
> Add console.info on native, fix console on the web

- docs/docs/about.md
I added to documentation information about the impossibility of animating a virtual component.
For example we can’t animate nested `<Text>` components because React Native change 
```
<Text>
string1
<Text>string2</Text>
</Text>
``` 
to 
```
<RCTTextView>
string1
<RCTVirtualText>string2</RCTVirtualText>
</RCTTextView>
``` 
and the `RCTVirtualText` is a virtual component.
It is related with issue: #1455
- Updated `about.md` docs
> Add information about nested <Text> components

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
- android/src/main/java/com/swmansion/reanimated/nodes/PropsNode.java
- ios/Nodes/REAPropsNode.m
- ios/REANodesManager.h
- ios/REANodesManager.m
This PR fixes the way we perform sync updates on iOS by avoiding UIManager observers from firing. This in turn fixes the problem of ui manager commands that may be executed out of order as reported in #1498. The reason behind that issue was that due to the fact we'd trigger ui manager observers, those may enqueue some commands in the ui-manager block and we'd run them along the sync ui updates that we were expecting to get after layout phase. In the sync layout call we only expect the ui commands to come from the layout calculations and not from other sources (e.g. native animated or reanimated which uses ui manager observers to enqueue additional commands).
1) This PR wraps uimanager batchDidComplete call with additional code that temporarily removes registered ui observers and only puts …
> Don't run observer callbacks during sync uimanager batch update

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
Add `callback` to `withRepeat` type
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1538
> Add callback to withRepeat type

- docs/versioned_docs/version-2.0.0-alpha.9/shared-values.md
Just fixing a small typo: interplate -> interpolate.
I ran
```sh
$ yarn
$ yarn start
$ yarn build
```
It doesn't seem like there are any static / build changes – is this expected for simple markdown changes?
> Correct typo in Shared Values doc

- Example/android/app/build.gradle
- android/build.gradle
- android/src/main/JNI/Android.mk
To enable debug native (C/C++) code was added required changes to `Android.mk` file and `build.gradle`s.
- Added required to build.gradle and Android.mk config to enable native debugging with LLDB;
- Fixed some warnings;
Live demo of native code debug setup
[![Live demo of native code debug setup](
https://user-images.githubusercontent.com/6543359/102722766-06f01d00-430c-11eb-9771-de8ac66b3785.gif
)](https://user-images.githubusercontent.com/6543359/102721791-ad84ef80-4305-11eb-9eb5-7a9b5a72c9cb.mp4)
Live debugging demo session
[![Live debugging demo session](
https://user-images.githubusercontent.com/6543359/102722876-d197ff00-430c-11eb-880f-b5aa9b5898c6.gif
)](https://user-images.githubusercontent.com/6543359/102721798-b37ad080-4305-11eb-9a14-d6da393e36d1.mp4)
To enable native code …
> Feature: enable native code debugging via LLDB

- mock.js
> Add mocks for addWhitelistedUIProps & addWhitelistedNativeProps

- src/core/AnimatedNode.js
requestAnimationFrame is called before frame is flushed, as soon as possible.
https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame
Fixes #1520 
For example:
- Changed setImmediate to requestAnimationFrame as node update scheduler for web
Change can be seen clearly when using imperative Value.setValue(number) along with calling React.setState. React.setState is handled much faster in this scenario.
Background color in below example is updated via standard React state cycle, and position is set via ReanimatedNode.setValue. Both are fired in same synchronous scope (see below repo).
https://github.com/DrRefactor/reanimated-issue-1520-repro
I've included instructions for running versions "before" and "after". I'm not sure this is the easiest way to do so though.
> [v1] Replace setImmediate with requestAnimationFrame

- Common/cpp/SharedItems/ShareableValue.cpp
When an anonymous function is called `fn(() => {})` we can't get the name of this function. In this case the exception message isn't really helpful. I changed the exception message and also added information about worklet localization. It isn't exactly localization of this lambda/function called, but localization of the worklet where lambda/function is called.
Imrovement for PR: [#1361](https://github.com/software-mansion/react-native-reanimated/pull/1361)
Fixes #1503
<details>
<summary>Example of code</summary>
```js
import { useAnimatedStyle } from 'react-native-reanimated';
import React, { useCallback } from 'react';
export default function AnimatedStyleUpdateExample(props) {
const testfunc = useCallback(() => {
console.log('test');
}, []);
useAnimatedStyle(() => {
testfunc();
return …
```
> Information about worklet localization to exception message

- Common/cpp/SharedItems/ShareableValue.cpp
ShareableValue keeps a reference to its JS representation. Unfortunately, worklet retains `this` in lambda function what creates a reference loop.
Capture in the lambda function only necessary values.
```JS
makeShareable(
() =>{
'worklet'
//nothing
}
);
```
ShareableValue destructor is never called.
> Remove ref loop from ShareableValue

- src/reanimated2/__mocks__/MutableValue.js
- src/reanimated2/__mocks__/NativeReanimated.js
- src/reanimated2/hooks.useSharedValue.test.js
- src/reanimated2/mock.js
Previous implementation did lack "memoize" feature, essentially yielding incorrect return in certain cases.
I added mocks of `useSharedValue`'s hook in order to "unmock" this hook and use its implementation in global mock.
PR contains hook test.
> Use implementation of useSharedValue in mock

- .travis.yml
- docs/docs/api/withSpring.md
- docs/docs/api/withTiming.md
- package.json
- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
- tsconfig.json
- yarn.lock
Fixes #845.
Now we can use strings in `withTiming()` and `withSpring()` to animate color value like `"rgba(20,20,20,0)"`
> Allow string as toValue type in withTiming and withSpring

- Common/cpp/SharedItems/FrozenObject.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/headers/SharedItems/FrozenObject.h
- Common/cpp/headers/SharedItems/ShareableValue.h
- Example/ios/Podfile.lock
- Example/src/AnimatedStyleUpdateExample.js
- src/createAnimatedComponent.js
- src/reanimated2/Hooks.js
Here we will solve/discuss/work on issues related to memory leaks and also code changes in #1543.
Every case will be taken care of separately in terms of both the code and the description.
- solution
- prevent applying cache for objects containing host functions(be1cb52)
- remove ref loop from ShareableValue(#1580)
<details>
<summary>graph</summary>
</details>
<details>
```
import {
makeShareable,
import { Text } from 'react-native';
import React, { useEffect, useRef } from 'react';
export default function OneMakeShareable() {
function sth() {}
class Temp1 {
constructor(fun) {
this.fun = fun;
}
}
const ctx = useRef(null);
if (ctx.current === null) {
const temp = new Temp1(sth);
ctx.current = {
t: makeShareable(temp),
};
} …
```
> Memory leaks

- src/reanimated2/Colors.js
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1488
Fix interpolate of alpha channel. Alpha value is normalized to [0-1] float value by parser and in the next step this value is mapped to [0-255] value but mapping was without usage of round() and alpha value was still float instead of integer.
<details>
<summary>Example code</summary>
```js
withTiming,
Easing,
interpolateColor,
export default function AnimatedStyleUpdateExample() {
const color = useSharedValue(0)
const animatedStyles = useAnimatedStyle(() => {
return {
backgroundColor: interpolateColor(
color.value,
[0, 1],
['rgba(255,0,0,0.1)', …
```
> Fix interpolate of alpha channel

- src/reanimated2/Hooks.js
Fix initialization of animation value. In some case It wasn't possible to initiate animation with 0 value because `if` condition deal with 0 value and `undefined` in the same way.
Fixes: #1547
I replace `if` condition from comparing 0 to boolean to comparing with `undefined`
<details>
```js
import React from 'react'
import { Button, View } from 'react-native'
withSpring,
} from 'react-native-reanimated'
const AnimatedStyle = () => {
const offset = useSharedValue(0)
const defaultSpringStyles = useAnimatedStyle(() => {
return {
transform: [{ translateX: withSpring(offset.value) }],
}
})
return (
<View>
<Animated.View style={[{width: 50, height: 50, backgroundColor: '#001A72'}, defaultSpringStyles]} />
<Button …
```
> Fix initialization of animation value

- ios/REANodesManager.m
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1576
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1579
In https://github.com/software-mansion/react-native-reanimated/pull/1501 we forgot that sometimes we have to notify mounting listeners about a mounting. The problem we had with operation running out of order won't happen when we notify listeners after the mounting block is prepared. That's what I want to do in the pr.
It's also important to understand that we won't capture a new mounting block by calling `setNeedsLayout`because we add NodesManager as an observer only for the time of syncLayout.
Add setNeedsLayout after sync layout.
```JS
import React, { useEffect } from "react";
import { StyleSheet, View } from "react-native";
import …
```
> Fix synchronous layout.

- Example/src/ScrollableViewExample.js
The list in scroll Example app is inertness, and when list is moved and someone taps on screen and doesn't move by finger it calls only onStart() event from GestureHandler, and this sets the actual position but the list is still moving. If in the next step someone moves their finger then the list jumps to this position and starts animation of scroll from this position like in issue:
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1597
I just set the actual position of the animation to stop inertness of list.
> Fix stop condition for scroll animation in Example

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
Fixes #1614 (maybe?)
Sorry, I have no idea if this is the right fix, or just a band-aid that hides problems elsewhere.
Just skip calling .isAnyHandlerWaitingForEvent() when mNativeProxy is null
> NodesManager.onEventDispatch(): ignore mNativeProxy when null

- src/createAnimatedComponent.js
This fixes the case when we create an animated component out of a component that does not render anything(render function returns `null`).
An example would be [svg Stop](https://github.com/react-native-svg/react-native-svg/blob/develop/src/elements/Stop.tsx)
Fixes #1569 
<details>
<summary>code example</summary>
```
import Svg, { Defs, Stop, RadialGradient, ClipPath, G, Circle, Ellipse, Rect, Polygon } from 'react-native-svg';
import { Text } from 'react-native';
const AnimatedStop = Animated.createAnimatedComponent(Stop);
const Test = () => (
<Svg height="100" width="100">
<Defs>
<RadialGradient
id="grad"
cx="50%"
cy="50%"
rx="50%"
ry="50%"
fx="50%"
fy="50%"
gradientUnits="userSpaceOnUse">
<AnimatedStop …
```
> Fix no host instance case

- src/reanimated2/Hooks.js
We don't handle the case when `null` is passed as dependencies in either `useAnimatedGestureHandler` or `useAnimatedScrollHandler`. Although in types it's not an option we have to consider that not all of the users use TypeScript.
Automatic casting to boolean works fine here as `!![] === true`.
<details>
<summary>example code</summary>
```
const gestureHandler = useAnimatedGestureHandler({
onActive: (event, ctx) => {
// ...
},
}, null);
```
</details>
> Handle null deps in hooks

- src/reanimated2/Hooks.js
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1588
There is a case In `runAnimations` function (used by `useAnimatedStyle`) in which we have an array of animations.
Of course, we have to wait until the last animation from the array is done but we cannot execute finished animations. 
To prevent that I've added an additional check.
Added check if the animation has already finished.
```JS
import React from 'react'
import {
StyleSheet
} from 'react-native'
withSequence,
withSpring
// withTiming
} from 'react-native-reanimated'
// const withSpring = withTiming;
export default function SequenceBug() {
const animatedStyle = useAnimatedStyle(() => ({
// if you change every instance of withSpring to withTiming, it works.
transform: [ …
```
> do not execute finished animation

- react-native-reanimated.d.ts
- src/reanimated2/animations.js
Add support for animate string value with %
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1613
<details>
<summary>Example code</summary>
```js
withTiming,
Easing,
export default function AnimatedStyleUpdateExample(props) {
const randomWidth = useSharedValue('10%');
const config = {
duration: 500,
easing: Easing.bezier(0.5, 0.01, 0, 1),
};
return {
width: withTiming(randomWidth.value, config),
};
});
return (
<View>
<Animated.View
style={[
{ width: '100%', height: 80, backgroundColor: 'black' },
style,
]}
/>
<Button
title="toggle"
onPress={() => {
randomWidth.value = …
```
> Add support for animate string value with %

- src/reanimated2/Hooks.js
- src/reanimated2/core.js
Until now we used to break the execution of setting a new value of a mutable with animation in order to prevent going through the setting process for the same value. But we cannot do this for higher-order animations(they have the same current value as the ones they include).
The problem occurs when we have a shared value and, let's say, a couple of animations placed together in some higher-order animation like `withSequence`, and the first one has the same target value as the shared value current value. The flow stops but it should go on and execute the rest of the animations.
Another thing is we didn't support breaking animations on component unmount until now. The worst scenario(not that rare though) would be when a user would run infinite animation using `withRepeat` with repeats value …
> Fix animations

- Example/src/App.js
- Example/src/DragAndSnapExample.js
- Example/src/ExtrapolationExample.js
- react-native-reanimated.d.ts
- src/reanimated2/interpolation.js
Motivation: to see extrapolating for both sides, just like in v1.
Fixes #1255
- Added ts types for extrapolation
- Added ExtrapolationExample
- Added Error handling for invalid config or invalid interpolation value 
IDK which example is better currently 2 in this PR
https://user-images.githubusercontent.com/32239452/102691648-a03d0780-4216-11eb-90e7-7ef8a5f1590a.mov
---
https://user-images.githubusercontent.com/32239452/102694608-df755380-422a-11eb-839c-8872d1427807.mov
> Feature: interpolate: Extrapolate left/right

- android/src/main/cpp/NativeProxy.cpp
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1610
By accident, somebody wrapped a different part of the code in frameTimestamp injection logic. They were supposed to wrap frameCallback but instead wrapped a part that registers frame callbacks.
NativeProxy.cpp - wrap callback before passing it to NodesManager.
```JS
withTiming,
useAnimatedReaction,
cancelAnimation,
useWorkletCallback,
Easing,
useAnimatedGestureHandler,
import { View, StyleSheet, Platform } from 'react-native';
import { PanGestureHandler } from 'react-native-gesture-handler';
export default function AnimatedStyleUpdateExample(props) {
const animatedPosition = useSharedValue(0);
const …
```
> Inject frameTimestamp to our context for time of frame

- ios/native/NativeProxy.mm
Related issue: https://github.com/software-mansion/react-native-reanimated/issues/1610
As it turned out CADisplayLink.timestamp is the time of the last frame, not the upcoming one. 
**Context from the [docs](https://developer.apple.com/documentation/quartzcore/cadisplaylink?language=objc):** ```The target can read the display link’s timestamp property to retrieve the time that the previous frame was displayed. ... To calculate the actual frame duration, use targetTimestamp - timestamp. You can use actual frame duration in your application to calculate the frame rate of the display, the approximate time that the next frame will be displayed, and to adjust the drawing behavior so that the next frame is prepared in time to be displayed.```
**Why it is a problem?**
We use …
> Use targetTimestamp instead of timestamp

- src/reanimated2/PropAdapters.js
There were two bugs in the SVG adapter's implementation:
- overwriting translateX
- lack of parsing translate values to numbers
Fixes #1593 
<details>
```
withTiming,
Easing,
interpolate,
SVGAdapter,
import { G, Svg, Rect } from 'react-native-svg';
const AnimatedG = Animated.createAnimatedComponent(G);
export default function AnimatedSVGPropsUpdateExample(props) {
const valueToAnimate = useSharedValue(0);
const intervalId = setInterval(() => {
valueToAnimate.value = withTiming(Math.floor(Math.random() * 15000), {
duration: 1000,
easing: Easing.linear,
});
}, 1000);
return …
```
> Fix SVG adapter

- src/reanimated2/Hooks.js
- src/reanimated2/interpolation.js
- problem 1
`animationsActive` wasn't propagated to recursive calls causing errors all around.
- problem 2
There was no default value for the interpolation type. Added one for backward compatibility(that would be `extend` like [here](https://github.com/software-mansion/react-native-reanimated/pull/1549/files?file-filters%5B%5D=.js#diff-6e3ba842c35e8c6f6f93c508caf29f134d9b457f836daf7850ef592afbdda9f5L12))
> Fix animationsActive + default interpolation type

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/Registries/EventHandlerRegistry.cpp
- Common/cpp/Tools/EventHandler.cpp
- Common/cpp/Tools/WorkletEventHandler.cpp
- Common/cpp/headers/Registries/EventHandlerRegistry.h
- Common/cpp/headers/Tools/WorkletEventHandler.h
Remove naming collision that led to crashes.
> Fix naming collision

- src/reanimated2/Hooks.js
This is a fix to the changes from #1619(problem 2). This change was good, but we forgot to check the fast refresh. When the fast refresh occurs, the components are being unmounted and mounted again. That's why there's a need to manually activate (again) the animations on the component mount. 
Run [this example](https://github.com/software-mansion/react-native-reanimated/blob/416b1759c9e3b498a9835130f59f132da1fc15e5/Example/src/AnimatedStyleUpdateExample.js), change a js file to trigger the hot reload, and see that the animation does not work.
> Reactivate animations on mount

- Example/test/AnimatedReactionTest.js
- docs/docs/api/useAnimatedReaction.md
- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
- src/reanimated2/Hooks.js
In some cases, we don't want to run the `reaction` callback from `useAnimatedReaction` if the value received from the `preparing` callback doesn't change. This equality could be checked always and calling the `reaction` callback would be then conditional. However, it's better to leave the decision to the user as there are as well cases when we still want to run the `reaction` even if its argument doesn't change.
To solve the problem, keeping backward compatibility, the value of the previous call of the `preparing` callback is now being passed to the `reaction`.
Besides the cases that were mentioned here, it lets users perform more custom operations.
```Js
const x = useSharedValue(0);
const flag = useSharedValue(false);
useAnimatedReaction(
() => {
return x.value > 125 && flag.value;
}, …
```
> Add previous result to useAnimatedReaction

- src/createAnimatedComponent.js
- src/reanimated2/Hooks.js
If we wanted to update animated props of a component that renders nothing, an error has to be thrown. Until now, the error message has looked like this: `Exception in HostFunction: Value is undefined, expected a number`. This PR makes it more clear and tells what went wrong.
Fixes #1638 
```Js
class MyComp1 extends React.Component {
constructor (props) {
super(props);
console.log('x passed 1', props.x);
}
render () {
return null;
}
};
class MyComp2 extends React.Component {
constructor (props) {
super(props);
console.log('x passed 2', props.x);
}
render () {
return <View></View>;
}
};
const Animated1 = …
```
> A better way to handle exceptional situations

- docs/docs/api/useSharedValue.md
- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
- src/reanimated2/Hooks.js
- src/reanimated2/hooks.useSharedValue.test.js
This is yet one more change to the logic of the `useSharedValue` hook and it comes as a modification of #1042. We decided to bring the rerender behavior of the `useSharedValue` closer to React's `useState` - every time a rerender happens(a state is changed), a shared value is not being rebuilt and it keeps the same value.
Fixes #1655 
With that change, when having something like this `useSharedValue(x)` and changing the code that the hook receives a different value `useSharedValue(y)` it's not going to work with a fast refresh. This shared value will not have an updated value. Still, we decided to implement it that way as it's more important how it acts in the release mode than in the debug mode.
```
import { useSharedValue } from 'react-native-reanimated';
import { View, Button } from …
```
> Shared value rerender behavior

- src/reanimated2/animations.js
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1657
There was a possibility for a too deep recursion call in `withDelay` animation caused by an incorrect value of a previous animation object passed to `withRepeat`. This resulted in a recursion loop during waiting for delay time to pass. If delay time was higher call stack was able to overflow.
Example code:
```js
const fadeAnimatedStyle = useAnimatedStyle(() => {
return {
opacity: withDelay(
10,
withRepeat(
withSequence(
withDelay(
500, 
withTiming(1, { duration: 1000 })
),
withDelay(
500, 
withTiming(0, { duration: 1000 })
)
),
-1
)
)
};
});
```
or
```js
const fadeAnimatedStyle2 = useAnimatedStyle(() => {
return {
opacity: withRepeat(
withDelay(
100, 
withTiming(1, { duration: 1000 })
),
-1
)
};
});
```
I pass a …
> Fix too deep recursion call

- Example/src/AnimatedScrollExample.js
- Example/src/App.js
I noticed we don't have any examples of `useAnimatedScrollHandler` in our Example app.
The code is taken from https://github.com/karol-bisztyga/reanimated-2-playground/blob/707eea1e7edde74d8c23abe8a12f5604dfd29ab8/blog_apps/scroll_events/ScrollEvents.js
> Add useAnimatedScrollHandler example

- .github/workflows/build-npm-package.yml
I noticed that upgrading gradle version from 3.5.2 to 4.1.2 might break workflow `build-npm-package` (the build.gradle throws at https://github.com/software-mansion/react-native-reanimated/blob/master/android/build.gradle#L285). 
I then noticed https://github.com/nttld/setup-ndk which can easily handle the installation of ndk and provide the installation path.
I tried it out and [it seems to be working fine](https://github.com/UNIDY2002/react-native-reanimated/runs/1827930983?check_suite_focus=true).
Hope that this will help.
> Use nttld/setup-ndk@v1 to setup ndk

- .travis.yml
- Example/android/app/build.gradle
- Example/android/app/src/main/res/values/styles.xml
- Example/android/build.gradle
- Example/android/gradle.properties
- Example/android/gradle/wrapper/gradle-wrapper.properties
- Example/babel.config.js
- Example/ios/Podfile
- Example/ios/Podfile.lock
- Example/ios/ReanimatedExample.xcodeproj/project.pbxproj
- Example/ios/ReanimatedExample/AppDelegate.m
- Example/metro.config.js
- Example/package.json
- Example/yarn.lock
- RNReanimated.podspec
- android/build.gradle
- android/gradle.properties
- package.json
- yarn.lock
Bump  RN in Example to 0.64.0-rc.2.
I went through https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.0-rc.2
> Bump rn to 0.64.0-rc.2 in Example

- src/reanimated2/interpolation.js
In interpolation code, we want to use `Object.assign` instead of a spread operator in worklets in order to avoid errors.
> Interpolation: replace spread operator with Object.assign

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
Until now `createAnimatedComponent` took the `ComponentType<P>` parameter, and returned a `ComponentType<AnimateProps<P>>` animated component as a result.
This added a few problems, such as the loss of information on whether a component is a class or a function component.
This PR concretizizes the function to return `ComponentClass<AnimateProps<P>>` if a class component was passed, and `FunctionComponent<AnimateProps<P>>` if a function component was passed.
```tsx
const ReanimatedCircle = Reanimated.createAnimatedComponent(Circle);
function App() {
const svgCircleRef = useRef<React.Component<CircleProps>>();
return <ReanimatedCircle ref={svgCircleRef} />;
}
```
The above code now doesn't raise an error.
> Concretize createAnimatedComponent

- ios/native/UIResponder+Reanimated.mm
After upgrading to RN 0.64 and enabling Hermes, I noticed that my console.logs were gone.
That's the only thing I saw in metro:
After a long journey of debugging (see https://github.com/facebook/metro/issues/635#issuecomment-775939213) I finally found the weird side-effect our custom executor factory creation was having.
This is our `jsExecutorFactoryForBridge` func's return:
```objc
return std::make_unique<ExecutorFactory>([weakSelf, bridge](facebook::jsi::Runtime &runtime) {
if (!bridge) {
return;
}
__typeof(self) strongSelf = weakSelf;
if (strongSelf) {
#if RNVERSION < 63
auto callInvoker = std::make_shared<react::BridgeJSCallInvoker>(bridge.reactInstance);
auto reanimatedModule = reanimated::createReanimatedModule(callInvoker);
#else
auto reanimatedModule = …
```
> Install global bindings for executor factory

- src/reanimated2/core.js
Until now, the console object in worklets only allowed pseudo-sync calls with `log`, `info`, `warn` and `error`. I was using `debug` a lot, so that was always a bit weird to encapsulate it in `runOnJS`
- Adds `console.debug` to worklet console
```jsx
const x = useAnimatedStyle(() => {
console.debug('works')
return { opacity: opacity.value };
}, []);
```
> Add console.debug to worklets

- android/src/main/java/com/swmansion/reanimated/NativeMethodsHelper.java
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1703
If FlatList contains `onRefresh` property then `ReactScrollView` is wrapped by `ReactSwipeRefreshLayout` who doesn't have `smoothScrollTo()` method.
ReactSwipeRefreshLayout support only vertical scroll - "[The SwipeRefreshLayout should be used whenever the user can refresh the contents of a view via a vertical swipe gesture.](https://developer.android.com/reference/androidx/swiperefreshlayout/widget/SwipeRefreshLayout)"
> Fix Flatlist scroll with refresh

- Example/src/ExtrapolationExample.tsx
- react-native-reanimated.d.ts
`interpolate()` supports left/right interpolation and types didn't reflect that.
ExtrapolationExample in the example app.
> Fix type of `type` param in interpolate()

- docs/docs/api/useAnimatedGestureHandler.md
- docs/versioned_docs/version-2.0.0-rc.2/api/useAnimatedGestureHandler.md
On documentation page of [Api/Hooks/useAnimatedGestureHandler](https://docs.swmansion.com/react-native-reanimated/docs/api/useAnimatedGestureHandler), links to the documentation page of react-native-gesture-handler is broken. They all end up in page not found.
- updated `docs/docs/api/useAnimatedGestureHandler.md`
- updated `docs/versioned_docs/version-2.0.0-rc.2/api/useAnimatedGestureHandler.md`
Just change of links. I don't think so this needs that much testing.
> Fix broken links in docs

- Common/cpp/headers/SharedItems/ShareableValue.h
- Common/cpp/headers/SharedItems/ValueWrapper.h
`JSIStoreValueUser.h` is a local file, use `"` instead of `<` for importing user headers.
This compiled fine before since CocoaPods allows flattening system headers, but once I try to import some REA headers in another library, it fails to compile:
> Use `"` instead of `<` for `JSIStoreValueUser.h` include

- Common/cpp/SharedItems/ShareableValue.cpp
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1782
In `adapt()` function we use conversion to utf8 during `set`, but during `get` we used `jsi::String::createFromAscii` instead of `jsi::String::createFromUtf8`.
<details>
```js
import {TextInput, Button} from 'react-native';
const AnimatedTextInput = Animated.createAnimatedComponent(TextInput);
const value = 'ööö';
export const Repro = () => {
const sharedValue = useSharedValue(value);
const animatedProps = useAnimatedProps(() => {
return {value: `${value} ${sharedValue.value}`};
}, []);
return <Animated.View>
<AnimatedTextInput animatedProps={animatedProps} />
<Button …
```
> Fix UTF-8 encoding on Android

- src/core/AnimatedDebug.js
In Expo SDK 40 we deprecated the global Expo object. In SDK 41, we are deleting it, so we need to change this.
Fixes #1612
Instead of using the global Expo object, we check for the `executionEnvironment` on the `ExponentConstants` native module, if it is available. This is the same thing we do in @react-native-async-storage/async-storage. In the future, we could potentially move to try/catch around requiring expo-constants, but this feature is only available on react-native@>=63 so I don't think we should start depending on it in libraries yet.
This is a bit tricky for react-native-reanimated authors to test in the Expo Go context. Outside of Expo Go, you can use AnimatedDebug to ensure that this does not cause any new problems outside of Expo Go (although I think this is easy to …
> [v1] Replace global.Expo.Constants with NativeModules check

- android/src/main/JNI/Android.mk
Code style
Use consistent whitespaces
None
> Use spaces instead of tabs in Android.mk

- Common/cpp/headers/Tools/ReanimatedHiddenHeaders.h
Fixes #1805
Reanimated **v2.0.0** was causing compile errors in React Native iOS projects who used `use_frameworks!` in their Podfile.
**Error:**
`'../../hidden_headers/Logger.h' file not found`
Updated the paths in `ReanimatedHiddenHeaders.h` to use `Common/cpp/hidden_headers/` instead of `../../`.
Original repro repository https://github.com/mrbrentkelly/reanimated2-logger-not-found
Testing
> fix headers for use_frameworks! projects

- src/createAnimatedComponent.js
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1808
If someone uses `animatedProps` instead of `style`, we didn't set `viewRef` and without properly setting `viewRef` we weren't able to update any web component property.
<details>
```js
import * as React from "react";
import { StyleSheet, View, Button } from "react-native";
} from "react-native-reanimated";
Animated.addWhitelistedNativeProps({
pointerEvents: true,
});
Animated.addWhitelistedUIProps({
pointerEvents: true,
});
const pointerEvents = useSharedValue("auto");
const bottomProps = useAnimatedProps(() => ({
pointerEvents: pointerEvents.value,
}));
const toggle = () => {
if (pointerEvents.value === …
```
> Set missing viewRef for animatedProps

- docs/docs/animations.md
- docs/versioned_docs/version-2.0.0-rc.2/animations.md
- docs/versioned_docs/version-2.0.0/animations.md
The link to `withDecay` from the Animations doc page seem to be broken because of a typo: `widthDecay`
- Updated animations.md files to fix the typo
> Fix broken link in animations docs

- src/reanimated2/Hooks.js
We want to handle a situation when a user forgets `.value` using `transform` in `useAnimatedStyle`:
```
const sv = useSharedValue(0);
return {
transform: [{translateX: sv}],// should be sv.value
width: sv,// should be sv.value
};
});
```
For now, in such a case an uninformative error is being thrown.
> Show proper error for transform in UAS

- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/java/com/swmansion/reanimated/Scheduler.java
fixes: https://github.com/software-mansion/react-native-reanimated/issues/1815
There can be a situation when reanimated has been destroyed but there is still a runnable on UI queue that wants to trigger our render method. In order to avoid the scenario, I've added a condition in scheduler.schedulerOnUI that checks if react native instance has been destroyed.
> Fix full reload on Android

- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/headers/SharedItems/HostFunctionHandler.h
- Common/cpp/headers/SharedItems/ValueWrapper.h
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/1758
Currently, when we send callback function to UI thread and then back to RN then we will get function wrapper that checks is somebody uses runOnJS. In order to solve the problem, I've added logic that attaches additional info to a function wrapper that allows to get original callback.
> Fix Host Function

- Example/reanimated1/src/interpolate/Basic.js
- react-native-reanimated-tests.tsx
- src/reanimated1/derived/interpolate.js
This PR will add support for strings with radians in interpolate's outputRange.
Currently code like this works on iOS but crashes on Android.
ref.
https://github.com/software-mansion/react-native-reanimated/issues/1436#issuecomment-726779954
```typescript
Animated.interpolate(animatedValue, {
inputRange: [0, 1],
outputRange: ['0rad', `${Math.PI}rad`]
})
```
- Added code to convert strings with radians to number
- Added a test in `interpolateNodeTest()` function
Added test case
> [v1] Support radians in interpolateNode()

- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/headers/SharedItems/HostFunctionHandler.h
Method `std::shared_ptr<jsi::Function> get()` from `struct HostFunctionHandler : jsi::HostObject` had name conflict wtih `virtual Value get(Runtime&, const PropNameID& name)` from `jsi::HostObject` and this crashed CI and compilation for android.
Related with: https://github.com/software-mansion/react-native-reanimated/pull/1844
> Fix collision name

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/Registries/WorkletsCache.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/headers/NativeModules/NativeReanimatedModule.h
- Common/cpp/headers/Registries/WorkletsCache.h
- Example/ios/Podfile.lock
- android/src/main/cpp/AndroidLogger.cpp
- android/src/main/cpp/NativeProxy.cpp
- ios/native/NativeProxy.mm
- ios/native/REAIOSLogger.mm
- ios/native/UIResponder+Reanimated.mm
Part 1 of 3
* Re-indents a few wrongly indented code-pieces
* Uses `std::make_shared`/`std::make_unique` instead of `new` (it's a bit faster, and cleaner to read imo)
* Restructures `UIResponder+Reanimated.mm` to be a bit more future proof and easier to read (dummy macro, include checking, ...)
> Restructure code

- .github/ISSUE_TEMPLATE/bug-report-v2.md
- .github/workflows/issue-validator.yml
Just a minor change on a Github issues template. 
Title 'steps to reproduce' separated from 'Actual behavior & steps to reproduce'. It makes the github-bot validator fail if you don't put it separately.
1. Create a new Github issue.
2. When sending it, the validator will not fail on steps to reproduce item.
> Update validator bot configuration

- package.json
`tsc` generated directory structure reflects source structure, starting from `rootDir` specified in ts-config. We can't set it to `src/reanimated2` because it has to contain _all_ sources (including d.ts files we have in repo root). To workaround that we move generated directory two levels upper.
This PR also splits `type:generate` task to make it more maintainable.
> Fix tsc generation

- docs/docs/about.md
hi, since 2.1.0 JSC is supported so this clarifies that
I'm not sure how you handle the versioned docs, but here it is :)
> docs: JSC on android is supported

- src/reanimated2/js-reanimated/JSReanimated.ts
Fix #1890
Don't call `window` in the constructor of JS Reanimated, since this isn't available on the server. 
One-line change, which reverts back to what was already there in `2.0.0-rc.0`. Let me know if this is needed, but given that it's simply a regression patch, I figure it isn't.
> fix: ssr support (#1890)

- docs/src/pages/index.js
One of the links on the main page of the docs had an additional slash character resulting in navigating to 404 page.
https://user-images.githubusercontent.com/39658211/115391540-de0b6600-a1df-11eb-8ffb-178a9aebfaed.mov
- Fixed href in `<a>` tag in `docs/src/pages/index.js`
> fix: remove unnecessary slash in docs

- mock.js
- src/Animated.js
After an internal discussion with @Szymon20000 we concluded that reanimated 2 should be exported only via named exports.
Default exports are antipattern in es6 (they prevent tree-shaking for example).
This PR is a breaking change so we may wait with merging it.
> Remove Reanimated 2 from default exports

- src/reanimated1/animations/decay.js
- src/reanimated1/animations/spring.js
- src/reanimated1/animations/timing.js
When used with NextJS, this library produces this warning on compile
```
warn  - ./node_modules/react-native-reanimated/lib/reanimated1/animations/timing.js
Anonymous function declarations cause Fast Refresh to not preserve local component state.
Please add a name to your function, for example:
Before
export default function () { /* ... */ }
After
export default function Named() { /* ... */ }
A codemod is available to fix the most common cases: https://nextjs.link/codemod-ndc
```
Named the default exported function
> [v1] Name exported animation functions

- plugin.js
This PR adds an option to the react-native-reanimated plugin: `globals`. It is of type Array and specifies any additional globals the Babel Plugin allows. 
The main motivation behind this change was that I am developing a Camera library which allows native host-functions to be called inside worklets in a custom runtime. So for instance, a custom `scanQRCodes(...)` function that is registered to the `jsi::Runtime::global` property was not callable before because the REA plugin whitelists all available globals here: https://github.com/software-mansion/react-native-reanimated/blob/462e21ee18e732cabc4381816486a5808ce7e961/plugin.js#L33-L70
With this PR you can now add additional globals, without breaking any behaviour. To add the `_scanQRCodes` host-function to the globals simply edit your …
> Plugin: Allow adding custom globals for Worklets (e.g. HostFunctions)

- Example/android/app/src/main/res/values/styles.xml
The text on the Example project is very hard to read with white text
on the gray background. This PR changes the default text color to
black so it is readable.
The text in the Example project when run on Android is white on a gray background making it very hard to read. I actually thought there was no text at first.
Changes the default text color to black on Android for the Example project.
Here you can add screenshots / GIFs documenting your change.
You can add before / after section if you're changing some behavior.
Build the project on Android. May require launching to a physical device to see the bug.
> Set default text color to black in Example app

- Common/cpp/SharedItems/MutableValue.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/Tools/RuntimeDecorator.cpp
- Common/cpp/headers/Tools/RuntimeDecorator.h
There are a few functions that check if you're currently on the REA UI Runtime by using `RuntimeDecorator::isWorkletRuntime`. This might actually lead to threading issues if you're calling those functions from another worklet runtime that is not from Reanimated (e.g. VisionCamera Frame Processors, Multithreading, ...) - so this PR fixes this. A few of those functions should actually check if they are specifically on the UI thread, Worklet thread is not enough.
- Add `RuntimeDecorator::isUIRuntime` - a function that specifically checks if the given `jsi::Runtime` is the REA UI Runtime as opposed to any Worklet Runtime
- Replace a few `isWorkletRuntime` calls with `isUIRuntime`
> Fix Threading issues (SV access from different Thread)

- docs/docs/installation.md
- docs/versioned_docs/version-2.0.0/installation.md
Added a link in the iOS installed documentation to the old native code previously needed to enable Turbo Modules. This will help people like me who installed v2 alphas and are trying to install 2.0.0
Added hyperlinks to doc markdown
It's just docs
~- [ ] Included code example that can be used to test this change~
~- [ ] Updated TS types~
~- [ ] Added TS types tests~
~- [ ] Added unit / integration tests~
> Add link to iOS "previous instruction" in installation docs

- ios/REANodesManager.m
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2031
Added null check in dispatchEvent method after RCTExecuteOnMainQueue.
See issue for further details.
> Fix bundle reload on iOS, Event handler null check.

- ios/native/NativeMethods.mm
`measure` checks if the `x` values is exactly `-1234567.0` - if it is, it's an error. if it isn't, a result is available.
We returned an incorrect vector from the native `measure` function.
- Updated native method `measure` to correctly return error-ish values
> Fix Error in `measure` not throwing

- __tests__/Animation.test.js
- src/reanimated2/jestUtils.ts
Added support for `@quilted/react-testing` - used by Shopify.
`@testing-library/react-hooks` uses `render()`
`@quilted/react-testing` uses `mount()`
Both methods `render()` and `mount()` returns objects with different structure.
```js
import Animated, { useSharedValue, useAnimatedStyle, withTiming, } from '../src/';
import { withReanimatedTimer, advanceAnimationByTime, } from '../src/reanimated2/jestUtils';
import { mount } from '@quilted/react-testing';
const PinCircle = ({filled = false}) => {
const animatedValue = useSharedValue(0);
animatedValue.value = withTiming(filled ? 0 : 1, {duration: 250});
}, [animatedValue, filled]);
const scale = animatedValue.value;
return { transform: …
```
> Added support for `@quilted/react-testing`

- react-native-reanimated.d.ts
- src/createAnimatedComponent.js
Here we can use an adaptor via setNativeProps to animate component outside the React lifecycle.
The goal is to still be able to use the benefit of the Animated API even thought there are no performance benefits.
A common example is to animate OpenGL node (bare webgl, gl-react, or react-three-fiber) on the JS thread:
```tsx
import { Node } from "gl-react";
// In gl-react, updating the gl API outside React is done via setDrawProps()
// In threejs, we would have a call on a prop by prop basis.
// In webgl, we would use the gl object directly.
const AnimatedNode = Animated.createAnimatedComponent(Node, {
setNativeProps: (ref, props) => {
ref.setDrawProps(props);
},
});
```
> Add adaptor to createAnimatedComponent()

- Example/tsconfig.json
I just cloned this repo and installed node_module at root and in Example then i saw 
```
Cannot find module 'react-native-reanimated' or its corresponding type declarations.ts(2307)
```
i fixed IntelliSense by edit `Example/tsconfig.json` and set the correct path of `react-native-reanimated.d.ts`
just clone this repo and installed node_module at root and in Example then when you will hover mouse on `Animated` then you will see this error
> fix: intellisense for Example directory

- android/CMakeLists.txt
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/headers/NativeProxy.h
- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
Replacement for PR https://github.com/software-mansion/react-native-reanimated/pull/1960
> Fix runtime creation

- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
I forgot about removing reference to JavaScriptExecutor, and this was a cause nullPointerException.
> Remove old refference to jsexecutor

- .github/workflows/validate-cpp.yml
- package.json
- scripts/cpplint.sh
This PR adds a script to run [cpplint](https://github.com/cpplint/cpplint), a C++ linter.
You can run the script with `npm run lint-check-cpp`, and any changes to C++ code will be linted automatically by the GitHub action workflow.
I just ran it once and noticed 503 errors, so either we tweak the config to ignore a few errors, or we fix them. Most of them are style guidelines, but there are some performance/efficiency tips in there as well.
> Add cpplint to check C++ code

- src/reanimated2/layoutReanimation/defaultAnimations/Bounce.ts
Previously, all bounce animations had a hardcoded duration set to 250. The pr makes it possible to set arbitrary duration.
> Make bounce animations more flexible

- Example/src/LayoutReanimation/Carousel.tsx
- src/reanimated2/animations.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Flip.ts
- src/reanimated2/layoutReanimation/index.js
Before this pr all properties in animations object returned by animation builder had to be wrapped in animation manually. The pr makes it automatic. 
```js
return (targetValues) => {
'worklet';
return {
initialValues:{
transform: [
{ perspective: 500 },
{ rotateX: '90deg'},
{ translateY: -targetValues.height },
],
},
animations: {
transform: [
{ perspective: 500 },
{ rotateX: delayFunction(delay, animation('0deg', config)) },
{ translateY: delayFunction(delay, animation(0, config)) },
],
}
}
};
```
+ some Example's fixes and exporting Layout
> Wrap in animation if needed && export Layout [Layout Animations]

- src/createAnimatedComponent.js
- src/reanimated2/Hooks.ts
- src/reanimated2/jestUtils.ts
- src/reanimated2/layoutReanimation/AnimatedRoot.tsx
Issues:
- for web, we shouldn't process color to integer representation - I removed color processing for the web implementations
- for web the `requireNativeComponent`method is not defined - I added check for the web platform
- default animation requires `global. __reanimatedWorkletInit` - I changed the order of imports
> Fix web errors

- docs/docs/api/LayoutAnimations/AnimatedLayout.md
- docs/versioned_docs/version-2.3.0-alpha.1/api/LayoutAnimations/AnimatedLayout.md
Fixed a typo in documentation of `<AnimatedLayout>`
Fixed Typo in `AnimatedLayout.md` in two locations.
1. In docs/docs/api/LayoutAnimations/AnimatedLayout.md
2. in docs/versioned_docs/version-2.3.0-alpha.1/api/LayoutAnimations/AnimatedLayout.md
> Fixed Typo in AnimatedLayout.md

- src/reanimated2/Colors.ts
- src/reanimated2/Hooks.ts
Application crash when using transform or color properties on a style object. Replacing for..of loop on for loop solves it problem.
- #2120
- #2125
> Fix, replace for..of on for loop

- react-native-reanimated.d.ts
`outputRange` is a little better name than `output` :), plus this unifies the naming of params to `interpolation` so that it's the same as in `interpolateColor` and others. 
tested in IDE locally
> chore: improve parameter naming in TS typings

- android-npm/build.gradle
Problem: An application module can have different name than `:App` and currently, we are only looking for enableHermes property in `:App` module.
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/2129
To find App module I iterate over all modules and choose the one with `com.android.application` plugin applied as only application module can apply it.
> Find App module instead of hardcoding it

- src/reanimated2/js-reanimated/index.web.ts
Add the ability to animate svg components with `createAnimatedComponent` on the web.
Cf : https://github.com/software-mansion/react-native-reanimated/issues/1951
> fix: animated react native svg web

- Common/cpp/Tools/JSIStoreValueUser.cpp
- Common/cpp/headers/Tools/JSIStoreValueUser.h
- Example/ios/Podfile.lock
fixes: https://github.com/software-mansion/react-native-reanimated/issues/2092
As you can see in the stack trace from the issue static object are deallocated before StoreUser destructor is called. 
It seems like the problem only occurs when a user closes an app. However, it's still a serious problem as crashing apps are treated differently on iOS. In order to get rid of the problem, I store old static members as one object which is kept as shared_ptr instance field.
> Fix ios crash

- src/reanimated2/animations.ts
In timing animation, we use the following function to compute the value for the current frame of animation:
```js
animation.current += ((toValue - current) * (newProgress - progress)) / (1 - progress);
```
But these function has asymptote in `progress = 1` and value 1 is inside function's domain. In summary, if progress was equal to 1 we had division by 0 in consequence `animation.current` was `NaN`. Android can't handle style with `NaN` value and this was a cause of blinking.
I decided to change this function to a complementary form without asymptote:
```js
animation.current = startValue + (toValue - startValue) * progress;
```
another possible solution (but imo worst):
```js
const a = ((toValue - current) * (newProgress - progress)) / (1 - (progress == 1 ? 1 + Number.EPSILON : …
```
> Replace inner timing function

- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/headers/SharedItems/ShareableValue.h
Now on iOS is possible to catch JSError thrown from the worklet.
```js
const a = () => {
'worklet';
throw new Error('exception_message')
}
'worklet'
if(_WORKLET) {
try {
a();
} 
catch(e) {
console.log("SUCCESS!", e.message)
}
}
return {
width: withTiming(sv.value),
};
});
```
> Handling JSError on iOS

- RNReanimated.podspec
- ios/native/NativeProxy.mm
- ios/native/UIResponder+Reanimated.mm
RN 0.65 has updated the way hermes header are being imported
Context: See https://github.com/facebook/react-native/commit/59abb5f378e116288cdea2f619de0c128bb0b0eb 
added a third statement for backward compat
> fix for using hermes on iOS 0.65 after the headers update

- createNPMPackage.sh
Currently, I added once again aar to the building script but I think that we need to consider how to limit the number of aars in the reanimated package.
I tested `rea.65.aar` on RN64 app but unfortunately, it doesn't work.
> Building script for RN65

- package.json
- src/createAnimatedComponent.js
- src/reanimated1/core/AnimatedAlways.js
- src/reanimated1/core/AnimatedBezier.js
- src/reanimated1/core/AnimatedBlock.js
- src/reanimated1/core/AnimatedCall.js
- src/reanimated1/core/AnimatedCallFunc.js
- src/reanimated1/core/AnimatedConcat.js
- src/reanimated1/core/AnimatedCond.js
- src/reanimated1/core/AnimatedDebug.js
- src/reanimated1/core/AnimatedEvent.js
- src/reanimated1/core/AnimatedFunction.js
- src/reanimated1/core/AnimatedOperator.js
- src/reanimated1/core/AnimatedParam.js
- src/reanimated1/core/AnimatedProps.js
- src/reanimated1/core/AnimatedSet.js
- src/reanimated1/core/AnimatedStartClock.js
- src/reanimated1/core/AnimatedStopClock.js
- src/reanimated1/core/AnimatedStyle.js
- src/reanimated1/core/AnimatedTransform.js
- src/reanimated1/core/InternalAnimatedValue.js
- src/reanimated1/core/__mocks__/AnimatedProps.js
- src/reanimated1/derived/interpolate.js
- yarn.lock
React Native has removed the dependency on `fbjs` for several releases. The library is for sharing JS code between Facebook projects, and is not intended to be used by the broader open-source community.
React Native replaced the implementation for `invariant` a couple years ago, so I used the same replacement:
https://github.com/facebook/react-native/commit/4148976a83ab96029de1b26b515ff95d3cb58c10
- Use `invariant` instead of `fbjs/lib/invariant`
- Use `lodash.isequal` instead of `fbjs/lib/areEqual`
All tests pass
> Remove dependency on `fbjs`

- plugin.js
AST body of expression: `() => ({})` isn't `BlockStatement` but `ObjectExpression`, so I added check for this. The problem occurred in ExtrapolationExample.
> Babel plugin update

- src/reanimated2/interpolation.ts
`__DEV__` was undefined for release build. I changed this to a property check instead of a variable check.
Fixes:
- https://github.com/software-mansion/react-native-reanimated/issues/2160
> Fix release build

- src/createAnimatedComponent.js
`flattenArray` function was not used during filtering non-animated props, so when the style property in `Animated.View` was a nested array, the app was crashing. I've changed that so know nested array can be passed as a style property.
Fixes #2188
> Fixed filtering nested animated styles.

- src/reanimated2/core.ts
- src/reanimated2/layoutReanimation/AnimatedRoot.tsx
Currently, when the user wants to animate property to the same value as property has, animation doesn't run and so the animation callback. It might be not intuitive so I changed it, and now callback runs even if the new value is the same as the old one.
Fixes #1959 
- added callback triggering when new value is the same as the old one
> Fixed callback doesn't run when animating to the same value

- Example/android/app/build.gradle
- Example/src/AnimatedStyleUpdateExample.tsx
- android-npm/build.gradle
- android/CMakeLists.txt
- android/build.gradle
- createNPMPackage.sh
I added `libfbjni.so` (in version 0.2.2 with dynamic loading of libc++.so) to reanimated aar package. Reanimated will automatically change application configuration and add Gradle option:
```
android {
...
packagingOptions {
pickFirst 'lib/**/libfbjni.so'
}
...
}
```
To disable this behavior user just need to add to `app/gradle.build` the following config:
```
project.ext.reanimated = [
enablePackagingOptions: false,
]
```
> Override libfbjni.so

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/SharedItems/MutableValue.cpp
- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/Tools/JSIStoreValueUser.cpp
- Common/cpp/headers/NativeModules/NativeReanimatedModule.h
- Common/cpp/headers/SharedItems/RemoteObject.h
- Common/cpp/headers/SharedItems/RuntimeManager.h
- Common/cpp/headers/SharedItems/ShareableValue.h
- Common/cpp/headers/Tools/JSIStoreValueUser.h
- Example/ios/Podfile.lock
Until now, the `JSIStoreValueUser` class was used to cache `jsi::Value`s. This worked fine for Reanimated since there was only one separate Runtime apart from the React-JS runtime, but once another library tries to use the workletization code, this will break since `JSIStoreValueUser` is accessed from multiple runtimes. Instead, it should only be used on a per-runtime basis, so I moved the static code to instance code, and added a Shared Pointer to `RuntimeManager`.
This fixes SIGABRT crashes for when trying to use a captured variable (such as `console`) in multiple runtimes (REA, VisionCamera, react-native-multithreading, ...):
The above crash happened because a `jsi::Value` (`console`) cached inside `StoreUser` was accessed from the VisionCamera runtime, but the value was initially …
> fix: Cache `StoreUser` (`JSIStoreValueUser`) on a per-`RuntimeManager`-basis

- Example/ios/Podfile.lock
- ios/native/REAInitializer.h
- ios/native/REAInitializer.mm
- ios/native/UIResponder+Reanimated.mm
If somebody has to turn off autoinstallation, they have to copy-paste our implementation of `jsExecutorFactoryForBridge` and update that code whenever we change something in the library.  To make it a bit more flexible I want to add another layer of abstraction so that our code is hidden behind the `REAJSIExecutorRuntimeInstaller` function.
> Simplify manual installation process.

- ios/native/REAInitializer.h
- ios/native/UIResponder+Reanimated.mm
This pull request fixes the following compilation error when using Reanimated 2 with React Native 0.63.4 or earlier:
```
react-native-reanimated/ios/native/REAInitializer.h:32:1: Use of undeclared identifier 'JSIExecutor'
```
> Fix Use of undeclared identifier 'JSIExecutor'

- Common/cpp/Tools/Mapper.cpp
- Common/cpp/headers/Tools/Mapper.h
I can't copy the viewDescriptors set because it can be empty during starting of the mapper.
> Use shared value instead of copy

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
On android sometimes layout transition animation was started multiple times with start and target values equal which resets the very first animation. I've added checking if the start and target values are equal for layout transition animation and if they are I'm not starting that animation.
Fixes #2235 
- added check if start and target values are equal for layout transitions
https://user-images.githubusercontent.com/48885911/127633922-1485d765-c129-4dc5-ab74-69d27a81c668.mov
https://user-images.githubusercontent.com/48885911/127633942-b864759f-727b-4a00-9dd1-05ff0d72c383.mov
-->
> Fixed layout transition animation was started multiple times on android

- docs/docs/api/LayoutAnimations/CustomAnimations.md
- docs/docs/api/LayoutAnimations/EntryAnimations.md
- docs/docs/api/LayoutAnimations/ExitAnimations.md
Fixed typos in:
* CustomAnimations.md: dimentions -> dimensions
* EntryAnimations.md: ZoomInEadyDown -> ZoomInEasyDown
* ExitAnimations.md: ZoomOutEadyDown -> ZoomOutEasyDown
> Fixed typos in Layout Animations md files

- src/ConfigHelper.js
This PR fixes #2273.
- Added `placeholderTextColor` to `NATIVE_THREAD_PROPS_WHITELIST`
> [v1] Fix animation of placeholderTextColor

- src/reanimated2/hook/useAnimatedGestureHandler.ts
We had a problem with the casting event type. Because we used custom type from reanimated instead of event type from gesture-handler.
> Use gesture-handler event type

- android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java
Fixes #2297 by adding stub implementations of newly-required
methods from react-native 0.65
See e.g. 
- https://github.com/react-native-device-info/react-native-device-info/commit/3917f339207a5a2b05e3922f7489a0568dfde666
- https://github.com/invertase/react-native-firebase/pull/5616
> fix(android): react-native 0.65 event emitter stubs

- src/reanimated2/Colors.ts
When one of the colors in the output range was transparent, interpolateColors doesn't work, due to a wrong undefined check.
Fixes #2328 
- Changed to explicit check if color is undefined, to prevent issue when color value is 0
> Fixed transparent colors in interpolateColors

- android/build.gradle
- android/rnVersionPatch/62/layoutReanimation/ReanimatedNativeHierarchyManager.java
- android/rnVersionPatch/62/layoutReanimation/ReanimatedUIImplementation.java
- android/rnVersionPatch/63/layoutReanimation/ReanimatedUIImplementation.java
- android/rnVersionPatch/64/layoutReanimation/ReanimatedUIImplementation.java
- android/settings.gradle
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
- createNPMPackage.sh
We have many dependencies to React Native, but react is changing. If we want to support many versions of RN we need to add some specific changes dedicated to react version. In Java, it is harder than C++ because we haven't `#ifdef` mechanism. So I added a patch-like mechanism to replace some specific files during compilation time for specific RN versions.
> Fix build-script

- docs/docs/installation.md
- docs/versioned_docs/version-2.0.0/installation.md
- docs/versioned_docs/version-2.1.0/installation.md
- docs/versioned_docs/version-2.2.0/installation.md
- docs/versioned_docs/version-2.3.0-alpha.1/installation.md
- docs/versioned_docs/version-2.3.0-alpha.2/installation.md
- docs/versioned_docs/version-2.3.0-alpha.3/installation.md
The bash commands on the installation page are currently prefixed with `> `. If you hover over any of the code fields, you’ll see a “copy” button, but clicking it will copy the code sample including the > meaning you can’t actually paste it in your terminal.
This PR removes the `>`, meaning the code snippets can be pasted directly to the terminal when copying them using the "copy" button.
Removes `>` from the bash commands on the installation change.
> Remove > from bash commands

- Common/cpp/Tools/JSIStoreValueUser.cpp
After changes in Hermes's garbage collector - the host object destructor can be called from another thread than JNI is assigned. We need to change the way of calling JNI in destructors to avoid calling a function on a null object.
We should make it like Hermes: https://github.com/facebook/hermes/blob/6e5868763b08eb80f4164a926abb92fa5c71117f/lib/Platform/Intl/PlatformIntlAndroid.cpp#L319
Related issue: https://github.com/facebook/hermes/issues/590
Fixes #2256
Authors: @Szymon20000 @piaskowyk
> Fix JNI null refference in destructor

- .github/workflows/android-build.yml
- .github/workflows/ios-build.yml
- Common/cpp/Tools/JSIStoreValueUser.cpp
On ios build didn't work because of `<AndroidScheduler.h>` include. I made this include conditional, so it will be included only on android.
* Added conditional include
* Added triggering build check when files inside common directory are edited
> Fixed ios build

- ios/LayoutReanimation/REAUIManager.mm
We missed setup bridge in the parent class - RCTUIManager
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2364, https://github.com/facebook/react-native/issues/32145
> Set bridge in RCTUIManager

- src/createAnimatedComponent.js
If any of the style in a style prop array is falsy (which is allowed by React Native), an error will throw upon component unmount.
This case is already handled for mobile but in not in the web, resulting to a `of undefined` error.
Fixed #2413
Check if style is not falsy in AnimatedComponent._detachStyles for the case of `Platform.OS = 'web'`
(Please use the CodeSandBox below)
It throws the error:
```
createAnimatedComponent.js:153 Uncaught TypeError: Cannot read properties of undefined (reading 'viewsRef')
at AnimatedComponent._detachStyles (createAnimatedComponent.js:153)
at AnimatedComponent.componentWillUnmount (createAnimatedComponent.js:94)
at callComponentWillUnmountWithTimer (react-dom.development.js:20413)
```
if any of the style in style prop is falsy.
Does not throw anymore. …
> Check falsy style item in AnimatedComponent._detachStyles

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
React native stores some tags as pending to delete in a separate array. To keep a consistency of states we clear `mPendingDeletionsForTag` before we call `manageChildren`.
We also resolve an issue with the unknown view manager for the tag. React `dropView` method removes only children of views, we added removing parent view also.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2393, https://github.com/software-mansion/react-native-reanimated/issues/2394
Authors: @Szymon20000 @piaskowyk
> Clear `mPendingDeletionsForTag`

- __tests__/__snapshots__/plugin.test.js.snap
- __tests__/plugin.test.js
- plugin.js
This PR adds support for detecting patterns in JavaScript code which are specific to [React Native Gesture Handler](https://github.com/software-mansion/react-native-gesture-handler), like `Gesture.Tap().onEnd(...)`, so that they can be automatically converted into worklets even if they are not marked with `'worklet';` directive.
The general pattern is `Gesture.Foo()[*].bar(fun)`, where:
* `Foo` is a gesture object, like `Tap`, `Pan`, `Pinch`, etc.
* `[*]` is any number of chained builder method calls (e.g. `numberOfTaps(2)` or `onStart(...)`)
* `bar` is any builder method name, e.g. `onEnd`
* `fun` is a function declaration, function expression or arrow function expression
The following callback functions will be auto-workletized:
```ts
import { Gesture } from …
```
> Auto-workletize React Native Gesture Handler callback functions

- android-npm/build.gradle
- android/build.gradle
- createNPMPackage.sh
- package.json
I removed `packagingOptions.pickFirst("lib/**/libfbjni.so")` from `build.gradle` script because this was a cause of some `.so` conflicts in expo projects.
> Remove pickFirst from gradle

- Common/cpp/SharedItems/FrozenObject.cpp
- Common/cpp/headers/SharedItems/FrozenObject.h
We used `unordered_map` to store object keys. It may cause different results of `Object.keys()` called on JS or UI thread. I added `vector` of keys to store the right order of keys and keep constant complexity. Instead of this solution I also can use just `std::map` to store objects in the right order but `map` logarithmic complexity.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2352
```js
import { View } from 'react-native';
import { useAnimatedStyle } from 'react-native-reanimated';
const obj = {
a: 0,
b: 1,
};
console.log("is worklet:", _WORKLET + ",", "keys:", Object.keys(obj));
return {};
});
return <View></View>;
}
```
```
is worklet: false, keys: ["a", …
```
> Set order for keys in object inside a worklet

- src/reanimated2/NativeMethods.ts
- src/reanimated2/NativeReanimated.ts
- src/reanimated2/NativeReanimated/NativeReanimated.ts
- src/reanimated2/NativeReanimated/index.ts
- src/reanimated2/UpdateProps.ts
- src/reanimated2/ViewDescriptorsSet.ts
- src/reanimated2/WorkletEventHandler.ts
- src/reanimated2/animation/util.ts
- src/reanimated2/commonTypes.ts
- src/reanimated2/core.ts
- src/reanimated2/globals.d.ts
- src/reanimated2/hook/useAnimatedGestureHandler.ts
- src/reanimated2/hook/useAnimatedRef.ts
- src/reanimated2/hook/useAnimatedScrollHandler.ts
- src/reanimated2/hook/useAnimatedStyle.ts
- src/reanimated2/hook/utils.ts
- src/reanimated2/js-reanimated/JSReanimated.ts
- src/reanimated2/js-reanimated/Mapper.ts
- tsconfig.json
As the next step of the react-native-reanimated smooth transition to TypeScript, this PR updates types for:
* `WorkletEventHandler`
* `NativeMethods`
* `NativeReanimated`
* `UpdateProps`
* `ViewDesriptorsSet`
> Types update

- src/createAnimatedComponent.js
- src/reanimated2/hook/useAnimatedStyle.ts
In the previous approach, initialUpdaterRun was called inside createAnimatedComponent(), and if `createAnimatedComponent` was called during an animation, it can cause an inconsistent state of style because on UI thread was scheduled to update and on JS thread was computed current style. But on the UI thread, this update can be executed before action on the JS thread or after them.
I moved `initialUpdaterRun` to createAnimatedComponent and compute initial style in the component's constructor.
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/2406
> Initial style for component with shared style

- ios/LayoutReanimation/REAUIManager.mm
When not having react-native-screens installed, react-native-reanimated does not build in alpha.3 (or current master).
There is an import: 
```objc
#import <RNScreens/RNSScreen.h>
```
which does not work since RNScreens does not exist. This PR fixes this issue by conditionally importing RNScreens.
- Conditionally import RNScreens depending on whether it's installed or not
- Conditionally use RNSScreen class depending on whether it's available or not
> fix: Fix `RNScreens/RNSScreen.h` import if react-native-screens is not installed

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
mPendingDeletionsForTag is only initialized in some constructor paths, in others it might be null,
so we cannot always blindly dereference it
Fixes #2477
For me, I'm able to reproduce a crash here anytime minifyEnabled is true in my build (you can set it in debug, to check it), and it crashes on startup for me.
> fix(android): avoid using null mPendingDeletionsForTag / mReaLayoutAnimator

- Example/src/App.tsx
- Example/src/LayoutReanimation/NativeModals.tsx
- Example/src/LayoutReanimation/index.ts
- ios/LayoutReanimation/REAUIManager.mm
PR fixing buggy behavior of RN modals and laggy animation of `RNScreens` `native-stack` JS going back animation. It does not apply layout animation logic in case one of those is removed.
`NativeModals` in `Example` app.
> fix: ios native stack and RN modals

- ios/REAEventDispatcher.m
- ios/REAModule.h
- ios/REAModule.m
- ios/native/NativeProxy.h
- ios/native/NativeProxy.mm
- ios/native/REAInitializer.mm
Fixes #2555. 
Perhaps I'm missing something, but it seems to me that `_bridge_renimated` is a vestigial organ that no longer serves any practical purpose. Its use in REAEventDispatcher is unnecessary, since we already assign RCTEventDispatcher.bridge with the same value, and its only other use in createReanimatedModule is a single call where we can pass bridge as an argument.
Since bridge is now passed as an explicit dependency, a race condition is no longer possible.
I've realized that I can reproduce #2555 quite easily by repeatedly ⌘Ring in the simulator in quick succession. I've easily managed to get to the point where REAEventDispatcher has a null `_bridge_reanimated`, but `[self bridge]` is correct, confirming that the fix works.
n/a
Reload the app in simulator repeatedly and see if …
> Remove _bridge_renimated, fix #2555

- android/build.gradle
Add stack protector flag to build.gradle to add a stack canary value to the compiled libraries.
> chore: add '-fstack-protector-all' flag to build.gradle

- mock.js
this avoids the ` Jest encountered an unexpected token` error when running tests,  because the mock uses JSX syntax.
So instead of transforming the code, I figured it's easier to use React.createElement()
- use React.createElement() instead of JSX transform in the mock setup file
Here you can add screenshots / GIFs documenting your change.
You can add before / after section if you're changing some behavior.
Details:
```
/Users/vojta/_dev/abc/node_modules/react-native-reanimated/mock.js:83
return <Component {...this.props} />;
^
SyntaxError: Unexpected token '<'
```
error is gone
> chore: use createElement instead of JSX transform

- src/reanimated2/js-reanimated/Mapper.ts
Fixes #2589
* https://github.com/software-mansion/react-native-reanimated/issues/2589
[`extractMutableFromArray` function](https://github.com/software-mansion/react-native-reanimated/blob/12093cbe04d978b2ef619531755ef7d472242cd9/src/reanimated2/js-reanimated/Mapper.ts#L40) now returns empty array when `array` is `null | undefined`
Use this code to see that it now works on web:
```tsx
import React from 'react'
import { useDerivedValue } from 'react-native-reanimated'
export default function HelloWorld() {
const broken = null
useDerivedValue(() => {
const d = broken
})
return (<Text>Test</Text>)
}
```
> [Web] Fix 2589: `null` in `useDerivedValue` 

- Example/ios/ReanimatedExample/Info.plist
- ios/REANodesManager.m
This PR adds support for 120 fps on iOS devices. On Android, 120 fps is already supported without any changes.
There's nothing to do. Just make sure that your device has 120 fps mode enabled in the general system settings.
Add the following lines to `Info.plist` of your app:
```diff
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
...
+	<key>CADisableMinimumFrameDurationOnPhone</key>
+	<true/>
</dict>
</plist>
```
Once added, it should be visible Project Settings > Info > Custom iOS Target Properties:
If it's not, then restart Xcode. Finally, build and run your app as usual.
<details>
<summary>FpsCounter.tsx</summary>
```tsx
runOnUI, …
```
> Reanimated 120 fps

- src/reanimated2/ViewDescriptorsSet.ts
Use `requestAnimationFrame` on Web, instead of `setImmediate`.
See #2621 and https://github.com/software-mansion/react-native-reanimated/pull/1521 for reference.
Fix #2621
`setImmediate` breaks SSR on Web. `requestAnimationFrame` is better. This was already discussed and merged previously at #1521.
> Fix SSR regression in 2.3.0

- src/createAnimatedComponent.tsx
This pull request fixes a bug appearing when using animated styles (or props) conditionally. The root cause is that animated styles (or props) are not properly detached.
|-|-|
| <video src="https://user-images.githubusercontent.com/20516055/140052148-f0584f2d-eeb0-45b8-af2f-dcfa12164f67.mp4" /> | <video src="https://user-images.githubusercontent.com/20516055/140052808-d3f566fd-4ac3-4d0a-908f-e9113d1c2691.mp4" /> |
| <video src="https://user-images.githubusercontent.com/20516055/140053185-d1a5a4d4-66a8-41e8-b0fe-7601248bd638.mp4" /> | <video src="https://user-images.githubusercontent.com/20516055/140052901-d5afada0-b782-43e3-ae38-752806091d05.mp4" /> |
- Added missing calls to detach animated styles and props
<details>
<summary>AnimatedStylesExample.tsx</summary>
```tsx …
```
> Detach old animated styles and props

- ios/LayoutReanimation/REAUIManager.mm
Added all navigators using `screens` to list of disabled views for applying `layoutAnimations`. Should fix https://github.com/software-mansion/react-native-reanimated/issues/2639.
> feat: disable layout animations in other navigators

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/NativeModules/NativeReanimatedModuleSpec.cpp
- Common/cpp/Tools/FeaturesConfig.cpp
- Common/cpp/headers/NativeModules/NativeReanimatedModule.h
- Common/cpp/headers/NativeModules/NativeReanimatedModuleSpec.h
- Common/cpp/headers/Tools/FeaturesConfig.h
- android/CMakeLists.txt
- android/src/main/cpp/LayoutAnimations.cpp
- android/src/main/cpp/headers/LayoutAnimations.h
- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/LayoutAnimations.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/NativeMethodsHolder.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
- ios/LayoutReanimation/REAUIManager.mm
- ios/native/NativeProxy.mm
- react-native-reanimated.d.ts
- src/createAnimatedComponent.tsx
- src/reanimated2/NativeReanimated/NativeReanimated.ts
- src/reanimated2/core.ts
- src/reanimated2/js-reanimated/JSReanimated.ts
I added the possibility to disable layout animations. By default layout animations are disabled, but you don't need to turn it on manually, because these will be enabled if you will use the `entering`/`exiting`/`layout` prop in an animated component. You also have the possibility to disable/enable it manually.
```js
import { enableLayoutAnimations } from 'react-native-reanimated';
enableLayoutAnimations(false);
```
> Disable by default layout animation

- ios/native/NativeMethods.mm
```c++
if (rootView == nil || (![rootView isReactRootView])) {
return <error>;
}
```
```c++
if (rootView == nil) {
return <error>;
}
```
Native Modal on iOS is not attached to ReactRootView.
Because React does it the same!  - [react-native measure method](https://github.com/facebook/react-native/blob/1465c8f3874cdee8c325ab4a4916fda0b3e43bdb/React/Modules/RCTUIManager.m#L1315-L1324)
https://github.com/emilioschepis/reanimated-2-in-modal
https://snack.expo.dev/@piaskowyk/github.com-emilioschepis-reanimated-2-in-modal
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1973
> Fix measure in iOS Modal

- plugin.js
Added `onTouchesDown`, `onTouchesMove`, `onTouchesUp` and `onTouchesCancelled` to the list of gesture handler builder methods in the babel plugin.
> Add Gesture Handler touch events setters to babel plugin

- ios/LayoutReanimation/REAUIManager.mm
I am not convinced to fix it by reanimated side. IMO this assertion is not necessary and handling it this way looks like dirty hacks for edge cases. I ask them to remove this assertion. in spite of it, I prepared a fix.
Handle Assert exception during disappearing of a component. Caused by https://github.com/oblador/react-native-shimmer/blob/620a9e899df40e1bef38127d4ef61384e1a195c5/ios/RNShimmeringView.m#L26
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2554
Related: https://github.com/oblador/react-native-shimmer/pull/33
> Handle removing exception

- Common/cpp/Tools/RuntimeDecorator.cpp
- Common/cpp/headers/Tools/RuntimeDecorator.h
Possibly fix for crash during access to `RuntimeDecoratorRegistry`
Stack trace:
```
0 std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<facebook::jsi::Runtime*, reanimated::RuntimeType>, void*>*> std::__1::__hash_table<std::__1::__hash_value_type<facebook::... + 124 (__hash_table:2394)
1 std::__1::unordered_map<facebook::jsi::Runtime*, reanimated::RuntimeType, std::__1::hash<facebook::jsi::Runtime*>, std::__1::equal_to<facebook::jsi::Runtime*>, std::__1::allocator<std::__1::pair<fa... + 16 (unordered_map:1352)
2 reanimated::RuntimeDecorator::isReactRuntime(facebook::jsi::Runtime&) + 20 (RuntimeDecorator.h:73)
```
The solution described here: https://stackoverflow.com/a/13893502/7276742
> Fix for uninitialized map

- ios/native/REAInitializer.mm
When I was adding https://github.com/software-mansion/react-native-reanimated/pull/2253 I forgot about iOS part, this PR injects the same value as on android
- console.log value in the bare expo project
- run code that is using that pointer
> Attach pointer to worklet runtime in main runtime on iOS

- src/createAnimatedComponent.tsx
> Fix detaching old animated props

- __tests__/__snapshots__/plugin.test.js.snap
- __tests__/hooks.useSharedValue.test.js
- __tests__/plugin.test.js
- src/reanimated1/core/Core.test.js
Fix typos, update jest snapshots to make jest tests pass.
* Replace onBegan with onBegin in one of tests located in plugin.test.js (method name changed in [this commit](https://github.com/software-mansion/react-native-reanimated/pull/2519/commits/5696bfa742d86f6e0817a887b997ed0e8158ebd5))
* Update jest snapshot for the test
* Fix path to `NativeReanimated` (location of this file changed [here](https://github.com/software-mansion/react-native-reanimated/pull/2401))
run `yarn test:unit` and see it passes
> Make jest test pass

- react-native-reanimated.d.ts
- src/Animated.js
- src/createAnimatedComponent.tsx
- src/reanimated2/component/FlatList.tsx
- src/reanimated2/component/WrappedComponents.ts
- src/reanimated2/component/index.ts
The default implementation of `FlatList` wraps every item by custom component. This component hasn't got children's properties - in effect wrapping component hasn't the layout property with `layout` animation. It means the animation of the layout will not run because the "layout event" will be consumed by the wrapping component instead of his child.
```js
<Animated.FlatList // use Animated.FlatList instead of FlatList
itemLayoutAnimation={Layout.springify()} // this animation will be apply as layout property for every list item
data={itemsData} // as always
renderItem={renderItem} // as always
/>
```
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/2664 https://github.com/software-mansion/react-native-reanimated/issues/2424
Inspired by: @nicholash747 's …
> Layout animation for FlatList

- android-npm/build.gradle
- android-npm/expo/linking.gradle
- android-npm/expo/src/main/java/com/swmansion/reanimated/EXReanimatedAdapter.java
- android-npm/expo/src/main/java/expo/modules/adapters/reanimated/EXReanimatedPackage.java
- expo-module.config.json
- package.json
Previously, to support reanimated in Expo SDK, we had reanimated builtin in our template even user don't use it. In newer SDK, we plan to support native modules as opt-in without extra setup; we proposed https://github.com/expo/expo/pull/14883 and this pr is for reanimated integration.
- Add `expo-module.config.json` for expo autolinking
- Add `android/expo` files dedicated for expo integration
- Just add single line to existing build.gradle for the integration.
We will check the gradle dependencies to see if there are `expo` project and only enable the integration then.
[demo repo](https://github.com/Kudo/ExpoAndroidWrapper) which based on expo sdk43 bare template with additional changes:
1. adapts https://github.com/expo/expo/pull/14883 patch because it doesn't publish yet.
2. remove …
> Propose Expo integration

- android-npm/expo/src/main/java/expo/modules/adapters/reanimated/EXReanimatedPackage.java
- expo-module.config.json
remove unnecessary expo integration code and reduce maintain cost from future interfaces change.
- remove unused autolink `name` from [the review comment](https://github.com/software-mansion/react-native-reanimated/pull/2595#discussion_r760030289)
- remove unused override methods where we will change expo-modules-core to support java 8 interface default method https://github.com/expo/expo/pull/15421
to verify it works, i also update the [demo repo](https://github.com/Kudo/ExpoAndroidWrapper) and the same patch [here](https://github.com/Kudo/ExpoAndroidWrapper/commit/3f95bdd35cc2e0f465e66c22b51deb71db82176e#diff-42ef841dc27fe0b5aa2d06bd31308bb63a59cdcddcbcddd917248349d22020a3)
> [expo] remove unnecessary integration code

- Common/cpp/Tools/RuntimeDecorator.cpp
- src/reanimated2/core.ts
Adds support for measuring performance/elapsed time in millisecond precision using Chrono with `performance.now()` in Worklets.
- Inject `_chronoNow` func in global runtime object
```ts
'worklet'
const start = performance.now()
for (let i = 0; i < 1000000; i++) {}
const end = performance.now()
console.log(`Loop took ${end - start} ms!`)
})()
```
* https://github.com/facebook/react-native/pull/32695
> feat: Add `performance.now()` to Worklets

- Example/src/LayoutReanimation/Modal.tsx
- Example/src/LayoutReanimation/ModalNewAPI.tsx
- Example/test/CustomLayout2.tsx
- Example/test/CustomLayout3.tsx
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/Snapshot.java
- react-native-reanimated.d.ts
> Fix lint errors

- android-npm/expo/linking.gradle
- in expo auto setup integration, we create an android library project and implicitly generate a `BuildConfig` class. reanimated also has one `BuildConfig` in aar. in release build, R8 will throw error when there's duplicated class.
- fix the error `Direct local .aar file dependencies are not supported when building an AAR.`.
fixes #2711 
- disable implicitly `BuildConfig` creation in the android library project. 
- disable `bundleDebugAar` and `bundleReleaseAar` tasks
1. the [auto setup example repo](https://github.com/Kudo/ExpoAndroidWrapper)
```
expo run:android
expo run:android --variant release
cd android && ./gradlew assembleRelease
```
2. scratch from expo project
```
expo init reanimatedexpo # choose blank managed project
expo run:android
expo run:android --variant release
```
> [expo] fix duplicated BuildConfig error in release build

- src/reanimated2/core.ts
For web implementation we shouldn't mock `performance.now()` function. I added a check to disable mocking for the web.
Fixes #2714
Based on https://github.com/software-mansion/react-native-reanimated/pull/2715 
Thanks, @yusufyildirim I really appreciate that you report an issue and fixed it! Awesome! ❤️
> Do not mock `performance.now` for web

- ios/LayoutReanimation/REAUIManager.mm
- ios/Nodes/REAPropsNode.m
react classes should be imported by `#import <React/RCTSomeClass.h>` which clang can convert as `@import React.RCTSomeClass;` and find correct clang modules.
`#import "RCTSomeClass.h"` -> `#import <React/RCTSomeClass.h>`
build passing:
```
yarn
cd Example && yarn
cd Example/ios && pod install
npx react-native run-ios
```
> [ios] import react classes from formal react module

- src/reanimated2/core.ts
Description and motivation for this PR.
`global._chronoNow` doesn't seem to be defined when connected to chrome debugger but `global.performance` is defined already. So I think there is no need to mock in that case.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2760
do not mock `global.performance` when connected to chrome debugger (same behaviour as for web)
> do not mock global.performance when connected to chrome debugger

- src/reanimated2/core.ts
Alternative solution to #2761, related: #2760
> fix: Only inject `global.performance.now` if not already defined

- docs/docs/fundamentals/installation.md
After upgrading to 2.3.0 i was getting instant crashes on release variants. 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.swmansion.reanimated.layoutReanimation.f.j()' on a null object reference
```
Adding reanimated to proguard rules fixes the issue.
> Add reanimated to proguard rules.

- src/reanimated2/hook/utils.ts
This PR fixes the ability to use color animations directly in useAnimatedStyle. 
This diff changes the way `parseColors` method works. Before this change we'd run all the updates for color properties (e.g. `backgroundColor`) via that method and expect it to update color to a normalized form. This way we'd get normalized values to send to the native side. However, if you'd specify `withTiming(someColor)` as a value, the parser would return `undefined` and override that animated value. As a result removing that animation object from styles would result in disabling that animation completely (the code fragment responsible for running animation would never see it). What we should be doing instead is to allow animated color values to be passed as animation objects and be parsed only when they …
> Fix animating colors direclty from useAnimatedStyle

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
- ios/LayoutReanimation/REAAnimationsManager.h
- ios/LayoutReanimation/REAAnimationsManager.m
The problem occurs since #2651
Why?
Layout animations are disabled by default until someone call layout animation. Then layout animation is enabled. The problem is when someone uses layout animation in components that don't appear in the first render. It breaks the previous assumption of layout animation - "every component is sent to `onViewCreate` function". In effect, we tried to remove the view that wasn't registered in `_viewForTag` register.
There was also another problem because uses this:
```c++
ViewState state = [_states[tag] intValue];
```
without checking if `_states[tag]` is `nil`. Then `nil` was converted to `0` and then to the first value from `ViewState` (`Appearing`), but this is wrong because the default state should be `Inactive` because not every component has animation. …
> Changed default ViewState

- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/java/com/swmansion/reanimated/ReanimatedJSIModulePackage.java
- android/src/main/java/com/swmansion/reanimated/Utils.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
Layout animated provided many changes, one of the effects is that Reanimated always tries to load the native module, but this breaks the chrome debugger on Android, unfortunately. I detected when chrome debugger is enabled based on React Native code: [source](https://github.com/facebook/react-native/blob/v0.67.0-rc.6/ReactAndroid/src/main/java/com/facebook/react/modules/blob/BlobCollector.java#L25-L26)
```js
// When debugging in chrome the JS context is not available.
if (jsContext.get() != 0) {
```
ant then I don't load the native reanimated module.
Crash:
```
E/AndroidRuntime: FATAL EXCEPTION: mqt_js
Process: com.swmansion.reanimated.example, PID: 3681
java.lang.AssertionError: No source URL loaded, have you initialised the instance?
at …
```
> Fix chrome debugger for android

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
- src/reanimated2/Easing.ts
During the performance optimization, I changed the implementation of `Easing.bezier` function, now return an object instead of a plain function, so I added the old implementation in `Easing.bezierFn`
Fixes #2766
> Old implementation of bezier function

- plugin.js
Add `onChange` to set of Gesture Handler builder methods in the Babel plugin.
Related PR: https://github.com/software-mansion/react-native-gesture-handler/pull/1802
> Add `onChange` to set of Gesture Handler builder methods in the Babel plugin

- ios/native/NativeMethods.h
- ios/native/NativeProxy.mm
I just changed the way of importing gesture handler headers because in some configurations these were unknown.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2740
> Fix import of gesture handler headers on iOS

- docs/versioned_docs/version-2.3.0/fundamentals/installation.md
We had updated information about Proguard only in the newest version of the documentation: https://github.com/software-mansion/react-native-reanimated/blob/main/docs/docs/fundamentals/installation.md#proguard
I added this info also documentation in version 2.3.0
Related PR: https://github.com/software-mansion/react-native-reanimated/pull/2725
> Add info about proguard to docs

- src/reanimated2/hook/useAnimatedStyle.ts
- src/reanimated2/hook/utils.ts
When I was doing performance optimizations, I removed function `styleDiff`, this function computes differences between old style and new style and returns only differences. In effect, we updated only changed style properties. When I removed the call of styleDiff (because was expensive) there was possible to call `layout()` too many times, even if someone doesn't change the layout property (layout is also expensive) but there was another problem because we need an update synchronous and asynchronous updates in the same `updateProps` call. So we decided to restore `styleDiff` but with faster implementation. We get rid of comparison by `JSON.stringify()`, the shall computation should be enough in this way.
<details>
```js
const objA = {
a: 1,
b: 2,
c: {},
d: [],
e: { …
```
> Compute style changes before update

- .github/workflows/close-when-stale.yml
This PR introduces a new GitHub Actions swmansion-bot feature - `close-when-stale`. The code of this action can be found [here](https://github.com/software-mansion-labs/swmansion-bot/tree/main/close-when-stale).
This action runs daily and closes issues that have a specified label (here `close-when-stale`) with no activity for some time (here `20` days).
The label is automatically removed when activity on an issue from someone outside of the organization is detected.
- Added `close-when-stale.yml` - an action that closes the issue with a specified label after some time of inactivity
- Added `close-when-stale` label
> feat: add close-when-stale action

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
Reanimated exposes animated `FlatList` component under `Animated` namespace, but using it in a real world scenario is a bit cumbersome, since it doesn't accept a type parameter that is used to describe list items. 
Fixes #2858
- Updated type for `Animated.FlatList`
- Added additional type test for `Animated.FlatList`
> Accept generic type in Animated.FlatList

- android/rnVersionPatch/62/layoutReanimation/ReanimatedNativeHierarchyManager.java
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
- src/reanimated2/commonTypes.ts
- src/reanimated2/hook/useAnimatedStyle.ts
- src/reanimated2/hook/utils.ts
Close https://github.com/software-mansion/react-native-reanimated/issues/2773
ADB log crash
```
W/System.err( 5236): java.lang.NoSuchFieldException: accessFlags
W/System.err( 5236): 	at java.lang.Class.getDeclaredField(Class.java:890)
W/System.err( 5236): 	at com.swmansion.reanimated.layoutReanimation.ReanimatedNativeHierarchyManager.<init>(ReanimatedNativeHierarchyManager.java:208)
W/System.err( 5236): 	at com.facebook.react.uimanager.ReanimatedUIImplementation.<init>(ReanimatedUIImplementation.java:40)
W/System.err( 5236): 	at com.facebook.react.uimanager.ReaUiImplementationProvider.createUIImplementation(ReanimatedUIManager.java:23)
W/System.err( 5236): 	at com.facebook.react.uimanager.UIManagerModule.<init>(UIManagerModule.java:189)
W/System.err( 5236): 	at …
```
> fix: fixed NullPointerException on Android 5.1

- docs/docs/fundamentals/installation.md
- docs/versioned_docs/version-2.0.0/installation.md
- docs/versioned_docs/version-2.1.0/installation.md
- docs/versioned_docs/version-2.2.0/installation.md
- docs/versioned_docs/version-2.3.0/fundamentals/installation.md
After the stable release, we no longer need to use `@next` during the installation
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2633
> Removed @next

- src/reanimated2/NativeMethods.ts
I replaced the exception with a warning message in the `measure` function because if someone uses `measure` inside `useDerivedValue` the initial call is called on react native side.
Fixes #2779
> Display only warn if measure is called on RN side

- mock.js
`interpolate is not a function` was encountered during test when `reanimated` is mocked, it was, in fact, missing from `mock.js`
add `interpolate` to `mock.js`
```js
// jest.setup.js
jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'));
```
Test render a component that has interpolation.
- [?] Included code example that can be used to test this change
> fix(mock): add interpolate to mock

- .github/workflows/needs-more-info.yml
- .github/workflows/needs-repro.yml
- .github/workflows/platforms.yml
This PR adds a way to disable GitHub Actions bot replies by adding a `maintainer-issue` label. 
Also, this PR fixes the concurrency issue when two independent actions close one other.
> Add maintainer-issue label

- ios/native/NativeProxy.mm
Fixes:
- #1776
- #2757
See https://github.com/software-mansion/react-native-reanimated/issues/1776#issuecomment-1024215820 for details
- Fix crash when handling event containing `NaN` or `INF` values
1. Set breakpoint in `NativeProxy.mm:259` to make sure that there is no regression in handling valid Reanimated events.
2. Send an event with `NaN` or `INF` value and set breakpoint in `catch` block to make sure the exception is caught.
> Fix crash when handling event containing `NaN` or `INF` values for iOS

- android/src/main/cpp/headers/NativeProxy.h
Applies the iOS fix in https://github.com/software-mansion/react-native-reanimated/pull/2896 for android.
Fixes:
- #2662
- #2814
- #2914
Fix crash when handling event containing NaN or INF values
tested by manually inserting NaN and INF values in receiveEvent.java
> Fix crash when handling event containing NaN or INF values for android

- docs/docs/guide/testing.md
Updating documentation for jest >= 27 since the 'modern' useFakeTimers does not work (yet) with react-native: https://github.com/facebook/jest/issues/10221
> Adding legacy hint for useFakeTimers

- createNPMPackage.sh
- react-native-reanimated.d.ts
- src/reanimated2/Colors.ts
`InterpolateConfig` interface is [declared here](https://github.com/software-mansion/react-native-reanimated/blob/7820ec095de7a719150dc5021561f0b8b0b10f38/src/reanimated2/Colors.ts#L768-L773) as follows:
```ts
export interface InterpolateConfig {
inputRange: readonly number[];
outputRange: readonly (string | number)[];
colorSpace: ColorSpace;
cache: SharedValue<InterpolateRGB | InterpolateHSV>; // <-- Shared value of non-null type!
}
```
few lines below it is being used:
```ts
export function useInterpolateConfig(
inputRange: readonly number[],
outputRange: readonly (string | number)[],
colorSpace = ColorSpace.RGB
): SharedValue<InterpolateConfig> {
return useSharedValue({
inputRange,
outputRange,
colorSpace,
cache: makeMutable(null), // <-- returns shared value of null type
});
}
``` …
> Quick fix for yarn type:generate command failing

- src/reanimated2/NativeReanimated/index.ts
We need to mock the native module by JS implementation for web, jest, and chrome debugger. We mock it on the condition `nativeShouldBeMock` - `isJest() || isChromeDebugger()` i check it to more proper `shouldBeUseWeb` - `isJest() || isChromeDebugger() || isWeb()`.
It worked because the web had implemented `global.nativeCallSyncHook`, but I am not sure that it will work for every edge case.
> Check platform better

- android/src/main/cpp/NativeProxy.cpp
The hermes profiler expects the runtime to be running on the same thread as it was created on. Since the UI JS runtime is created from the JS thread it seems to be the cause of the issue. As a workaround it is possible to disable the profiler for the UI runtime.
Fixes #2143
Disable profiler for Hermes JS runtime on Android.
N/A
On android open the dev menu and select "Enable Sampling Profiler". This will cause the app to crash before this fix, after it will properly record a sample trace.
> Disable sample profiler for UI hermes JS runtime

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
Sometimes RN passes ReadableMap/Array instead of WritableMap/Array when updateProps is called. Currently adding a ReadableMap/Array to a WritableMap/Array is not supported (I opened a PR to allow it since there's no reason it can't be allowed https://github.com/facebook/react-native/pull/32910). In the meantime we have to check if it's not Writable and copy before adding it.
Fixes #2722
N/A
I'm not sure exactly what the minimum repro is, I could 100% repro the crash in an app, but wasn't able to isolate. The app makes heavy usage of a bottom sheet lib that uses reanimated. I was able to repro a few times in the example app with the repro in the linked issue, but not consistently.
In the app where I could repro consistently I verified that it no longer crashes after this change.
> Fix "Illegal type provided" crash

- react-native-reanimated.d.ts
By adding empty interfaces extending RN components with names being the same as exported classes, we merge declarations from RN types with ours. This allows for correctly typing refs.
Used autocompletion in VSCode
```tsx
const ref = useRef<Animated.ScrollView>();
ref.current. // autocomplete here
```
After this patch, it listed `scrollResponder*` methods.
> Add RN components' methods to Animated counterparts in TS

- .github/workflows/static-root-checks.yml
- package.json
- src/reanimated2/NativeMethods.ts
- src/reanimated2/NativeReanimated/NativeReanimated.ts
- src/reanimated2/animation/commonTypes.ts
- src/reanimated2/animation/decay.ts
- src/reanimated2/animation/delay.ts
- src/reanimated2/animation/index.ts
- src/reanimated2/animation/repeat.ts
- src/reanimated2/animation/sequence.ts
- src/reanimated2/animation/spring.ts
- src/reanimated2/animation/styleAnimation.ts
- src/reanimated2/animation/timing.ts
- src/reanimated2/animation/util.ts
- src/reanimated2/commonTypes.ts
- src/reanimated2/core.ts
- src/reanimated2/hook/commonTypes.ts
- src/reanimated2/hook/useAnimatedRef.ts
- src/reanimated2/hook/useAnimatedStyle.ts
- src/reanimated2/hook/utils.ts
- src/reanimated2/index.ts
- src/reanimated2/js-reanimated/JSReanimated.ts
- src/reanimated2/js-reanimated/Mapper.ts
- src/reanimated2/js-reanimated/MapperRegistry.ts
- src/reanimated2/js-reanimated/commonTypes.ts
- src/reanimated2/layoutReanimation/defaultTransitions/EntryExitTransition.ts
- src/reanimated2/utils.ts
- yarn.lock
I resolved some circular dependencies:
```
1) reanimated2/js-reanimated/JSReanimated.ts > reanimated2/js-reanimated/Mapper.ts
2) reanimated2/js-reanimated/JSReanimated.ts > reanimated2/js-reanimated/MapperRegistry.ts
3) reanimated2/animation/util.ts > reanimated2/animation/delay.ts
4) reanimated2/animation/util.ts > reanimated2/animation/repeat.ts
5) reanimated2/animation/util.ts > reanimated2/animation/sequence.ts
6) reanimated2/animation/styleAnimation.ts > reanimated2/animation/timing.ts > reanimated2/animation/util.ts
7) reanimated2/NativeMethods.ts > reanimated2/hook/useAnimatedRef.ts
```
Because files used each other's TS types.
I added [madge](https://github.com/pahen/madge) tool to detect circular dependencies to CI test
Fixes …
> Fix circular deps

- mock.js
`interpolateColor is not a function` was encountered during test when `reanimated` is mocked, it was, in fact, missing from `mock.js`
I think there's more of this (#2895), what's a good way to add all of the missing ones?
add `interpolateColor` to `mock.js`
```js
// jest.setup.js
jest.mock('react-native-reanimated', () => require('react-native-reanimated/mock'));
```
Test render a component that has interpolateColors.
- [?] Included code example that can be used to test this change
> Add `interpolateColor` mock

- docs/versioned_docs/version-2.3.0/fundamentals/installation.md
This PR fixes a couple of typos in the installation steps in the documentation on the `/react-native-reanimated/docs/fundamentals/installation` page.
> Fix typos in the installation docs

- react-native-reanimated-tests.tsx
- react-native-reanimated.d.ts
Fixes #1717.
- Added `style` property for every component that has animated props.
- `Added test in react-native-reanimated-tests.tsx`
> Add style prop to every animated component

- ios/LayoutReanimation/REAAnimationsManager.m
`CGPointMake(x, y)` doesn't accept `NaN` as argument. I added a check for this case.
```js
import React, { memo, useState } from 'react';
import { Button, SafeAreaView, View } from 'react-native';
import Animated, { SlideInDown } from 'react-native-reanimated';
const AppComponent = () => {
const [count, setCount] = useState(0);
return (
<SafeAreaView style={{flex: 1}}>
<Button title="increment" onPress={() => setCount(v => v + 1)} />
<View style={{height: 40, overflow: 'hidden'}}>
<Animated.Text exiting={SlideInDown} key={count}>
{count}
</Animated.Text>
</View>
</SafeAreaView>
);
};
```
Fixes https://github.com/software-mansion/react-native-reanimated/issues/2878
> Check for NaN

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
This aims to prevent some of the crashes [reported here](https://github.com/software-mansion/react-native-reanimated/issues/2508#issuecomment-1032330992), however it is likely that it is not final solution to the problem.
Catch & ignore IllegalViewOperationException in AnimationsManager#removeLeftovers
> Catch & ignore IllegalViewOperationException in AnimationsManager#removeLeftovers 

- Common/cpp/NativeModules/NativeReanimatedModuleSpec.cpp
Exported JSI functions seem to follow some name conventions. The function name prefix is quite long and easy to make typos so I added a macro for generating them.
Built and ran the example app
> Add macro for JSI spec exported functions

- android/src/main/cpp/headers/NativeProxy.h
- ios/native/NativeProxy.mm
This is a follow up pr of https://github.com/software-mansion/react-native-reanimated/pull/2901 which unfortunately doesn't solve [the issue](https://github.com/software-mansion/react-native-reanimated/issues/2814). I do not fully understand why but the try/catch currently has no effect. It's a bit surprising to me because as far as I can see `folly::json::parse_error` should be the same as `std::exception` but I see that the crash is still happening for us in production after updating to 2.4.1 and I can also reproduce it with the example app.
@piotrekzyla @tomekzaw 
Make sure the try/catch actually works by catching a more generic error.
I tested the code change with the example app by manually adding a `NaN` value to the event.
> Fix crash when handling event containing NaN or INF values

- android/src/main/java/com/swmansion/reanimated/ReanimatedPackage.java
This PR adds a getter for `ReactInstanceManager`. The motivation for this PR is to fix issues #2719 and #2801
Those Android apps whose application class does not implement `ReactApplication` or simply have a different mechanism for storing a `ReactInstanceManager`, currently they have an incompatibility with `react-native-reanimated` ending in a crash when launching the app, as the issues indicates.
Normally, those apps are where [React Native is integrated with existing Android apps](https://reactnative.dev/docs/integration-with-existing-apps)
So, introducing this getter allows us to override this getter and implement a custom way to return the `ReactInstanceManager` to be used by `react-native-reanimated`.
- Added `getReactInstanceManager` method for android.
This is an example of how …
> Add getter for `reactInstanceManager` 

- android/build.gradle
- package.json
The `maven` plugin has been deprecated since gradle 6.0 and was removed in gradle 7.0.
React Native 0.67.1 uses gradle 7.2
This PR updates the library to use `maven-publish` so it works with gradle 7.2 and React Native 0.67.1
If you run use `"react-native-reanimated": "1.13.3"` with `"react-native": "0.67.1"` and gradle `7.2` the app fails with:
```
node_modules/react-native-reanimated/android/build.gradle' line: 21
* What went wrong:
A problem occurred evaluating project ':react-native-reanimated'.
> Plugin with id 'maven' not found.
```
With the changes in this PR or the following `patch-patch` changes, the app builds:
```
diff --git a/node_modules/react-native-reanimated/android/build.gradle b/node_modules/react-native-reanimated/android/build.gradle
index 21c386c..627334a 100644
--- …
```
> [V1] Use maven-publish to support React Native 0.67.1 (gradle 7)

- docs/docs/api/LayoutAnimations/EntryAnimations.md
- docs/docs/api/LayoutAnimations/ExitAnimations.md
- react-native-reanimated.d.ts
- src/reanimated2/layoutReanimation/animationBuilder/ComplexAnimationBuilder.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Bounce.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Fade.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Flip.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Lightspeed.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Pinwheel.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Roll.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Rotate.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Slide.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Stretch.ts
- src/reanimated2/layoutReanimation/defaultAnimations/Zoom.ts
This pr introduce a new layout animation modifier `withInitialValues` to sets initial values for pre-defined animations.
This is needed for third-party libraries to override animation props and add initial values - like `originX` & `originY`.
- feat: added `withInitialValues` modifier to `ComplexAnimationBuilder`.
- docs: added the mention for the `withInitialValues` modifier.
Tested the example `DefaultAnimations.tsx >> FadeIn`, where i added a background color as an initial value, and it works
```tsx
FadeIn.withInitialValues({ backgroundColor: 'red' })
```
> feat: added withInitialValues modifier

- android/gradle.properties
Fixes the issue when Gradle would crash while linting. More information: https://github.com/diffplug/spotless/issues/834
- Added workaround from https://github.com/diffplug/spotless/issues/834#issuecomment-819118761
Linted some Java code.
> Fix Java lint on JDK 16+

- react-native-reanimated.d.ts
#2979 introduced a typo, [as reported here](https://github.com/software-mansion/react-native-reanimated/pull/2979#discussion_r809231482).
🤦🏼 
Fixed the typo
```js
withTiming,
Easing,
export function TestScreen() {
const randomWidth = useSharedValue(10);
const config = {
duration: 500,
easing: Easing.bezier(0.5, 0.01, 0, 1),
};
return {
width: withTiming(randomWidth.value, config),
};
});
return (
<View
style={{
flex: 1,
alignItems: 'center',
justifyContent: 'center',
flexDirection: 'column',
}}>
<Animated.View
style={[{ width: 100, height: 80, backgroundColor: 'black', margin: 30 }, style]}
/> …
```
> Fix typo introduced in #2979

- android/build.gradle
React native support this property to allow building for specific architectures only.
Add support for reactNativeArchitectures like in https://github.com/facebook/react-native/blob/main/ReactAndroid/build.gradle#L227.
Use source build with the latest react-native version and run react-native start-android.
> Source build: support reactNativeArchitectures

- android/build.gradle
This will be more reliable in a mono-repo setup. We assume the react-native / other deps are in the same directory as react-native-reanimated instead of assuming it is in rootDir/../node_modules.
Use relative path from the react-native-reanimated package instead of project root.
Use source build in a monorepo.
> Source build: resolve react-native and other packages relative to reanimated package

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/NativeModules/NativeReanimatedModuleSpec.cpp
- Common/cpp/headers/NativeModules/NativeReanimatedModule.h
- Common/cpp/headers/NativeModules/NativeReanimatedModuleSpec.h
- Common/cpp/headers/Tools/PlatformDepMethodsHolder.h
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/headers/NativeProxy.h
- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/java/com/swmansion/reanimated/NodesManager.java
- android/src/main/java/com/swmansion/reanimated/ReanimatedModule.java
- ios/REAModule.m
- ios/REANodesManager.h
- ios/REANodesManager.m
- ios/native/NativeProxy.mm
- src/ConfigHelper.ts
- src/reanimated2/NativeReanimated/NativeReanimated.ts
- src/reanimated2/core.ts
There was a possibility to run updateProps before an update of the allowlist of properties on the native side. It happened because an update of properties allowlist was asynchronous. I added the JSI function to make it update synchronously.
> ConfigureProps by JSI

- package.json
Some users are reporting that they get an error of `Cannot find module '@babel/preset-typescript'`
This appears to be because `@babel/preset-typescript` is used at runtime for [the worklet plugin](https://github.com/software-mansion/react-native-reanimated/blob/main/plugin.js#L361). Many React Native projects won't have this dependency by default as it's not included in the [React Native TypeScript template](https://github.com/react-native-community/react-native-template-typescript/blob/main/template/package.json).
Fixes #2746
Add `@babel/preset-typescript` to `peerDependencies` to fix error: `Cannot find module '@babel/preset-typescript'`
1. Spin up a new React Native TypeScript project: `npx react-native init MyApp --template react-native-template-typescript`
2. [Install …
> Add @babel/preset-typescript to peerDependencies as it's used at runtime for the worklet plugin

- docs/docs/guide/testing.md
- docs/versioned_docs/version-2.0.0/testing.md
- docs/versioned_docs/version-2.1.0/testing.md
- docs/versioned_docs/version-2.2.0/testing.md
- docs/versioned_docs/version-2.3.0/guide/testing.md
Changed mentions of `moveAnimationByTime` to `advanceAnimationByTime` in code sample (documentation).
- replaced `moveAnimationByTime` to `advanceAnimationByTime`
Try to copy the code from documentation and run it 🙂
> moveAnimationByTime -> advanceAnimationByTime in docs

- ios/REANodesManager.m
Invalidate display link instead of pausing it when invalidating the nodes manager
Pausing the display link on invalidation will still make it call the onAnimationFrame selector one more time as its already schedule. When this happens animation blocks will be called and crash while accessing the jsi runtime thats already dealloced.
Fixes #2035
Fixes #2899
See #2035 for reproduction
> Invalidate display link instead of pausing it when invalidating the nodes manager

- android/build.gradle
Fixes #3119. 
Use `implementation` instead of `compile`. This is the same fix as https://github.com/auth0/react-native-auth0/pull/450.
Include `react-native-reanimated` with this change in a project using Gradle 7 and it should successfully build.
> Remove reference to deprecated "compile" configuration for compatibility with Gradle 7

- android/build.gradle
The task names changed and include the architecture when using the gradle plugin v7. This is compatible with new and old task names.
- Register task dependencies in afterEvaluate instead of whenTaskAdded
- Check for tasks containing CMake instead of buildCMake to match tasks like `configureCMakeDebug[arm64-v8a]`
- Make sure task doesn't include Clean to avoid matching clean tasks
- Keep checking for `externalNative` to support older gradle plugin versions
Use gradle plugin@7
android/build.gradle
```groovy
classpath 'com.android.tools.build:gradle:7.1.1'
```
> Source build: Support gradle plugin v7

- src/ConfigHelper.ts
Currently, `opacity` prop is listed both in `UI_THREAD_PROPS_WHITELIST` and `NATIVE_THREAD_PROPS_WHITELIST`. However, when splitting props into three groups (namely: UI props, native props and JS props), we always search in the UI props set first, so effectively `opacity` is always animated like a UI prop (which is the expected behaviour). Nevertheless, we would like to avoid confusion by keeping these two sets disjoint, so this PR removes `opacity` from `NATIVE_THREAD_PROPS_WHITELIST`.
- Removed `opacity` from native props list
1. Launch Example app
1. Open Olympic animation demo
1. See if opacity is properly animated
> Remove `opacity` from native props list

- package.json
- yarn.lock
This PR removes `react-native-screens` from dependencies in package.json.
Fresh version of #2762.
- Removed `react-native-screens` from dependencies
1. Run Example app on Android and iOS
> Remove `react-native-screens` from dependencies

- package.json
The gesture-handler isn't required as a peer dependency.
> Remove gesture-gandler

- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
In Expo, `ApplicationContext` is not an instance of `ReactApplication`, and the casting caused a runtime exception. I added a check for `instanceof` to make it safe.
> Fix Expo dev menu

- Common/cpp/SharedItems/ShareableValue.cpp
- Common/cpp/Tools/RuntimeDecorator.cpp
- __tests__/__snapshots__/plugin.test.js.snap
- __tests__/plugin.test.js
- plugin.js
- src/reanimated2/Easing.ts
- src/reanimated2/commonTypes.ts
- src/reanimated2/core.ts
- src/reanimated2/globals.d.ts
This PR removes `__reanimatedWorkletInit` function as well as `__worklet` property in favor of checking for existence of `__workletHash` property.
Additionally, in the past we've had some problems related to using spread operator in worklets (see #1453). However, this seems to work fine now thanks to the fact that we use `transformSync` to apply other plugins before workletization (in particular, stringification). Check out the attached test example. By the way, spread operator is allowed in `_f.asString` (I've confirmed that by running the unit tests on the main branch).
- Removed `__reanimatedWorkletInit` function
```tsx
import { runOnUI } from 'react-native-reanimated';
function worklet() {
'worklet'; …
```
> Remove `__reanimatedWorkletInit` function and `__worklet` property

- .github/workflows/validate-java.yml
- android/src/main/java/com/swmansion/reanimated/NativeProxy.java
This PR fixes Java linter not firing automatically for PRs with changes to Java files.
- Fixed path for Java linter
- Fixed formatting in NativeProxy.java
1. Check that "Java Lint" appears on the list of checks for this PR.
> Fix CI config for Java linter

- package.json
Follow up to #3077 makes `@babel/preset-typescript` a full dependency to properly solve runtime issues for users without `@babel/preset-typescript` present.
Previously I added it as a `peerDependency` but a soft warning at package install time is too easy to miss.
Add `@babel/preset-typescript` to `dependencies` to fix error: `Cannot find module '@babel/preset-typescript'`
1. `npx react-native init MyApp --template react-native-template-typescript`
2. [Install Reanimated](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation)
3. Run app
4. Get error! 💥 
6. Install `@babel/preset-typescript`
7. Error sorted ✅ 
1. `npx react-native init MyApp --template react-native-template-typescript`
2. [Install Reanimated](https://docs.swmansion.com/react-native-reanimated/doc …
> Make @babel/preset-typescript a full dependency as it's used at runtime

- package.json
@babel/plugin-transform-object-assign requires to have @babel/core as peer dependency. That warning is provided by yarn when using the latest version reanimated version 2.6.0.
- Added @babel/core as peer dependency.
- Create template project
- Add reanimated
- Run yarn install
- That will output a warning that reanimated is missing a peer dependency.
- Create template project
- Add reanimated
- Run yarn install
- No warning for reanimated.
> Add @babel/core as peer dependency which is required by @babel/plugin-transform-object-assign

- src/reanimated2/Easing.ts
Missing `worklet` directive in the return function of `Easing.back()` results in an error shown below.
Add `worklet` directive at the top of the return function of `Easing.back` function
```
import { Button, View } from 'react-native';
withTiming,
Easing,
} from "react-native-reanimated";
export default function EasingBackExample() {
const anim = useSharedValue(0);
const animStyles = useAnimatedStyle(() => {
const translateY = interpolate(
pitaAnim.value,
[0, 1],
[0, 200],
Extrapolate.EXTEND,
);
return {
transform: [{ translateY: translateY }],
};
});
const runAnimation = () => {
anim.value = withTiming(1, {
duration: 600,
easing: Easing.back(1),
});
}
return (
<View>
<Animated.View
style={[
{
width: 120, …
```
> Add worklet to easing back return function

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
ReactApplicationContext.getCurentContext sometimes return null. This causes a crash (NullPointerException) in reanimated due to not checking if context exists. As per react native's examples, we can only measure device metrics when current activity is not null (https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/ReactCommon/react/nativemodule/samples/platform/android/SampleTurboModule.java#L56)
Fixes #2959.
Check if current activity is not null before measuring the device.
> fix: android layout reanimation null pointer exception (2959)

- docs/docs/fundamentals/migration.md
- docs/versioned_docs/version-2.0.0/migration.md
- docs/versioned_docs/version-2.1.0/migration.md
- docs/versioned_docs/version-2.2.0/migration.md
- docs/versioned_docs/version-2.3.0/fundamentals/migration.md
I fixed a typo in the migration docs (v1->v2) where the wrong `there` was used. :)
Updated typo in v2.3.0 docs.
If wanted, I can fix this typo in older docs too.
n/a
> Fix typo in migration docs

- ios/native/NativeProxy.mm
- src/Animated.js
At the time, the `RNGestureHandlerModule` is loaded when the `createReanimatedModule` method is called. This causes `RCTBridge required dispatch_sync to load RNGestureHandlerModule.` warning to appear. This PR changes it, so the module is loaded only the first time the `setGestureState` function is called.
Install `react-native-reanimated` and `react-native-gesture-handler` and check if the warning appears.
> Load `RNGestureHandlerModule` lazily on iOS

- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/headers/NativeProxy.h
Fixes:
```
2022-04-19 12:01:12.545 23863-23863/? A/DEBUG: Abort message: '/Users/lukasz/work/expo/android/ReactAndroid/../ReactCommon/jsi/JSCRuntime.cpp:394: virtual facebook::jsc::JSCRuntime::~JSCRuntime(): assertion "objectCounter_ == 0 && "JSCRuntime destroyed with a dangling API object"" failed'
2022-04-19 12:01:12.545 23863-23863/? A/DEBUG:     x0  0000000000000000  x1  0000000000005cd1  x2  0000000000000006  x3  0000006f7acdc3f0
2022-04-19 12:01:12.545 23863-23863/? A/DEBUG:     x4  0080808080808080  x5  0080808080808080  x6  0080808080808080  x7  8080808080808000
2022-04-19 12:01:12.545 23863-23863/? A/DEBUG:     x8  00000000000000f0  x9  57ea5f66b3577129  x10 0000000000000000  x11 ffffff80fffffbdf
2022-04-19 12:01:12.545 23863-23863/? A/DEBUG:     x12 0000000000000001  x13 …
```
> Fix JSCRuntime destroyed with a dangling API object

- android/src/main/cpp/NativeProxy.cpp
- ios/native/REAInitializer.mm
If a pointer to worklet jsi:Runtime has large enough value (happens on android 11) static_cast to double is affecting the value.
It's not possible to do reinterpret_cast there because JSC is tagging numeric values, so pointer value can change https://github.com/WebKit/WebKit/blob/8afe31a018b11741abdf9b4d5bb973d7c1d9ff05/Source/JavaScriptCore/API/JSValueRef.cpp#L355
Instead of passing value as a number use ArrayBuffer
This is a breaking change, but anyone that is relying on that value should also check for that value existence.
Did not test it here, but this is exact copy of changes I made in versioned expo code and tested it there 
https://github.com/expo/expo/pull/17194
> Pass worklet runtime pointer using ArrayBuffer

- Common/cpp/Tools/RuntimeDecorator.cpp
- src/reanimated2/core.ts
Adds performance.now on cpp side, instead of the js side. The `global` object is overwritten by reanimated, so adding functions to `global` object on js side doesn't make them visible in global scope. Adding them on cpp side makes them visible in global scope.
Add `console.log(performance.now())` to any worklet.
Before: worklet stops executing
After: worklet works and prints current time
> Fix performance.now() in worklets

- src/reanimated2/NativeReanimated/NativeReanimated.ts
This fixes the remote debugging failure on Android using Chrome as installTurboModule is annotated @ReactMethod(isBlockingSynchronousMethod = true) and triggers an error when called in Chrome.
Fixes #3174.
Tested by attempting to debug on Android simulator and not observing the error anymore.
The last version where remote debugging using Chrome worked was 2.4.1 as the changes to NativeAnimated.ts was introduced in 2.5.0.
> Fix Android remote debugging failure

- FabricExample/App.tsx
This PR removes a workaround in FabricExample app that I've prevously added because I forgot to wrap the flatlist with `<GestureHandlerRootView>`.
- Added `<GestureHandlerRootView>` in FabricExample app
1. Run FabricExample app on Android
2. Check if tapping any flatlist item opens up a new screen with the example
> [Fabric] Add `<GestureHandlerRootView>` in FabricExample

- src/reanimated2/component/FlatList.tsx
This PR renames `ReanimatedFlatlistProps` to `ReanimatedFlatListProps` for consistency reasons.
- Changed `ReanimatedFlatlistProps` to `ReanimatedFlatListProps`
1. Check if TypeScript CI job passes
> Fix typo in `ReanimatedFlatListProps`

- ios/native/NativeProxy.mm
- ios/native/REAJSIUtils.h
This PR moves JSI Obj-C++ static helper functions such as `convertObjCObjectToJSIValue` etc. to a separate file for readability purposes.
- Moved JSI Obj-C++ static helper functions to `REAJSIUtils.h`
1. Check if iOS CI job passes
> [Fabric] Move Obj-C++ static helper functions to `REAJSIUtils.h`

- android/src/main/cpp/NativeProxy.cpp
This PR moves the definition of `configurePropsFunction` into `#else` block since it is used only on Paper, fixing the following warning on Android:
```
../../../../src/main/cpp/NativeProxy.cpp:237:8: warning: unused variable 'configurePropsFunction'
```
- Define `configurePropsFunction` only on Paper
1. Check if both Example and FabricExample apps for Android successfully compile on CI
> [Fabric] Define `configurePropsFunction` only on Paper

- src/reanimated2/mock.ts
v2 mocks is missing `Extrapolation`, getting following error in test:
```
TypeError: Cannot read property 'CLAMP' of undefined
```
Add `Extrapolation` mock
Run test with reference to `Extrapolation.CLAMP`.
> Add `Extrapolation` mock

- src/reanimated2/fabricUtils.web.ts
`require('react-native/Libraries/Renderer/shims/ReactFabric').findHostInstance_DEPRECATED;` is causing a bunch of errors on web. I believe that webpack resolves require statically, so the surrounding `try .. catch` doesn't help.
- adds a separate `fabricUtils.web.ts` file that doesn't try to load `findHostInstance_DEPRECATED` function, since Fabric is not supported on web at the moment
I tested it on `reanimated-2-playground` with updated dependencies.
Running it on web with 3.0.0-rc.0 ends with a lot of errors. After this change the errors should be gone.
> Add web-specific version of `fabricUtils`

- FabricExample/react-native-reanimated-tests.tsx
- plugin.js
- react-native-reanimated.d.ts
I just removed type form TS for unimplemented method `createWorklet`
This PR should be copied to Reanimated2 branch also.
Fixes: https://github.com/software-mansion/react-native-reanimated/issues/3131
> Remove unimplemented type

- docs/docs/fundamentals/installation.md
- docs/versioned_docs/version-2.0.x/installation.md
- docs/versioned_docs/version-2.1.x/installation.md
- docs/versioned_docs/version-2.2.x/installation.md
- docs/versioned_docs/version-2.3.x/fundamentals/installation.md
- docs/versioned_docs/version-2.5.x/fundamentals/installation.md
During the installation of `react-native-reanimated` it's incredibly common to encounter a false-positive error that is easily fixed by clearing the cache.
This PR adds a note to the docs about cleaning the cache after installing reanimated's babel plugin.
Fixes https://github.com/software-mansion/react-native-reanimated/issues/1875
Sorry for the dark theme 🙈 
```sh
cd docs/
yarn
yarn start
```
and navigate to http://localhost:3000/react-native-reanimated/docs/fundamentals/installation
> docs: add clean cache note after adding babel plugin

- docs/docs/api/animations/withSpring.md
- docs/versioned_docs/version-2.0.x/api/withSpring.md
- docs/versioned_docs/version-2.1.x/api/withSpring.md
- docs/versioned_docs/version-2.2.x/api/withSpring.md
- docs/versioned_docs/version-2.3.x/api/animations/withSpring.md
- docs/versioned_docs/version-2.5.x/api/animations/withSpring.md
This PR adds descriptions to options of the `withSpring` animation.
https://docs.swmansion.com/react-native-reanimated/docs/api/animations/withSpring
Sorry for the dark theme 🙈
```sh
cd docs/
yarn
yarn start
```
and navigate to http://localhost:3000/react-native-reanimated/docs/api/animations/withSpring
> docs: document withSpring options

- ios/REAModule.mm
Fixes https://github.com/react-navigation/react-navigation/pull/10639
Added back supported events.
```ts
import {Button, View} from 'react-native';
import {
createDrawerNavigator,
DrawerScreenProps,
} from '@react-navigation/drawer';
import {NavigationContainer} from '@react-navigation/native';
type RootStackParamList = {
Home: undefined;
Notifications: undefined;
};
function HomeScreen({
navigation,
}: DrawerScreenProps<RootStackParamList, 'Home'>) {
return (
<View style={{flex: 1, alignItems: 'center', justifyContent: 'center'}}>
<Button
onPress={() => navigation.navigate('Notifications')}
title="Go to notifications"
/>
</View>
);
}
function NotificationsScreen({
navigation,
}: DrawerScreenProps<RootStackParamList, 'Notifications'>) {
return (
<View …
```
> Fix react-navigation drawer crash:  is not a supported event type

- src/reanimated2/animation/sequence.ts
This PR allows to run a sequence of just one animation. It makes little sense, but this is no reason to crash the whole app.
Removed code that throws exception when there's just one animation in a sequence.
It was added in https://github.com/software-mansion/react-native-reanimated/commit/66232c6579f429c74819af6c7ad076a6a3929d72 but removing it doesn't break the app.
> Allow to run a sequence of one animation

- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/yarn.lock
This PR upgrades react-native from 0.69.0-rc.0 to 0.69.0 stable in FabricExample.
> Bump react-native in FabricExample to 0.69.0

- react-native-reanimated.d.ts
Override of `style` props in `AnimatedProps` is conflicting and throw an error. Omitting the `style` key before merging the new interface fix the issue.
Fixes #2968 .
Upgrade `AnimatedProps` type.
> fix: overriden style type in AnimatedProps

- src/reanimated2/animation/util.ts
Fixes a bug with rotation animation.
Fixes #3269
When running animations in sequence, the last animation in sequence is set as a previous animation. It has no prefix/suffix/strippedValue calculated yet, so everything is `undefined`.
Then in `prefNumberSuffOnStart`  the previous value is set to string `"undefined"` (as `""+undefined+"" = "undefined"` in js).
When re-running an animation while the previous one is still running, the previous animation state is copied to current animation state and string "undefined" is further propagated, breaking animation.
The solution is to calculate prefix/suffix/strippedValue of previousAnimation from its current value in `prefNumberSuffOnStart` every time. 
Press the red button quickly a few times, the blue square no longer rotates.
```ts
import * as …
```
> Fix cancelling rotation animation

- Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp
- Example/src/AnimatedSensorExample.tsx
- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensor.java
- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensorType.java
- docs/docs/api/hooks/useAnimatedSensor.md
- docs/versioned_docs/version-2.5.x/api/hooks/useAnimatedSensor.md
- ios/sensor/ReanimatedSensor.m
- react-native-reanimated.d.ts
- src/reanimated2/hook/useAnimatedSensor.ts
Fixes a couple of issues with `useAnimatedSensors`.
- fixed quaternion on iOS
- normalized values between Android and iOS
- typed sensor value
- added `'auto'` interval
> Sensors fixes

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
Fixes https://github.com/software-mansion/react-native-reanimated/issues/3265
Add null check in AnimationsManager.java to `removeLeftovers` since the `mToRemove` can be set to null if app is shut down (for example by react-native-restart) before the callback fires.
- [ N/A ] Included code example that can be used to test this change
- [ N/A ] Updated TS types
- [ N/A ] Added TS types tests
- [ N/A ] Added unit / integration tests
- [ N/A ] Updated documentation
> Fix NPE in AnimationsManager during app shutdown

- docs/docs/guide/testing.md
- docs/versioned_docs/version-2.2.x/testing.md
- docs/versioned_docs/version-2.3.x/guide/testing.md
- docs/versioned_docs/version-2.5.x/guide/testing.md
- src/reanimated2/jestUtils.ts
Add support for Jest 28 with backward compatibility.
Based on: https://github.com/software-mansion/react-native-reanimated/pull/3217
> Support for Jest 28

- docs/docs/fundamentals/installation.md
- docs/versioned_docs/version-2.5.x/fundamentals/installation.md
The `Install` section of the documentation was missing a link to the playground repo and a git clone command.
The link and command were added to the current documentation as well as version `2.5.x`.
`n/a`
> Added missing link and command in reanimated documentation

- .github/workflows/ios-build.yml
Depends on https://github.com/software-mansion/react-native-reanimated/pull/3256.
This pr simply caches hermes build, reducing build time on CI.
> Add hermes cache on CI on ios

- ios/REANodesManager.mm
Hiya :wave:
We stumbled on an issue where an animation was queued on an unmounted component (to fade in), and it would often either a) not fade in at all, or b) fade in after a second or two.
This only occurred on iOS (simulator + device), and was introduced in 2.5.0. I narrowed the changeset to this PR: https://github.com/software-mansion/react-native-reanimated/pull/2580
The problem is [this](https://github.com/software-mansion/react-native-reanimated/blob/03bdda7560d3fc89564df1a838fbb42c87026546/ios/REANodesManager.mm#L398) line. If the component is mounted but has a snapshot, it remains in the queue. There's no guarantee of the next time `-maybeFlushUpdateBuffer` will get called - it comes from `-[REAModule uiManagerWillPerformMounting:]`, so another component has to be mounted to …
> Ensure unmounted components are updated correctly after mounting on iOS

- src/reanimated2/Colors.ts
The regular expression used to parse numbers could be abused to cause a denial of service if the color to be parsed is controlled by an attacker.
For information about this vulnerability, see https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS.
Changed the code so the new regex isn't vulnerable, since there's always only one possible path to take given any input.
Here is a proof-of-concept of how I made the existing regular expression cause a 100% CPU usage for several seconds, after being interrupted:
```
Welcome to Node.js v14.19.3.
Type ".help" for more information.
> (new RegExp('^[-+]?\\d*\\.?\\d+$')).test(`${'1'.repeat(1e6)}z`)
^CUncaught Error: Script execution was interrupted by `SIGINT`
at Script.runInThisContext (vm.js:134:12)
at …
```
> Fix ReDoS when parsing colors

- src/reanimated2/frameCallback/FrameCallbackRegistry.ts
- src/reanimated2/frameCallback/FrameCallbackRegistryJS.ts
- src/reanimated2/frameCallback/FrameCallbackRegistryUI.ts
- src/reanimated2/globals.d.ts
- src/reanimated2/hook/useFrameCallback.ts
This is a fix for PR #3372. The `useFrameCallback` hook introduced in that PR was not running on the UI thread, which would make the animations choppy if heavy callculations were running on the JS thread.
The `useFrameCallback` hook runs on the UI thread now. This can easily be confirmed by adding `console.log(_WORKLET)` in one of the example callbacks. While running the callback `true` should be written out to the console.
> Fixed useFrameCallback hook not running on UI thread

- docs/docs/fundamentals/web-support.md
- docs/versioned_docs/version-2.0.x/web-support.md
- docs/versioned_docs/version-2.1.x/web-support.md
- docs/versioned_docs/version-2.2.x/web-support.md
- docs/versioned_docs/version-2.3.x/fundamentals/web-support.md
- docs/versioned_docs/version-2.5.x/fundamentals/web-support.md
`process.env.JEST_WORKER_ID` is used in 2 files (`PlatformChecker` and `useAnimatedStyle`) and if webpack doesn't know about it, it replaces the whole `process.env` (which is not empty).
Added a line about `JEST_WORKER_ID` to docs.
Tested on webpack@4.43.0 (in an Expo project) but should work in webpack@5 too.
> docs: Update webpack config requirements.

- src/reanimated2/layoutReanimation/LayoutAnimationRepository.ts
Prevent the `configs` object from having properties inherited from `Object.prototype`, such as `toString` or `__proto__`. Otherwise, using these properties could potentially have a security impact.
Changed the prototype of the `configs` object so it doesn't inherit from `Object.prototype`, as regular JS objects do by default.
Couldn't find a test case that I could base on to demonstrate how this could present a risk.
An example of the problem caused by using an object inheriting from `Object.prototype` can be demonstrated by the following line (corresponding to the `startAnimationForTag` function):
```js
const style = configs[tag][type](yogaValues);
```
If both `tag` and `type` had the value `constructor`, style would have the result of evaluating …
> fix: use null prototype for LayoutAnimationRepository config

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
- src/reanimated2/NativeMethods.ts
Resolves #3188. See https://github.com/software-mansion/react-native-reanimated/issues/3188#issuecomment-1196795764 for details.
- Return array of NaNs instead of zero-length array when Android view is not found in `measure`
- Add console.warn with user-friendly message when `measure` returns NaNs
Copy `App.tsx` and `components/Ripple.tsx` from https://snack.expo.dev/@boxedition/ripple-measure-random-values
> Add warning when measuring flattened view on Android

- Common/cpp/Fabric/FabricUtils.cpp
- Common/cpp/Fabric/ReanimatedUIManagerBinding.cpp
- Common/cpp/headers/Fabric/FabricUtils.h
This PR updates c++ types to use `ShadowNode` namespace.
This change is required to compile Reanimated with RN v70.
`SharedShadowNode` -> `ShadowNode::Shared`
`SharedShadowNodeSharedList` -> `ShadowNode::SharedListOfShared`
> fix: use ShadowNode types from namespace

- RNReanimated.podspec
As a version of folly can change between versions of React-native we need to remove an explicit version of `folly_version` from our libraries to let RN infer the correct version.
Change based on https://github.com/th3rdwave/react-native-safe-area-context/commit/eb111ff4eebc8d06ca01e7d12d9661147d03da20
Removed explicit folly version from RNReanimated.podspec
Build FabricExample/
> fix: remove explicit folly version

- src/reanimated2/frameCallback/FrameCallbackRegistryJS.ts
- src/reanimated2/frameCallback/FrameCallbackRegistryUI.ts
This PR removes import cycles on `runOnUI` in `FrameCallbackRegistryJS.ts` and `FrameCallbackRegistryUI.ts`.
The solution is to import `runOnUI` directly from `core.ts` instead of from `index.ts` which imports it.
- Removed import cycles in `FrameCallbackRegistryJS.ts` and `FrameCallbackRegistryUI.ts`
1. Change `inlineRequires: true` to `inlineRequires: false` in `Example/metro.config.js`
2. Launch the Example app
> Remove import cycles in FrameCallbackRegistries

- src/reanimated2/Colors.ts
PR based on issue requested in comment: https://github.com/software-mansion/react-native-reanimated/pull/3382#issuecomment-1195439278
I updated the regex to prevent empty string matches. 
The new regex `[-+]?(?:\d+(?:\.\d*)?|\.\d+)` - https://regex101.com/r/aHhlXG/1 is equivalent with the old version `[-+]?\d*\.?\d+` - https://regex101.com/r/Z0xMqR/1
I also tested ReDoS, and the new regex is safe.
```
(new RegExp('^[-+]?(?:\d+(?:\.\d*)?|\.\d+)$')).test(`${'1'.repeat(1e6)}z`)
```
> Prevent empty string match in color regex

- RNReanimated.podspec
- android/build.gradle
- docs/docs/fundamentals/troubleshooting.md
When a project exists with more than one instance of Reanimated, two versions of Reanimated JS module try to use the same Native Module. It can occur when some of your dependency has installed Reanimated inside their own `node_modules` instead of using it as a peer dependency. The problem is, for example, when the old version of JS tries to call a removed function in a newer version of the native module or can call twice initialization of the native module and override existing data. The solution to this issue is to modify the `package.json` file, requiring only one reanimated version. [Details in the documentation.](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/troubleshooting#multiple-versions-of-reanimated-were-detected)
Fixes …
> Detect two versions of Reanimated

- src/index.ts
- src/reanimated2/js-reanimated/global.ts
The PR with tree shaking moved global objects initialization for web to another file and then imported it into the `index` file (`import './reanimated2/js-reanimated/global';`). However, the Webpack can lazy import modules, but we don't have any call to this module, so global objects were never initialized.
Fixes #3355
> Ensure global objects initialization for web

- RNReanimated.podspec
Fixes a minor typo in the podspec file
RNReanimated.podspec/line 41
Before:
```
puts "[RNReanimated] Unable to recognized your `react-native` version! Default `react-native` version: " + reactVersion
```
After:
```
puts "[RNReanimated] Unable to recognize your `react-native` version! Default `react-native` version: " + reactVersion
```
> Fixed typo in RNReanimated.podspec

- RNReanimated.podspec
- android/build.gradle
The old version didn't work when someone installed reanimated from Github due to yarn/npm breaking symlinks. Package manager changes symlinks `DirName -> ../../DirName` to `DirName -> DirName`. The previous implementation throws exceptions, but the new one can ignore broken symlinks.
> Fix symlinks

- android/build.gradle
- android/src/main/java/com/swmansion/reanimated/keyboardObserver/ReanimatedKeyboardEventListener.java
- docs/docs/api/hooks/useAnimatedKeyboard.md
On Paper architecture, we need to manually set the bottom inset to prevent cropping application content by the navigation bottom bar, but this is no longer required on Fabric.
Since rn70 Paper also doesn't need an additional bottom inset.
> Fix useAnimatedKeyboard inset

- createNPMPackage.sh
This PR removes a warning when running script `createNPMPackage.sh` without nightly mode:
```
./createNPMPackage.sh: line 4: [: =: unary operator expected
```
> Fix "unary operator expected" warning in `createNPMPackage.sh`

- package.json
This PR removes `start` script from top-level `package.json`.
You never want to run `yarn start` here.
Run `cd Example` or `cd FabricExample` and then run `yarn start`.
- Removed `start` script from top-level `package.json`
> Remove start script in root directory

- docs/docs/community.md
- docs/src/css/custom.css
- docs/versioned_docs/version-2.3.x/community.md
- docs/versioned_docs/version-2.5.x/community.md
At the moment the images in the community page in the docs are a bit large. For some reason (I haven't investigated) the class applied to the `img` tag gets overwritten, so I added a `div` wrapping the images and applied the class to that element. Also updated the current team and hidden the arrow next to the GitHub logo in the navbar.
Wrapped the images with a div with the correct class applied.
Updated the current team.
Hidden the arrow next to the GitHub logo in the navbar.
Visit https://docs.swmansion.com/react-native-reanimated/docs/next/community/ and change version
> Update community page in the documentation

- android/src/main/cpp/NativeProxy.cpp
> Fix Android crash when reloading JSC runtime

- Common/cpp/Fabric/ShadowTreeCloner.cpp
- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/headers/Fabric/ShadowTreeCloner.h
- android/CMakeLists.txt
This PR improves the implementation of ShadowTree cloning algorithm in `NativeReanimatedModule::performOperations`.
Previously, `ShadowNode::cloneTree` was called for each update, so effectively the root node was cloned $n$ times.
In this PR I've proposed an algorithm for solving this task more optimally. The main idea is that unsealed ShadowNodes can be still updated. In particular, their children can be replaced using `ShadowNode::replaceChild`. Also, freshly cloned ShadowNodes are unsealed, so each ShadowNode can be cloned only once and then updated.
One important thing to mention is that `replaceChild` does not update `yogaChild_` field in ShadowNode, so we need to invoke `ShadowNode::updateYogaChildren` manually. This function has $O(n)$ time complexity where $n$ denotes the number …
> [Fabric] Optimize cloning ShadowTree when animating layout props

- Common/cpp/Fabric/ShadowTreeCloner.cpp
This PR fixes the following compile error:
> Replace `SharedShadowNodeList` with `ShadowNode::ListOfShared`

- package.json
The PR [#3365](https://github.com/software-mansion/react-native-reanimated/pull/3365) was partially reverted. We use Bob to generate JS for the web, but we need to have the old d.ts file because of some TypeScript types problems in the d.ts file generated by Bob. Unfortunately, we forgot about restoring the old `react-native-reanimated.d.ts` to the package.
Fixes #3487
> Restore d.ts file to npm package

- src/reanimated2/animation/delay.ts
- src/reanimated2/animation/repeat.ts
- src/reanimated2/animation/sequence.ts
This PR removes the following functions which were deprecated in 2.x:
* `delay` &rarr; use [`withDelay`](https://docs.swmansion.com/react-native-reanimated/docs/api/animations/withDelay/) instead
* `repeat` &rarr; use [`withRepeat`](https://docs.swmansion.com/react-native-reanimated/docs/api/animations/withRepeat/) instead
* `loop` &rarr; use [`withRepeat`](https://docs.swmansion.com/react-native-reanimated/docs/api/animations/withRepeat/) instead
* `sequence` &rarr; use [`withSequence`](https://docs.swmansion.com/react-native-reanimated/docs/api/animations/withSequence/) instead
- Removed deprecated functions `delay`, `repeat`, `loop`, `sequence`
> Remove deprecated functions `delay`, `repeat`, `loop`, `sequence`

- Common/cpp/headers/Fabric/ShadowTreeCloner.h
This PR fixes `warning: field 'newestShadowNodesRegistry_' will be initialized after field 'propsParserContext_' [-Wreorder]` when compiling Reanimated sources for Android with Fabric enabled.
> Reorder fields in `ShadowTreeCloner`

- android/build.gradle
The previous implementation was broken and always detected the release as `debug`. The new implementation correctly recognizes build variants.
> Fix incorrect build type resolution on Android

- .github/workflows/android-build.yml
- .github/workflows/ios-build.yml
- .github/workflows/static-example-apps-checks.yml
This PR should hopefully fix CI jobs for Example and FabricExample apps being cancelled by using `matrix.working_directory` variable in `concurrency.group` identifier.
> Fix CI concurrency

- .github/workflows/validate-java.yml
This PR removes duplicate `concurrency.group` key by renaming one key to `validate-java-...`.
> Fix CI concurrency again

- android/CMakeLists.txt
This PR removes `FABRIC_UTILS_CPP` and `REANIMATED_UI_MANAGER_BINDING_CPP` variables in CMakeLists.txt which are not necessary since the files are already included in `SOURCES_COMMON`. Also, the contents of these files is wrapped inside `#ifdef RCT_NEW_ARCH_ENABLED` so they are effectively empty when compiling for Paper.
> Remove unnecessary variables from CMakeLists.txt

- Example/ios/Podfile.lock
- Example/ios/ReanimatedExample.xcodeproj/project.pbxproj
- Example/package.json
- Example/yarn.lock
- FabricExample/ios/FabricExample.xcodeproj/project.pbxproj
- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/yarn.lock
- package.json
- yarn.lock
This PR upgrades `react-native` from 0.70.0-rc.4 to 0.70.0 (stable) in project root as well as Example and FabricExample apps. I've also decided to commit `project.pbxproj` since the whole Reanimated team uses M1-based Macs.
> Bump to React Native 0.70.0

- plugin.js
Currently when adding the plugin to `babel.config.js` without passing any options to it, `state.opts` will be undefined causing the webpack build to fail because it can't read relativeSourceLocation of undefined.-->
- Added check wheter plugin options are being passed before accesing them
> Fix plugin crashes when no options are being passed to it

- android/build.gradle
it's not ideal to download 3rd party libraries multiple times, so i'm proposing to add `REACT_NATIVE_DOWNLOADS_DIR` as react-native to specify a custom download locations. also having a pr for expo: https://github.com/expo/expo/pull/19015
add `REACT_NATIVE_DOWNLOADS_DIR` environment variable to specify custom download location 
execute `REACT_NATIVE_DOWNLOADS_DIR=$HOME/foo ./gradlew :app:assembleDebug` in Example app and verify whether $HOME/foo contains the download files after builds
> Add `REACT_NATIVE_DOWNLOADS_DIR` to specify custom download location

- FabricExample/App.tsx
- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/src/SvgExample.tsx
- FabricExample/yarn.lock
This PR adds `react-native-svg@13.1.0` as a dependency in FabricExample app as well as Animated SVG circle example.
> Add react-native-svg example in FabricExample

- RNReanimated.podspec
- android/build.gradle
> Raise error when using Reanimated 2.x with Fabric enabled

- .github/PULL_REQUEST_TEMPLATE.md
Noticed a typo.
Just corrected it in GH editor.
N/A
> chore: fix typo in PR template

- docs/docusaurus.config.js
The current convention for making a new version in docs is to make a new one when there have been API changes. This is a good solution as it doesn't result in redundant versions of docs that are exactly the same but has one major flaw: it's not obvious what it means. This PR updates the labels to reflect that they cover more than one version of Reanimated.
- Added custom labels for docs versions covering more than one minor version
> Add ranges in version labels in docs

- android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/cpp/NativeProxy.cpp
- android/src/paper/java/com/swmansion/reanimated/NativeProxy.java
This PR changes the signature and implementation of Android method used for getting current time from `private String getUptime()` to `private long getCurrentTime()`.
The motivation behind this PR is to eliminate redundant conversions, in particular parsing number from a string:
* Before: `long` &rarr; (`Long.toString`) `String` &rarr; `local_ref<JString>` &rarr; `std::string` &rarr; (`std::strtoll`) &rarr; `double`
* After: `long` &rarr; `jlong` &rarr; `double`
I've also decided to rename method `getUptime` to `getCurrentTime` in order to match the name of lambda in C++ as well as to obtain more informative error message in case of Java/C++ code mismatch (e.g. missing method `getUptime`).
Finally, I've added `static` keyword to FBJNI reference to `getCurrentTime` method for the purpose …
> Get current time as `long` on Android

- FabricExample/android/gradle.properties
- android/build.gradle
Fixes #3523 on v3
Fix for v2 comes with https://github.com/software-mansion/react-native-reanimated/pull/3602
Added `resolve<lib>` tasks. Each of them check whether `<lib>` is already downloaded by `:ReactAndroid` project - if so - they copy archive files to `reanimated` downloads directory -> this causes `download<lib>` tasks to not run, as they're up to date.
To achieve this, setting dependency between `resolve<lib>` & `:ReactAndroid:download<lib>` was required.
I checked it on Reanimated v3:
> fix: dependency downloads on v3

- docs/docs/api/nativeMethods/measure.md
- src/reanimated2/NativeMethods.ts
When `measure()` was called inside `useAnimatedStyle()` a warning would appear with the message:
`[Reanimated] measure() cannot be used for web or Chrome Debugger`.
This message isn't very helpful, since we aren't running Chrome Debugger and aren't on web. This was previously shown because `useAnimatedStyle()` runs an initial update on the JS thread.
When measure is called from the JS thread, but on native platforms, then show a message that explains why this could be happening.
> Show more useful message when using `measure()` in `useAnimatedStyle()`

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- FabricExample/src/ArticleProgressExample.tsx
- src/reanimated2/NativeMethods.ts
- src/reanimated2/globals.d.ts
This PR removes error `Cannot read property 'x' of undefined` when using `measure` function. For details, see changes.
Follow-up of #3598 and #3453.
References:
* https://github.com/facebook/react-native/blob/278dad6438eac8358a6caaf9dc3b192c0b6137e2/ReactCommon/react/renderer/uimanager/UIManagerBinding.cpp#L557-L560 – `measure`
* https://github.com/facebook/react-native/blob/8bd3edec88148d0ab1f225d2119435681fbbba33/ReactCommon/react/renderer/core/LayoutMetrics.h#L63-L69 – `EmptyLayoutMetrics`
* Changed the return value of native measure function from `undefined` to `null` in case of empty layout metrics
* Fixed type of `_measure` function in `globals.d.ts`
* Added appropriate variant of warning message in case of empty layout metrics
* Added missing spaces in other warning message in …
> Return `null` instead of `undefined` from `measure` on Fabric

- android/build.gradle
When trying to compile Detox and Reanimated from source there is an intermediate dependency conflict stemming from the META-INF folder. To resolve, excluded META-INF from Gradle packagingOptions. 
Please cherrypick onto v2
- Exclude meta-inf from gradle to prevent intermediate compile conflicts with Detox
- [] Included code example that can be used to test this change
- [] Updated TS types
- [] Added TS types tests
- [] Added unit / integration tests
- [] Updated documentation
> Exclude meta-inf from gradle to prevent intermediate compile conflicts

- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/yarn.lock
This PR bumps `react-native-safe-area-context` from 4.3.3 to 4.4.0 both in Example and FabricExample apps.
> Bump react-native-safe-area-context to 4.4.0

- Example/android/app/build.gradle
- Example/android/build.gradle
- android/build.gradle
The Example app crashes on Android if compiled with JSC instead of Hermes. Error message:
```
2022-09-15 12:34:45.701 15509-15509/com.swmansion.reanimated.example W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found: needed by /data/app/~~YZvjm8gAMg_2TYxNnYOCDA==/com.swmansion.reanimated.example--9SU_U_zrfiGBnf1eSq-kA==/lib/arm64/libjscexecutor.so in namespace classloader-namespace
```
The `build.gradle` files in the Example app were outdated, which caused multiple issues. Some of the changes are:
- Added missing 64-bit architectures in some places
- Fixed enabled build abi resolution
- Fixed incorrect maven repositories definition in top-level `build.gradle`
> Fix Example app with JSC on Android

- scripts/reanimated_utils.rb
I disabled the second multiple instance assertion if React Native and Reanimated are in the same node modules location.
> Disable check for the same path

- src/reanimated2/globals.d.ts
This PR eliminates differences between two sections in `globals.d.ts`. Also, two types needed to be fixed.
> Improve globals.d.ts

- android/build.gradle
Fix for the building issue:
```
../../../../src/main/cpp/AndroidScheduler.h:3:10: fatal error: 'fbjni/fbjni.h' file not found
#include <fbjni/fbjni.h>
```
CI fail: https://github.com/piaskowyk/reanimated-rn-version-tester/actions/runs/3250602268/jobs/5334494271
Solution:
We need to execute our tasks before `generateJsonModel` because in this step FBJNI's headers should be unpacked in the proper location. Same as here: https://github.com/software-mansion/react-native-reanimated/blob/376730edb6dc2b610553a0ce87ba7040031e422b/android/build.gradle#L995-L997
> Fix gradle task order

- plugin.js
BABEL_ENV should consider using production
> fix: BABEL_ENV should consider using production

- android/build.gradle
- src/reanimated2/frameCallback/FrameCallbackRegistryUI.ts
- src/reanimated2/globals.d.ts
I added the missing `_frameCallbackRegistry` property to the globals variables declaration. And I used recommended syntax with `import type` - https://stackoverflow.com/questions/61412000/do-i-need-to-use-the-import-type-feature-of-typescript-3-8-if-all-of-my-import
> [Reanimated2] Added missing FrameCallback type in globals

- Example/index-template.js
- Example/index.js
- ios/REAModule.mm
Fixes #3678. Reverts part of #3555 for Paper.
On Paper, the warning "RCTBridge required dispatch_sync to load REAModule" was gone when I removed `requiresMainQueueSetup` method introduced in #3678. However, the PR description explicitly states that this method was added in order to eliminate the following warning:
> This is because the `init` method was not present before and after adding it, it caused this warning:
> 
> `Module RCTImagePickerManager requires main queue setup since it overrides init but doesn't implement 'requiresMainQueueSetup'. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.`
However, after the removal of `requiresMainQueueSetup` no warning appears, so I assume that it is in fact not …
> Fix iOS Warning: RCTBridge required dispatch_sync to load REAModule

- RNReanimated.podspec
When there are frameworks used and Hermes enabled in the Podfile of your project, RN falls back to JSC in debug mode and crashes in production mode.
This PR makes it possible to use Hermes when there is `use_frameworks!` enabled in the Podfile.
Thanks @Kudo who originally fixed this issue in ReactNative repository: https://github.com/facebook/react-native/pull/34222
Added path to `Framework Search Paths` in Podspec of react-native-reanimated.
1. Create empty ReactNative project
2. Add react-native-reanimated dependency.
3. For ReactNative 0.69.3 apply patch from: https://github.com/facebook/react-native/pull/34222/files
4. Enable frameworks in Podfile: `use_frameworks! :linkage => :static`
5. Build project in debug mode -> you will not see `engine: hermes` in top right corner.
6. Build …
> Fix Hermes not available on iOS when use_frameworks enabled

- ios/REAModule.mm
Fixes #3716
Check if listers have been set up, and only if so send events. 
See reproduction in #3716.
Then add the changes I added, and the warnings will disappear.
> fix: fix #3716 warning

- src/reanimated2/jestUtils.ts
Reanimated is not fully compatible with Jest 28+ even after the PR https://github.com/software-mansion/react-native-reanimated/pull/3347. Using it with Jest 28+ leads to this error:
The reason is, the "expect" module's export approach has changed starting from Jest 28. It used to export the `expect` function directly, as can be seen [here](https://github.com/facebook/jest/blob/v27.5.1/packages/expect/src/index.ts#L441). 
This means, requiring the "expect" module like this
```ts
const expect = require('expect')
```
was providing direct access to the `expect` function alongside with its attached methods, like `extend`.
This has [changed with Jest 28](https://github.com/facebook/jest/blob/v28.0.0/packages/expect/src/index.ts#L449). `export default expect` is the new export statement, which …
> Fix Jest 28+ `expect.extend is not a function` error

- .github/workflows/main.yml
This PR disables publishing GitHub Pages from Reanimated2 branch because it overwrites the docs from main branch.
> Don't publish GitHub Pages from Reanimated2 branch

- docs/src/css/custom.css
- docs/src/pages/index.js
Search modal has too big margin. It is due to the fact that html element `section` was styled in `custom.css` file that should style only the landing page, therefore serach modal was styled by mistake.
before:
after:
> Fix search modal styling

- .github/workflows/build-v8.yml
- .github/workflows/helper/configureV8.js
- Common/cpp/ReanimatedRuntime/ReanimatedRuntime.cpp
- Common/cpp/ReanimatedRuntime/ReanimatedRuntime.h
- android/src/main/cpp/NativeProxy.cpp
- ios/native/NativeProxy.mm
This PR is an attempt to fix V8 integration with Reanimated V3. Current issue:
```
react-native/node_modules/react-native-reanimated/Common/cpp/ReanimatedRuntime/ReanimatedRuntime.cpp:40:38: error: use of undeclared identifier 'runtime_'
```
Updated `ReanimatedRuntime::make` to accept a new parameter `jsi::Runtime *runtime`, which is necessary to initialize V8
- Create a new RN app
- Setup the app to have V8 as engine
- Enable the new architecture (might not be necessary)
- Build the Android app
- Confirm the app builds and runs fine with this change
> Fix V8 integration for Reanimated V3

- .github/workflows/build-v8.yml
- .github/workflows/helper/configureV8.js
This PR fixes the Android V8 CI that wasn't running because `env` is not available in `concurrency.group` context:
Instead, we should use `${{ github.ref }}` to differentiate jobs for different branches/PRs.
> Fix V8 on Android CI build

- android/build.gradle
I get cmake error (`Invalid character escape '\K'.`) when using latest Reanimated on RN version 0.64.3, this will fix Android build on windows because latest version of reanimated doesn't provide prebuilt AAR for older version, so it will attempt to rebuild from source
- added method `toPlatformFileString(File path)` to android/build.gradle to replace windows file separator character with '/'
- call `toPlatformFileString` on cmake arguments REACT_NATIVE_DIR
- fix sources taken from [this PR](https://github.com/Kudo/react-native-v8/pull/132)
- create new project with RN v0.64.3
- install latest version of react-native-reanimated
- try to build apk for Android `./gradlew clean installDebug`
> Fix cmake error on windows

- .github/workflows/build-monorepo-action.yml
- .github/workflows/build-monorepo.yml
This PR fixes the following error which occurs on iOS monorepo CI during `npx react-native init` phase:
```
✖ Installing Bundler
error Your Ruby version is 3.0.4, but your Gemfile specified 2.7.5
```
SInce we already run `pod install` once the project setup is complete, the solution is to add `--skip-install` flag which prevents installing dependencies during init.
> Fix monorepo CI

- package.json
This PR moves @types/invariant to devDependecies as suggested by @hendryems in #3770.
Since there is only one occurrence of `invariant` in our codebase, first I thought we can replace this check with some simple JS code (if + throw new Error). However, invariant is also a dependency of react-native, so it makes no difference in terms of number of dependencies if we also rely on it.
- Move @types/invariant to devDependencies
Just see if everything works before release.
> Move @types/invariant to devDependencies

- .github/workflows/build-monorepo.yml
- .github/workflows/ios-build.yml
- scripts/reanimated_utils.rb
Fixes #3771 as suggested by @ahayllas.
- Added missing double quotes around project path
- Added reanimated_utils.rb to paths in CI workflows
> Fix pod install error when project path contains space

- scripts/reanimated_utils.rb
This PR addresses the issue #3754
Invalid RNReanimated.podspec file: no implicit conversion of nil into Array. IOS when updating from reanimated 2.8.0 to 2.12.0 caused by  (https://github.com/software-mansion/react-native-reanimated/blob/05c93b02ede93950904812239fbe95366e372ab6/scripts/reanimated_utils.rb#L63) as its possible that we can have multiple instances of react-native-reanimated in the same node_modules directory (i.e. we require `react-native-reanimated` and one of our dependencies also requires it). If this happens to be the case, the condition that there are multiple react native reanimated instances is evaluated as `true`. As we attempt to evaluate the `parsed_location` its possible that `lib_instances_in_reanimated_node_modules_array` may be null if `react_native` and the …
> Fix null array reference in utilities

- ios/REAModule.mm
This PR fixes iOS crash on reload of FabricExample app. Most likely the regression was caused by #3332.
First, I observed that the crash was gone after I commented out the following line:
https://github.com/software-mansion/react-native-reanimated/blob/1bec9a069371bc27a3319d8c0a7aa31b77a98de7/ios/REAModule.mm#L159
Next, I confirmed that `removeEventListener` was indeed called in `invalidate` here:
https://github.com/software-mansion/react-native-reanimated/blob/1bec9a069371bc27a3319d8c0a7aa31b77a98de7/ios/REAModule.mm#L70
However, this method was called on the ShadowQueue thread while `addEventListener` was called on the JS thread. As this may potentially cause a race condition when accessing internal `std::vector` of EventListeners, I decided to wrap the call with `runtimeExecutor` in …
> Fix Fabric crash on reload on iOS

- src/reanimated2/hook/useAnimatedRef.ts
This PR fixes crash on Fabric when using synchronous measure/scrollTo etc – this error was a regression introduced in #3722.
The issue was that did not transform shadow node wrapper ref into shareable ref. Shareable ref was necessary for the UI side to recognize and extract the shadow node wrapper that was needed for the sync calls to execute.
Run FabricExample, use "Measure on UI" on the "Measure Example" screen and "ScrollTo on UI" button on the "ScrollTo Example" screen.
> Fix animated refs on Fabric

- Common/cpp/SharedItems/Shareables.h
- src/reanimated2/commonTypes.ts
- src/reanimated2/core.ts
- src/reanimated2/threads.ts
After #3722 the error message presented after attempting to synchronously call React runtime function from the UI runtime has changed and became less descriptive than before. This PR adds a way for us to throw a more descriptive error in such scenario.
Use the following code:
```
function rnMethod() {
console.log('from RN');
}
function uiMethod() {
'worklet';
rnMethod(); // this should throw
}
runOnUI(uiMethod)();
```
Before this change you'd get a generic "Object is not a function" thrown at the line where we call `rnMethod`, now the error message says "Tried to synchronously call a non-worklet function" and presents possible solution (see the diff for the whole error message)
> Better error message when trying to call non-worklet from UI thread

- Common/cpp/Tools/RuntimeDecorator.cpp
JSI's `asBool` was only added in RN 69. This PR changes `asBool` to `getBool` calls in order to support older RN versions.
Check if things build on RN 67 and on RN 70
> Use getBool instead of asBool to make it work with RN pre 69

- Common/cpp/Tools/RuntimeDecorator.cpp
This PR removes a piece of code in `RuntimeDecorator` that used to overwrite `global` property of the global JS object with a dummy JS object which was a regular JS object filled only with Reanimated-specific values.
I tried to confirm that Hermes was indeed enabled on the UI context with the following snippet:
```ts
'worklet';
console.log('HermesInternal' in global); // should return true
})();
```
However, it returned `false`, despite the fact that a breakpoint on `facebook::hermes::makeHermesRuntime` was hit.
Then I noticed that we call `RuntimeDecorator::decorateRuntime(rt, "UI");` which overwrites `global` property in the UI context with a "dummy global", effectively causing `global.HermesInternal` to be `undefined`. 
The concept of dummy global was introduced in the …
> Remove `dummyGlobal`

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
This PR fixes an iOS crash with Hermes on app reload that occurs only if some animation is still running:
1. Build and launch Example app on iOS simulator
2. Open Animated Style Update Example
3. Increase duration to 5000 ms
4. Click "Toggle" button
5. Press <kbd>r</kbd> in simulator
6. Make sure the app reloads correctly
> Fix new implementation iOS crash on reload while animation is running

- Common/cpp/SharedItems/Shareables.h
This PR enables weak object implementation for shareables when using V8 runtime.
As @Kudo mentioned in https://github.com/software-mansion/react-native-reanimated/pull/3722#discussion_r1040966675, react-native-v8 exposes weak objects API via JSI (see [here](https://github.com/Kudo/react-native-v8/blob/96a1a2c8a35349967a3ad7219106a3475b85433a/src/v8runtime/V8Runtime.cpp#L982-L997)).
Run Example app with react-native-v8 and check if everything works.
> Use weak object for shareables on V8

- ios/LayoutReanimation/REAAnimationsManager.h
- ios/LayoutReanimation/REAAnimationsManager.m
- ios/LayoutReanimation/REAUIManager.mm
- src/reanimated2/layoutReanimation/animationsManager.ts
Currently, when views with an `exiting` animation are unmounted, any deleted in that transaction aren't removed from the UIManager's view registry (the mapping of react tags to native views).
This can cause memory leaks of removed views.
This PR restores the original behaviour of UIManager when removing views, allowing it to clean them up properly, and reattaches the views with `exiting` animations after the transaction removing the views has completed.
- In example app, go to "Entering and Exiting with Layout"
- Set a breakpoint somewhere in `RCTUIManager`, for example `_manageChildren`.
- Press "Toggle" to create the animated views, and note the number of entries in `_viewRegistry`.
- Disable the breakpoint, resume the app and start spamming the toggle button.
- Enable the breakpoint …
> [iOS][Layout Animations] Remove `exiting` views from UIManager's view registry

- Common/cpp/Tools/RuntimeDecorator.cpp
- plugin.js
- src/reanimated2/__mocks__/NativeReanimated.ts
- src/reanimated2/core.ts
- src/reanimated2/globals.d.ts
- src/reanimated2/js-reanimated/global.ts
After #3838 we can now access the main global object via `global` variable. This eliminates a need for _setGlobalConsole JSI method that we'd install in the UI runtime only so that we can set the console object as global on the UI runtime. In this PR we change the call to _setGlobalConsole with just reassigning global.console.
Add some logs in worklets, run the app, see the logs appear on the output, also that console.warn displays in the log box.
> Remove _setGloalConsole JSI method

- Example/src/App.tsx
- Example/src/LayoutReanimation/DeleteAncestorOfExiting.tsx
- Example/src/LayoutReanimation/index.ts
- ios/LayoutReanimation/REAAnimationsManager.m
#3824 introduces a bug with how we register ancestors of views with `exiting` animations.
When a tree with `exiting` views is reattached to the native view hierarchy, we don't register the ancestors of that tree as ancestors of exiting subviews. This may cause issues with deleting these views early, while there're still `exiting` animations running inside them.
> [Layout Animations][iOS] Fix registering exiting view ancestors

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
This PR fixes crashes related to concurrent writes to a non-thread-safe frameCallbacks vector. The primary role of frameCallbacks vector was to facilitate requestAnimationFrame calls and hence it has not been designed to allow for other than the main thread to append their callbacks. However, after recent rewrite #3722 we introduced a new methods "scheduleOnUI" that was originally meant to interface with a thread-safe scheduler API but was later updated (see c8a77da44a6cf53f14f224f6f15527a26c770f09) to use frameCallbacks in order for errors to be handled using the same code-path the rAF uses. That change introduces a bug in which we'd access and modify that vector from different threads which is undesirable. This PR reverts that change and since #3846 provides a better way of handling …
> Fix crash due to concurrent writes to frameCallbacks vector

- FabricExample/src/WorkletExample.tsx
- FabricExample/yarn.lock
This PR adds `<GestureHandlerRootView>` in `WorkletExample` that are not necessary unless you paste the demo directly to `App.tsx` and lose 30 minutes of your life trying to figure out what's wrong.
1. Launch FabricExample
2. Check if WorkletExample works
> Add GestureHandlerRootView in WorkletExample

- src/reanimated2/globals.d.ts
- src/reanimated2/initializers.ts
This PR overrides requestAnimationFrame on the UI runtime such that it keeps a list of callbacks for a given frame locally and only calls into the native requestAnimationFrame once in every frame where the method gets triggered.
This results in a greatly reduced number of calls that need to happen over JSI in case where there are multiple components/values being animated at the same time. This also, apparently, fixes a crash in BokehExample on android that was due to some race condition issues in the naitve requestAnimationFrame implementation. Calling it only once in a given frame resolves that issue.
Run BokehExample on Android with the number of circles bumped up to 300. The app should not crash and perform well on an emulator (note that 300 will be too high for low-end devices but …
> Avoid multiple rAF calls over JSI when called on the same frame

- src/reanimated2/hook/useAnimatedStyle.ts
This PR removes a chunk of code that was supposed to be executed only if a worklet has some optimization applied in Babel plugin but since #3722 completely removes these optimizations, this chunk of code is no longer necessary.
Co-authored-by: @kmagiera @piaskowyk 
Check if BokehExample works correctly.
> Remove redundant call to `parseColors`

- src/reanimated2/mock.ts
This Pr adds missing mocks for default layout animations.
- Adds missing reanimated2 default layout animations mocks
```javascript
// Component.tsx
export const AnimatedComponent =
Animated.createAnimatedComponent(ComponentToAnimate);
const Component = () => (
<View>
<AnimatedComponent entering={FadeIn} />
</View>
)
// Component.test.tsx
describe(Component, () => {
it('should render', () => {
render(<Component/>); // Before these mocks were added this would fail (Cannot call `.delay()` or `.duration()` of undefined )
});
});
```
> Adds mocks for default layout animations

- Example/src/App.tsx
- Example/src/InvertedFlatListExample.tsx
- src/reanimated2/component/FlatList.tsx
`Animated.FlatList` currently presents each item flipped when using the `inverted` prop, this due to how the `inverted` props works internally (it literally flips the ScrollView). [In the React  Native codebase](https://github.com/facebook/react-native/blob/29caed22cc1c9a426e524e498cf44cf18df0577e/Libraries/Lists/VirtualizedList.js#L1845-L1850) they then apply a style to each cell item to flip it back to the correct orientation. However this fix isn't applied to Reanimated's `FlatList` implementation because it overrides the `CellRendererComponent` prop.
Fixes #2769
I've used the same fix from React Native to correct the implementation in Reanimated and included an example in the Example app so it's easy to verify if this gets regressed in the future.
Before | After
---|---
Check the …
> Fix inverted cell style for inverted Animated.FlatList

- FabricExample/src/ScrollToExample.tsx
This PR fixes the import of `runOnUI` in ScrollToExample.tsx
Launch FabricExample, open ScrollToExample and check if it works.
> Fix `runOnUI` import in ScrollToExample

- FabricExample/src/MeasureExample.tsx
This PR fixes the import of `runOnUI` in MeasureExample.tsx
Launch FabricExample, open MeasureExample and check if it works.
> Fix `runOnUI` import in MeasureExample

- Common/cpp/ReanimatedRuntime/ReanimatedHermesRuntime.h
This PR fixes a warning that `debugToken_` field is unused in release mode after #3745  which gets escalated to a compile error thanks to `-Werror`.
Check if Example app compiles in release mode.
> Fix unused `debugToken_` in release mode

- android/src/reactNativeVersionPatch/nativeHierarchyManager/latest/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
Fixes #2906 #3368 #3813
Previously, when layout animations were enabled, when updating layout for `react-native-screens`' `Screen`, we set it's dimensions to the dimensions of the component containing that screen.
On the JS side, header’s height is set to 0 due to it being a wrapper for the native Android/iOS header component, but on the native side, its height is calculated by the system and the information about the new Screen’s height (which is effectively smaller due to that header) is passed to UIManager here: [https://github.com/software-mansion/react-native-screens/blob/100ed4f9ffd5f27ace4d[…]7a00c64/android/src/main/java/com/swmansion/rnscreens/Screen.kt](https://github.com/software-mansion/react-native-screens/blob/100ed4f9ffd5f27ace4ddbb5c5ffbb80e7a00c64/android/src/main/java/com …
> [Android] fix components being placed under the screen header

- src/reanimated2/threads.ts
This PR adds an user-friendly error message when worklet cannot be created due to missing Reanimated Babel plugin.
Before:
After:
Check on a fresh RN app without editing `babel.config.js`.
> Add user-friendly error message when worklet cannot be created due to missing Babel plugin

- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensorContainer.java
Fixes https://github.com/software-mansion/react-native-reanimated/issues/3896
In the scenario presented in the issue every time the component was mounted two `ReanimatedSensor` were created: one was just initialized and the second one added to the hashmap. Then, when unregistering, only the second one was unregistered, the first one was kept registered. After some time the max limit of registered listeners is hit. 
```js
import { Text, View, StyleSheet } from 'react-native';
import Constants from 'expo-constants';
import { useAnimatedSensor, SensorType } from 'react-native-reanimated';
export function BasicLayoutAnimation() {
return (
<Parent />
</View>
);
}
const Parent = () => {
const [state, setState] = React.useState(0); …
```
> Fix sensor listener leak on Android

- src/createAnimatedComponent.tsx
Current `FlashList` implementation wraps ScrollView in `StickyHeaderContainer` (https://github.com/Shopify/flash-list/blob/main/src/FlashList.tsx#L317). As a result `findNodeHandle(this)` in `createAnimatedComponent` returns tag of the view in `StickyHeaderContainer` instead of ScrollView tag. Because of that event listeners aren't registered correctly.
This is an attempt to fix it for the `FlashList` - if the component is a `FlashList` we take the scrollview reference from `recyclerlistview_unsafe` (https://github.com/Shopify/flash-list/blob/218f314e63806b4fe926741ef73f8b9cd6ebc7eb/src/FlashList.tsx#L824) (it's unsafe because it may change in the future but at least it's public).
This is not a foolproof solution - FlashList implementation may change in the future and there may be other …
> Fix useAnimatedScrollHandler when using FlashList

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
- ios/LayoutReanimation/REAAnimationsManager.m
Currently, if a React render happens during an `entering` layout animation and causes the layout of the animated component to change, that component will continue it's animation and remain at the position it finished.
This changes the behaviour of `entering` animations to instead move the component to the correct place after the animation finishes.
This issue (and this change) doesn't affect screens with `layout` layout animations, since these are already combined with `entering`.
> Fix layout after entering animation ends

- scripts/reanimated_utils.rb
Noticed on accident when I upgraded Ruby on accident to 3 - that my `pod install` failed with:
```
[!] Invalid `Podfile` file: 
[!] Invalid `RNReanimated.podspec` file: undefined method `exists?' for File:Class.
>  config = find_config()
```
Theres a good deal of other errors after I fixed this one on other projects, but this looks like a safe change to get ahead of the future Ruby upgrade. Yeah I did downgrade back to 2.7.5.
Resolves the removed method of `File.exists` in Ruby3. The alternative method of `File.exist` is recommended and already exists on 2.5 for no breaking changes.
https://rubyapi.org/2.5/o/file#method-c-exist-3F
A local working `pod install`
> Cocoapods: Fix deprecated/removed File.exists method

- ios/native/NativeProxy.mm
Fixes #3800
The type `REAHasAnimationBlock` is defined as:
```obj-c
typedef BOOL (^REAHasAnimationBlock)(NSNumber *_Nonnull tag, NSString *_Nonnull type);
```
but lambda from code had `bool (^REAHasAnimationBlock)(NSNumber *_Nonnull tag, NSString *_Nonnull type)` type and it was breaking some build configurations.
> Convert c-like `bool` to obj-c-like `BOOL` for `REAHasAnimationBlock`

- src/reanimated2/NativeReanimated/NativeReanimated.ts
- src/reanimated2/platform-specific/checkVersion.ts
- src/reanimated2/platform-specific/checkVersion.web.ts
Fixes issues when bundling web apps using reanimated due to relative path to `package.json` being wrongly resolved in prebuild reanimated modules.
> Fix issues with relative paths when bundling web apps

- src/createAnimatedComponent.tsx
Fixes #3933.
`viewTag` is declared as `const` but for FlashList component we overwrite it afterwards. However, this doesn't trigger an error since there is a `// @ts-ignore` in the previous line.
> Fix TypeError: 'viewTag' is read-only on Animated.createAnimatedComponent(FlashList)

- .github/workflows/build-npm-package-action.yml
This PR removes the following warnings that appear when building package on CI:
Before: https://github.com/software-mansion/react-native-reanimated/actions/runs/3902166126
After: https://github.com/software-mansion/react-native-reanimated/actions/runs/3904875919
Check if package is okay.
> Fix build package CI warnings

- android/build.gradle
Fixes #3952.
1. Build Reanimated 2 package on CI
2. Create a new RN 0.70.6 app with Reanimated
3. Copy BokehExample to App.js
4. Build the app in release mode for Android
5. Check if the runtime error is gone
> Disable `HERMES_ENABLE_DEBUGGER` when building Reanimated 2 AAR package

- src/createAnimatedComponent.tsx
> Fix: 3.0.0-rc.9 , useAnimatedScrollHandler with FlashList not working

- android/CMakeLists.txt
I have a `libglog.so` in my default path so CMAKE takes it instead of provided one.
Build failed then.
Put `libglog.so` in another architecture in your default path and you will see how linker fails.
> Don't look in default path for libs if path is procided

- src/reanimated2/hook/utils.ts
This PR provides a new better implementation of `isAnimated` utility function as the previous version was very poorly written. The old implementation holds a queue of props to be checked and thus needs to allocate and populate a new array on each call, whereas the new implementation uses recursion instead &ndash; however, in most of the real-world cases, it is never called recursively. Since `isAnimated` is used very frequently throughout the codebase, previously it took ~7% of total execution time. After the changes, it dropped down to ~3%.
Co-authored-by: @kmagiera
Just check if BokehExample works.
> Rewrite `isAnimated` function

- src/reanimated2/hook/useAnimatedStyle.ts
This PR contains two little optimizations in `styleUpdater`:
1. Since we never use `oldValues` again (because references the same object as `state.last` does before we overwrite it in the very same line), we can re-use this instance instead of creating a new one.
2. Since we just calculated the difference between the new and old styles, we can overwrite `oldValues` just with `diff` instead of `newValues` because the values that are not present in `diff` are the same in `oldValues` and `newValues`.
Co-authored-by: @kmagiera
Just check if BokehExample works.
> Optimize previous style calculation in `styleUpdater`

- ios/keyboardObserver/REAKeyboardEventObserver.m
Fixes a bug when changing keyboard language on iOS:
Bug:
https://user-images.githubusercontent.com/6280457/212095624-4df7e0b0-d3e6-4bdd-8378-ad8c077e6fb2.mp4
Fixed bug:
https://user-images.githubusercontent.com/6280457/212096575-aa36cb88-fee5-4f4c-bd37-676973834d48.mp4
Fixes https://github.com/software-mansion/react-native-reanimated/issues/3721
`useAnimatedKeyboard` reported invalid keyboard height in that case, because we invalided display link too early, in `stopAnimation` and we reported the height before suggestions bar appeared. In the next frame the suggestion bar appears and we can calculate correct keyboard height.
Run AnimatedKeyboardExample, bring up the keyboard and change keyboard language. The text input should be above the keyboard in correct position.
<details> …
> Fix keyboard height in useAnimatedKeyboard on language change on iOS

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/NativeModules/NativeReanimatedModule.h
- Common/cpp/NativeModules/NativeReanimatedModuleSpec.cpp
- Common/cpp/NativeModules/NativeReanimatedModuleSpec.h
- Common/cpp/Tools/PlatformDepMethodsHolder.h
- android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/NativeProxy.h
- android/src/main/java/com/swmansion/reanimated/keyboardObserver/ReanimatedKeyboardEventListener.java
- android/src/paper/java/com/swmansion/reanimated/NativeProxy.java
- docs/docs/api/hooks/useAnimatedKeyboard.md
- ios/native/NativeProxy.mm
- react-native-reanimated.d.ts
- src/reanimated2/NativeReanimated/NativeReanimated.ts
- src/reanimated2/commonTypes.ts
- src/reanimated2/core.ts
- src/reanimated2/hook/useAnimatedKeyboard.ts
Fixes https://github.com/software-mansion/react-native-reanimated/issues/3631
Fixes the issue with translucent StatusBar on Android by adding the option `isStatusBarTranslucentAndroid` in `useAnimatedKeyboard`. It is the same solution as the one mentioned in the issue: https://github.com/kirillzyusko/react-native-keyboard-controller/commit/2a7c92f7861e38d2a6d437577a6e3a9a7946a191 
There is an excellent example in the issue that reproduces the problem: https://github.com/ChildishForces/reanimated-bug-repro
I tested on real Android device with Android 12 and RN 71.
I think it would be nice to also test on RN < 70 because the bottom padding may behave differently.
> Make  work with transluscent StatusBar on Android

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
JSI's `asBool` was only added in RN 69. This PR changes `asBool` to `getBool` call in order to support older RN versions.
> Use `getBool` instead of `asBool`

- src/reanimated2/mock.ts
We have a typo on `react-native-reanimated/lib/commonjs/reanimated2/mock`, where `FadeInDown` is typed wrong, and mocked as `FadFadeInDown`. This PR fixes it.
I'm mocking Reanimated on jest in this way, on the new version:
```ts
jest.mock('react-native-reanimated', () => {
return {
...jest.requireActual('react-native-reanimated/mock'),
...jest.requireActual(
'react-native-reanimated/lib/commonjs/reanimated2/mock',
),
};
});
```
But, as this typo makes the Reanimated2 mocks not contain the FadeInDown method, Jest throws this error on files that use this Fade.
I'm currently fixing it with patch-package, while that isn't officially merged and released. The issue is still present after updating to 3.0.0-rc.10
> Fix typo on reanimated 2 mock.ts

- ios/native/NativeProxy.mm
Fixes #3965.
```
npx react-native@next init MyApp --version 0.71.0 --skip-install
yarn add react-native-reanimated@2.14.2
cd ios && NO_FLIPPER=1 USE_HERMES=0 RCT_NEW_ARCH_ENABLED=0 pod install
open ios/MyApp.xcworkspace
```
> Fix 'jsi/JSCRuntime.h' file not found in NativeProxy.mm

- Example/ios/Podfile.lock
- Example/package.json
- Example/yarn.lock
- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/patches/react-native-svg+13.7.0.patch
- FabricExample/yarn.lock
This PR updates react-native to 0.71.0 as well as other third-party libraries to the latest versions both in Example and FabricExample apps.
Run Example and FabricExample apps on Android and iOS in debug and release mode.
> Bump react-native to 0.71.0 in Example and FabricExample

- src/reanimated2/mock.ts
This PR extends https://github.com/software-mansion/react-native-reanimated/pull/3801 by introducing layout animation types and modifiers that those animation types require to be fully functional.
Currently, the tests fail with something like:
```
TypeError: Cannot read properties of undefined (reading 'delay')
> 107 |   const transition = CurvedTransition.delay(10).duration(10),
|                                       ^
```
Creating a test (e.g. using React Native Testing Library) of a component containing any of the freshly added layout animation types and / or chained modifiers they support. E.g.:
```tsx
const MyComponent = () => (
<Animated.View layout={CurvedTransition.delay(10).duration(10)} />
)
test('test the test', () => {
const screen = render(<MyComponent />)
})
```
The above …
> Extend the set of layout animation mocks

- Example/ios/Podfile.lock
- Example/package.json
- Example/patches/metro-inspector-proxy+0.73.7.patch
- Example/yarn.lock
- FabricExample/ios/Podfile.lock
- FabricExample/package.json
- FabricExample/patches/metro-inspector-proxy+0.73.7.patch
- FabricExample/yarn.lock
This PR bumps react-native from 0.71.0 to 0.71.1 in Example and FabricExample.
✅ Checked on Example and FabricExample on Android and iOS in debug mode.
> Bump react-native to 0.71.1

- android/src/main/cpp/NativeProxy.cpp
This PR simplifies code in `NativeProxy.cpp` by replacing `*runtime_` and `runtime_->` with `rt` and `rt.`, respecively.
Check if Example works on Android.
> Assign `*runtime_` to `rt`

- Common/cpp/Fabric/FabricUtils.cpp
- RNReanimated.podspec
- scripts/reanimated_utils.rb
This PR removes an outdated React Native version check when Fabric is enabled in C++ code since there already exists such mechanism in Android build scripts (see [here](https://github.com/software-mansion/react-native-reanimated/blob/ef888c2cc941d5175b9ac007a237a00ea4c2593d/android/build.gradle#L595-L604)), as well as adds an analogous check on iOS.
Check if FabricExample works on Android and iOS.
> Remove version check in FabricUtils.cpp

- src/createAnimatedComponent.tsx
Fixes #3873
`getScrollableNode()` works not only on FlashLists, but also on RN scrollable components (ScrollView, Flatlist). It's brought back from [there](https://github.com/software-mansion/react-native-reanimated/commit/5829e95b5e452761c659cb7fb73bb98a630f86c1#diff-fdad18d3281131f92aa76c0969f84d27f2314251842763fedbc756df07b1eab7L234)
- tested on the repro from the issue (https://github.com/diogoquintas/reanimated-scroll-issue)
- tested on several examples from the example app (examples related to scroll events and events in general for example chat heads)
- tested on FlashList
> Fix attaching a scroll event if the scrollable component is not the root view

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
Fixes a potential crash due to a null pointer exception being thrown.
This crash occurs in the Example app when navigating back during the exiting animation on the "Nested layout animation" example.
> [Android] Fix crash when navigating during an exiting animation

- Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp
- Common/cpp/AnimatedSensor/AnimatedSensorModule.h
- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/NativeModules/NativeReanimatedModule.h
- Common/cpp/SharedItems/Shareables.h
- android/src/main/cpp/NativeProxy.cpp
Fixes #3645
The reason for the crash when reloading was that, when the sensor listeners where cleaned up in the `AnimatedSensorModule`'s destructor, the `NativeProxy` object used for calling JNI functions has already been destroyed, causing a null pointer dereference.
This PR moves the sensor listener cleanup to `NativeProxy`'s destructor, where JNI functions are still safe to call.
In the Example app:
- go to the "Use Animated Sensor" example
- trigger a reload (e.g. by typing "r" in metro)
- 🤞 for no crash
> [Android] Cleanup animated sensors in NativeProxy destructor

- RNReanimated.podspec
This PR removes legacy flag `-DRN_FABRIC_ENABLED` argument in Reanimated's podspec in favor of using only `RCT_NEW_ARCH_ENABLED`.
Check if FabricExample works on iOS.
> Remove `RN_FABRIC_ENABLED` flag in RNReanimated.podspec

- docs/src/css/custom.css
Hides the `back-to-top` button in the documentation. Same as https://github.com/software-mansion/react-native-gesture-handler/pull/2398.
Build the docs and scroll a bit.
> Hide `back-to-top` button in the documentation

- ios/keyboardObserver/REAKeyboardEventObserver.m
Fixes https://github.com/software-mansion/react-native-reanimated/issues/3568
Fixes https://github.com/software-mansion/react-native-reanimated/issues/3712
Related to https://github.com/software-mansion/react-native-reanimated/pull/3704
The crash was caused because `_listeners` could be accessed by two threads at the same time. For example it could happen that while js thread in `unsubscribeFromKeyboardEvents` was deleting a listener, `updateKeyboardFrame` was iterating over it on the main thread. Now it's synchronised, so only one thread can access `_listeners` at the same time (and `_state` too just in case)
You can reproduce the crash easier by mounting 1000 components that use `useAnimatedKeyboard` in AnimatedKeyboardExample (I tested on simulator). Just enter and exit the example a …
> Fix crash caused by data race in useAnimatedKeyboard

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/SharedItems/Shareables.h
- src/createAnimatedComponent.tsx
- src/reanimated2/hook/useAnimatedRef.ts
- src/reanimated2/shareables.ts
This PR changes code that was used to handle host objects such that it applies to all kinds of host objects, not only on Fabric and not only to ShadowNodeWrapper classes. This simplifies the codebase a bit, because we get rid of a few code branches with fabric specific checks as well as allows for other types of Host Objects to be made shareable.
Changes that were made cover:
1) changes in shareables c++ code where we remove fabric specific shadow wrapper shareable type and replace it with generic HostObjectType
2) changes on the JS side in shareables.ts where we detect if host object is provided and then we let it be processed by `makeShareableClone` method directly. For this purpose we add code for recognizing whether a given object is a host object or not.
3) we get rid of JS code that …
> Make shareable HostObject code more generic

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- src/createAnimatedComponent.tsx
This PR fixes a Fabric crash in `NativeReanimatedModule::removeShadowNodeFromRegistry`. I don't know the exact root cause but I know how to fix it.
First, I added missing `makeShareableShadowNodeWrapper` call. However, since only the view tag is required on the native side, there's no need to pass the whole ShadowNodeWrapper, so I simply grab the view tag from `this._viewTag` and pass it to the cleanup worklet via closure.
1. Launch FabricExample on iOS
2. Open "forwardRef & useImperativeHandle" example
3. Increase animation duration to 3000 ms
4. Randomly click both buttons
5. Go to previous screen
6. Crash
https://user-images.githubusercontent.com/20516055/216365412-edb406ad-6947-4cdf-94aa-5b82bd079fab.mp4
> Fix Fabric crash in `NativeReanimatedModule::removeShadowNodeFromRegistry`

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/NativeModules/NativeReanimatedModule.h
- Common/cpp/Registries/EventHandlerRegistry.cpp
- Common/cpp/Registries/EventHandlerRegistry.h
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/NativeProxy.h
- ios/native/NativeProxy.mm
- ios/native/REAJSIUtils.h
This PR unifies code responsible for handling events on Paper and Fabric on both platforms.
* Remove `#ifdef` for `registerEventHandler` and make it renderer-agnostic
* Use `convertObjCObjectToJSIValue` instead of `convertIdToFollyDynamic`, `folly::toJson` and `jsi::Value::createFromJsonUtf8` on iOS
* Move Obj-C/JSI conversion functions from `NativeProxy.mm` to `REAJSIUtils.h`
* Still use JSON as intermediate format between `ReadableMap` and `jsi::Value` on Android (no known alternatives)
* Pass JNI values to EventHandler function instead of `std::string` (like on iOS we pass `id<RCTEvent>`)
* Use `const jsi::Value &` for event payload
* Use `const std::string &` for event name
Check if `GestureHandlerExample.tsx` and `ScrollViewExample.tsx` work on all configurations (Paper/Fabric, …
> Unify event handling on Paper and Fabric

- android/src/main/cpp/NativeProxy.cpp
This PR should fix "JSON Parse error: Unexpected end of input" error from Hermes VM happening when `JSON.parse` invoked by `jsi::Value::createFromJsonUtf8` (see [here](https://github.com/facebook/react-native/blob/62fa6d9dac185add0b8998fe1a443beaef3a49bc/ReactCommon/jsi/jsi/jsi.cpp#L139-L144)) fails due to malformed payload.
Related issues:
* https://github.com/Expensify/App/issues/14878
* https://github.com/wordpress-mobile/WordPress-Android/issues/16842
* https://github.com/software-mansion/react-native-reanimated/issues/2823
Run Example and FabricExample app on Android.
> Ignore events with malformed JSON payload

- Common/cpp/LayoutAnimations/LayoutAnimationsManager.cpp
- android/src/main/java/com/swmansion/reanimated/layoutReanimation/AnimationsManager.java
- android/src/reactNativeVersionPatch/nativeHierarchyManager/latest/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
- ios/LayoutReanimation/REAAnimationsManager.h
- ios/LayoutReanimation/REAAnimationsManager.m
- ios/LayoutReanimation/REASharedTransitionManager.h
- ios/LayoutReanimation/REASharedTransitionManager.m
- ios/LayoutReanimation/REASnapshot.h
- ios/LayoutReanimation/REASnapshot.m
- react-native-reanimated.d.ts
- src/createAnimatedComponent.tsx
This PR contains improvements after the latest reviews form PR with [Shared Element Transition](https://github.com/software-mansion/react-native-reanimated/pull/3827)
Changes:
- Naming improvements
- Get rid of the key-value observer - In the previous implementation I used KVO to change the context of execution. That was because swizzled method changes the context of execution, so the self in the swizzled method is `RNSScreen` instead of `REASharedTransitionManager`. That's why I used KVO to change the context of execution back to `REASharedTransitionManager`
- I used directly `[RNSScreen class]` and `[RNSScreenView class]` in the `swizzleScreensMethods` method, instead of getting it from the instance of screen (`[screen class]`)
- Refactor Snapshot on iOS
> [Shared Element Transition] Improvements after review v1

- ios/LayoutReanimation/REAAnimationsManager.m
- ios/LayoutReanimation/REASharedTransitionManager.m
I added a check to prevent adding already existing views to the shared transition registry. The issue only occurred when the view had a layout animation, as the registry is cleared after the animation ends. Afterwards, views from the registry were removed from their parent view. In the case of a shared transition, the parent screen is a custom temporary transition container, but in the case of a regular layout animation, the super view is the original parent. As a result, the view disappeared.
> [Shared Element Transition] Fix: view disappeared after layout animation

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
- ios/LayoutReanimation/REASharedTransitionManager.m
I shouldn't clear the layout animation config when the shared element transition doesn't start. Without this check, the exiting layout animation couldn't start because LayoutAnimationManager doesn't contain the view config.
Run exiting layout animation on Android.
> [Shared Element Transition] Fix exiting animations on Android

- android/src/main/java/com/swmansion/reanimated/layoutReanimation/SharedTransitionManager.java
- android/src/reactNativeVersionPatch/nativeHierarchyManager/latest/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
- ios/LayoutReanimation/REASharedTransitionManager.m
- ios/LayoutReanimation/REASnapshot.m
PR contains improvements in snapshotting view properties. 
- Android - Now animation will start when the screen has an attached header. In effect, the values in the snapshot will be valid.
- iOS - I replaced the old approach by detecting the screen header and adding information about header size to the snapshot.
> [Shared Element Transition] Problem with headers

- Common/cpp/AnimatedSensor/AnimatedSensorModule.cpp
- Common/cpp/AnimatedSensor/AnimatedSensorModule.h
- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/NativeModules/NativeReanimatedModule.h
- Common/cpp/NativeModules/NativeReanimatedModuleSpec.cpp
- Common/cpp/NativeModules/NativeReanimatedModuleSpec.h
- Common/cpp/Tools/PlatformDepMethodsHolder.h
- Example/src/AnimatedSensorExample.tsx
- Example/src/App.tsx
- Example/src/CubesExample.tsx
- __tests__/sensors.test.ts
- android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/NativeProxy.h
- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensor.java
- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensorListener.java
- android/src/paper/java/com/swmansion/reanimated/NativeProxy.java
- docs/docs/api/hooks/useAnimatedSensor.md
- ios/native/NativeProxy.mm
- ios/sensor/ReanimatedSensor.h
- ios/sensor/ReanimatedSensor.m
- ios/sensor/ReanimatedSensorContainer.h
- ios/sensor/ReanimatedSensorContainer.m
- react-native-reanimated.d.ts
- src/reanimated2/NativeReanimated/NativeReanimated.ts
- src/reanimated2/commonTypes.ts
- src/reanimated2/core.ts
- src/reanimated2/hook/useAnimatedSensor.ts
- src/reanimated2/js-reanimated/JSReanimated.ts
- Adds `adjustToInterfaceOrientation` option that adjusts the sensors values to current device orientation
- Adds `interfaceOrientation` shared value that contains the current interface orientation
- Adds `iosReferenceFrame` option that allows setting ios reference frame. Some reference frames doesn't work for example on iPods but give better results.
- `AnimatedSensorExample.tsx`
- `CubesExample.tsx` - when device faces north the cubes should rotate in the correct way on every device orientation.
> Make sensors work with different device orientations

- ios/LayoutReanimation/REASharedTransitionManager.m
This PR prevents starting shared transition at screen swipe back on iOS. In the future, for this use case, we want to add a new type of shared animation controlled by transition progress.
> [Shared Element Transition] Disable animation on swipe back

- Common/cpp/SharedItems/Shareables.h
This PR removes an import which became redundant after #4024.
Check if `Shareables.h` compiles successfully.
> Remove unnecessary import

- android/src/fabric/java/com/swmansion/reanimated/NativeProxy.java
- android/src/main/cpp/NativeProxy.h
- android/src/main/java/com/swmansion/reanimated/Utils.java
- android/src/main/java/com/swmansion/reanimated/keyboardObserver/ReanimatedKeyboardEventListener.java
- android/src/main/java/com/swmansion/reanimated/nativeProxy/AnimationFrameCallback.java
- android/src/main/java/com/swmansion/reanimated/nativeProxy/EventHandler.java
- android/src/main/java/com/swmansion/reanimated/nativeProxy/KeyboardEventDataUpdater.java
- android/src/main/java/com/swmansion/reanimated/nativeProxy/NativeProxyCommon.java
- android/src/main/java/com/swmansion/reanimated/nativeProxy/SensorSetter.java
- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensor.java
- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensorContainer.java
- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensorListener.java
- android/src/paper/java/com/swmansion/reanimated/NativeProxy.java
Refactor of `NativeProxy.java` to avoid some code duplication.
Run Example app and FabricExample app. Make sure things like keyboard, sensors, layout animations still work.
> Refactor NativeProxy on Android

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/SharedItems/Shareables.h
- __tests__/__snapshots__/plugin.test.js.snap
- plugin.js
This PR removes a plugin-level optimization that made it so that when using nested variables we'd only capture the most inner value and not the whole object.
The reason is that we now allow objects to be proxies in which case this won't work as we'd capture the object field instead of capturing the reference to proxy. An example of such was reported in #3967 but we also noticed similar problems when passing host objects.
We decided to drop optimization that landed in #1174 arguing that shared values after the rewrite are much faster and more reliable hence we can allow for larger objects to be converted even if we only use one or two fields from such objects. In the majority of the cases such conversion will only happen at most once. If this turns out to be problematic in certain …
> Get rid of only-value-capture optimization that breaks the world

- docs/docs/api/hooks/useAnimatedGestureHandler.md
- docs/versioned_docs/version-2.x/api/hooks/useAnimatedGestureHandler.md
This PR fixes links to React Native Gesture Handler documentation on `useAnimatedGestureHandler` hook
> docs: fix links to gesutre handler docs

- react-native-reanimated.d.ts
Fixed [#4056](https://github.com/software-mansion/react-native-reanimated/issues/4056) by adding proxy interface to the inheritance chain. Also changing `itemLayoutAnimation` to be optional, since it is optional in source files.
build & run `InvertedFlatList` in `Example` app
run `yarn jest`
> Add proxy interface for Animated.FlatList to enable passing itemLayoutAnimation prop

- src/reanimated2/animation/util.ts
Some recent changes (#4060 and #4024) resulted in introducing a reference loop. The reason was that we started capturing the whole module as host object due to the fact we referenced the module in `defineAnimation` method. As a result, the VM wouldn't deallocate properly and we started getting instance checker crashes on reloads.
Start app on iOS. Try out reloading JS several times -> no crash.
> Fix host obj reference loop

- scripts/cpplint.sh
This PR changes the behavior of `yarn lint:cpp` script when cpplint is not found.
Dude trust me
> Raise error when cpplint is not installed

- .github/workflows/validate-cpp.yml
- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/Registries/EventHandlerRegistry.cpp
- Common/cpp/Registries/EventHandlerRegistry.h
- Common/cpp/SharedItems/Shareables.cpp
- Common/cpp/Tools/WorkletEventHandler.h
- scripts/cpplint.sh
This PR replaces all occurrences of `unsigned long` and `unsigned long long` with `uint64_t` in order to make our codebase compliant with C++ code style without having to ignore `runtime/int` errors from cpplint.
* Confirm that `sizeof(unsigned long)` and `sizeof(unsigned long long)` are equal to `sizeof(uint64_t)` i.e. `8` across all target architectures
* Check if Example compiles successfully
> Resolve `runtime/int` errors in cpplint

- __tests__/Animation.test.js
- __tests__/InterpolateColor.test.js
- src/reanimated2/mappers.ts
- src/reanimated2/threads.ts
This PR adds Jest specific code to places where we'd used setImmediate. We want to avoid calling setImmediate as it makes writing tests a bit tricky.
The reason is that Jest mocks all the timer-related stuff putting all enqueued function in a single bucket. Then, in order to run these enqueued functions, the test needs to call advanceTimersByTime. It isn't allowed to schedule a callback for the same "tick" which results in the chain of setImmediate calls requiring a several separate runs to advanceTimersByTime. This can be seen in the previous workaround where we had three subsequent calls to that method just in order to start a single animation.
With this change we no longer expect from test to run any additional setup / timer-advancing steps when testing reanimated components and …
> Avoid setImmediate calls on Jest environment

- docs/docs/guide/testing.md
- src/reanimated2/jestUtils.ts
This diff updates documentation about testing to remove mentions of `withReanimatedTimer` that we no longer require to use.
Run md preview and check if the testing page look alright
> Update docs about testing after recent changes

- ios/LayoutReanimation/REAAnimationsManager.m
The `transformMatrix` prop in snapshot is optional and used only for Shared Transitions. I added a check in the `prepareDataForLayoutAnimatingWorklet` function to prevent inserting `nil`s objects.
> Fix crash with snapshot on iOS

- scripts/reanimated_utils.rb
This PR fixes a broken link in the error message in `reanimated_utils.rb` which no longer works because `next` version was removed by @kacperkapusciak in #4066.
Check if the URL is valid.
> Fix docs link in reanimated_utils.rb

- src/reanimated2/layoutReanimation/animationsManager.ts
In #4043 I changed the restarting animation logic in `animationManager.ts`. Accidentally I removed restarting animation for the rest of the Layout Animations. Fortunately, I found a better way to handle restart animation for both LA and SET animations types.
> Fix Layout Animation restart

- __tests__/versionCheck.test.js
- src/reanimated2/NativeReanimated/NativeReanimated.ts
- src/reanimated2/platform-specific/checkVersion.ts
We hardcode the version of Reanimated here in order to compare it with the version used to build the native part of the library in runtime.
Ideally, we'd grab this version from the `package.json` file instead, but this causes issues when packaging the library due to misaligned relative paths.
> Hardcode JS library version in `checkVersion`

- ios/REANodesManager.mm
Before this change we'd only call `performOperations` for a subset of filtered events (initially introduced in #312). The event's that weren't considered "direct" would require additional animation frame for having their updates flushed. This change makes it so that we call `performOperations` for all types of events therefore matching the behavior [on Android](https://github.com/software-mansion/react-native-reanimated/blob/99b8b3ed56e36ca615cce7164ccaf04d154571b1/android/src/main/java/com/swmansion/reanimated/NodesManager.java#L283)
A consequence of this change was that for some event types, the updates reanimated was performing weren't getting flushed onto screen. Namely, we noticed this problem in Pager example where a view pager component with some custom set of events is used and …
> Make all events on iOS flush updates immediately

- src/reanimated2/core.ts
This diff fixes an issue with animated views not updating when animating along keyboard. This problem regressed after #3970 where we changed the logic of when enqueued callbacks for animation frame and immediates are flushed. The logic has been moved from c++ to js and we added some code to execute animation frame and immediates as a part of event handling process. However, keyboard events have a separate flow of providing event data (we should unify this at some point), and we missed updating it in that place.
This PR adds similar logic to [what we use for regular events](https://github.com/software-mansion/react-native-reanimated/blob/535b5d64c0720da3a9a39d99a67e878fe09b5154/src/reanimated2/core.ts#L117) into the code responsible for handling keyboard events.
Run animated keyboard …
> Flush animation-frame and immediates on keyboard event to follow same flow as other types of events

- src/reanimated2/initializers.ts
This PR fixes a perf regression introduced in #3722. The issue was that we'd schedule a native request animation frame callback several times in a single frame. As a result we'd run mapper updates more than once per frame which resulted in UI thread skipping frames. The bug would surface in examples where we had both timing (active) and gesture driven animations. In such scenario we'd enqueue native requestAnimationFrame callback twice – first time for the running timing animation, and the second time as a result of handling the touch event. These two callbacks would then run as long as there are update happening and would incur additional cost to all updates happening on the UI thread. Moreover, for each new gesture started afterwards we'd add a new call to requestAnimationFrame and yet …
> Skip flushing animation-frame callbacks if update was already run for a given frame

- Common/cpp/SharedItems/Shareables.h
I noticed that `HAS_JS_WEAK_OBJECTS` is no longer used so it makes sense to remove it from our codebase.
Just see if the Example and FabricExample apps compile.
> Remove `HAS_JS_WEAK_OBJECTS` definition

- plugin/index.js
This PR stores the result of `shouldGenerateSourceMap` to avoid calling it twice.
Trust me bro
> Call `shouldGenerateSourceMap` only once

- .github/workflows/build-v8.yml
This PR bumps `react-native` version from 0.70.5 to 0.71.3 because of the failing CI after the successful release of `react-native-v8@2.0` which requires `react-native>=0.71.0`.
Just see if the V8 CI is green.
> Bump react-native version in V8 CI

- Common/cpp/Tools/JsiUtils.h
`asBool()` is supported by JSI since RN@0.69. I replaced `asBool()` with `getBool()` syntax.
CI fail: https://github.com/piaskowyk/reanimated-rn-version-tester/actions/runs/4281203461/jobs/7453937810
> Fix backward compatibility with asBool()

- Common/cpp/Tools/RuntimeDecorator.cpp
Fixes build issue on older (<= 0.64) RN versions of Android caused by template instantiation errors when converting from any Callable (like raw function pointers) to `std::function` in `jsi_utils::installJsiFunction`.
This is resolved by wrapping the problematic functions in lambdas assigned to `std::function` variables before calling `installJsiFunction`.
> [Android] Fix build error on older React Native versions

- src/reanimated2/utils.ts
Fixes #4129.
This PR expands the guard for the `isSharedValue` util to rule out nullish values (`null` and `undefined`).
This was necessary because `typeof null` returns `object` (some JS shenanigans) and the current implementation would try to access the `_isReanimatedSharedValue` property on that `null` value, causing an exception to be raised (and possibly crashing the app).
```ts
// before
isSharedValue(null) // raises an Exception
// after
isSharedValue(null) // returns `false`
```
> Guard `isSharedValue` against nullish values

- src/reanimated2/threads.ts
Fixes https://github.com/software-mansion/react-native-reanimated/pull/3970#issuecomment-1449812409
This logic matches that of `runOnUI`.
> Fix web on v3 when not using a Babel plugin

- src/createAnimatedComponent.tsx
style might be undefined at this point and `Object.keys(style)` would throw an exception
I use a third party library and after upgrading to reanimated 3.0.0 I get the exception at line 123. 
I don't have a simple test case but checking that style is defined does not hurt
> style might be undefined at this point

- mock.js
- react-native-reanimated.d.ts
- src/reanimated2/mock.ts
This PR removes old stuff from react-native-reanimated.d.ts and mock.js.
???
> Cleanup react-native-reanimated.d.ts and mock.js

- src/reanimated2/hook/useAnimatedSensor.ts
When we update the shared value on the UI thread without animation, we need manually flush queued mappers.
> Add flushImmediates to useAnimatedSensor

- __tests__/__snapshots__/plugin.test.js.snap
- plugin/index.js
The babel plugin transformed the code and added some helper code, it uses `new Error()` to get the call stack. this works in general unless you have a variable called `Error` in the local scope, in this case, It references the wrong Object. this PR uses `global.Error` to avoid this.
`'Date'` is duplicated in this `global` array, and I removed the second one.
```jsx
import { useState } from 'react';
import Animated, { useAnimatedStyle, useSharedValue } from 'react-native-reanimated';
import Error from './components/Error'; // imported an arrow function component named 'Error'
const [hasError, setHasError] = useState(false);
const offset = useSharedValue(0);
// `new Error()` not working here, because `Error` reference to the function component, it's a arrow function, not …
```
> fix `Error` Variable scope conflicts, and remove duplicate `Date`

- android/src/main/java/com/swmansion/reanimated/nativeProxy/NativeProxyCommon.java
This issue: https://github.com/software-mansion/react-native-reanimated/issues/4135 describes an error happening on old Android versions.
The error message is
> 🚫 ${\color{red}\text{Error}}$
> Exception in HostFunction: java.lang.NoSuchMethodError: no non-static method "Lcom/swmansion/reanimated/NativeProxy;.registerEventHandler(Lcom/swmansion/reanimated/nativeProxy/EventHandler;)V", js engine: hermes
It can be simply fixed by changing some function from `private` to `public` ones as suggested [here](https://github.com/software-mansion/react-native-reanimated/issues/4135#issuecomment-1463572593).
Fixes #4135
Tested on android simulator
> [V3 bugfix] Change private methods to public ones

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
- ios/REANodesManager.mm
This PR addresses the problem from #3879 on iOS where application would fall into a deadlock when performing synchronous layout updates. The reason for the issue was that sync layout updates requires UI thread to lock and wait for layout thread to perform some tasks. On the other hand, layout thread sometimes schedules UI tasks to be performed synchronously (with `dispatch_sync` mechanism).
The solution this PR implements is to add a timeout on waiting and fallback to updating layout props asynchronously. This feels like a right approach as the cases when dispatch_sync is used are relatively rare and the consequences of updating layout asynchronously aren't serious (there will be a one frame delay for that one update).
This solution is based on #3082 but on top of just adding the timeout …
> Fix issue causing ANR when performing sync layout updates

- .github/workflows/build-monorepo-action.yml
Fixing our red main as `react native run-ios` is having troubles with launching a default (non-specified) simulator.
CI is the way.
> Fix monorepo worklow

- ios/keyboardObserver/REAKeyboardEventObserver.m
When you try to hide animation during keyboard opening, this ends the current animation and starts another one. I added a missing flag setter to prevent the clearing of the displayLink object.
| Before      | After |
| ----------- | ----------- |
| <video src="https://user-images.githubusercontent.com/36106620/227270299-5f7cd5e6-21b3-47c3-85fb-2860fb9fbac9.mov" /> | <video src="https://user-images.githubusercontent.com/36106620/227269574-bf94ebc9-3132-49d9-bd2d-f5cd8671990c.mov" /> |
Fixes https://github.com/software-mansion/react-native-reanimated/issues/4194
> Fix useAnimatedKeyboard animation restart on iOS

- .github/workflows/docs-check.yml
- .github/workflows/static-example-apps-checks.yml
- .github/workflows/static-root-checks.yml
- .github/workflows/validate-java.yml
- .github/workflows/validate-plugin.yml
This PR upgrades Node.js from 14 to 16 to match React Native 0.72 (see [here](https://github.com/facebook/react-native/blob/2c6edee68e936129644c14736e684a14bd11c55c/packages/react-native/template/package.json#L32-L34)).
> Use Node.js 16 on CI

- .github/workflows/build-monorepo-action.yml
There seems to be a problem with running `npx react-native` from inside a directory that contains package.json file (see https://github.com/facebook/react-native/issues/34441#issuecomment-1275186909), however I wasn't able to reproduce it locally.
This PR swaps the order of steps, so that `npx react-native` is run before package.json is created.
Just check if CI is green.
> Fix monorepo workflow

- .github/workflows/build-v8.yml
- android/src/main/java/com/swmansion/reanimated/NodesManager.java
- ios/REANodesManager.m
The port of https://github.com/software-mansion/react-native-reanimated/pull/4239 PR for Reanimated 2.
> Fix issue causing ANR when performing sync layout updates, for Reanimated 2

- .github/workflows/docs-check.yml
- WebExample/WithoutBabel.tsx
- WebExample/babel.config.js
- WebExample/package.json
- WebExample/tsconfig.json
- WebExample/yarn.lock
- docs/docs/fundamentals/web-support.md
- src/reanimated2/hook/useAnimatedReaction.ts
- src/reanimated2/hook/useAnimatedStyle.ts
- src/reanimated2/hook/useDerivedValue.ts
The port of https://github.com/software-mansion/react-native-reanimated/pull/3997 PR for Reanimated 2.
> Add web support without a Babel/SWC Plugin, for Reanimated 2

- src/reanimated2/js-reanimated/JSReanimated.ts
This PR adds missing `configureLayoutAnimation` method in `JSReanimated` class and resolves a crash when using Layout Animations on web or while debugging in Chrome.
Fixes #3964.
1. Copy BasicLayoutAnimation.tsx into WebExample/App.tsx
2. Launch WebExample
3. See the error in the browser console
4. Apply this patch
5. ???
6. Profit
> Add missing configureLayoutAnimation on web

- src/reanimated2/frameCallback/FrameCallbackRegistryUI.ts
- src/reanimated2/hook/useFrameCallback.ts
This PR fixes the problem of multiple callbacks after fast refresh
To prevent multiple loops, we use this if statement 
```
// runCallback() should only be called after registering a callback,
// so if there is only one active callback, then it means that there were
// zero previously and the loop isn't running yet.
if (this.activeFrameCallbacks.size === 1) {
requestAnimationFrame(loop);
}
```
The problem with fast refresh is that we unregister the callback and immediately register new.
Before unregistration is completed we register new one, so the previous loop doesn't stop.
We also start second loop, because we have one active frame. So in the end, after each fast refresh, we add new loop that execute the same callback.
To fix it, I added variable `newCallId` and pass it to each …
> Fix useFrameCallback fast refresh

- react-native-reanimated.d.ts
- src/reanimated2/Easing.ts
- src/reanimated2/mock.ts
This pull request adds a new `steps` easing function to React Native Reanimated. The steps function allows for animations to jump between discrete values, similar to the CSS `steps()` function.
The steps function takes two arguments: `n`, which specifies the number of steps in the animation, and `start`, which specifies whether the animation should start at the beginning (start) or end (end) of the step.
```js
rotate.value = withTiming(360, { duration: 60 * 1000, easing: Easing.steps(60, false) })
```
- This function has been tested and is confirmed to be working correctly on both the `Android`, `Expo`, and `Web` platforms.
- 👉 [expo snack example](https://snack.expo.dev/@alabsi91/react-native-reanimated-steps-easing-function-example)
> Add `steps` easing function

- Common/cpp/NativeModules/NativeReanimatedModule.cpp
- Common/cpp/SharedItems/Shareables.h
This PR adds support for passing JSI HostFunctions to worklet runtime as a follow-up to #4024 which makes it possible for JSI HostObjects.
Previously, it was possible only to pass HostObjects:
```tsx
import { TurboModuleRegistry } from 'react-native';
import { runOnUI } from 'react-native-reanimated';
const Clipboard = TurboModuleRegistry.getEnforcing('Clipboard');
Clipboard.setString('hello world');
'worklet';
console.log(Clipboard);
Clipboard.getString().then(console.log);
})();
return null;
}
```
This PR makes it possible to pass HostFunctions as well:
```tsx
import { runOnUI } from 'react-native-reanimated';
const turboModuleProxy = global.__turboModuleProxy;
console.log(turboModuleProxy); …
```
> Add shareable HostFunction

- android/src/main/cpp/NativeProxy.cpp
- android/src/main/cpp/NativeProxy.h
> Cleanup NativeProxy on Android

- Common/cpp/Tools/SingleInstanceChecker.h
- RNReanimated.podspec
- android/CMakeLists.txt
- android/build.gradle
Currently, Reanimated crashes on some configurations due to an assert in `SingleInstanceChecker` which was meant to help us detect retain cycles and thus memory leaks in the library at an early stage but actually causes lots of troubles in client apps. This PR changes the behavior of `SingleInstanceChecker` so that it always prints the warning to the console but calls the failing `assert` only in Reanimated example apps (i.e. Example or FabricExample).
This PR wraps the failing assert inside a preprocessor conditional based on the flags passed from `build.gradle` via `CMakeLists.txt` (Android) or `RNReanimated.podspec` (iOS). Additionally, it introduces `__android_log_print` instead of `std::cerr` on Android so that the warning is also visible in logcat.
Android:
iOS:
1. Check if …
> Call assert in `SingleInstanceChecker` only in example apps

- src/reanimated2/hook/useAnimatedReaction.ts
Hey!
If we do not specify an array of dependencies in useAnimatedReaction and prepare or react has external dependent values (._closure), then the startMapper and stopMapper methods will be called an extra time on each render, even if the external values have not changed.
If the functional component has such a block of code, then useEffect is called inside useAnimatedReaction on every render before these changes.
```
const value = 1;
useAnimatedReaction(
() => value,
() => {},
);
```
> Fix unnecessary calls startMapper/stopMapper in useAnimatedReaction

- android/build.gradle
To fix this kind of error with the package:
We need to specific grade dependencies. The `+` sign instead of fix version breaks the package build for `rn@0.7.+` because `rn@0.72.0-rc.0` was released.
> Set right ReactAndroid version

- src/reanimated2/mappers.ts
This fixes a problem when reanimated would get stuck in an infinite update loop triggered by shared value update in useAnimatedStyle or useDerivedValue. Although we don't recommend updating shared values in these stages of the mapper loop, it was still being used by some users that way and therefore the change mapper logic we introduced in reanimated 3 introduced a regression in that behavior.
When updating shared values in mapper phase we can never guarantee the correct order of mapper execution (as it may be the case that some mappers that used the shared value has already run and others didn't). To match the behavior of reanimated 2 we enqueue an update for the next frame that will run with the updated value.
I used the following example that updates height in useDerivedValue:
```ts …
```
> Break infinite queueMicrotask loop when updates are triggered in mapper-run phase

- ios/keyboardObserver/REAKeyboardEventObserver.m
This PR refactors the logic in REAKeyboardEventObserver to address some number of different issues:
1) no change notification when keyboard size changes due to change in language or showing suggestions bar
2) issue with keyboard height notification when opening modal (see #4339)
3) issue with non-zero height after keyboard hides completely.
Here is the list of the main thing that this refactor changes:
1) We no longer use willShow/willHide/didShow/didHide notifications for keyboard and only use willChangeFrame which is the most reliable one and triggers also when the keyboard updates
2) We no longer use a technique where the keyboard size is determined based on the frame of the keyboard view. This was problematic as that frame would sometimes reflect a one-frame delayed size which …
> Refactor keyboard observer on iOS

- src/reanimated2/initializers.ts
Fixes #3951 #4263 #4354
I can now successfully debug using React Native Debugger again. Same fix was proposed by @rililive https://github.com/software-mansion/react-native-reanimated/issues/3951#issuecomment-1384223013
> fix: console.assert is not defined during debug

- src/reanimated2/threads.ts
This PR adds additional call to convert worklet and arguments to shareables directly from runOnUI such that we avoid doing the conversion from the microtasks queue. The reason for that is that if the object to be converted triggers an error (stack exceeded or cyclic object), converting it from microtasks queue makes it difficult to narrow down the actual object that triggered the exception. 
Since make-shareable method keeps a cache of converted objects we can be sure the conversion doesn't happen twice, but nevertheless we only do that in DEV mode.
Run Example app.
> Convert to shareable directly from runOnUI

- src/createAnimatedComponent.tsx
When writing a new documentation for `createAnimatedComponent` I've found out that this function works not only for class-based components but also for functional components with `React.forwardRef()`. 
This PR updates the warning caused by using plain functional components to guide users to use forwardRef.
When plain functional component is passed to `createAnimatedComponent` the app errors out:
```jsx
function MyComponent(props) {
return <View {...props} />;
}
const MyAnimatedComponent = Animated.createAnimatedComponent(MyComponent);
```
but warning guides to use `React.forwardRef()`.
When a functional component is wrapped with forwardRef it works just fine:
```jsx
function WrappedView(props, ref) {
return <View {...props} ref={ref} />;
}
const MyComponent = …
```
> Update misleading createAnimatedComponent warning

- src/reanimated2/errors.ts
The `__ErrorUtils` is available only in Reanimated Runtime, to use `reportFatalError` we need to use ReactNative internal function available in `ErrorUtils` global object.
```
function fn() {
'worklet'
throw new Error('error');
}
runOnUI(fn)()
```
> Fix undefined `ErrorUtils.reportFatalError`

- src/reanimated2/NativeMethods.ts
- src/reanimated2/errors.ts
The flag `_IS_FABRIC` is only defined on React Runtime, we can't use them on Reanimated Runtime. I removed the check of this flag for Reanimated Runtime because this one prevents any `_dispatchCommand` call.
Run any scrollTo example on Fabric
> Fix scrollTo on Fabric

- android/build.gradle
Makes single instance assertion not break builds when using [Gradle Configuration Cache](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:intro).
Related: https://github.com/software-mansion/react-native-gesture-handler/pull/2453
Enable Gradle Configuration Cache by adding `org.gradle.unsafe.configuration-cache=true` in the `gradle.properties` file. If testing on the Example app, remove `disableMultipleInstancesCheck=true`.
Build the app with and without this PR.
> Make single instance assertion work with Gradle Configuration Cache

- app/src/examples/ScreenStackHeaderConfigBackgroundColorExample.tsx
- ios/REANodesManager.mm
This PR fixes ScreenStackHeaderConfigBackgroundColor example on iOS with Paper.
See also https://github.com/software-mansion/react-native-screens/pull/1760 
https://user-images.githubusercontent.com/20516055/233048052-7c35c443-9e89-497d-9aa5-552d57bb1838.mov
Check if the example works
> Fix updating props of ScreenStackHeaderConfig on Paper iOS

- android/src/main/java/com/swmansion/reanimated/sensor/ReanimatedSensorListener.java
The sensors on Android and iOS return opposite values, which cause inconsistencies. To fix this, I modified the Android sensor listener to return opposite values.
I didn't modify rotation values, because these are the same.
- Ran each sensor and compared the values returned by both platforms
- Tested an example application to confirm that the behavior of the sensors is consistent across both platforms.
> Set the opposite sensor values on android to be consistent with iOS

- Example/ios/Podfile.lock
- TVOSExample/ios/Podfile.lock
- package.json
> Release 2.16.0

- src/reanimated2/hook/useAnimatedRef.ts
Fixes #4376. Analogous to #3988.
Solution: copy the code from `createAnimatedComponent.tsx` to `useAnimatedRef.ts`
https://github.com/software-mansion/react-native-reanimated/blob/87fb9c6a1fb6b8c839b65b90ad16f574f45a1294/src/createAnimatedComponent.tsx#L289-L291
Example:
<details>
<summary>App.tsx</summary>
```tsx
runOnUI,
scrollTo,
import {Button, StyleSheet, Switch, Text, View} from 'react-native';
import {FlashList} from '@shopify/flash-list';
declare const _WORKLET: boolean;
const AnimatedFlashList = Animated.createAnimatedComponent(FlashList);
interface Item {
label: string;
}
const DATA: Item[] = [...Array(100)].map((_, i) => ({label: String(i)}));
function getRandomOffset() {
'worklet'; …
```
> Fix scrollTo on FlashList

- ios/REANodesManager.mm
This PR tries to address the problem with assert that we make in `REANodesManager.mm` when receiving mounting block from the React's UI Manager. 
The issue was due to a fact that we only hold a single reference for mounting block as well as the timed-out flag, while under certain conditions, the `performOperations` may re-enter before these values are cleaned up correctly. This didn't happen before #4239 because the lock would guarantee that `performIOperation` is never called again before the block scheduled on UIManagerQueue is finished. However in #4239 we changed this behavior to stop potential ANR issues due to locking and this caused this new issue to surface. 
The change we are making here is that we create a new instance of observer that is specific to a given `performOperation` …
> Resolve sync UI updates concurency issue on iOS

- src/reanimated2/shareables.ts
The goal of freezing is to freeze JS objects used on the UI thread. But we don't need and don't want to freeze objects used only on the UI thread.
```js
const sv1 = useSharedValue([0]);
const sv2 = useSharedValue({ prop: [0] });
'worklet';
sv1.value[0]++;
sv2.value.prop[0]++;
console.log(sv1.value, sv2.value.prop, Object.isFrozen(sv1.value));
})()
```
Output before:
```
LOG  RENDER -----------------------------------
LOG  [1] [1] false
LOG  RENDER -----------------------------------
LOG  [1] [1] true
LOG  RENDER -----------------------------------
LOG  [1] [1] true
```
Output after:
```
LOG  RENDER -----------------------------------
LOG  [1] [1] false
LOG  RENDER -----------------------------------
LOG  [2] [2] false
LOG  RENDER -----------------------------------
LOG …
```
> Unfreeze UI objects :cold_face: -> :sunglasses:

- Example/package.json
- Example/yarn.lock
- FabricExample/package.json
- FabricExample/yarn.lock
This fixes [this](https://github.com/software-mansion/react-native-reanimated/security/dependabot/224) and [this](https://github.com/software-mansion/react-native-reanimated/security/dependabot/223).
🚀
> Bump patch-package for dependabot alerts

- __typetests__/react-native-reanimated-tests.tsx
- src/reanimated2/NativeMethods.ts
- src/reanimated2/hook/commonTypes.ts
- src/reanimated2/hook/useAnimatedRef.ts
- src/reanimated2/utils.ts
_This PR is part of an ongoing effort to get rid of the .d.ts file and use type definitions generated based on the source code._
It's a direct follow-up to #3778.
- Added type tests for `NativeMethods`.
I still need some guidance with them - what exactly do we want to test there and how.
- Added extra type `AnimatedRef<T>` which is an alias to `RefObjectFunction<T>`.
Reason for that was in many parts of code we explicitly ask for an `animatedRef` as an argument and it seems just more logical to have an alias for it.
🚀
> Add type tests for NativeMethods and add AnimatedRef type

- __tests__/checkVersion.test.ts
- src/reanimated2/NativeReanimated/NativeReanimated.ts
- src/reanimated2/platform-specific/checkCppVersion.ts
- src/reanimated2/shareables.ts
This PR changes the behavior of the app when version mismatch is detected. Previously, we called `console.error` in such case, but the app still continued to execute. This PR replaces `console.error` with `throw new Error` which stops the execution and shows full-screen LogBox.
|:-:|:-:|
| <img width="459" alt="before" src="https://github.com/software-mansion/react-native-reanimated/assets/20516055/4b58c8f8-350a-4d17-8c3a-51a9a3cf1fc9"> | <img width="459" alt="after" src="https://github.com/software-mansion/react-native-reanimated/assets/20516055/53cd425f-4da1-4ff4-86c8-776fdcbfe4a0"> |
> Replace console.error with throw new Error

- scripts/set-nightly-version.js
This PR changes nightly version numbering from `0.0.0-yyyymmdd-commithash` to `<x>.<y+1>.<z>-nightly-yyyymmdd-commithash` to keep things analogous to react-native (see [here](https://www.npmjs.com/package/react-native?activeTab=versions)) as well as to fix failing Android builds due to conditionals in build.gradle and RNReanimated.podspec which use major version for build config.
1. Clone the repository
2. Run `node scripts/set-nightly-version.js`
3. Check if the version in `package.json` and `jsVersion.ts` starts with `3.2.0-nightly-`
> Change nightly version numbering

- react-native-reanimated.d.ts
For better DX and consistency with the docs (current and the new ones) I've decided to rename the first argument of `useScrollViewOffset`, `measure`, `getRelativeCoords`, and `scrollTo` to `animatedRef`.
Just `ref` as an argument  indicates that a plain `const ref = React.useRef()` works with these functions leading to a confusing developer experience.
Also, `aref` is a bit cryptic and a hard thing to look up on the Internet when just starting to learn Reanimated.
> Rename `ref` & `aref` -> `animatedRef` in types

- docs/docs/guide/testing.md
- docs/versioned_docs/version-2.x/guide/testing.md
- package.json
- src/reanimated2/index.ts
- src/reanimated2/jestUtils.ts
- src/reanimated2/jestUtils.web.ts
We have waited for it a long time. 
Here it is.
A perfect summary of weeks time of our work and research - two line fix.
Ever since we've adopted CommonJS as target for our built JavaScript files we made it very difficult to our users to properly use Jest with Reanimated. This is due to fact that Reanimated Babel plugin is prone to break hoisting and this becomes critical in CommonJS. This issue had never surfaced before because we were building only for ES modules which can handle the way our plugin works. Therefore, after many talks we've decided to drop support for CommonJS and revert to ES modules only.
Refer to #4449 for _slightly_ more information.
This is likely to fix (I want to wait for confirmation):
- #4347,
- #4197,
- #4185,
- #4175,
- #4136,
- #4001,
- #3971.
- I tested it on …
> Remove commonjs generation

- src/reanimated2/js-reanimated/index.ts
Smol fix after #4352 because `react-native-web` may not be installed.
> Fix createReactDOMStyle import

- src/reanimated2/hook/useAnimatedReaction.ts
Values returned by the `prepare` function inside `useAnimatedReaction` are assigned to the `previous` shared value. Even though it is only read from the UI thread, those values are cloned so that they can be read from the JS thread. This process turns out to be a tad problematic when dealing with large objects, as it can take a significant amount of time.
This PR sets the `oneWayReadsOnly` flag when creating `previous` to true, disabling the cloning process and reducing the performance impact of the hook.
<details>
<summary>
Here's a simple reproduction for this problem
</summary>
```jsx
import {SafeAreaView} from 'react-native';
import {
Gesture,
GestureDetector,
GestureHandlerRootView,
} from 'react-native-gesture-handler'; …
```
> Optimize `useAnimatedReaction`

- src/reanimated2/jestUtils.native.ts
- src/reanimated2/jestUtils.ts
This PR fixes bundling error which appeared after #4468.
```
error: Error: Unable to resolve module path from /Users/tomekzaw/RNOS/Jest/react-native-reanimated/node_modules/jest-message-util/build/index.js: path could not be found within the project or in these directories:
../node_modules
```
```
../node_modules/jest-util/build/requireOrImportModule.js:Invalid call at line 55: import(moduleUrl.href)
```
> Fix Jest bundling error

- src/createAnimatedComponent.tsx
Fixes #3769
Each time `componentDidUpdate` is triggered we have to subscribe for events again. However we used to use the same viewTag, although the viewTag may change each time the view is updated. This mean that the given view will stop receiving any events.
Look at the above-linked issue to see the description of bug in the recordings. In the console you can see viewTag used to subscribe for events. In a buggy example it doesn't change when you modify the orientation of the scroll.
<table>
<tr><td>BEFORE</td><td>
https://github.com/software-mansion/react-native-reanimated/assets/56199675/e8db724a-620f-4da1-ac44-bdc73e4d936b
</td></tr>
<tr><td>AFTER</td><td>
https://github.com/software-mansion/react-native-reanimated/assets/56199675/b2a8d2c1-0476-4ddf-b543-b7c0b768389e
</td></tr> …
> Update view tag on `componentDidUpdate`

- src/reanimated2/threads.ts
This PR fixes the following error which appeared after #4477.
Check if WebExample works.
> Fix runOnUI on web

- android/src/main/cpp/NativeProxy.cpp
- ios/REAModule.mm
- ios/native/REAInitializer.mm
- src/reanimated2/threads.ts
> Inject `_WORKLET` to RN runtime

- docs/docs/guide/testing.md
This testing example was using `jest.advanceAnimationByTime`. As far as I understand this method doesn't exist on `jest`. `advanceAnimationByTime` was a API exported by the reanimated lib and [it was deprecated](https://github.com/software-mansion/react-native-reanimated/blob/2426f32095af417f1cfc1789479c3d2ee7c72e18/src/reanimated2/jestUtils.ts#L171). 
N/A
> Fix testing example

- RNReanimated.podspec
when open 'use_frameworks!' in Podfile, build will fail because of unable to find hermes related headers. We need to declare hermes dependency explicit in podspec
> fix: ios build error when using 'use_frameworks!' in Podfile

- ios/native/RCTAppDelegate+Reanimated.h
Fixes #4553. Copied from expo/expo ([link](https://github.com/expo/expo/blob/acf89113e6ecff4841553991e743157cd8e49db1/packages/expo-modules-core/ios/AppDelegates/EXAppDelegateWrapper.h#L8-L13)), originally fixed by @Kudo, thanks to @tsapeta for code pointers.
```
npx react-native@next init MyApp --version 0.72.0-rc.5 --skip-install
cd MyApp
yarn add react-native-reanimated@nightly
cd ios
code Podfile
USE_FRAMEWORKS=static pod install
```
> Fix RCTAppDelegate.h file not found error when `USE_FRAMEWORKS=static`

- package.json
- tsconfig.json
Currently our `tsconfig.json` and config for react-native-builder-bob in `package.json` are misconfigured and we are getting type declarations for tests and typetests. PR removes them and restores proper structure.
|--------|--------|
|  <img width="331" alt="Screenshot 2023-05-25 at 08 14 06" src="https://github.com/software-mansion/react-native-reanimated/assets/40713406/31706cda-e844-41f5-87fe-b97d08aec742"> | <img width="321" alt="Screenshot 2023-05-25 at 08 15 17" src="https://github.com/software-mansion/react-native-reanimated/assets/40713406/00782729-84c1-4eea-ae52-0a7b33c66e72"> |
`tsconfig.json` doesn't need to be specified in builder-bob configuration as it [takes root tsconfig by default](https://github.com/callstack/react-native-builder-bob#typescript).
Unit …
> Fix lib directory structure generated by builder-bob

- android/src/main/java/com/swmansion/reanimated/NodesManager.java
- src/reanimated2/initializers.ts
This PR fixes an issue with long animations. On Android, it was possible to execute ChoreographerCallback twice during the same frame (after frame drop). In effect, existing animations were canceled due to this if-condition in `requestAnimationFrame` method:
```js
nativeRequestAnimationFrame((timestamp) => {
if (lastNativeAnimationFrameTimestamp >= timestamp) {
// Make sure we only execute the callbacks once for a given frame
return;
}
...
```
To fix it, I moved this check to the native code. When double execution happens I skip the execution of the JS callback, but I still need to schedule another choreographer callback.
```java
final long[] lastTimestamp = {0};
new GuardedFrameCallback(context) {
@Override
protected void doFrameGuarded(long frameTimeNanos) {
if (lastTimestamp[0] == …
```
> Fix ChoreographerCallback double execution

- src/reanimated2/initializers.ts
This PR fixes a bug in v3 which prevents animations from running when Chrome Debugger is attached (or, in general, when web implementation of Reanimated is used). Originally reported by @coayscue.
In order to reproduce the issue, you can simply force use web implementation in `PlatformChecker.ts`:
```diff
export function isChromeDebugger(): boolean {
-  return !(global as any).nativeCallSyncHook || (global as any).__REMOTEDEV__;
+  return true;
}
```
When testing gesture-based examples, you will also need to make this change in `gesture.ts`:
```diff
export function isRemoteDebuggingEnabled(): boolean {
// react-native-reanimated checks if in remote debugging in the same way
// @ts-ignore global is available but node types are not included
-  return !(global as any).nativeCallSyncHook || …
```
> Fix animations not running when Chrome Debugger is attached
